### ISSUE TITLE
Bug: multiple Solid Gauges causes rendering issue

### ISSUE THREAD

**Issue by wramp** [highcharts/highcharts-react#100]
Hi,
I have this strange behaviour happening with Highcharts which Im trying to figure out elegant way.

**Basically:**
I`m having two Solid Gauge components on page:

**First one:**

```js
import React from "react";

import HighchartsReact from "highcharts-react-official";
import Highcharts from "highcharts/highcharts";

import HCMore from "highcharts/highcharts-more";
import SolidGauge from "highcharts/modules/solid-gauge";

HCMore(Highcharts);
SolidGauge(Highcharts);

const GaugeChart = () => {
    let options = {
        chart: {
            type: "solidgauge",
            width: 100,
            height: 100
        },
        title: {
            text: ""
        },
        pane: {
            startAngle: 0,
            endAngle: 360,
            background: [
                {
                    outerRadius: "100%",
                    innerRadius: "70%",
                    backgroundColor: "#e8e8e8",
                    borderWidth: 0
                }
            ]
        },
        yAxis: {
            min: 0,
            max: 100,
            lineWidth: 0,
            tickPositions: []
        },
        plotOptions: {
            solidgauge: {
                dataLabels: {
                    enabled: false
                },
                linecap: "round",
                stickyTracking: false,
                rounded: true
            }
        },
        credits: {
            enabled: false
        },
        series: [
            {
                data: [{
                    color: "red",
                    radius: "100%",
                    innerRadius: "70%",
                    y: 30
                }]
            }
        ]
    }
    return (
        <div>
            <HighchartsReact
                highcharts={Highcharts}
                options={options}
            />
        </div>
    );
}

export default GaugeChart;
```
**Second one:**
its basically copy of first one but have different styling.

Im rendering them like so: 
```js
ReactDOM.render(
  <>
    <Gauge />
    <Gauge2 />
  </>, document.getElementById('root'));
```

**Results Im getting are:**
![image](https://user-images.githubusercontent.com/4153115/54058209-30859600-41c3-11e9-8dc6-0f35a3eefc5d.png)

**Ive noticed two things:**

1.
When I set **plotOptions.solidgauge.rounded** options to **false**, it will fix itself, but edges will not be rounded like it is intended.

![image](https://user-images.githubusercontent.com/4153115/54058375-a984ed80-41c3-11e9-91c8-2b2e9a2cc34a.png)

2.
It seems like issue is that modules HCMore(Highcharts) and SolidGauge(Highcharts) are called twice. Once for each component. If I remove this declaration from one of the component. It works.

![image](https://user-images.githubusercontent.com/4153115/54058484-ec46c580-41c3-11e9-9603-04f3c4a8c4ea.png)

**Conclusion:**
Can someone please suggest to me nice and clean way how to fix this problem ?
Only one I could think of is having this HCMore, SolidGauge & other module inits in parent <App /> component. 

! Ive tried wrapping module initialization in

```js
if(typeof Highcharts !== 'object'){
...
}
```

but didnt work!

**Comment by ppotaczek** [comment]
Hi @wramp,

Thank you for reporting!

This problem is caused by multiple loading `solid-gauge` module and it is related with the `rounded` property: https://jsfiddle.net/BlackLabel/cmrx24yz/

I reported this issue on Highcharts main repository: https://github.com/highcharts/highcharts/issues/10293

To workaround you can disable the `rounded` option or you can try to load the module in this way:

    if (Highcharts && !Highcharts.seriesTypes.solidgauge) {
      SolidGauge(Highcharts);
    }

Best regards!

**Comment by wramp** [comment]
Thanks @ppotaczek, this workaround will do for now.
