### ISSUE TITLE
Change lang

### ISSUE THREAD

**Issue by LucaProgrammer** [highcharts/highcharts-react#104]
Hi,
First of all i want to congratulate with you for your grate work.

I want to change lang of tooltip in datatime axes in format " %Y %b %e, %H:%M:%S ", but i don't know how do it.
Can you show me how to do?

Thank you from now.

**Comment by ppotaczek** [comment]
Hi @LucaProgrammer,

Thank you for contacting us!

You can use `xDateFormat` property to change the format for the date in the tooltip header:

    tooltip: {
        xDateFormat: "%Y %b %e, %H:%M:%S"
    }

Live demo: http://jsfiddle.net/BlackLabel/btrexms8/
API Reference: https://api.highcharts.com/highcharts/tooltip.xDateFormat

We try to keep this repository as a bug tracker, so in the future, for these types of questions please contact us by support channels: https://www.highcharts.com/blog/support/

Best regards!
