### ISSUE TITLE
Question: Equivalent to Highcharts.setOptions()

### ISSUE THREAD

**Issue by stovmascript** [highcharts/highcharts-react#105]
Is there a way to dynamically change options such as [`lang`](https://api.highcharts.com/highcharts/lang), so I can react to language changes in my app?

**Comment by ppotaczek** [comment]
Hi @stovmascript,

You can set the `lang` options only before the chart is initialized. So, if you want to change the options dynamically, you have to create a new chart.

Live demo: http://jsfiddle.net/BlackLabel/2jp0tkyz/
API Reference: https://api.highcharts.com/highcharts/lang

Best regards!

**Comment by SaeedZhiany** [comment]
@ppotaczek 

the live demo is not a react example, can you please provide how to do that in react?
Is there any options to pass lang as props?

**Comment by stovmascript** [comment]
Ok, thanks.

**Comment by ACPK** [comment]
@ppotaczek - How did you set the lang in the initial chart options? I tried doing it in your example, but it's not implementing the thousandsSp function.

http://jsfiddle.net/a349359/v2xomz60/2/

**Comment by ppotaczek** [comment]
Hi @ACPK, 

Define `lang` in `setOptions` method:

```
  Highcharts.setOptions({
    lang: {
      thousandsSep: ','
    }
  });
```

**Live demo:** http://jsfiddle.net/BlackLabel/pu18whzb/
