### ISSUE TITLE
Navigator handles on mobile do not smoothly drag

### ISSUE THREAD

**Issue by kayqq** [highcharts/highcharts-react#108]
Navigator handles on mobile do not smoothly drag, they drag in 'ticks'. 

When dragging in the handles they do not move more than 1 tick in any direction. Computer view/mouse works fine and is smooth but mobile/tablet touch seems to be having a problem.

Not my Codepen but this example should help you understand the problem:
https://codepen.io/SamEureka/full/OXbyyZ

Just view in mobile/tablet and try to touch/move navigator handles to reproduce the problem.

**Comment by ppotaczek** [comment]
Hi @kayqq,

I tested your example:

- with React: https://codepen.io/ppotaczek/full/KYVYWr
- without React: https://codepen.io/ppotaczek/full/dLGEZK

and it looks like both cases work very similarly. I did not notice any problems with the navigator on mobile. Could you create some video to demonstrate the issue?

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.

**Comment by samsonmaconi** [comment]
I'm having the same issue. If the liveRedraw option is explicitly set to true. 
```
  scrollbar: {
     liveRedraw: true,
   },
...
```
Without setting the liveRedraw option, liveRedraw is enabled on PC but disabled on Mobile/Touch devices.
