### ISSUE TITLE
Why is this library not versioned when installed through npm ?

### ISSUE THREAD

**Issue by sanjesh** [highcharts/highcharts-react#11]
npm install highcharts/highcharts-react highcharts react react-dom --save
In package.json it installed the dependencies as 

    "highcharts": "^6.0.7",
    "highcharts-react-official": "github:highcharts/highcharts-react"

why is highcharts-react-official not versioned ?

**Comment by KacperMadej** [comment]
Official NPM is at https://www.npmjs.com/package/highcharts-react-official
You can install it by `npm i highcharts-react-official`.

Could you update the NPM package @TorsteinHonsi ?

**Comment by TorsteinHonsi** [comment]
Done! Please make sure this step is added to the release procedure.

**Comment by KacperMadej** [comment]
Resolved through the package update (thank you Torstein!) and docs update - https://github.com/highcharts/highcharts-react/pull/12 (thank you sanjesh!).
