### ISSUE TITLE
How to reset yAxis tick positions?

### ISSUE THREAD

**Issue by potty** [highcharts/highcharts-react#110]
Hi, is there any way how to reset tick positions on yAxis? I have one graph and I'm updating it based on a selected metric. One metric has fixed tick positions (percentage 0-100%), the rest of the metrics have automatically calculated tick positions. The problem is when I select metric with fixed tick positions, then when I want to switch to auto tick positions, it stays on fixed ones. Based on the documentation, the default value for tick positions is `undefined`, but if I set it to undefined, it's not reset. If I set tickPositions to `null`, it magically works, but TS doesn't like it, null is not allowed. Example of code:

```
const newOptions: Highcharts.Options = {
		xAxis: {
			categories: getUnits(data),
			title: {
				text: xAxisTitle,
			},
		},
		yAxis: {
			tickPositions: getTickPositions(selectedSeries),
			labels: {
				formatter(): string {
					const self: any = this
					return formatYAxisLabel(self.value, maxSeriesValue, selectedSeries)
				},
			},
		},
		tooltip: {
			formatter(): string {
				const self: any = this
				return `${self.point.name}<br> <b>${formatTooltip(self.y, selectedSeries)}</b>`
			},
		},
		series: [
			{
				type: SERIES_TYPE,
				name: '',
				data: seriesData,
			},
		],
	}
```

```
export const getTickPositions = (series: StatsData) => {
	if (series === 'ratingAvg') {
		return [0, 25, 50, 75, 100]
	}
	return undefined
}
```

**Comment by bre1470** [comment]
Hi @potty!
Thank you for reporting this issue. I have created an issue in our main repository.
