### ISSUE TITLE
Charts messed up when changing chart type

### ISSUE THREAD

**Issue by miliu99** [highcharts/highcharts-react#113]
I'm trying to switching the bar chart from stacked to non-stacked (or vice versa), and chart is messed up after switched, although the starting chart is always correct.

Is there a way to completely reset the chart like new start?

**Comment by ppotaczek** [comment]
Hi @miliu99, 

Could you provide me with some live example of that situation? Updating `stacking` option seems to work correctly:

    constructor(props) {
      super(props);
      this.state = {
        chartOptions: {
          ...,
          plotOptions: {
            series: {
              stacking: "normal"
            }
          }
        }
      };
    }

    updateStacking() {
      this.setState({
        chartOptions: {
          plotOptions: {
            series: {
              stacking: null
            }
          }
        }
      });
    }

    render() {
      return (
        <div>
          <HighchartsReact
            highcharts={Highcharts}
            options={this.state.chartOptions}
          />
          <button onClick={this.updateStacking.bind(this)}>
            Change stacking
          </button>
        </div>
      );
    }

Live demo: https://codesandbox.io/s/4w4v5l36lw

Best regards!

**Comment by miliu99** [comment]
Hi Pawel,

Thank you very much for your quick response.

Ok, I made some changes based on your demo to fit my use case,
https://codesandbox.io/s/7m52qjmjo1. When you click Change Stacking several
times, you will see charts and legends get messed up.

One problem I try to address is that when stacked, the data sets are
reversed. I want to have the first set always at the bottom. Based on my
search, I could workaround it by reversing data series. It works on the
initial refresh. However, it gets messed up if you toggle after that.

**Comment by miliu99** [comment]
Here is the code for updateStacking:

updateStacking() {
this.stacking = this.stacking === 'normal' ? null : 'normal'
let categories = ['set1', 'set2', 'set3']
let dataSeries = [{name: 'test1', data: [2, 1, 3]}, {name: 'test2', data: [1,
3, 2]}, {name: 'test3', type: 'scatter', data: [4, 5, 6], marker: { radius:
8 }}]
if (this.stacking) {
dataSeries = dataSeries.reverse()
}
this.setState({
chartOptions: {
plotOptions: {
series: {
stacking: this.stacking
}
},
legend: { reversed: this.stacking },
xAxis: { categories: categories, title: { text: '' } },
series: dataSeries
}
});
}

**Comment by ppotaczek** [comment]
Hello @miliu99, 

Your live example is not working, could you fix it? When I change the chart options so that the button is shown (https://codesandbox.io/s/n3x2jqkm3m), everything seems to work correctly.

Best regards!

**Comment by miliu99** [comment]
Sorry, I was out of town...if you just copy my updateStacking into your
original  Live demo: https://codesandbox.io/s/4w4v5l36lw, and the click
change stacking button a few times (first time no problem) you will see
it's problem.

updateStacking() {
this.stacking = this.stacking === 'normal' ? null : 'normal'
let categories = ['set1', 'set2', 'set3']
let dataSeries = [{name: 'test1', data: [2, 1, 3]}, {name: 'test2', data: [1,
3, 2]}, {name: 'test3', type: 'scatter', data: [4, 5, 6], marker: { radius:
8 }}]
if (this.stacking) {
dataSeries = dataSeries.reverse()
}
this.setState({
chartOptions: {
plotOptions: {
series: {
stacking: this.stacking
}
},
legend: { reversed: this.stacking },
xAxis: { categories: categories, title: { text: '' } },
series: dataSeries
}
});
}

**Comment by ppotaczek** [comment]
@miliu99,

I have set the series type individually and now the chart seems to work the way you want:
https://codesandbox.io/s/qvl8xwqxj6

If it does not meet your requirements, please describe precisely what you want to achieve.

Best regards!

**Comment by miliu99** [comment]
Hi Pawel,

I just tried and it works. The only imperfection is that the market color
and shape changes - do you know how to make them stay same?

Thank you very much!

**Comment by ppotaczek** [comment]
@miliu99,

You update the series with reversed options, which causes the mix of default and custom properties.
Set `series.color` and `series.marker.symbol`:

```
    series: [
      {
        ...,
        color: "blue"
      },
      {
        ...,
        color: "black"
      },
      {
        ...,
        color: "orange",
        marker: {
          symbol: "circle",
          radius: 8
        }
      }
    ]

```
Live demo: https://codesandbox.io/s/4qywr0zpk0

Best regards!

**Comment by miliu99** [comment]
That's great, Pawel. Thank you very much!
