### ISSUE TITLE
 type: "pyramid" chart gives error#17

### ISSUE THREAD

**Issue by MusabAkram** [highcharts/highcharts-react#115]
I'm using pyramid chart. i provided the options as were on the highcharts website. Line and scatter charts are working perfectly but cant figure out the issue with pyramid chart.
This is my options object
![image](https://user-images.githubusercontent.com/19502504/56556487-92eaf800-65b1-11e9-95c2-9073b281014e.png)

I have also tried providing type with chart key like this => chart : { type : "pyramid" }

**Comment by sebastianbochan** [comment]
Hi @MusabAkram,
The pyramid chart requires the `funnel` module. Do you have it?

Docs about loading modules is available here:
- https://github.com/highcharts/highcharts-react

**Comment by MusabAkram** [comment]
> Hi @MusabAkram,
> The pyramid chart requires the `funnel` module. Do you have it?
> 
> Docs about loading modules is available here:
> 
> * https://github.com/highcharts/highcharts-react
> 
> Let me know if it solves your issue.

can you tell me how to import the funnel module? 

currently i'm importing these two :
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";

**Comment by ppotaczek** [comment]
Hi @MusabAkram, 

You need to import and initialize the `funnel` module:

    import funnel from "highcharts/modules/funnel.js";

    funnel(Highcharts);

**Live demo:** https://codesandbox.io/s/8x256rxpv0

Best regards!

**Comment by MusabAkram** [comment]
> Hi @MusabAkram,
> 
> You need to import and initialize the `funnel` module:
> 
> ```
> import funnel from "highcharts/modules/funnel.js";
> 
> funnel(Highcharts);
> ```
> **Live demo:** https://codesandbox.io/s/8x256rxpv0
> 
> Best regards!

Thanks for the help!!!
