### ISSUE TITLE
highMaps map disappears when options are updated using setState

### ISSUE THREAD

**Issue by sethimcclaine** [highcharts/highcharts-react#116]
Using the `Optimal way to update` as suggested in the documentation (https://www.npmjs.com/package/highcharts-react-official#optimal-way-to-update) I've built a highMap implementation. When I change the options (using react `setState`) the map then disappears. 

More details here: https://stackoverflow.com/questions/55818365/highmaps-map-disappears-when-options-are-updated-in-react

Demo here: https://codesandbox.io/s/7oz0m56px

**Comment by ppotaczek** [comment]
Hi @sethimcclaine, 

That problem looks like Highmaps regression. I reported it on Highcharts main repository: https://github.com/highcharts/highcharts/issues/10617

To workaround use Highcharts version 7.0.3: https://codesandbox.io/s/p74m3xwkwq

Best regards!
