### ISSUE TITLE
styledMode doesn't work

### ISSUE THREAD

**Issue by jdmoliner** [highcharts/highcharts-react#117]
Hi,

I'm trying to enable styledMode to use custom CSS but it doesn't work: 
https://api.highcharts.com/highcharts/chart.styledMode
https://www.highcharts.com/docs/chart-design-and-style/style-by-css

```
chart: {
  styledMode: true
}, 
```

**Comment by ppotaczek** [comment]
Hello @jdmoliner, 

I tested the `styledMode` with the wrapper and it seems to work correctly.

Maybe you forgot to import the default style sheet: `import "highcharts/css/highcharts.css";`

**Live demo:** https://codesandbox.io/s/rjqn38v1op

Best regards!

**Comment by jdmoliner** [comment]
Thanks! my problem was that I placed the highcharts options inside `componentDidMount`. When I place options in constructor woks fine.
