### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by jdmoliner** [highcharts/highcharts-react#118]
I'm trying to enable `timezone` option that requires moment.js:

https://api.highcharts.com/highcharts/time.timezone

I get this error: 

Highcharts Error #25
Can't find Moment.js library
Using the global.timezone option requires the Moment.js library to be loaded.

I tried to import package `moment ` and `moment-timezone` in my react code with no success.

Is there a way to use this option?

**Comment by ppotaczek** [comment]
Hello @jdmoliner,

Please refer to this issue: https://github.com/highcharts/highcharts/issues/8661

You need to set `moment` as `window.moment`: 

`window.moment = moment;`

Best regards!
