### ISSUE TITLE
highcharts.d.ts is not a module

### ISSUE THREAD

**Issue by fantapop** [highcharts/highcharts-react#119]
I'm starting out with the highcharts typescript example here:

https://github.com/highcharts/highcharts-react#highcharts-with-typescript

VSCode is giving me this error on this line:

```
import * as Highcharts from 'highcharts';
```
File '/home/chris/Development/hamilcar-ui/node_modules/highcharts/highcharts.d.ts' is not a module.ts(2306)

I looked at highcharts.d.ts and its true, there is no module declaration there.  It seems all the types are going into the global scope.  

I'm a typescript newbie but I found this similar issue regarding the lodash types: https://github.com/Microsoft/TypeScript/issues/10690#issuecomment-244493129
Someone on the typescript team there is suggesting they should be wrapped in a module.

**Comment by fantapop** [comment]
hmm, actually when I closed VSCode and reopened the error went away.   Maybe comment on why its not using a module and then feel to close...

**Comment by bre1470** [comment]
Hi @fantapop
For me this happens usually, when I change file references in the `tsconfig.json` or install node_modules, that are not picked up by Visual Studio Code. Restarting Visual Studio Code is the only way to solve this kind of issues.

Regarding the "it is not a module" - every TypeScript file with an `export` statement becomes a module. The `module` keyword is not necessary.

I close this issue, because likely just an editor glitch.

**Comment by jontiefer** [comment]
I am bumping into the same problem after migrating my React project to a computer that was re-formatted and had a new version of windows installed.  Have no clue what is going on, but double clicking on the module or closing and re-opening VS Code fixes it.  It's a nightmare and I wish I could resolve this issue!

**Comment by bomb-kst** [comment]
> Hi @fantapop For me this happens usually, when I change file references in the `tsconfig.json` or install node_modules, that are not picked up by Visual Studio Code. Restarting Visual Studio Code is the only way to solve this kind of issues.
> 
> Regarding the "it is not a module" - every TypeScript file with an `export` statement becomes a module. The `module` keyword is not necessary.
> 
> I close this issue, because likely just an editor glitch.

I think this is not the point when I try to restart the error is still there.
