### ISSUE TITLE
Incorrect typings field used in package.json

### ISSUE THREAD

**Issue by fantapop** [highcharts/highcharts-react#120]
VSCode was having an issue finding the types for this module.  I noticed that the key used in  package.json to locate them is `"type"` and not `"types"` as specified in the typescript publishing documentation:

https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

https://github.com/highcharts/highcharts-react/blob/23294efc52e819a67c4a7b3d4280703b897825f8/package.json#L5

changing this to `"types"` locally fixed the issue for me.

**Comment by bre1470** [comment]
@fantapop
Thank you for reporting the issue.
