### ISSUE TITLE
lat/lon value is inaccurate

### ISSUE THREAD

**Issue by jjzjx118** [highcharts/highcharts-react#123]
I'm trying to create a map like : https://www.highcharts.com/maps/demo/mappoint-latlon

here is my confige:
```javascriptreact
import React from "react";
import { Component } from "react";
import { render } from "react-dom";
import Highcharts from "highcharts";
import HC_map from "highcharts/modules/map";
import HighchartsReact from "highcharts-react-official";
import mapData from "./mapdata.js";
import usaMapData from "./UsaMapData.js";
import usaBubbleData from "./usaBubbleData";

HC_map(Highcharts);

const mapOptions = {
	title: {
		text: "Highmaps basic lat/lon demo"
	},
	series: [
		{
			mapData: usaMapData,
			name: "Basemap",
			borderColor: "#A0A0A0",
			nullColor: "rgba(200, 200, 200, 0.3)",
			showInLegend: false
		},
		{
			type: "mappoint",
			name: "Cities",
			color: "#7cb5ec",
			showInLegend: false,
			data: [
				{
					name: "Montgomery",
					lat: 32.38012,
					lon: -86.300629
				},
				// {
				// 	name: "Montgomery",
				// 	lat: 32.38012,
				// 	lon: -86.300629
				// }
			]
		}
	]
};

export default class Mapdemo extends Component {
	// eslint-disable-next-line no-useless-constructor
	constructor(props) {
		super(props);
	}

	render() {
		console.dir(usaBubbleData);
		return (
			<div className='container'>
				<HighchartsReact
					highcharts={Highcharts}
					constructorType={"mapChart"}
					options={mapOptions}
				/>
			</div>
		);
	}
}
```
but it only show me a basic USA map , the point no added to  the map. But I can do it base on the official demo :https://codepen.io/jjzjx118/pen/OYJrWp

is there anything I have missed ?
______________________________________________________
I have found the reason , the lat/lon value is inaccurate, I must transfer them to x,y.
I don't know why , but in official demo , lat/lon works fine : https://codepen.io/jjzjx118/pen/OYJrWp
but , when I use it in highcharts-react , the value sees not correct . so I copied the x,y value from official demo . and now it works fine.

`data: [
				{
					name: "Montgomery",
					x: 6686,
					y: -4961
				}`

so how can I transfer it from lat/lon to x,y? or How can I get the right lat/lon in highcharts-react?(I tried use GeoJson file , it doesn't work.

**Comment by zhy1stgg** [comment]
you should import `[proj4](https://github.com/proj4js/proj4js)` to transform lat/lon to Highmaps x/y

demo: https://stackblitz.com/edit/react-auwgqv?file=index.js

**Comment by jjzjx118** [comment]
@zhy1stgg thanks for helping , it works now~
