### ISSUE TITLE
Remote Loading to HighStock causes navigator re-rendering and loss previous navigator chart

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts-react#124]
I'm using highstock in similar way to this [use case ](https://www.highcharts.com/stock/demo/lazy-loading).
but with one major difference. my data is a state variable and when user change time range (using navigator or by drag and drop on chart) a function has been triggered to fetch new data. This causes the state to change and the chart will be rendered again. so the navigator chart has been changed and doesn't show the previous chart anymore. (which in the use case navigator chart never changes, no matter what ranges is selected)

```
<HighchartsReact
  key={'timeline chart by HC'}
  ref={this.highchartsReact}
  highcharts={Highstock}
  constructorType={'stockChart'}
  options={{
    exporting: {enabled: false},
    credits: {enabled: false},

    chart: {
      zoomType: 'x',
    },

    title: undefined,

    legend: {
      enabled: true,
      layout: 'horizontal',
      align: 'center',
      verticalAlign: 'bottom',
      borderWidth: 0,
    },

    navigator: {
      adaptToUpdatedData: false,
    },

    scrollbar: {
      liveRedraw: false,  // load data and redraw only after the user stops scrolling
    },

    xAxis: {
      events: {
        afterSetExtremes: function(event: Highcharts.AxisSetExtremesEventObject): void {
          const {min, max} = event;
          if (event.trigger && ((min !== componentThis.preMin) || (max !== componentThis.preMax))) {
            componentThis.preMin = min;
            componentThis.preMax = max;
            componentThis.updateSelectedRange(new Date(min), new Date(max));
          }
        },
      },
      minRange: 3600 * 500, // half hour
    },

    yAxis: {
      title: {
        text: '',
      },
      min: lowerLimit,
      max: upperLimit,
      labels: {
        formatter: function(): string {
          // @ts-ignore
          return componentThis.generateLabel(this.value, lowerLimit, upperLimit, data);
        },
        align: 'left',
      },
    },

    plotOptions: {
      series: {
        marker: {
          enabled: true,
          radius: 4,
        },
      },
      area: {
        fillOpacity: 0.2,
      },
    },

    series: data.map((item: RemoteLineSeriesData) => ({
      type: 'area',
      data: item.data ? item.data.map((point: Data) => {
        const {timestamp, value, styleCode} = point;
        return {
          x: timestamp,
          y: value,
          color: getChartColors(styleCode).normal,
        };
      }) : [],
      dataGrouping: {
        enabled: false,
      },
      name: generateSeriesTitle(item),
      color: getChartColors(item.styleCode).normal,
    })),
  }}
/>
```

Am I using the component wrong?
As you might see I'm using typescript in my project, so please suggest a way that is compatible with typescript. it also would be great if you can show me how to exactly using highstock in such use cases (remote data loading)

**Comment by ppotaczek** [comment]
Hi @SaeedZhiany,

Thank you for contacting us!

You use the wrapper in the right way, but `setState` causes `chart.update` method to be called. You need to use `setData` on the series, like in the use case that you provided.

Please check the example below. I will try to help you in case of any further questions.

Live demo: https://codesandbox.io/s/m38nm9r79y

Best regards!

**Comment by SaeedZhiany** [comment]
Thank you,
currently I use the other way suggested in [main page of repository](https://github.com/highcharts/highcharts-react#optimal-way-to-update) ( it's more compatible with my current code than using ajax http request and setData.)
But there is a new problem. according to your example I can initial fix options in component constructor and then update only necessary options when new data has been fetched. but using this approach does not work for me. instead I have to initial `chartOptions` state variable in `componentDidMount`, which is not preferred as much as initialization in constructor is possible.

related part of my code:

```
class A {

    constructor(props, state) {
        ...
        this.state = state;
        ...
    }
}

class B extends A {
    constructor(props) {
        super(
            props, 
            {
                 chartOptions: {
                     // some fix config for chart like below
                     credits: {enabled: false},
                     plotOptions: {
                         series: {
                             marker: {
                                 enabled: true,
                                 radius: 4,
                             },
                         },
                         area: {
                             fillOpacity: 0.2,
                         },
                      },
                 }
            }
        )
    }

    fetchNewData() {
        // fetching remote Data and manipulate...
        this.setState({          <- this statement is in successful fetching data callBack function
            chartOptions: {
                series: manipulatedRemoteData,
            }
        });
    }

    render() {
        return (
            <HighchartsReact
              highcharts={Highstock}
              constructorType={'stockChart'}
              options={chartOptions}
            />
        );
    }
}
```


chart is rendered data correctly but some of options does not apply, like the options I mentioned in constructor (credits and plotOptions). this is so weird I think, because when I initialize all options in `componentDidMount` instead of constructor, all options has been applied and the chart is what it should be.

```
componentDidMount() {
    this.setState({
        chartOptions: {
            credits: {enabled: false},
            plotOptions: {
                series: {
                    marker: {
                        enabled: true,
                        radius: 4,
                    },
                },
                area: {
                    fillOpacity: 0.2,
                 },
            },
        }
    });
}
```

**Comment by SaeedZhiany** [comment]
Thank you,
currently I use the other way suggested in [main page of repository](https://github.com/highcharts/highcharts-react#optimal-way-to-update) ( it's more compatible with my current code than using ajax http request and setData.)
But there is a new problem. according to your example I can initial fix options in component constructor and then update only necessary options when new data has been fetched. but using this approach does not work for me. instead I have to initial `chartOptions` state variable in `componentDidMount`, which is not preferred as much as initialization in constructor is possible.

related part of my code:

```
class A<Props, State> {

    constructor(props: Props, state: State) {
        ...
        this.state = state;
        ...
    }
}

class B extends A<Props, State> {
    constructor(props: Props) {
        super(
            props, 
            {
                 chartOptions: {
                     // some fix config for chart like below
                     credits: {enabled: false},
                     plotOptions: {
                         series: {
                             marker: {
                                 enabled: true,
                                 radius: 4,
                             },
                         },
                         area: {
                             fillOpacity: 0.2,
                         },
                      },
                 }
            }
        )
    }

    fetchNewData() {
        // fetching remote Data and manipulate...
        this.setState({          <- this statement is in successful fetching data callBack function
            chartOptions: {
                series: manipulatedRemoteData,
            }
        });
    }

    render() {
        return (
            <HighchartsReact
              highcharts={Highstock}
              constructorType={'stockChart'}
              options={chartOptions}
            />
        );
    }
}
```


chart is rendered data correctly but some of options does not apply, like the options I mentioned in constructor (credits and plotOptions). this is so weird I think, because when I initialize all options in `componentDidMount` instead of constructor, all options has been applied and the chart is what it should be.

```
componentDidMount() {
    this.setState({
        chartOptions: {
            credits: {enabled: false},
            plotOptions: {
                series: {
                    marker: {
                        enabled: true,
                        radius: 4,
                    },
                },
                area: {
                    fillOpacity: 0.2,
                 },
            },
        }
    });
}
```

**Comment by ppotaczek** [comment]
Hi @SaeedZhiany,

Sure, I can only provide you an example how you can achieve the wanted result. Instead of `setData` method you can also update the series data by `setState`:

        this.setState({
          chartOptions: {
            series: [
              {
                data: data
              }
            ]
          }
        });

**Live demo:** https://codesandbox.io/s/o7wykxjvwz

You need to keep all of the chart options in a state. 

If your problem is still unresolved, please provide me with minimal live example that demonstrate the issue.

Best regards!
