### ISSUE TITLE
How to replace highstock chart datepickers with my own component?

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts-react#125]
I'm using highchart in multi-language web application. so I have create a custom datePicker for different calendar locale. so I prefer replace highchart date picker with my own component for look consistence with other form datepickers in my application.

**Comment by ppotaczek** [comment]
Hi @SaeedZhiany,

Thank you for contacting us!

You can disable the default date picker and create the custom one as a separate component. To bind the selected date with the chart use `setExtremes` method.

Useful example: http://jsfiddle.net/BlackLabel/fkyg6xrb/
API Reference: https://api.highcharts.com/class-reference/Highcharts.Axis#setExtremes

Best regards!
