### ISSUE TITLE
Need Column Chart with progress bar

### ISSUE THREAD

**Issue by sdei-lovepreet** [highcharts/highcharts-react#126]
Hello Team,
I need a chart like an image below. Can you suggest me any chart or the way how can I customize the 
![Screen Shot 2019-05-08 at 10 40 03 PM](https://user-images.githubusercontent.com/49263176/57427727-da74b380-7242-11e9-8414-86a5fea2cf35.png)
column chart to look like this?

**Comment by ppotaczek** [comment]
Hi @sdei-lovepreet, 

We try to keep this repository as a bug tracker, so in the future, for these types of questions please use one of the support channels: 

https://www.highcharts.com/blog/support/

To create that chart, you can use basic `column` series type with `scrollablePlotArea` and data labels as images.

**Live demo:** http://jsfiddle.net/BlackLabel/ym1vqgbw/
**API Reference:** https://api.highcharts.com/highcharts/series.column.dataLabels.formatter

Best regards!

**Comment by sdei-lovepreet** [comment]
I am able to implement it using your guides and some of my customizations. Thanks for the help.
