### ISSUE TITLE
In react how to use event "mouseOver" in HighChart ?

### ISSUE THREAD

**Issue by deepakbhattmits** [highcharts/highcharts-react#128]
plotOptions:{
                series: {
                    points: {
                        events: {
                                    mouseOver: 
                                    this.setHoverData.bind(this),
                                   
                                    mouseOut:
                                    this.setHoverData.bind(this)
                                    ,
                                    select: 
                                    this.setHoverData.bind(this)
                                    ,
                                    unselect:  
                                    this.setHoverData.bind(this) 
                                    
                                }
                    }
                }
            },
i am trying this code but it not works

**Comment by ppotaczek** [comment]
Hi @deepakbhattmits,

Could you reproduce that issue in some online code editor?

In a similar example from the docs: https://stackblitz.com/edit/react-hketvd?file=index.js everything works as expected.

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.

**Comment by alvarotrigo** [comment]
> Closed due to inactivity.



> In a similar example from the docs: https://stackblitz.com/edit/react-hketvd?file=index.js everything works as expected.

How do you get the x or y position? 
`this.x` seems to be undefined?

**Comment by ppotaczek** [comment]
Hi @alvarotrigo, You can get `x` and `y` values from the `e.target` object.
