### ISSUE TITLE
Update chartOptions in getDerivedStateFromProps causes chart reset all previous options 

### ISSUE THREAD

**Issue by SaeedZhiany** [highcharts/highcharts-react#130]
According to [your advice](https://github.com/highcharts/highcharts-react#optimal-way-to-update) I keep chartOptions in my component state like below:

```
state: {
    chartOptions: {
        ...
    }
}
```

the component is responsible for creating a solid gauge chart and take a value as props for drawing a series. so every when value prop has been changed in parent I update the state of the component using `getDerivedStateFromProps` method like below:

```
public static getDerivedStateFromProps(nextProps: Props, prevState: State): Partial<State> | null {

  const {
    value,
    minValue = 0,
    maxValue,
    header,
  } = nextProps;

  return {
    chartOptions: {
      series: [
        {
          name: header,
          data: [value],
        },
      ],

      yAxis: {
        max: maxValue,
        tickPositions: [minValue, maxValue],
      },
    },
  };
}
```

Even though I initial all necessary options for solid gauge in the constructor method, but the above code causes to reset the options to default and result shown as a line chart.

Am I doing something wrong?

**Comment by ppotaczek** [comment]
Hi @SaeedZhiany,

Thank you for contacting us again!

Could you reproduce that issue in some online code editor? (stackblitz or codesandbox would be great). It will be much easier to help you with some live example.

Best regards!

**Comment by SaeedZhiany** [comment]
@ppotaczek 
I don't familiar with those tools too much but I tried to provide a simple code of mine,

https://codesandbox.io/s/optimistic-johnson-eq0g4

the code is not running because of another unrelated error in the code (it gives me an error about static keyword and I don't know why it occurs right now, please do not mention it, that is not a problem in my main project). I only provide a simple code that, if you can please solve the error and run it to see the problem

**Comment by ppotaczek** [comment]
@SaeedZhiany,

Thank you for the example. I've successfully reproduced your problem.

The chart options are overwritten in `getDerivedStateFromProps` method, before the chart is created. You can add a condition to correctly use the right options:

    static getDerivedStateFromProps(nextProps, prevState) {
      const { value } = nextProps;

      if (prevState.firstRender) {
        return Object.assign({}, prevState, { firstRender: false });
      }

      return {
        firstRender: false,
        chartOptions: {
          series: [
            {
              data: [value]
            }
          ]
        }
      };
    }

**Live demo:** https://codesandbox.io/s/awesome-frog-x77gv

Best regards!

**Comment by SaeedZhiany** [comment]
@ppotaczek 

Thank you for your response, Yes, I came to the same conclusion and I used exactly the same method. but forgot to mention it here earlier, Sorry about that.

for anyone has my problem (maybe in the future!); you can take a look at the picture below, it's the lifecycle of a react component.

![react new lifecycle](https://user-images.githubusercontent.com/13766432/58146593-101a9300-7c6c-11e9-9621-1767a9db9b77.jpg)

As you can see in the `Mounting` phase, `getDrivedStateFromProps` has been calling before the `render` method. so the options initialized in the constructor has been overwritten and causes the problem. So a workaround for it is preventing the first `getDrivedStateFromProps` call from changing the options by defining a new state boolean variable (e.g. isFirstRendering) initially to true and set it to false in the first `getDrivedStateFromProps` call.

like below:

```
interface state {
    isFirstRendering: boolean;
    chartOptions: Highcharts.Options;
}

...

constructor() {
    this.state = {
        isFirstRendering: true,
        chartOptions: {
            // initiate with your options
        },
    };
}

public static getDerivedStateFromProps(nextProps: Props, prevState: State): Partial<State> | undefined {
    const {isFirstRendering} = prevState;
    if (isFirstRendering) {
        return {
            isFirstRendering: false,
        };
    } else {
        return {
            chartOptions : {
                // change the options as you want
            }
        };
    }
}
```
