### ISSUE TITLE
There should be release logs

### ISSUE THREAD

**Issue by adeelibr** [highcharts/highcharts-react#134]
Currently their are no release logs, so it's hard to know what changes were made during which release. Or if a new release has a breaking change in the API.

The last releases in the 6 hours has caused some unknown crashes in my codebase & I can't seem to trigger out as to where the crashes happened or what I need to update in my code to reflect the new breaking changes.

### Current Behavior

- Release logs does not have details on the changes in a particular release.

### Expected Behavior

- Release logs have details on the changes in a particular release.

**Comment by ppotaczek** [comment]
Hi @adeelibr,

Please check the [changelog](https://github.com/highcharts/highcharts-react/blob/master/CHANGELOG.md) file - all changes in this wrapper with links to commits are added there.

The last problem resulted from wrong `externals` setting, but was quickly fixed. Sorry for the inconvenience.

Best regards!

**Comment by Denyllon** [comment]
@ppotaczek Maybe would be great to mention in the documentation about the fact, that the changelog file is available on the package? It also refers to another wrappers.

**Comment by adeelibr** [comment]
@ppotaczek Oh wow, my bad. I was looking at the changelog for each release in https://github.com/highcharts/highcharts-react/releases Thank you. I'll close this issue.
