### ISSUE TITLE
Couldn't run lib

### ISSUE THREAD

**Issue by ernestipekchiiev** [highcharts/highcharts-react#135]
There is an webpack case sensitive error when `yarn start`

`Failed to compile.

./node_modules/highcharts-react-official/dist/highcharts-react.min.js
Cannot find file: 'index.js' does not match the corresponding name on disk: './node_modules/React/react'.`

**Comment by ppotaczek** [comment]
Hi @ernestipekchiiev,

It is probably duplicated of #132. The problem is solved since v2.2.2, so please update your package.

Best regards!

**Comment by ernestipekchiiev** [comment]
Hi @ppotaczek! Very quick release. Thanks
