### ISSUE TITLE
serie not appearing in indicators parameters

### ISSUE THREAD

**Issue by silto** [highcharts/highcharts-react#136]
Hello,

I was just about to post an issue about having trouble using highstock's stock tools, because my serie did not appear in the "Series" dropdown of the indicator parameters popup. I found the trick to make it work but since it is not obvious at all I think it is still useful to post it here. Feel free to mark this as solved.

The problem:
My serie was displayed on the chart, the stock tools were displayed, but when I clicked on the indicators button, the "Series" dropdown didn't contain anything. This makes it impossible to select the serie to apply the indicator to.
If I tried to add the indicator anyway, I got a console.log:

> `Series undefined not found! Check "linkedTo".`

I just found out that it is actually necessary to add an `id` to the serie for it to be detected by the indicators. Like so:
`
{
          type: "line",
          id: "mainserie0",
          name: "my serie",
          data: ...,
}
`

The only way to know this is to deduce it from the fact that the "linkedTo" doc in the API reference says:

> linkedTo: string
The id of another series to link to.

Which made me think about adding an id to my serie.
This might also be a new issue because I don't see anybody using the "id" field in the code examples of other indicator-related issues, yet their problems were solved.

Maybe a documentation update is in order, if not I hope this might help someone having the same issue.
Nice job on this awesome tool team!

**Comment by pawelfus** [comment]
Thanks for reporting the issue @silto 

You are right, we should mention in our API docs that `series.id` is required in order to show series in the popup. Created separate ticket in the main repo: https://github.com/highcharts/highcharts/issues/11093 - closing this one.

PS: Thanks for your kind words, we really appreciate that! :)
