### ISSUE TITLE
StockTools | Lot of non proper handled eventListners causing warnings and performance issues

### ISSUE THREAD

**Issue by slashvortal** [highcharts/highcharts-react#139]
### Situation
**On Chrome**
Lot of noticeable non proper handled eventListners thrown in the console. mainly refers to touchstart event
`[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive.`

**On Fireforx and IE11**
Low performance on drag and accessing stockTools scroller.

### To reproduce
This can be easily noticeable in the console of any react-based demo of StockChart with enabled stock-toos module.
Here is a quick demo: https://codesandbox.io/s/10yv629397

**Comment by ppotaczek** [comment]
Hi @slashvortal,

I tested your example, but I did not notice any difference in performance or messages in a browser console. This react wrapper should not have any effect on how the stock tools work.

Could you check if that issue is also noticeable in [this example](https://jsfiddle.net/BlackLabel/cu0xa926/), without the wrapper? 

Best regards!

**Comment by slashvortal** [comment]
Yes I'm able to reproduce it without the wrapper.
I think it is non react-version-related issue as I can reproduce the same here or with any StockTools enabled ones:
https://www.highcharts.com/stock/demo/stock-tools-gui

Mainly on Mac's Chrome lates 2 versions
On windows Edge, you can see it when you try to resize the screen ++
Tested on several machines
<img width="1054" alt="Screenshot 2019-07-08 at 16 38 38" src="https://user-images.githubusercontent.com/10398252/60818994-ff33cb80-a19e-11e9-9cc3-4b3655bb178f.png">

**Comment by KacperMadej** [comment]
Unable to recreate using Chrome, Edge, Firefox on Windows 10.

**Comment by slashvortal** [comment]
Here is a video using MacOS (Mojave) Chrome (Version 75.0.3770.100) - Also tried it with the team on different machines/chromes. Chrome is the only one showing these warnings. Edge is about a performance when resizing but you can ignore it for now till I am able to provide more details on Edge.

https://imgur.com/a/Wba2Aft

**Comment by slashvortal** [comment]
Shall I report this ing the HighCharts repo since it is not react-version-related issue?

**Comment by sebastianbochan** [comment]
Im closing this ticket due to incorrect repo.

New ticket is here: https://github.com/highcharts/highcharts/issues/11353
