### ISSUE TITLE
Cannot find module 'highcharts-react'

### ISSUE THREAD

**Issue by ashok-sc** [highcharts/highcharts-react#14]
Thanks for creating this library. However, I'm getting the error, Cannot find module 'highcharts-react' after copying the sample code. I've installed all the necessary packages as well. What am I missing?

**Comment by ashok-sc** [comment]
Thanks @BrandonWilliamsCS! Greatly appreciated.

Highcharts people: I'm not being rude, but your documentation as a whole has been quite lacking and it's been a painful experience using your library. Please please please fix your documentation.

**Comment by KacperMadej** [comment]
@ashok-sc 

I'm on it.

**Comment by KacperMadej** [comment]
@ashok-sc 

Uploaded new docs.
