### ISSUE TITLE
React bubble map with HighchartsMore, Error: Highcharts error #17: www.highcharts.com/errors/17

### ISSUE THREAD

**Issue by JoaoAlrc** [highcharts/highcharts-react#140]
Hi! I'm a young dev and i have a trouble trying to make a bubble map, someone could help me? And, I wanna make a brazil map chart, how can I set this? i'm getting the Error: Highcharts error #17: www.highcharts.com/errors/17

see my code:

```
import React, { Component } from 'react';
import ReactHighcharts from 'react-highcharts';
import HighchartsMore from 'highcharts/highcharts-more';

HighchartsMore(ReactHighcharts.Highcharts);

export default class MapChart extends Component {
  // mapData = Highcharts.maps['countries/br/br-all']
  config = () => {
    return {
      chart: {
        borderWidth: 1,
        map: 'custom/world'
      },

      title: {
        text: 'World population 2013 by country'
      },

      subtitle: {
        text: 'Demo of Highcharts map with bubbles'
      },

      legend: {
        enabled: false
      },

      mapNavigation: {
        enabled: true,
        buttonOptions: {
          verticalAlign: 'bottom'
        }
      },

      series: [{
        name: 'Countries',
        color: '#E0E0E0',
        enableMouseTracking: false
      }, {
        type: 'mapbubble',
        name: 'Population 2016',
        joinBy: ['iso-a3', 'code3'],
        data: [],
        minSize: 4,
        maxSize: '12%',
        tooltip: {
          pointFormat: '{point.properties.hc-a2}: {point.z} thousands'
        }
      }]
    }
  }

  render() {
    return (
      <div>
        <ReactHighcharts config={this.config()} ref="chart" ></ReactHighcharts>
      </div>
    );
  }
}
```

"highcharts": "7.0.0"
"react-highcharts": "^16.0.2"

_Originally posted by @JoaoAlrc in https://github.com/highcharts/highcharts-react/issues/43#issuecomment-509252109_

**Comment by ppotaczek** [comment]
Hi @JoaoAlrc,

It looks like you're using an unofficial React wrapper. This repository is related with [highcharts-react-official](https://www.npmjs.com/package/highcharts-react-official) package. Below you can find a simple example of using our wrapper with `bubble` series type:

    import Highcharts from "highcharts/highstock";
    import HighchartsMore from 'highcharts/highcharts-more';
    import HighchartsReact from "highcharts-react-official";

    HighchartsMore(Highcharts);

    const options = {
      series: [{
        type: 'bubble',
        data: [[1,2], [2,2]]
      }]
    }

    class App extends React.Component {
      render() {
        return (
          <div>
            <HighchartsReact
              highcharts={Highcharts}
              options={options}
            />
          </div>
        );
      }
    }

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-x2k0r

Best regards!

**Comment by JoaoAlrc** [comment]
Hi @ppotaczek ! Thank for your help, but, didnt work yet, same error, see my code now:

```
import React, { Component } from 'react';
import Highcharts from "highcharts/highstock";
import HighchartsMore from 'highcharts/highcharts-more';
import HighchartsReact from "highcharts-react-official";

HighchartsMore(Highcharts);

const options = {
  chart: {
      borderWidth: 1,
      map: 'custom/world'
  },

  title: {
      text: 'World population 2013 by country'
  },

  subtitle: {
      text: 'Demo of Highcharts map with bubbles'
  },

  legend: {
      enabled: false
  },

  mapNavigation: {
      enabled: true,
      buttonOptions: {
          verticalAlign: 'bottom'
      }
  },

  series: [{
      name: 'Countries',
      color: '#E0E0E0',
      enableMouseTracking: false
  }, {
      type: 'mapbubble',
      name: 'Population 2016',
      joinBy: ['iso-a3', 'code3'],
      data: [],
      minSize: 4,
      maxSize: '12%',
      tooltip: {
          pointFormat: '{point.properties.hc-a2}: {point.z} thousands'
      }
  }]
}

export default class MapChart extends Component {
  render() {
    return (
      <div>
        <HighchartsReact
          highcharts={Highcharts}
          options={options}
        />
      </div>
    );
  }
}
```

**Comment by ppotaczek** [comment]
Hi @JoaoAlrc, 

You need to: 
- add `@highcharts/map-collection` npm package
- import the map from map collection
- import and initialize `map` module
- use `"mapChart"` constructorType
- import or get data

Example:

    import Highcharts from "highcharts";
    import HighchartsMap from "highcharts/modules/map";
    import HighchartsReact from "highcharts-react-official";

    import map from "@highcharts/map-collection/custom/world.geo.json";
    import mapData from "./mapData";

    HighchartsMap(Highcharts);

    const options = {
      chart: {
        ...,
        map: map
      },
      ...,
      series: [...,
        {
          ...,
          data: mapData
        }
      ]
    };

    class App extends React.Component {
      render() {
        return (
          <div>
            <HighchartsReact
              highcharts={Highcharts}
              options={options}
              constructorType={"mapChart"}
            />
          </div>
        );
      }
    }

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-r4yll

Best regards!

**Comment by ppotaczek** [comment]
Hi @gloonch,

You need to add `sankey` and `arc-diagram` modules:

```
import Highcharts from "highcharts";
import sankey from "highcharts/modules/sankey";
import arcDiagram from "highcharts/modules/arc-diagram";

sankey(Highcharts);
arcDiagram(Highcharts);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-pvcxss?file=/demo.jsx
**API Reference:** https://api.highcharts.com/highcharts/series.arcdiagram

Best regards!
