### ISSUE TITLE
Using the accessibility module

### ISSUE THREAD

**Issue by gregwhitworth** [highcharts/highcharts-react#141]
Hello, I'm trying to use the [accessibility module here](https://www.highcharts.com/docs/accessibility/accessibility-module) and it doesn't seem to work. Here is my imports at the top:

```
import React, {Component} from 'react';
import Highcharts from 'highcharts/highcharts'
import HighchartsReact from 'highcharts-react-official'
import checkBounds from '@components/surveys/checkbounds'
import 'highcharts/modules/accessibility'
```
And the high charts don't have the `aria-*` attributes on them as they do on this [page](https://www.highcharts.com/demo/accessible-line) as well as the `accessibility` object is not utilized.

Thanks.

**Comment by pawelfus** [comment]
Hi @gregwhitworth 

Please check our FAQ: https://github.com/highcharts/highcharts-react#how-to-add-a-module

Snippet:
```js
import Highcharts from 'highcharts'
import highchartsAccessibility from "highcharts/modules/accessibility";
import HighchartsReact from 'highcharts-react-official'

// init the module
highchartsAccessibility(Highcharts);
```

**Comment by gregwhitworth** [comment]
@pawelfus Thanks, that got it working in development (I'm using Gatsby) but it isn't working in build. It's throwing this error: 

```
 ERROR #95313

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html


  30 | a.legendItem.element&&(a.a11yProxyElement=e.createProxyButton(a.legendItem,e.legendProxyGroup,{tabindex:-1,"aria-pressed":!a.visible,"aria-label":b.langFormat("accessibility.legendItem",{chart:b,itemName:e.stripTags(a.name)})},a.legendGroup.div?a.legendItem:a.legendGroup,function(){e.legendProxyButtonClicked=!0}))})))},getKeyboardNavigation:function(){var b=this.keyCodes,a=this,d=this.chart,e=d.options.accessibility;return new
l(d,{keyCodeMap:[[[b.left,b.right,b.up,b.down],function(h){h=h===b.left||
  31 | h===b.up?-1:1;return d.highlightLegendItem(a.highlightedLegendItemIx+h)?(a.highlightedLegendItemIx+=h,this.response.success):1<d.legend.allItems.length&&e.keyboardNavigation.wrapAround?(this.init(h),this.response.success):this.response[0<h?"next":"prev"]}],[[b.enter,b.space],function(){var
b=d.legend.allItems[a.highlightedLegendItemIx];b&&b.a11yProxyElement&&c.fireEvent(b.a11yProxyElement,"click");return
this.response.success}]],validate:function(){var a=d.options.legend;return d.legend&&d.legend.allItems&&
> 32 | d.legend.display&&!(d.colorAxis&&d.colorAxis.length)&&a&&a.accessibility&&a.accessibility.enabled&&a.accessibility.keyboardNavigation&&a.accessibility.keyboardNavigation.enabled},init:function(b){b=0<b?0:d.legend.allItems.length-1;d.highlightLegendItem(b);a.highlightedLegendItemIx=b}})}});return
k});m(g,"modules/accessibility/components/MenuComponent.js",[g["parts/Globals.js"],g["modules/accessibility/AccessibilityComponent.js"],g["modules/accessibility/KeyboardNavigationHandler.js"]],function(c,
     |     ^
```
Looking at this [Gatsby help page for this error](https://www.gatsbyjs.org/docs/debugging-html-builds/) I have checked and you're doing the correct check for window in global.js and no where else. So I think it may come down to that this error appears when using calling `highchartsAccessibility(Highcharts);` outside of `componentDidMount()` as the error goes away.

**Comment by pawelfus** [comment]
Thanks for the info! I'm no expert in Gatsby, but from the docs you send, this seems to be a proper solution: https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-window-is-defined

```js
import Highcharts from 'highcharts'
import highchartsAccessibility from "highcharts/modules/accessibility";
import HighchartsReact from 'highcharts-react-official'

// init the module
if (typeof window !== `undefined`) {
  highchartsAccessibility(Highcharts);
}
```

Of course, if moving initialization into `componentDidMount()` works, then it's fine. But this way, you need to init module in every component, right?

**Comment by gregwhitworth** [comment]
> Of course, if moving initialization into componentDidMount() works, then it's fine.

The odd thing is that this does not work, it builds but the method does not fire in dev nor build.

> // init the module
if (typeof window !== `undefined`) {
  highchartsAccessibility(Highcharts);
}

This worked!! Kind of surprised and irked by this because the gatsby site says to see if the offending module isn't doing that check - your modules are, maybe it's a webpack issue more than anything. At any rate, this has allowed me to get a build that I can push to prod with accessibility working.

Now for a slight tangent but I'm not sure where else to place this:
@pawelfus Thank you so much for HighCharts and your focus on accessibility, I looked at many offerings for charting systems and none of them came close to a good accessible experience; this made the developer license worth it. The amount of time I would have had to spend to retro fit accessibility into the other ones would have been huge. Additionally, your quick response to the support questions has made the purchase even more valuable. Again, sorry for the tangent but thank you so much!

**Comment by pawelfus** [comment]
Thanks for kind words @gregwhitworth !

Regarding checking for window - we do check how module is loaded, but I'm not sure what happens in the build in Gatsby, maybe something similar to Next/Nuxt where everything is build twice (build for an app and build for the backend) so this check is necessary.

**Comment by lcyper** [comment]
```
import Highcharts from 'highcharts';
import HighChartsMore from 'highcharts/highcharts-more';
import HC_exporting from 'highcharts/modules/exporting';
import HC_exportData from 'highcharts/modules/export-data';
import HighchartsReact from 'highcharts-react-official';
import { getStyles } from './InsightChart.styled';
// accessibility module
require('highcharts/modules/accessibility')(Highcharts);
```

in development mode i used like this and seems to work. mybe this can help you.
