### ISSUE TITLE
Bar Chart shows index the first time it's loaded

### ISSUE THREAD

**Issue by Dan-Matt** [highcharts/highcharts-react#142]
I am using the following options to set up my chart, the first time it renders on the x axis the reg1 and reg2 labels display as 4 and 5. I have to get the render method to run a second time to show the correct labels. However when I run these options through JSFiddle they render correctly.

https://jsfiddle.net/mr2qhsz4/

Also I've run this through the npm package 'react-highcharts' using '@types/highcharts' and it works fine.

**Comment by ppotaczek** [comment]
Hi @Dan-Matt, 

Thank you for contacting us!

Our wrapper should not cause any differences in the way that charts are displayed. I have tested that chart options and the chart looks exactly the same as in jsfiddle. Could you show the issue in some online code editor?

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-bgku1

Best regards!

**Comment by Dan-Matt** [comment]
Hi @ppotaczek thanks for your response. It looks like this occurs when the react render() method is called multiple times. I don't know of a way to show an example of this. It still appears to be a bug but I'll try adding the options to the state and see if this resolves the issue.
