### ISSUE TITLE
access addPoint outside the state scope!

### ISSUE THREAD

**Issue by slashvortal** [highcharts/highcharts-react#145]
It seems there is not way to access addPoint outside the state scope!

I've been struggling to access a method outside the scope of the options' state.
In the following example, I failed. I wanted to access the method (ticker) from within the load event in vain:
(The reason I want to do this is that I want to addpoint from my context provider or any other self property, e.g., this.context, this.props...)

https://codesandbox.io/s/highcharts-react-demo-zeefr

**More reproducible challenge:**
Try to replace the point [x,y] with a point from props, state or context if any.
I tried making the load as arrow function 
```
load: () => {
self = this ...
```
But then you will not be able to access the addPoint method of the series..

**Comment by ppotaczek** [comment]
Hi @slashvortal,

Thank you for contacting us! To resolve your problem you can:

- store the component reference in a variable created in constructor method:

    constructor(props) {
      super(props);

      const component = this;

      this.state = {
        options: {
          chart: {
            events: {
              load: function() {
                const series = this.series[0];

                setInterval(function() {
                  component.ticker(series);
                }, 1000);
              }
            }
          },
          ...
        }
      };

- or use IIFE function: 

    constructor(props) {
      super(props);

      this.state = {
        options: {
          chart: {
            events: {
              load: (function(component){
                return function() {
                  const series = this.series[0];
  
                  setInterval(function() {
                    component.ticker(series);
                  }, 1000);
                }
              })(this)
            }
          },
          ...
        }
      };
    }

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-kd6iq

Best regards!
