### ISSUE TITLE
Refactor using Hooks

### ISSUE THREAD

**Issue by NMinhNguyen** [highcharts/highcharts-react#146]
Hey, would you be interested in me submitting a PR that rewrites the component using Hooks and bumps the minimum React version to 16.8? The main advantage is smaller bundle size from using function components vs class components.

**Comment by ppotaczek** [comment]
Hi @NMinhNguyen,

Thank you for your proposition, but currently we do not plan to refactor this wrapper by using Hooks. However, you can submit the PR because it can be useful for future improvements.

Best regards!

**Comment by NMinhNguyen** [comment]
Hey @ppotaczek, just wondering if you've had a chance to look at my PR #151?
