### ISSUE TITLE
Highcharts update removing series

### ISSUE THREAD

**Issue by Kierchon** [highcharts/highcharts-react#148]
I'm having a weird use case where when I dynimacally update my highcharts series, some of the series are being removed from the chart instance. So on the initial render it will show  4 data sets, then when I update the options (While keep the number of series the same, just change the values of the data) it will show 3. And when I update my options again, it will go down to two.

My code is pretty simple to reproduce this.

```
import React from "react";
import "../node_modules/kyber/dist/css/ema.min.css";
import HighchartsReact from "highcharts-react-official";
import Highcharts from "highcharts";
import { Button } from "kyber";
import options1 from "./options1";
import options2 from "./options2";

class App extends React.Component {
  state = {
    series1: true
  };

  toggleSeries = () => {
    this.setState({
      series1: !this.state.series1
    });
  };

  render() {
    const options = this.state.series1 ? options1 : options2;
    console.log(options);
    return (
      <div className="App">
        <header className="App-header">
          <Button onClick={this.toggleSeries}>Toggle Series</Button>
          <HighchartsReact highcharts={Highcharts} options={options} />
        </header>
      </div>
    );
  }
}

export default App;

```

Here are the two sets of options. I attached them because they're quite big.

[options1.txt](https://github.com/highcharts/highcharts-react/files/3447655/options1.txt)
[options2.txt](https://github.com/highcharts/highcharts-react/files/3447656/options2.txt)

One work around I've found is to pass a unique key prop on the HighchartsReact component and that will force a new chart to be rendered every time and this seems to fix it but definitely is pretty inefficient.

**Comment by ppotaczek** [comment]
Hi @Kierchon,

Thank you for contacting us!

That issue is caused by reverse indexing of your series and default enabled `oneToOne` flag in this wrapper.

I have simplified your code: http://jsfiddle.net/BlackLabel/gfkvm9rw/

As a solution you can disable `oneToOne` argument in `updateArgs` prop array:

    <HighchartsReact
        highcharts={Highcharts}
        options={options}
        updateArgs={[true, false, true]}
    />

Example: http://jsfiddle.net/BlackLabel/Lcvs216d/

or add an `id` to your series: http://jsfiddle.net/BlackLabel/n4bgx153/

**API Reference:** https://api.highcharts.com/class-reference/Highcharts.Chart#update

Best regards!

**Comment by Kierchon** [comment]
Great thanks @ppotaczek 

I am still seeing a little weirdness when I try the solution of setting oneToOne to false.

When I flip back and forth between the datasets. Im actually getting double of one of them. In my example its the Withdrawls series. They're stacking on top of eachother. I've attached two screenshots. The first is the initial render with just the one withdrawl's sections. And the the second has two. You can see that in the legend. 

<img width="1459" alt="initialRender" src="https://user-images.githubusercontent.com/8461436/62223309-f2576180-b371-11e9-92cf-98f3704189b9.png">
<img width="1465" alt="doubleWithdrawl" src="https://user-images.githubusercontent.com/8461436/62223310-f2576180-b371-11e9-91d3-4bd9e7963c03.png">

**Comment by ppotaczek** [comment]
Hi @Kierchon,

You are right - disabling `oneToOne` flag does not solve the problem in that case. You need to use the `id` option.

Best regards!

**Comment by Kierchon** [comment]
Okay thanks for the info!
