### ISSUE TITLE
constructorType prop typings do not allow module constructorTypes

### ISSUE THREAD

**Issue by wmain** [highcharts/highcharts-react#149]
The `constructorType` prop has a type of `keyof typeof Highcharts`. https://github.com/highcharts/highcharts-react/blob/9ba604d9632823fa24299889e4150e4aed2db26a/src/HighchartsReact.d.ts#L102 This throws a type error when passing constructor types for Highcharts modules (such as `ganttChart`).

**Comment by ppotaczek** [comment]
Hi @wmain,

Thank you for contacting us!

That type looks correct. Did you import and initialize `gantt` module?   

```
import Highcharts from 'highcharts'
import highchartsGantt from "highcharts/modules/gantt";
import HighchartsReact from 'highcharts-react-official'

// init the module
highchartsGantt(Highcharts);
```

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
