### ISSUE TITLE
Module not found: Can't resolve 'highcharts' in '\node_modules\highcharts-react-official\dist'

### ISSUE THREAD

**Issue by sampladoc** [highcharts/highcharts-react#150]
When I try to
´´´import HighchartsReact from 'highcharts-react-official´´´

I get the error as seen in the title.
I'm using:
Nodejs 10+
nmp 6.4.1
react:16.8.6

**Comment by sampladoc** [comment]
When I try to 
´´´import HighchartsReact from 'highcharts-react-official´´´

I get the error as seen in the title.
I'm using:
Nodejs 10+
nmp 6.4.1
react:16.8.6

**Comment by ppotaczek** [comment]
Hi @sampladoc,

Thank you for contacting us!

Could you reproduce the issue in some online code editor or provide me with some minimal project where that problem occurs?

Best regards!

**Comment by parag-thoughti** [comment]
I was also facing this issue. After some findings, I just added entry for "highcharts": "^6.0.0" in package json & it working.

I'm using:
Node: 11.7
NPM: 6.9
React: 16.9.0

**Comment by ppotaczek** [comment]
Closed due to inactivity.
