### ISSUE TITLE
When do I support VENN charts?

### ISSUE THREAD

**Issue by Gzbox** [highcharts/highcharts-react#155]
Hello

When do I support VENN charts?

Thank you

**Comment by ppotaczek** [comment]
Hi @Gzbox,

Thank you for contacting us! 

You can use `venn` chart type with this wrapper. All you need to do is import and initialize `venn` module:

    import Highcharts from "highcharts/highstock";
    import venn from "highcharts/modules/venn";
    import HighchartsReact from "highcharts-react-official";

    venn(Highcharts);

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-0jbo9

Best regards!
