### ISSUE TITLE
Snapshot testing fails because of dynamic ids and urls

### ISSUE THREAD

**Issue by chadi-kazan** [highcharts/highcharts-react#157]
using highcharts 7.1.3, highcharts-react-official 2.2.2 and react 16.9.2.
I cannot write snapshot tests for my charts because highcharts assigns dynamic ids and url references to things like clip-path. the snapshots never match because the ids change with every run. 
Can the id value generation be controlled/defined by the developer so we can at least determine it for the test?

**Comment by ppotaczek** [comment]
Hi @chadi-kazan,

Thank you for contacting us!

As a solution you can override `H.uniqueKey` method.

```
 * Get a unique key for using in internal element id's and pointers. The key is
 * composed of a random hash specific to this Highcharts instance, and a
 * counter.
 *
 * @example
 * var id = H.uniqueKey(); // => 'highcharts-x45f6hp-0'
 *
 * @function Highcharts.uniqueKey
 *
 * @return {string}
 *         A unique key.
 */
H.uniqueKey = (function () {
    var uniqueKeyHash = Math.random().toString(36).substring(2, 9), idCounter = 0;
    return function () {
        return 'highcharts-' + uniqueKeyHash + '-' + idCounter++;
    };
}());
```

https://github.com/highcharts/highcharts/blob/546eeb89c452843700b02bc2bcf968bcc3106253/js/parts/Utilities.js#L2410-L2427

**Docs:** https://www.highcharts.com/docs/extending-highcharts

Best regards!

**Comment by chadi-kazan** [comment]
not sure how to use that. I am using jest, I can mock highcharts but I cannot re-implement uniqueKey without providing a full working mock.
could you please provide an example? thanks

**Comment by ppotaczek** [comment]
Hi @chadi-kazan, 

You can for example get the key from some array or just use `idCounter`:

    H.uniqueKey = (function() {
        var idCounter = 0;
        return function() {
            return 'highcharts-' + idCounter++;
        };
    }());

**Live demo:** http://jsfiddle.net/BlackLabel/jm53cozf/

Best regards!

**Comment by chadi-kazan** [comment]
This doesn't really work with jest, I need to mock uniqueKeys but leave the rest of the highcharts functions intact. I am providing a highcharts.js 
something like this 

```javascript
// __mocks__/highcharts.js
const highcharts = jest.genMockFromModule("highcharts", {
	uniqueKey: () => {
		return "highcharts-test";
	},
});
export default highcharts;
```

**Comment by ppotaczek** [comment]
@chadi-kazan - Could you reproduce the problem in codesandbox?

https://codesandbox.io/docs/tests

**Comment by ppotaczek** [comment]
Closed due to inactivity.

**Comment by Rondip** [comment]
Any one got any solution

**Comment by ppotaczek** [comment]
Hi @Rondip,

Have you tried the solution with static unique key?

Best regards!

**Comment by gomorizsolt** [comment]
> This doesn't really work with jest, I need to mock uniqueKeys but leave the rest of the highcharts functions intact. I am providing a highcharts.js
> something like this
> 
> ```js
> // __mocks__/highcharts.js
> const highcharts = jest.genMockFromModule("highcharts", {
> 	uniqueKey: () => {
> 		return "highcharts-test";
> 	},
> });
> export default highcharts;
> ```

This works, but you lose the benefits of snapshot testing because the chart component doesn't get rendered. My goal would also be to override the `uniqueKey()` function and leave the rest of the implementation intact.

**Comment by gomorizsolt** [comment]
Have been struggling with this issue for a couple of days now.

> As a solution you can override `H.uniqueKey` method.

It's no longer feasible, it's been disabled since `v8.0.2`: https://github.com/highcharts/highcharts/issues/13074

```js
// __mocks__/highcharts.js
const highcharts = jest.genMockFromModule("highcharts", {
	uniqueKey: () => {
		return "highcharts-test";
	},
});

export default highcharts;
```

It works, but that way we unfortunately lose the benefits of snapshot testing because the tree doesn't get rendered.

For anyone who runs into the same issue: https://api.highcharts.com/class-reference/Highcharts#.useSerialIds

```js
if (process.env.NODE_ENV === 'test') {
   Highcharts.useSerialIds(true);
}
```

If it's enabled, the hashes will be omitted from the strings (clip paths and urls).

**Comment by endreujhelyi** [comment]
@gomorizsolt solution worked with the ids, but I still get different `"_reactListeningzti02fs9lep": true` each time I generate snapshots.

**Comment by ppotaczek** [comment]
Hi @endreujhelyi, Could you add more details about your problem? It would be perfect if you could reproduce it in some minimal project and provide it here.
