### ISSUE TITLE
updating chart data which changes order prints error to console

### ISSUE THREAD

**Issue by fantapop** [highcharts/highcharts-react#158]
I'm sorting my charts by x value.  On first render there are no printed errors.  If I update the date range and the new data set changes the sort order of the chart the chart is rendered correctly but there is a console error:

Highcharts error #15: www.highcharts.com/errors/15

which is
```
Highcharts expects data to be sorted
This happens when creating a line series or a stock chart where the data is not sorted in ascending X order.

For performance reasons, Highcharts does not sort the data, instead it requires that the implementer pre-sorts the data.
```

I think this is happening because the update function preserves the existing category indices instead of recreating them so they are now out of order.

![Screenshot from 2019-09-03 09-58-31](https://user-images.githubusercontent.com/6658984/64198446-13154a00-ce3d-11e9-9c35-7fcaf98d45ee.png)

I'm not sure if it's something I'm doing wrong, if its highcharts.update or if somehow the usage of highcharts.update that is causing the issue.

If I set the immutable value and recreate the chart the error does not show however animation is lost.

**Comment by ppotaczek** [comment]
Hi @fantapop,

Thank you for contacting us!

Could you provide me with some minimal live example with sample data, which presents the issue? You can start from: https://codesandbox.io/s/highcharts-react-demo-312tj

Best regards!

**Comment by fantapop** [comment]
Thanks for looking at this @ppotaczek .  I was able to reproduce the error with a minimal example.  It looks like its actually related to the usage of a category axis in a bar chart where a change to the update changes the order of the categories.

https://codesandbox.io/s/highcharts-react-demo-qp2hh

**Comment by ppotaczek** [comment]
Hi @fantapop,

Thank you for the example!

I was able to reproduce that issue without React and it looks like a regression since Highcharts v7.1.0. I reported that problem on the main repository: https://github.com/highcharts/highcharts/issues/11940

Best regards!
