### ISSUE TITLE
How to use multiple parts of highcharts

### ISSUE THREAD

**Issue by jerdbo** [highcharts/highcharts-react#159]
ex.
require("highcharts/modules/heatmap")(Highcharts);
require("highcharts/modules/map")(Highcharts);
require("highcharts/highcharts-more")(Highcharts);

how to use in 
<HighchartsReact highcharts={Highcharts} constructorType="mapChart" options={chartOptions} />

**Comment by ppotaczek** [comment]
Hi @jerdbo,

Could you describe the problem more precisely?

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
