### ISSUE TITLE
How to use bubble charts (highcharts-more issue)

### ISSUE THREAD

**Issue by raquelguimaraes** [highcharts/highcharts-react#16]
I am unable to create a chart of `bubble` type.

when I try:
```
import Highcharts from 'highcharts/highcharts-more'
<HighchartsReact
    highcharts={Highcharts}
    options={options}
/>
```
with chart type `bubble` on options I get a type error `"highcharts[constructorType] is not a function"`

and I get error [17](https://www.highcharts.com/errors/17) if I try:
```
import Highcharts from 'highcharts'
<HighchartsReact
    highcharts={Highcharts}
    options={options}
/>
```

What's the correct usage when `highcharts-more` is required? :)

**Comment by KacperMadej** [comment]
Hi @raquelguimaraes 

The module is loaded, but it needs to be initialized too. You could do this using `require` - like here:
`require('highcharts/indicators/indicators')(Highcharts)` - [an example in code](https://github.com/highcharts/highcharts-react/blob/master/demo/demo.jsx#L13)

or with `import` like this:
```
import Highcharts from 'highcharts' //core
import HC_more from 'highcharts/highcharts-more' //module
HC_more(Highcharts) //init module

<HighchartsReact
    highcharts={Highcharts} //pass core after module init
...
```

For technical support please use: https://www.highcharts.com/support

**Comment by louiechristie** [comment]
Also works for creating spider polar chart. And also works when using the npm module highcharts-react-official
