### ISSUE TITLE
Navigator handles on mobile do not smoothly drag if the liveRedraw option is set to true.

### ISSUE THREAD

**Issue by samsonmaconi** [highcharts/highcharts-react#160]
If the liveRedraw option is set for the navigator or line-chart, the navigator handles on mobile devices do not smoothly drag, they drag in 'ticks'. 

I tested by setting the liveDraw option to true in @ppotaczek's example (https://codepen.io/ppotaczek/full/KYVYWr) by adding the following option:
```
scrollbar: {
    liveRedraw: true,
  },
```
My CodePen:
- https://codepen.io/samsonmaconi/pen/zYOpwWa

Without setting the liveRedraw option, it live redraws on PC but not on mobile/touch devices. I'm trying to have it live redraw on both with the handles dragging smoothly.

**Comment by ppotaczek** [comment]
Hi @samsonmaconi,

Thank you for contacting us!

That problem does not seem to be related with `highcharts-react-official` wrapper. Could you try to reproduce the issue in pure JS and report it on the main repo? 

https://github.com/highcharts/highcharts/issues

Best regards!

**Comment by samsonmaconi** [comment]
Okay. Thank you.
