### ISSUE TITLE
Duplicate yAxis when exporting graph

### ISSUE THREAD

**Issue by pratikgaloria** [highcharts/highcharts-react#161]
Hello, first of all, thank you for this awesome wrapper.

I am using 'stockChart' `constructorType` and adding yAxis and series dynamically using `addAxis()` and `addSeries()` respectively. I am exporting the graph using `chart.exportChart()`. The problem I could see while exporting is that the yAxis is getting duplicated like the image below:

![image](https://user-images.githubusercontent.com/1481581/64428167-add98700-d0d0-11e9-97f3-3275aefdcfbf.png)

I am using `id` properly with series and its related yAxis.

The only solution I could try as of now is removing `constructorType` (or use 'chart' as default), and in that case the issue goes away! But, I have to use stockChart as per my requirements. I have tried using default `exporting` option and hamburger to download graph, still the same issue persists.

Somehow I feel like it has to do with navigator series, and `stockChart` is not hiding the navigator series when exporting.

I will also try to setup a jsFiddle today, but in case anyone already knows about the solution, all help will be appreciated.

**Comment by ppotaczek** [comment]
Hi @pratikgaloria,

Thank you for your kind words!

Unfortunately, it's very hard to help you without any code or example. I was trying to reproduce the issue, but exporting functionality seems to work fine in this example: http://jsfiddle.net/BlackLabel/5Lvdxn98/

Best regards!

**Comment by pratikgaloria** [comment]
hey @ppotaczek, thank you for your response.

I was going through my history of the code changes and could figure out where the problem was, but I couldn't understand the root cause.

So initally, I was generating axis like this:
```js
const createAxis = (series, index, theme) => ({
  id: series.id,
  opposite: !!(index % 2),
  tickAmount: 8,
  title: {
    align: 'low',
    offset: 30,
    rotation: 0,
    y: 20,
  },
});
```

And, series like this:
```js
const createSeries = ({ graphData }) => graphData.map(legend => ({
  color: legend.color,
  data: legend.currentData,
  id: legend.id,
  name: legend.name,
  navigatorOptions: {
    data: legend.data,
  },
  showInNavigator: true,
  type: 'line',
  unit: legend.unit,
  yAxis: legend.id,
}));
```
And these code could reproduce the issue.

Now, what I observed is that when I provide custom offset value to the yAxis, the issue goes away:
```js
const createAxis = (series, index, theme) => ({
  id: series.id,
  offset: 30, // This fixes the issue!
  opposite: !!(index % 2),
  ...
});
```

This looks strange and I am also facing challenge reproducing this behavior on jsFiddle. But I will give more tries and try with an actual wrapper itself.

**Comment by ppotaczek** [comment]
Hi @pratikgaloria,

Thank you for providing more information, but I still do not know exactly how you add axes and series to the chart. 

Please reproduce that issue with our wrapper. You can start from: https://codesandbox.io/s/highcharts-react-demo-g4o13

Best regards!

**Comment by pratikgaloria** [comment]
Hey @ppotaczek,

I could reproduce the same on http://jsfiddle.net/62k159wt/

So what I am doing here is that, I am adding a series and axis with same Id. Then I remove them and add again. This way I can reproduce it. I have scenarios where I've to remove the series and that can be added again. But to keep the code simple, I have illustrated only that what could reproduce the issue.

I might be wrong about defining or removing the axis or series, I guess you can help me find it out. And, my guess of `offset` making the issue go away seems incorrect now.

**Comment by pratikgaloria** [comment]
Another use-case with different IDs: http://jsfiddle.net/p84daLhc/1/

**Comment by ppotaczek** [comment]
@pratikgaloria - Thank you for the examples!

That problem is not related with `highcharts-react-official` wrapper, so I reported it on the main repository.

You can add your comments and follow the thread here: https://github.com/highcharts/highcharts/issues/11930

**Comment by pratikgaloria** [comment]
Thanks @ppotaczek
