### ISSUE TITLE
Tooltip disappearing after each render of the component that contains the chart.

### ISSUE THREAD

**Issue by jk171505** [highcharts/highcharts-react#162]
Each render of the component that contains the chart while the tooltip was displayed causes the tooltip to disappear. Is there a way to prevent it?

**Comment by ppotaczek** [comment]
Hi @jk171505,

Could you reproduce that problem in some online code editor? 
In this exampe: https://codesandbox.io/s/highcharts-react-demo-dvsyz everything works as expected.

Best regards!

**Comment by jk171505** [comment]
Hi,

partially resolved. Updating tooltip on each render in my case caused the problem. But I wonder if this is resolved by not being able to turn the stickyTracking off which causes the tooltip to be displayed always.
Problem reproducible here (only using the react wrapper):
https://codesandbox.io/s/highcharts-react-demo-fmlpv

It looks like if I move the mouse out of the point, the stickyTracking = false works. But if I won't move the pointer out of the point before chart is re-rendered the stickyTracking = false doesn't work any more.

Please note that besides the stickyTracking, there is also another problem with the tooltip which is not updated on chart re-render if the boost module is enabled:
https://codesandbox.io/s/highcharts-react-demo-rscmy

**Comment by ppotaczek** [comment]
Hi @jk171505,

Thank you for the examples! That issue is not related with this wrapper and could be easily reproduced without it: http://jsfiddle.net/BlackLabel/5m609gxe/

However, that problem looks like a bug so could you please report it on the main repo? https://github.com/highcharts/highcharts/issues/new

Best regards!
