### ISSUE TITLE
Adding drag events for 3D panning

### ISSUE THREAD

**Issue by rchancey** [highcharts/highcharts-react#163]
I am trying to add drag events to pan around a 3D chart.. I tried to use the example here:
https://www.highcharts.com/demo/3d-scatter-draggable
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/demo/3d-scatter-draggable/

but not able to figure how to add the drag even to the chart. I tried on the call back but no sure how to add events 

No demos of using 3D charts with some mouse events.. so perhaps adding the above example to teh demos would be a REALLY big help! :)

**Comment by rchancey** [comment]
chartCallback(chart) {
        let posX, posY, alpha, beta;
        let sensitivity = 5;  // lower is more sensitive
        let handlers = [];

        Highcharts.addEvent(chart.container, 'mousedown', function (eStart) {
            // eStart = chart.pointer.normalize(eStart);
            posX = eStart.chartX;
            posY = eStart.chartY;
            alpha = chart.options.chart.options3d.alpha;
            beta = chart.options.chart.options3d.beta;
            let mouseUp = Highcharts.addEvent(document, 'mouseup', function (e) {
                handlers.forEach(function (unbind) {
                    if (unbind) {
                        unbind();
                    }
                });
                handlers.length = 0;
            });

            let mouseMove = Highcharts.addEvent(document, 'mousemove', function (e) {
                // Get e.chartX and e.chartY
                e = chart.pointer.normalize(e);
                chart.update({
                    chart: {
                        options3d: {
                            alpha: alpha + (e.chartY - posY) / sensitivity,
                            beta: beta + (posX - e.chartX) / sensitivity
                        }
                    }
                }, undefined, undefined, false);
            })
            handlers.push(mouseMove);
            handlers.push(mouseUp);
        });
    }

**Comment by ppotaczek** [comment]
Hi @rchancey, 

Thank you for contacting us!

Here: https://codesandbox.io/s/highcharts-react-demo-txq2t you can find an example of a scatter draggable chart.

Best regards!

**Comment by rchancey** [comment]
Thank you!! I had solved it in a similar way, pasted the code earlier for others,  but yours is a more  complete example.. than you!
