### ISSUE TITLE
How to export XLSX or CSV report  ?

### ISSUE THREAD

**Issue by afsanefda** [highcharts/highcharts-react#165]
I added export to `xlsx`  and export to `csv` buttons in the following sandbox code but it doesn't work! do you know how to make it work?

<a href="https://codesandbox.io/s/exciting-robinson-omiub?fontsize=14">
  <img alt="Edit export-stockchart" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

```
exporting: {
  enabled: true,
    menuItemDefinitions: {
    // Custom definition
    viewFullscreen: {
      text: 'fullscreen',
    },
  },
  buttons: {
    contextButton: {
      menuItems: [
        'viewFullscreen',
        {
          text: 'DownloadXLSX',
          onclick() {
            this.downloadXLSX();
          },
        },
        {
          text: 'DownloadCSV',
          onclick() {
            this.getCSV();
          },
        },
      ],
    },
  },
},

```

**Comment by ppotaczek** [comment]
Hi @afsanefda, 

Thank you for contacting us!

To use `getCSV()` and `downloadXLS()` methods you need to add `export-data` module to your project:

    require("highcharts/modules/export-data")(Highcharts);

**Live demo:** https://codesandbox.io/s/export-stockchart-dg1s0

Best regards!

**Comment by afsanefda** [comment]
> Hi @afsanefda,
> 
> Thank you for contacting us!
> 
> To use `getCSV()` and `downloadXLS()` methods you need to add `export-data` module to your project:
> 
> ```
> require("highcharts/modules/export-data")(Highcharts);
> ```
> 
> **Live demo:** https://codesandbox.io/s/export-stockchart-dg1s0
> 
> Best regards!

Thanks a lot it works like a charm :)
