### ISSUE TITLE
Gantt setting chart instance from callback causes collapsed parent height issue

### ISSUE THREAD

**Issue by matsomo** [highcharts/highcharts-react#166]
I'm trying to flex a gantt container with another component using Split.js.

I need an instance of the gantt chart to run reflow() whenever its container width changes, 
but running the callback to get the chart instance causes the parent row to fill the space previously occupied by the child rows.

demo of issue: https://stackblitz.com/edit/ef-gantt-flex-width-scale-height-zpgsrj
simplified demo: https://stackblitz.com/edit/gantt-parent-height-wuo1z8

Any help would be appreciated.

**Comment by ppotaczek** [comment]
Hi @matsomo,

Could you describe the issue more precisely? In the examples that you have provided everything seems to work perfectly fine.

Best regards!

**Comment by matsomo** [comment]
Hey
if you comment out callback={chart => setChart(chart)} you'll see that the parent height remains the same when it's collapsed, but with the callback it'll extend to the combined height of the parent and children rows.

I was hoping to find a solution where I could get an instance of the chart and still have the parent collapse to just the height of one row.

I hope I make more sense now hehe

**Comment by ppotaczek** [comment]
Thank you for more detailed explanation. 

The issue is caused by `chart.update()` which is called with `useState()`. If you have static chart options, the simplest solution is to set `allowChartUpdate={false}`

**Live demo:** https://stackblitz.com/edit/gantt-parent-height-auca6i?file=index.js

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
