### ISSUE TITLE
Switching chart type from linear => log => linear represents 0 values as nulls

### ISSUE THREAD

**Issue by Whyseverythingtaken** [highcharts/highcharts-react#167]
Issue occurs when there are `0` values on the chart and we try to switch between `linear` and `logarithmic` scales.

Step-by-step the issue goes as follows

- `0` values are displayed correctly on initial load
- Switching to `logarithmic` scale shows `0` values as a gap - _which is expected_
- Switching back to `linear` scale shows `0` values as a gap - _unexpected_

When switching back to linear scale I would have expected the 0 values to be shown as 0s instead of gaps/nulls. I'm not sure if this is a bug or if I am doing something wrong. 

**Live Example**: https://codesandbox.io/s/highcharts-react-demo-7fjpo

**Comment by ppotaczek** [comment]
Hi @Whyseverythingtaken,

Thank you for contacting us!

That problem is a bug in Highcharts, reported here: https://github.com/highcharts/highcharts/issues/8631

You can use the workaround from the ticket.

Best regards!
