### ISSUE TITLE
Using pattern-fills with highcharts-react

### ISSUE THREAD

**Issue by dimapx** [highcharts/highcharts-react#169]
Hi,

Is there a build-in way to use pattern fills (pattern-fill-v2) with highcharts for react?
I'd appreciate if you can provide a usage example.

Thanks

**Comment by ppotaczek** [comment]
Hi @dimapx,

Thank you for contacting us!

You can use the [highcharts-pattern-fill](https://www.npmjs.com/package/highcharts-pattern-fill) module. All you need to do is import and initialize the module:

    import HC_patternFill from "highcharts-pattern-fill";

    HC_patternFill(Highcharts);

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-rkleb

Best regards!

**Comment by dimapx** [comment]
Hey @ppotaczek,

Thanks for the quick reply and live demo, appreciate the help!

Cheers

**Comment by spatil77937** [comment]
Hi,
Can you help me with another way like path and pattern all things in a color object of series instead of using url there.

**Comment by ppotaczek** [comment]
Hi @spatil77937, 
We use this repository as a bug tracker, so please use one of our support channels: https://www.highcharts.com/support/ and create a new thread with a more detailed description of your issue.
