### ISSUE TITLE
Best practice for updating chart with redux

### ISSUE THREAD

**Issue by ckirk** [highcharts/highcharts-react#171]
Thanks for providing a great [example](https://github.com/highcharts/highcharts-react#optimal-way-to-update) for the best way to update a chart by keeping all options in state. My current project uses redux and I'm not sure if/how that changes things.

Is there an example you can provide for the best way to update a chart efficiency using redux? Should I store the entire `chartOptions` object in the redux store? Can I use a combination of local state and redux? Due to the deeply nested shape of the `chartOptions` object, updating a chart parameter such as series data immutably can be a real pain. 

Any advice or examples would be very much appreciated. Thanks!

**Comment by ppotaczek** [comment]
Hi @ckirk,

Sorry for the late reply!

First of all - using `highcharts-react-official` with Redux is totally optional. You can use it to keep chart options in a global state and perhaps easier manipulate them. The main rule is the same - the optimal way to update is to overwrite options in state by the new ones.

Below you can find a simple example with the wrapper and Redux.

**Live example:** https://codesandbox.io/s/highcharts-react-demo-dju9y

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
