### ISSUE TITLE
Missing API endpoint when using highchart-react

### ISSUE THREAD

**Issue by ekaradon** [highcharts/highcharts-react#173]
Hello,

When I try to use the [following API](https://api.highcharts.com/highcharts/data.columns), I got nothing drawn.
Here an example showing the expected behavior:
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/data/columns/

 Here is what I got: https://codesandbox.io/s/highcharts-react-demo-e8ovg

Am I missing something here? Is it not possible to use the `data` part of the API when rendering series?

Regards,

**Comment by pawelfus** [comment]
Hi @ekaradon 

You didn't load the `modules/data` module, from API you linked:

> Requires
> - modules/data

Demo with module loaded: https://codesandbox.io/s/highcharts-react-demo-3fpfb

**Comment by ekaradon** [comment]
Oh ! Thanks @pawelfus for the (quick) answer ! 
I think it may be a good thing to add this as an example in the README.

**Comment by pawelfus** [comment]
It's already there @ekaradon ;)

https://github.com/highcharts/highcharts-react#how-to-add-a-module
