### ISSUE TITLE
Zones are not working using 'highcharts-react-official'.

### ISSUE THREAD

**Issue by Praveen8529** [highcharts/highcharts-react#175]
I have scenario, we need to have dotted lines for  x - series, but it works in plain Javscript library but not in  'highcharts-react-official'.. 

  series: [{
      name: '1st Quartile',
      data: [25, 25, 25, 25, 25],
      zoneAxis: 'x',
      zones: [{
        value: 4
      }, {
        dashStyle: 'LongDash',
        color: 'white',
        borderColor: '#ACACAC',
      }],
      color: '#D8DAFC',
      borderColor: '#D8DAFC',
      innerlabel: 'Q1',
    }
[Code.txt](https://github.com/highcharts/highcharts-react/files/3913034/Code.txt)

**Comment by ppotaczek** [comment]
Hi @Praveen8529,

Could you describe your problem more precisely and show it in some online code editor?

The code that you have provided works the same way:

- with the wrapper: https://codesandbox.io/s/highcharts-react-demo-gw56e
- without the wrapper: http://jsfiddle.net/BlackLabel/gf4k3qhp/

Best regards!

**Comment by Praveen8529** [comment]
Hi @ppotaczek ,
Thanks for the reply. My problem was simple for different scenario and figure out looking at our code. thanks again.

**My basic question as of now** : I am not using "highcharts-react-official" instead using "highcharts/highstock" or plain highchat.js file and binding the chat using ref of a div. could you please tell is there any drawback on this usage ..? if any like... in turns of destroying chat component, performance effect etc ..?
Below is my code example.

https://codesandbox.io/s/react-mdvfn

**Comment by ppotaczek** [comment]
Hi @Praveen8529, 

Yes, you also can use Highcharts in React without the wrapper. However, using `highcharts-react-official` provides you out of the box support for a component lifecycle:

- componentDidMount - create chart
- componentDidUpdate - update chart
- componentWillUnmount - destroy chart

You can check the wrapper source code to find out exactly how it works: https://github.com/highcharts/highcharts-react/blob/master/src/HighchartsReact.js

In your case, you should additionally call `chart.destroy()` in `componentWillUnmount` lifecycle method.

Best regards!

**Comment by Praveen8529** [comment]
Hi @ppotaczek,

Thanks! it helps a lot to explore more on implementation :).

Praveen
