### ISSUE TITLE
Does this support Highcharts 8?

### ISSUE THREAD

**Issue by jfbloom22** [highcharts/highcharts-react#178]
Thanks for an easy way to integrate Highcharts into my React app.  Highcharts 8 was released a few days ago and I wonder if it is safe to upgrade my production application?

**Comment by ppotaczek** [comment]
Hi @jfbloom22,

Thank you for using Highcharts!

Yes, you can safely update Highcharts to the newest version. Our wrapper fully supports Highcharts 8.

**Live example:** https://codesandbox.io/s/highcharts-react-demo-iuhhj

Best regards!
