### ISSUE TITLE
ToBase64Image

### ISSUE THREAD

**Issue by singhqwerty6** [highcharts/highcharts-react#179]
Hi,
I am new to react and highcharts. I need charts to be in base64image to use it in pdf. Please answer with demo ,since I am new to all this.

**Comment by ppotaczek** [comment]
Hi @singhqwerty6,

Thank you for using Highcharts!

You can get chart in SVG and convert it to base64 format.

That is not a problem with the wrapper, so in the future, for this kind of questions please use one of the support channels: https://www.highcharts.com/blog/support/

Useful article: https://ourcodeworld.com/articles/read/15/3-ways-to-export-highcharts-charts-to-image-with-javascript-client-side-solution-

**Live demo:** http://jsfiddle.net/BlackLabel/m9c137tq/

Best regards!
