### ISSUE TITLE
Piechart drilldown not working

### ISSUE THREAD

**Issue by PREM1980** [highcharts/highcharts-react#182]
Im trying to create a piechart with drilldown option but its not working. THe chart is working fine but the drill down never happens.

**Here is my code -** 

"dependencies": {
    "bootstrap": "^4.4.1",
    "bootstrap-styled": "^2.7.2",
    "countries-api": "^2.0.2",
    "highcharts": "^8.0.0",
    "highcharts-drilldown": "^0.1.7",
    "highcharts-react-official": "^2.2.2",
    "loadash": "^1.0.0",
    "lodash": "^4.17.15",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-flags": "^0.1.18",
    "react-scripts": "1.1.5",
    "styled-components": "^4.4.1"
  },

**REACTJS Code:-** 
```

`import React from 'react';
import { Row, Col } from 'react-bootstrap';
import Highcharts from 'highcharts';
import PieChart from 'highcharts-react-official';
`
const options = {
    chart: {
      type: "pie",
      events: {
          drilldown: function(e){
              console.log('test')
          }
      }
    `},`
    series: [
      {
        data: [
          {
            y: 50
          },
          {
            y: 20
          }
        ]
      }
    ],
    plotOptions: {
        series: {
            cursor: 'pointer',
            point: {
                events: {
                    click: function () {
                        console.log('Category: ' + this.id);
                    },
                }
            }
        },
  }
}


export default function(props){    
    return(
        <Row>        
            <Col sm={5}>                                  
                    <PieChart highcharts={Highcharts} options={options} />                
            </Col>            
            <Col>                  
                Chart2
            </Col>            
        </Row>
    )
} 
```

The click action is working fine but not the drilldown event.

**Comment by ppotaczek** [comment]
Hi @PREM1980,

Thank you for using Highcharts!

To use the drilldown functionality, you need to import and initialize the `drilldown` module.

**Docs:** https://github.com/highcharts/highcharts-react#how-to-add-a-module

Best regards!
