### ISSUE TITLE
Freeware Or Not

### ISSUE THREAD

**Issue by jigardarji318** [highcharts/highcharts-react#183]
Hello,

I am writing this to know that this NPM package is free to use or not?

**Comment by ppotaczek** [comment]
Hi @jigardarji318,

Yes, this NPM package is free. In the `LICENSE` file we can read:

> The software in Highcharts React repository is free and open source, 
> but as highcharts-react relies on Highcharts.js, it requires a valid 
> Highcharts license for commercial use.

Source: https://github.com/highcharts/highcharts-react/blob/master/LICENSE

Best regards!
