### ISSUE TITLE
Range selector button click events trigger increasing amount of times with each re-render

### ISSUE THREAD

**Issue by johnhansen-js** [highcharts/highcharts-react#184]
Each new re-render of highcharts-react component causes setExtremes be triggered an additional time for each click on range selector button.
Rerendering 10 times make setExtremes handler fire up 10 times for each range selector button click.

See example: https://stackblitz.com/edit/react-ukr68r

1. Click on any range-selector button. You should get one console entry per click.
2. Click multiple times on 'increment counter' button. Highcharts-react component rerenders each button click.
3. Now click again on any range-selector button. You will see multile console entries. 
Expected result of step 3: you only see one handler with different id from the previous re-renders.

```
    "highcharts": "^8.0.0",
    "highcharts-react-official": "^2.2.2",
```

**Comment by Basts** [comment]
Thank you for contacting us. 

The problem which you are struggling is not related to the Highcharts-React wrapper but it is a general Highcharts issue which is already reported here - [#6538 ].(https://github.com/highcharts/highcharts/issues/6538)

Another wrapper user noticed a similar issue before and @ppotaczek explained very well what is going on here [#112](https://github.com/highcharts/highcharts-react/issues/112), I encourage to get familiar with it if you want to know more.

And here is a suggested workaround: https://stackblitz.com/edit/react-wt8a2h?file=index.js

**Comment by johnhansen-js** [comment]
Thank you for comprehensive references and suggested workaround

**Comment by johnhansen-js** [comment]
PS

>And here is a suggested workaround: https://stackblitz.com/edit/react-wt8a2h?file=index.js

This particular suggested workaround does not work for my case, because in my case, I really need that counter as input to config-creating-function. So not only `title`, but also `setExtremes` event handler uses `counter`. I expected `HighchartsReact` to do the job of figuring what parts of config are new and updating my chart with it.

From the other linked threads I gathered that the only way to achieve successful (in particular) re-binding of events it is to access chartObject, and do `removeEvent` and `addEvent` manually.

This is far from ideal, but I guess it's up to highcharts team to fix their `.update` call. Until that is done, responsibility to connect idiomatic react part of code with non-declarative stateful js code of highcharts api is on users.

**Comment by Basts** [comment]
> From the other linked threads I gathered that the only way to achieve successful re-binding of events it is to access chartObject, and do removeEvent and addEvent manually; and to never provide events with config object except possibly for first render.

Currently is the best solution until this bug will be fixed.
