### ISSUE TITLE
Prevent drilldown of sunburst chart for a particular slice

### ISSUE THREAD

**Issue by edoteee** [highcharts/highcharts-react#185]
Is it possible to prevent drilldown of sunburst chart for a particular slice in React similar to [this](https://jsfiddle.net/BlackLabel/pe8szj25/) ?

**Comment by ppotaczek** [comment]
Hi @edoteee,

Thank you for using Highcharts!

The answer to your question is yes, you can overwrite the `onClickDrillToNode` method in the same way with React.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-b0348

**Comment by edoteee** [comment]
@ppotaczek Thanks alot, this works.
