### ISSUE TITLE
Rewrite optimal example using React Hooks

### ISSUE THREAD

**Issue by chaudhryjunaid** [highcharts/highcharts-react#187]
Currently the example for optimal use of this component (to avoid unnecessary re-renders) uses a class component. Can we please add an example which achieves this using hooks?

**Comment by ppotaczek** [comment]
Hi @chaudhryjunaid, 

Thank you for your suggestion!
Added example: https://stackblitz.com/edit/react-nwseym?file=index.js

Best regards!
