### ISSUE TITLE
chart.current.setTitle() is no t a function

### ISSUE THREAD

**Issue by jjzjx118** [highcharts/highcharts-react#189]
I use it in functional component,what I need is change the title on drill down. in pure js:
`
      drilldown: function(e) {
                    chart.setTitle({ text: drilldownTitle + e.point.name });
  },
`
and I want to know How to get chart in react component? I tired useRef,and I can get the chartRef, but I don't see setTitle in chart.current , if I try to call chart.current.setTitle() , it throws me `chart.current.setTitle() is no t a function`

**Comment by ppotaczek** [comment]
Hi @jjzjx118,

Thank you for using Highcharts!

You can get the `chart` reference as described here: https://github.com/highcharts/highcharts-react#how-to-get-a-chart-instance 

Please try the way with a callback function.

Best regards!

**Comment by jjzjx118** [comment]
thanks you , problem solved.
