### ISSUE TITLE
asynchronously updating options

### ISSUE THREAD

**Issue by rahildar** [highcharts/highcharts-react#19]
I tried the basic example of highchart with react wrapper but couldn't update the options asynchronously.
Please check the link to [code](https://codesandbox.io/s/984wnpmq5p) 
Also , when i set a key on the root component and update the key if options are updated , then it works fine.
Is there a way to update the options directly without the need to unmount the underlying component (by changing the key).

**Comment by KacperMadej** [comment]
Hi @rahildar 

Thank you for reporting about the problem.

The update should be done with `oneToOne` argument set to `true` - [docs](https://api.highcharts.com/class-reference/Highcharts.Chart#update). Currently there's no control over this, so this should be added.

_Internal note:_ ...probably in a similiar way as was done for Angular - https://github.com/highcharts/highcharts-angular/commit/8e7b8bf3858dbdc756bcdc0c2772325fb533a540

**Comment by Denyllon** [comment]
Hi @rahildar ,

Now it is possible to se the `oneToOne` parameter directly as a props of your component:
`oneToOne={true}`. 

Live example: https://codesandbox.io/s/3xv686167m

**Comment by TorsteinHonsi** [comment]
@Denyllon 
Wouldn't it make sense that `oneToOne` defaults to true? It was designed to handle updating of array configurations, and it is probably unnecessary to require this to be set. Would be better to leave it to `true` by default, with the option to set it to `false`.

**Comment by Denyllon** [comment]
hi @TorsteinHonsi ,

It make sense to me, and that's why I set it in `highcharts-vue` by default equal to `true`. I will commit the changes soon.

However, I wonder why this option is set to `false` in native Highcharts `update()` function, as well as in `highcharts-angular` wrapper.

**Comment by TorsteinHonsi** [comment]
> However, I wonder why this option is set to false in native Highcharts update() function

It's for backwards compatibility reasons. I think it should be `true` by default in the wrappers, where `chart.update` is abstracted.

**Comment by lucasdu4rte** [comment]
Hi everyone, I relied on the `highcharts-angular` when I did the pull-request and is set to `false` the default, I also see that `true` would make more sense.

It is enough to **analyze** the degree of impact in projects dependent on the package.

**Comment by Denyllon** [comment]
@KacperMadej 

So, we should consider to change it in `angular` wrapper too.
