### ISSUE TITLE
update data functional component in functional component?

### ISSUE THREAD

**Issue by rajaee-rad** [highcharts/highcharts-react#190]
hi
any example how to  update highcharts-react data in functional component?
thanks...

**Comment by ppotaczek** [comment]
Hi @rajaee-rad,

Thank you for using Highcharts!

You can find that type of example here: https://github.com/highcharts/highcharts-react#optimal-way-to-update

**Example:** https://stackblitz.com/edit/react-nwseym?file=index.js

Best regards!
