### ISSUE TITLE
Using Boost for Sunburst chart

### ISSUE THREAD

**Issue by edoteee** [highcharts/highcharts-react#191]
Is it possible to use Boost for Sunburst charts? Can you please help with the minimum configuration to get it working for React.

**Comment by ppotaczek** [comment]
Hi @edoteee,

Thank you for using Highcharts!

These are the series we allow boosting for:

- area
- arearange
- column
- columnrange
- bar
- line
- scatter
- heatmap
- bubble
- treemap

Best regards!
