### ISSUE TITLE
Why doesn't the graphic return to its original size once we return from full screen view?

### ISSUE THREAD

**Issue by juanmesaruiz** [highcharts/highcharts-react#195]
Hi, why doesn't the graphic return to its original size once we return from full screen view? You can try on your examples: https://react-4ded5d.stackblitz.io/ 

First time you enter:
![image](https://user-images.githubusercontent.com/30687723/73539284-547e4580-442d-11ea-8c63-47cc16f35389.png)

Once you return from full screen view:
![image](https://user-images.githubusercontent.com/30687723/73539323-6cee6000-442d-11ea-9370-966293658ba9.png)

Thank you

**Comment by ppotaczek** [comment]
Hi @juanmesaruiz,

Please check this example: https://react-zffnax.stackblitz.io/ - that is not an issue with this wrapper.

However, to make it works correctly set some height style for the chart container.

**Example:** https://react-tfhayn.stackblitz.io/

Best regards!

**Comment by juanmesaruiz** [comment]
It still doesn't work, I'm testing it on ios Chrome. I found the same environment as I told before

**Comment by ppotaczek** [comment]
Works fine for me. 

You need to set the style for example by `containerProps`: https://react-fzgvfp.stackblitz.io/

**Comment by juanmesaruiz** [comment]
True, I made it and it's works. My mistake was to create an external wrapper and set the height to it. 

Thank you!
