### ISSUE TITLE
Export data in CSV : React

### ISSUE THREAD

**Issue by hello-deepak** [highcharts/highcharts-react#2]
How can I export data in CSV and XLS format?

**Comment by pawelfus** [comment]
Hi @hello-deepak 

You need to include module `export-data.js` (after `exporting.js` module) and then you can configure your chart as always: https://api.highcharts.com/highcharts/exporting.csv

**Comment by pawelfus** [comment]
Well.. I don't know how this should work for `react-highcharts`, but `highcharts-export-csv` is a deprecated package since May 2017, see: https://www.npmjs.com/package/highcharts-export-csv#deprecation-notice

@KacperMadej

**Comment by KacperMadej** [comment]
For `highcharts-react` you only need to load the proper module in proper order.

Demo:
after [this line](https://github.com/highcharts/highcharts-react/blob/master/demo/demo.jsx#L17)
add `require('highcharts/modules/export-data')(Highcharts)`
