### ISSUE TITLE
Please add TypeScript definitions

### ISSUE THREAD

**Issue by JannesMeyer** [highcharts/highcharts-react#20]

**Comment by KacperMadej** [comment]
Hi @JannesMeyer 

For the wrapper?

If, for the Highcharts then please refer to this issue - https://github.com/highcharts/highcharts/issues/4876

**Comment by JannesMeyer** [comment]
By the way, we have a multi application license for the Highcharts Suite with the Premium Support.

Let me know if you want me to email the proof of license.

**Comment by KacperMadej** [comment]
For technical support please use support channels - https://www.highcharts.com/support

It would be for the best to keep issues in github for bugs - at least this it what we are trying to do.

**Comment by JannesMeyer** [comment]
Ok, I have written an email to support@highcharts.com requesting this enhancement.

Sorry for using the wrong channel.

**Comment by KacperMadej** [comment]
Not a problem. I'm keeping this issue open and labeled as an enhancement.

**Comment by BrandonWilliamsCS** [comment]
I created a types file for my personal use; hopefully it serves as a good starting point for someone to do so more formally (whether part of the package or in DefinitelyTyped). However, some work definitely needs to be done before Highstocks and Highmaps are covered.
It's short, so I'll just paste the contents `@types/highcharts-react-official/index.d.ts` (where `@types` is parallel to `node_modules`).

```typescript
declare module "highcharts-react-official" {
    import * as React from "react";
    import * as Highcharts from "highcharts";

    /**
     * Represents a "constructor" function for a ChartObject.
     * Not technically a constructor, as it's not called with `new`.
     */
    type Constructor = (
        renderTo: HTMLElement,
        options: Highcharts.Options,
    ) => Highcharts.ChartObject;
    /**
     * Represents all of the strings that are keys of T that map to a Constructor function.
     */
    type ConstructorName<T> = {
        [K in keyof T]: T[K] extends Constructor ? K : never
    }[keyof T];

    export interface HighchartsReactProps<TContainerProps = {}> {
        highcharts?: Highcharts.Static;
        constructorType?: ConstructorName<Highcharts.Static>;
        update?: boolean;
        options: Highcharts.Options;
        containerProps?: TContainerProps;
    }
    export class HighchartsReact<TContainerProps = {}> extends React.Component<
        HighchartsReactProps<TContainerProps>
    > {}

    export default HighchartsReact;
}
```

**Comment by andrasferenczi** [comment]
Thank you @BrandonWilliamsCS for the declarations. I did not find the `@types/highcharts-react-official` declarations either. Your declaration was mostly okay, but I had trouble with imports.

This is the version where the example seems to be working:

    declare namespace HighchartsReact {

    /**
     * Represents a "constructor" function for a ChartObject.
     * Not technically a constructor, as it's not called with `new`.
     */
    type Constructor = (
        renderTo: HTMLElement,
        options: Highcharts.Options,
    ) => Highcharts.ChartObject;
    /**
     * Represents all of the strings that are keys of T that map to a Constructor function.
     */
    type ConstructorName<T> = {
        [K in keyof T]: T[K] extends Constructor ? K : never
    }[keyof T];

    export interface HighchartsReactProps<TContainerProps = {}> {
        highcharts?: Highcharts.Static;
        constructorType?: ConstructorName<Highcharts.Static>;
        update?: boolean;
        options: Highcharts.Options;
        containerProps?: TContainerProps;
    }

    }

    declare class HighchartsReact<TContainerProps = {}> extends React.Component<HighchartsReactProps<TContainerProps>> {}

     export = HighchartsReact

**Comment by dandv** [comment]
See #36. Official definitions are expected in Q3.

**Comment by TheJhonny007** [comment]
As specified in #36 the official definitions are only for the normal highcharts api. So we still need official definitions for highcharts-react

**Comment by JannesMeyer** [comment]
I agree with @TheJhonny007. Pull request #36 is only for the options attribute. Like I mentioned in my first comment, there would still be the need for types for the rest of the `HighchartsReact` component.

**Comment by JannesMeyer** [comment]
Sorry, I just realised that the rest of the component's types are included in the pull request. Nevermind!!

**Comment by sophiebremer** [comment]
Hello! We will also work on declarations for Highcharts React. Development will start with the end of the beta phase for Highcharts declarations.

**Comment by TheJhonny007** [comment]
Thank you, that was the answer that I think we all wanted. 🙂

**Comment by jonfreedman** [comment]
Is there any ETA on this?

**Comment by bre1470** [comment]
No there is no ETA for this yet, because development has not started. First the Highcharts declerations have to be stable and generally available.

**Comment by bre1470** [comment]
I expect though that the support will be quite fast implemented, once the Highcharts declarations are leaving the beta state.

**Comment by jonfreedman** [comment]
@bre1470 thanks - my understanding for now is that I should follow the instructions @ https://github.com/highcharts/highcharts-declarations-beta plus the types from @BrandonWilliamsCS  updated to use your beta types e.g.
`Highcharts.ChartObject -> Highcharts.Chart`
`highcharts?: Highcharts.Static; -> highcharts?: typeof Highcharts;`
Is that fair?

**Comment by jonfreedman** [comment]
Happy to change later but the good news is this is working right now.

**Comment by pdeva** [comment]
now that Highcharts 7 contains typescript definitions by default, any updates on this issue?

**Comment by pdeva** [comment]
> ```ts
> declare module "highcharts-react-official" {
>     import * as React from "react";
>     import * as Highcharts from "highcharts";
> 
>     /**
>      * Represents a "constructor" function for a ChartObject.
>      * Not technically a constructor, as it's not called with `new`.
>      */
>     type Constructor = (
>         renderTo: HTMLElement,
>         options: Highcharts.Options,
>     ) => Highcharts.ChartObject;
>     /**
>      * Represents all of the strings that are keys of T that map to a Constructor function.
>      */
>     type ConstructorName<T> = {
>         [K in keyof T]: T[K] extends Constructor ? K : never
>     }[keyof T];
> 
>     export interface HighchartsReactProps<TContainerProps = {}> {
>         highcharts?: Highcharts.Static;
>         constructorType?: ConstructorName<Highcharts.Static>;
>         update?: boolean;
>         options: Highcharts.Options;
>         containerProps?: TContainerProps;
>     }
>     export class HighchartsReact<TContainerProps = {}> extends React.Component<
>         HighchartsReactProps<TContainerProps>
>     > {}
> 
>     export default HighchartsReact;
> }
> ```

@BrandonWilliamsCS  this no longer works with Highcharts 7.
getting error saying `Highcharts.ChartObject` and `Highcharts.Static` do not exist

**Comment by BrandonWilliamsCS** [comment]
@pdeva, Unfortunately, I don't use this actively use library any longer, so it won't be likely that I'll be taking a close look at v7.
It could be that there are other types that can be swapped in for `Highcharts.ChartObject` and `Highcharts.Static`, but it's also possible that v7 came with enough of an API change that the types I wrote are essentially incompatible.

**Comment by ppotaczek** [comment]
The TypeScript declarations for this wrapper have been added in verion 2.1.0.

Please report in case of any problems.

Best regards!

**Comment by jonfreedman** [comment]
I am seeing the following error:
```
node_modules/highcharts-react-official/dist/highcharts-react.min.d.ts
(51,29): An index signature parameter type must be 'string' or 'number'.
```
See https://github.com/Microsoft/TypeScript/blob/master/doc/spec.md#3.9.4
