### ISSUE TITLE
Sunburst doesn't drilldown after re-rendered (with multiple charts on the same page)

### ISSUE THREAD

**Issue by bmvantunes** [highcharts/highcharts-react#200]
Hello, 

The sunburst chart doesn't "drilldown" after it's re-rendered with more than one chart in the page.
If only one sunburst is in isolation it works even after re-render.
After a re-render, only the last one keeps "working".

I don't know if I should open the issue in this repository, or the highcharts one.

How to replicate this issue:
https://codesandbox.io/s/silent-surf-yxi5i

Please, let me know if you need any more details or replications,
Bruno

**Comment by ppotaczek** [comment]
Hi @bmvantunes,

Thank you for reporting!

That problem is not related with our wrapper, so we will continue the discussion in the thread on the main repository.

Best regards!
