### ISSUE TITLE
Small data values are not visible (getting squeezed) in a sunburst chart.

### ISSUE THREAD

**Issue by nvinayvarma189** [highcharts/highcharts-react#201]
Hi, I'm using highcharts-react. I have some hierarchical data and thought Sunburst would be a good option for visualizing the data. The problem is that when a data point is small (when compared to the other data points in the series), That data point does not appear on the chart. I can't even hover over that small data point. Later, I came to know that the small data point is actually getting rendered in the chart but it doesn't get enough space in the chart for it to be visible to us.

I tried the `logarithmic axis`, `zoomType` etc but I expected them not to work as these options felt more appropriate to plotting data. What can I do to make these small data points get enough space on the chart?

Steps to reproduce:
link: https://jsfiddle.net/nvinayvarma189/eqpb2496/2/

- When I navigate to `Asia>Southern Asia` I cannot see`India` on the chart.
- When I change the value of India (id: '3.136', parent: '2.13') from 1000 to 100000000, India appears on the chart.

I'm looking for a way to make India appear on the chart even when the value is 1000 (which is way lesser than other data point values).

Please help me with this and let me know if I can provide you with any more details. Thanks.

**Comment by ppotaczek** [comment]
Hi @nvinayvarma189,

Your question is not related with `highcharts-react-official` so for the future please use one of the support channels: https://www.highcharts.com/blog/support/

As a solution you can mock values in data and add some custom property with the real data to show it in a tooltip. For example: https://jsfiddle.net/BlackLabel/s3vbqk0w/

Best regards!
