### ISSUE TITLE
Does highcharts-react support zooming?

### ISSUE THREAD

**Issue by kartik2014** [highcharts/highcharts-react#204]
I have tried the way it is mentioned in highchart docs for zooming:
 options.zoomType = 'xy';
 options.zoomKey='shift'
options.panning=true;
options.panKey='shift';

This does not let me zoom the charts , so just wondering if zooming is supported in highcharts-react?

**Comment by ppotaczek** [comment]
Hi @kartik2014,

Yes, this wrapper supports all Highcharts features. 

Here: https://codesandbox.io/s/highcharts-react-demo-y9f3e you can find a working example with zoom feature.

Best regards!
