### ISSUE TITLE
Styling issue when integrated with react

### ISSUE THREAD

**Issue by spyD1803** [highcharts/highcharts-react#205]
Installed highcharts and highcharts-react-official.

But the dates are overlapping when I am trying to change the range. 

Am I missing something ? 

![image](https://user-images.githubusercontent.com/21107571/76081425-14335980-5fcf-11ea-86c4-e82c3b311250.png)

**Comment by ppotaczek** [comment]
Hi @spyD1803, 

Please reproduce that problem in some online code editor.
You can start from: https://codesandbox.io/s/highcharts-react-demo-jznoj

Best regards!

**Comment by spyD1803** [comment]
Hello

I am unable to reproduce the same in an online code editor. I am checking if any CSS is overriding the styles

**Comment by spyD1803** [comment]
Hello

It is happening when I include materialize-css in the file/component.
You can find the same here https://codesandbox.io/s/highcharts-react-demo-bxq8d

**Comment by ppotaczek** [comment]
Hi @spyD1803,

Thanks for the example. The problem is definitely caused by styles from `materialize.css`, to workaround you can overwrite some of them for example by:

    input.highcharts-range-selector {
      background: #ffffff !important;
    }

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-4slgc

Best regards!

**Comment by spyD1803** [comment]
Thanks
