### ISSUE TITLE
With immutable = false, chart not updated as expected 

### ISSUE THREAD

**Issue by 2manoj1** [highcharts/highcharts-react#206]
- Need to update chart on search (filter) so conditionally doing scroll show and hide base on data. But data not reflected as expected.
 
Example for reproduce - https://codesandbox.io/s/tender-monad-blxyi

- With  immutable = true its working fine
--->> Working as expected example: https://codesandbox.io/s/dry-wildflower-kikcj

**Comment by ppotaczek** [comment]
Hi @2manoj1,

Thank you for reporting!

Could you explain more precisely what do you mean by: 

> But data not reflected as expected.

Best regards!

**Comment by 2manoj1** [comment]
Searchable filter options. when I filter by 2 options. Chart not updated properly with **immutable = false**. But With **immutable = true**. its working fine.

Added codesandbox link. please go through.

**Comment by ppotaczek** [comment]
Hi @2manoj1,

I have simplified your example and it looks that the problem is related with `scrollbar`. I have created an issue on the main repository: https://github.com/highcharts/highcharts/issues/13184

As you rightly noticed, the workaround is to enable the `immutable` option.

Best regards!
