### ISSUE TITLE
bullet chart

### ISSUE THREAD

**Issue by mdashkezari** [highcharts/highcharts-react#207]
Can you please make a simple [bullet ](https://www.highcharts.com/demo/bullet-graph) chart example?
I keep getting errors like:
highcharts.src.js:464 Uncaught Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=bullet
missingModuleFor: bullet

thank you.

**Comment by ppotaczek** [comment]
Hi @mdashkezari, 

You probably missed to load and initialize the bullet module:

```
import Highcharts from "highcharts/highstock";
import bullet from "highcharts/modules/bullet.js";

bullet(Highcharts);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-341ny
**Docs:** https://github.com/highcharts/highcharts-react#how-to-add-a-module
