### ISSUE TITLE
getting error #17 when trying to use boxplot

### ISSUE THREAD

**Issue by omer72** [highcharts/highcharts-react#208]
I get :
Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=boxplot
missingModuleFor: boxplot

see example code in : 
[https://codesandbox.io/s/highcharts-react-boxplot-18m96](https://codesandbox.io/s/highcharts-react-boxplot-18m96)

**Comment by omer72** [comment]
Fix it:
```
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import HighchartsMore from 'highcharts/highcharts-more';

HighchartsMore(Highcharts);
```

**Comment by cyw233** [comment]
Thanks this solved my problem. But why would this happen...

**Comment by pawelfus** [comment]
> Thanks this solved my problem. But why would this happen...

You have explanation in the error :) 
- https://www.highcharts.com/errors/17/?missingModuleFor=boxplot
> (...) A typical reason may be that the module or extension where the series type is defined isn't included.

When you open docs for a particular series (or some options) you can see required module at the bottom: https://api.highcharts.com/highcharts/series.boxplot

<img width="1100" alt="Screen Shot 2020-04-08 at 11 04 53" src="https://user-images.githubusercontent.com/1453926/78765871-de481300-7988-11ea-9a43-447a06ef07a5.png">

**Comment by cyw233** [comment]
@pawelfus Thanks mate! Your explanation is so great and is exactly what I was looking for!
