### ISSUE TITLE
React component labels disappear on zoom / brush

### ISSUE THREAD

**Issue by queicherius** [highcharts/highcharts-react#209]
When using the recommended way to render React components as axis labels via portals, when the graph resizes (e.g. via the navigator on stock charts), the new labels do not get rendered, and the old labels disappear.
Demo: https://codesandbox.io/s/highcharts-react-demo-kfp05
Gif: ![2020-04-07_02-55-09](https://user-images.githubusercontent.com/4615516/78622000-e1a1a880-787b-11ea-995d-37683457d4cd.gif)

To get it working, I hooked into the `afterSetExtremes` event of the axis to force a re-render. 
Demo: https://codesandbox.io/s/highcharts-react-demo-36evp

Is this the recommended way to do this, or would `renderToStaticMarkup` be the better choice?

**Comment by ppotaczek** [comment]
Hi @queicherius,

Thank you for contacting us!

Yes, it is necessary to update label components in that case. As you rightly noticed, it is also possible to use `renderToStaticMarkup`, but then the labels lose their reactive property. 

I would recommend to stay with portals, it is more elastic solution and it seems to have better performance.

**Example with `renderToStaticMarkup`**: https://codesandbox.io/s/highcharts-react-demo-ew966?file=/demo.jsx

Best regards!

**Comment by queicherius** [comment]
Thank you, appreciate the answer!

I have opted to use `renderToStaticMarkup` for now, which makes the code easier, since my labels dont have any interactivity, and the performance metrics for my use case seemed comparable.
