### ISSUE TITLE
Cannot use solid gauge

### ISSUE THREAD

**Issue by gsouf** [highcharts/highcharts-react#21]
Solid gague cannot be used within highcharts-react. As found on this issue: https://github.com/kirjs/react-highcharts/issues/254

However I could not solve the issue to get gauge working as they did in this example.

**Comment by KacperMadej** [comment]
Hi @gsouf 

Please describe what code have you used and what error and problem you have.

**Comment by gsouf** [comment]
Hi @KacperMadej  Unfortunately I had very short delay to build the app the so I gave up and switched for the other react highcharts adapter. 

If it can help I can try again?

**Comment by KacperMadej** [comment]
Sure, no rush - we can reopen when you will be able to provide something for us to work with.
