### ISSUE TITLE
drilldown doesn't work the first loading

### ISSUE THREAD

**Issue by BrkDalkiran** [highcharts/highcharts-react#210]
I use drilldown on pie chart. I'm doing "point.doDrilldown()" in the "Load" event of "Chart". 

First of all, when I make this console, only log comes once. This is always the case, but there are two situations where it works correctly and incorrectly.

some important parts of the code;
```
import Highcharts from 'highcharts'
import HighchartsReact from 'highcharts-react-official'
import drilldown from 'highcharts/modules/drilldown'

class DetailView extends Component {
  componentDidMount() {
    drilldown(Highcharts)
  }

render() {
  return <HighchartsReact
    highcharts={Highcharts}
    options={this.getHighChartSeriesOptions(decoratedList)}
  />
}

getHighChartSeriesOptions = data => {
return {
      chart: {
        type: 'pie',
        events: {
          load: function (event) {
            console.log('loaded')
            this.series[0].data[clickedIndexFromState].doDrilldown()
          },
        },
      },
      series: [{
        events: {
          click: function (event) {
            //i write clicked serie index to state
          }
        },
      }]
    }
}
```

**PROBLEM**
Drilldown click does not work when i first open google chrome. After the chart load, I refresh the page once. Drilldown works normally.

Video: https://reccloud.com/u/jon7kyd

**Comment by ppotaczek** [comment]
Hi @BrkDalkiran, 

I have reproduced the same problem here: https://codesandbox.io/s/highcharts-react-demo-wt4u2?file=/demo.jsx

You need to initialize the drilldown module before class declaration, not in `componentDidMount`.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-gfxw7?file=/demo.jsx

Best regards!

**Comment by BrkDalkiran** [comment]
Thanks @ppotaczek .
I tried what you said did not work. Then I realized that the only thing that was different was `import Highcharts from 'highcharts/highstock'`. I do not understand what relation is there but it worked

**Comment by ppotaczek** [comment]
Hi @BrkDalkiran,

`import Highcharts from 'highcharts/highstock'` means that you use [Highstock](https://www.highcharts.com/docs/stock/understanding-highstock), which in your case should not have any affect.

Here: https://codesandbox.io/s/highcharts-react-demo-qlk2s?file=/demo.jsx you can check that the solution works also with importing Highcharts.

Best regards!
