### ISSUE TITLE
Need to update "highcharts-react-official": "^3.0.0"

### ISSUE THREAD

**Issue by v-abkhot** [highcharts/highcharts-react#211]
Hi Team i have seen that "highcharts-react-official": "^3.0.0" is supporting highchart version from +6.0.0.
But unfortunately all accessibility issues got resolved in from version 8.0.1 and above which are not supported by "highcharts-react-official": "^3.0.0". so facing all accessibility bugs of older version so please update  "highcharts-react-official": "^3.0.0" so that it will support highchart version 8.0.1 and and above in react

**Comment by ppotaczek** [comment]
Hi @v-abkhot,

Our wrapper supports all Highcharts versions above 6.0.0. That means that version < 8.0.0 are also supported.

Best regards!

**Comment by v-abkhot** [comment]
yah correct but  "highcharts-react-official": "^3.0.0" is last updated 2 months ago.
and 8.0.1 and above version updated on in month of march. this was issue same with react-highcharts

**Comment by ppotaczek** [comment]
The difference is that our wrapper does not internally provide Highcharts. Highcharts needs to be provided by user.

**Docs:** https://github.com/highcharts/highcharts-react#options-details
