### ISSUE TITLE
Issues when changing the series array

### ISSUE THREAD

**Issue by Alin13** [highcharts/highcharts-react#215]
Hello,

I have some issues with the charts series. My chart should display two series by default, and when the user clicks on a button I need to add a new serie between the initial ones.

I also tried to create an example (sorry for the messy code, but I can't reproduce it otherwise): https://codesandbox.io/s/highcharts-react-demo-6i0rd?file=/demo.jsx

So:
- at the first render I have _first_ serie (**red**) and _last_ serie (**green**), which also has a point with a custom marker
- when we click on **Change series** we add the new serie (**blue**)
1.  here we can see the first issue - the new serie has the custom marker rendered (the one from the other serie)
2.  if we keep clicking on **Change series** - we can see that the color of the last serie is changing

I don't know if the problem is in my code or it is from the library. Do you have any ideas ?

_**Edit1**_:
- if I keep the same order for series, some of the problems dissapear, but the color for the third serie is still changed.
https://codesandbox.io/s/highcharts-react-demo-20bz5?file=/demo.jsx

_**Edit2**_:
- I managed to fixed this by keeping the same order for series, adding a **legendIndex** options to the **last** serie and also adding **color** option on each serie.
https://codesandbox.io/s/highcharts-react-demo-pjxwy?file=/demo.jsx

But I think this is still a bug.

Thank you for your time :)

**Comment by ppotaczek** [comment]
Hi @Alin13,

Thank you for using our wrapper!

That is not a bug, a chart is not recreated with changing state, but only updated. This means that all chart options that are not overwritten are retained (color, marker options).

If you want to recreate a chart, set `immutable` option to true.

Best regards!

**Comment by Alin13** [comment]
Thank you :)

**Comment by qIsotope** [comment]
@ppotaczek how i can dynamically redraw my chart on chart.series change? for example i have array of series with length 3 and i wanna add new one array element
immutable create a lot of problems for my case

**Comment by ppotaczek** [comment]
Hi @qIsotope,

I don't know your exact use case, but in general changing array length shouldn't be a problem. Please check the below example.
 
Live example: https://stackblitz.com/edit/react-p7drtq?file=index.js

Best regards!

**Comment by qIsotope** [comment]
@ppotaczek thx for reply!

Somehow i can do immutable behaviour with condition? i need to recreate a chart only if my series changed

**Comment by ppotaczek** [comment]
@qIsotope, Sure, you can keep the value of `immutable` in a state and conditionally change it. 
Live example: https://stackblitz.com/edit/react-j6pcyg?file=index.js

**Comment by qIsotope** [comment]
@ppotaczek i fix it with prop "key" i just passed to there my series and it make recreate on every change, maybe it should be in documentation?
