### ISSUE TITLE
Patterns not working as series.data.color when using highcharts-react

### ISSUE THREAD

**Issue by dagognatt** [highcharts/highcharts-react#216]
I'm trying to display a simple pie-chart with custom pattern using highchart pattern-fill module, but this is not working as per the api for me. 

When not using the react-wrapper, the same config works, and the pattern is being used. 

I'm setting the series.data.color to this: 
```
color: { 
    pattern: {
        path: {
            d: "M 3 3 L 8 3 L 8 8 Z",
            fill: "red"
        },
        width: 12,
        height: 12,
        color: "red",
        opacity: 0.5
    }
}
```

CodePen WITHOUT react-wrapper: https://codepen.io/dagognatt/pen/ZEbjydN
CodePen WITH react-wrapper: https://codepen.io/dagognatt/pen/LYpBLBV

**Comment by Basts** [comment]
Hello @dagognatt, thank you for contacting us.

It is not a bug. The problem which you are struggling to is related to importing the modules in the Highcharts React Wrapper.

I encourage to use the traditional **import** method or ** require** than using the CDN. 

Demo: https://codesandbox.io/s/highcharts-react-demo-6mptt

API: https://github.com/highcharts/highcharts-react#how-to-add-a-module

**Comment by dagognatt** [comment]
Hi, thanks for your quick response. 

Usually I use the traditional import method. Just didnt know how to setup that in the CodePen. 

I see you used a traditional React.Component. I am trying to use React.FunctionComponents that use the Highchart-wrapper. Could that be the issue as well ? 

Tried in a codesandbox but seems I am missing something, now even the pie is missing: https://codesandbox.io/s/highcharts-react-demo-uohwl?file=/demo.jsx

**Comment by Basts** [comment]
@dagognatt,

Your code is almost fine, you did a small mistake by setting:
`const options = {
   options: {
     ...
   }
}`

Options nested in options variable. Corrected demo: https://codesandbox.io/s/highcharts-react-demo-oob3r

**Comment by Basts** [comment]
@dagognatt 

One more thing! May I ask which version of Highcharts do you use? Because in the CodePen which you have shared there is a 6.0.7 in using, but pattern-fill was add in v6.1.0. 

Demo v6.0.7: https://jsfiddle.net/BlackLabel/3uyp50be/
https://www.highcharts.com/blog/changelog/#highcharts-v6.1.0

**Comment by ppotaczek** [comment]
Closed due to inactivity
