### ISSUE TITLE
Need help in react gantt chart category update and conditionally update background color of first row(including category)

### ISSUE THREAD

**Issue by sreevidyaJ** [highcharts/highcharts-react#217]
Hi Team,

I'm using react highchart gantt.
Initially i will have only one row, with background color and when i click add data, rows gets appended and name of first row can change.

I'm facing 3 issues,

1) when I have only one row, chart doesn't render properly
2) when I try to change categories it is throwing error "Cannot read property 'index' of undefined"
3) when I'm using plotBand to make background-color as grey, it is not working.

https://codesandbox.io/s/highcharts-react-demo-ctgdo?file=/demo.jsx
 
Can you please help me?

Thanks,
Sreevidya

**Comment by ppotaczek** [comment]
Hi @sreevidyaJ,

Thank you for contacting us!

These issues are bugs in Highcharts v6.2. All of them are fixed in the newest version.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-x8k2j?file=/highchartdemo.jsx

Best regards!

**Comment by sreevidyaJ** [comment]
Thanks for your inputs!

Is it possible to highlight first row with some background color including category (x) in current version?

**Comment by ppotaczek** [comment]
Hi @sreevidyaJ, 

Yes, you can use `Highcharts.SVGRenderer` class to add a rectangle. Please check the example below.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-zjyms
**API Reference:** https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#rect

Best regards!

**Comment by sreevidyaJ** [comment]
Thank you !!

**Comment by sreevidyaJ** [comment]
Hi @ppotaczek,

I missed to check one point, when I click Add data, the height of the chart is not increasing automatically. if I add 10 rows, the chart will look messy. 

can you help me here.

Thanks,
Sreevidya

**Comment by ppotaczek** [comment]
Hi @sreevidyaJ, 

You are right, that problem looks like a bug so I reported it on the main repository: https://github.com/highcharts/highcharts/issues/13610

As a workaround you can update `chart.height` property.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-bvwi0?file=/highchartdemo.jsx
**API Reference:** https://api.highcharts.com/gantt/chart.height
