### ISSUE TITLE
The chart does not display the original size after exiting full screen mode

### ISSUE THREAD

**Issue by v-abkhot** [highcharts/highcharts-react#218]
Expected behaviour
click on export menu -> click on View full screen then press escape from full screen. it should fit in existing dimensions. container height should not change.

Actual behaviour
click on export menu -> click on View full screen then press escape from full screen. it should fit in existing dimensions. container height is getting changed.

![image](https://user-images.githubusercontent.com/63849538/82216085-0b97c180-9936-11ea-8cfe-bef228dfbe03.png)

after adding fix height to container (as suggested main hicharts team)

![image](https://user-images.githubusercontent.com/63849538/82216200-397d0600-9936-11ea-99dc-23fabeb1eb6b.png)

**Comment by sebastianbochan** [comment]
Closed due to duplicate: https://github.com/highcharts/highcharts/issues/13222

**Comment by v-abkhot** [comment]
this is issue with wrapper highcharts-react not hicharts
