### ISSUE TITLE
Trouble using sma, ema, etc indicators.

### ISSUE THREAD

**Issue by jamalmoir** [highcharts/highcharts-react#22]
Hello, I'm trying to use the EMA indicator but am getting `Error: Highcharts error #17: www.highcharts.com/errors/17` which is `The requested series type does not exist`.

I have added the imports
```
import 'highcharts/indicators/indicators';
import 'highcharts/indicators/ema';
```

at the top of my file and my series looks like this:

```
series: [{
                name: 'Candlestick',
                id: 'candles',
                type: type,
                data: initialData,
                dataGrouping: {
                    units: [
                        [
                            'day', // unit name
                            [1] // allowed multiples
                        ], [
                            'week',
                            [1]
                        ],  [
                            'month',
                            [1]
                        ]
                    ]
                },
                color: Palette.tears,
                upColor: Palette.blood,
                lineColor: Palette.iron,
            }, {
                type: 'ema',
                linkedTo: 'candles',
                params: {
                    period: 5
                }]

```

Obviously I am missing something here - can I get some direction please?

**Comment by KacperMadej** [comment]
Hi @jamalmoir 

I'm unable to recreate the problem. I have changed this repo's demo to match your data and all works fine.

Please check which type is not correct - you are using not explained and not defined in the code provided `type: type,`, so maybe it's causing the error.

Make sure that all modules are not only imported, but also initialized:

```jsx
require('highcharts/indicators/indicators')(Highcharts)
require('highcharts/indicators/ema')(Highcharts)
```

**Comment by jamalmoir** [comment]
@KacperMadej - Thank you for your reply - I was not initialising the modules! Problem solved!

**Comment by bennycode** [comment]
For everyone who faces the same problem using TypeScript, here is the import solution:

```
import Highcharts from 'highcharts/highstock';
import ema from 'highcharts/indicators/ema';

// ...

ema(Highcharts);
```
