### ISSUE TITLE
Proper way to format label on solidgauge with JSX

### ISSUE THREAD

**Issue by wcoppens** [highcharts/highcharts-react#220]
For a SolidGauge i would like to format the series.dataLabel with a FontAwesome icon and a value below it. Now i think i need to use react portals to create this kind of behaviour but can't seem to find a proper way to select the DOM element containing the label from the Chart object.

My question is, what is the proper way to do this? Is there any example with the use of a SolidGauge around? Because the examples with the line chart etc. are all using the 'ticks' which always contain a DOM element.

So far i got this: https://codesandbox.io/s/highcharts-react-demo-bsrfb?file=/demo.jsx
As you can see on line 102 im literally selecting the DOM element from the document, which will only work if there is only a single instance of the SolidGauge in the DOM.
Also you can see that the label itself is slightly off center because the position calculation don't seem to work anymore due to the portal?

Thanks in advance!

**Comment by ppotaczek** [comment]
Hi @wcoppens,

Thank you for contacting us!

First of all, please these two threads:

- https://www.highcharts.com/forum/viewtopic.php?t=34685
- https://www.highcharts.com/forum/viewtopic.php?t=41434

to find out how you can add a FontAwesome icon without portals and JSX.

As to your questions - you can get the data label element by: 
`dataLabel = chart.series[0].points[0].dataLabel.div;`

and yes, Highcharts don't have logic to align a data label from a portal, so you need to position it by yourself.

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
