### ISSUE TITLE
Hover performance with React and state hooks

### ISSUE THREAD

**Issue by seanvgarner** [highcharts/highcharts-react#224]
Hello! Thanks for putting in the time to maintain this lovely little wrapper for React. Hope you can help me sort out an issue I am bumping in to.

For some reason, if I am trying to set state in a functional react component with hooks during hover events (have tried the tooltip formatter function, as well as the mouseOver event on `plotOptions.series.point`) there is visible lag occurring that grows worse with the more series displayed on the chart. I had similar functionality working in angular with no issues here. This is likely partially do to the way react handles re-rendering with state changing, but was wondering if there is a known workaround or solution to this issue as I would expect with the official wrapper for React, this performance problem would not exist. 

I have a codesandbox example of the problem I am seeing. You will see with 1 plot, things work pretty well, but if you change `numPlots` on line 22 of `GraphResults.js` to a larger number, say 20 to generate more series, reload and then hover over the graph to see the lag I am experiencing. 

https://codesandbox.io/s/hardcore-butterfly-6btk5?file=/src/GraphResults.js

Even if you comment out the 'UPDATE_HOVER_VALUES' dispatch call which is doing relatively more expensive logic, and just leave in the simple set state call from the useStateHook, there is still a pretty noticeable lag occurring.

**Comment by Basts** [comment]
Hello @seanvgarner, thank you for contacting us!

I don't think that this low performance is related to the React wrapper working, but more with your custom functionalities, the explanation below.

Please take a look at this simplified demo of your chart where everything works fine: https://stackblitz.com/edit/react-mxrsih?file=index.js

Here is a demo with your config without the `SearchGraphLegend` functionality to comparing performance: https://codesandbox.io/s/romantic-driscoll-xzg42

A lot happens in your code, but I don't think that using the `tooltip.formatter` to trigger `onHover` feature is a good practice (this functionality loops through all series), have you tried to use the `plotOptions.series.point.events.mouseOver` just as I did?

**Comment by seanvgarner** [comment]
@Basts thanks for taking a look, could very well be something wrong with my implementation, I will experiment `plotOptions.series.point.events.mouseOver` and look at stream lining the way I initialize the options object. Thanks for your time!
