### ISSUE TITLE
React stacked column highchart doesn't work normally

### ISSUE THREAD

**Issue by geralt1011101** [highcharts/highcharts-react#225]
Hello team, thank you very much for your efforts to create this so useful library. Currently, I’m facing issues with stacked column highchart and hope you can help me.

This is the demo stacked column:
https://www.highcharts.com/demo/column-stacked

I used the exact config (you can take a look at my config in attached image) and it shows the chart but when I hover the bar, it doesn’t show the tooltip. Besides, when I click items in legend, they don’t toggle bars like the demo above. You can watch this clip to understand more clearly: https://vimeo.com/430583154

I tried to reproduce this in an online sandbox (the lib versions are the same as mine) but it works normally:
https://stackblitz.com/edit/react-2tg4hx?file=index.js

Now, I have no ideas of how to make it show the tooltips and toggle bars when clicking legend items. Hope you could give a hint :smile:

Here are the versions of libraries I’m using:
- "highcharts": "^8.1.2",
- "highcharts-react-official": "^3.0.0",
- "react": "^16.13.1",
- "react-dom": "^16.13.1"
![Screen Shot 2020-06-18 at 14 23 40](https://user-images.githubusercontent.com/14805742/85091622-11711300-b212-11ea-8f56-1765c11d70be.png)

Thank you so much!

**Comment by Basts** [comment]
@geralt1011101 

Thank you for contacting us. 

May I ask on which browser did you test this config? I reproduced your case on my local device and everything works fine. 

Tested on: Chrome 83.0.4103.97, macOS Mojave 10.14.6.

Are you able to ZIP your code and share it? If you don't want to do it public you can send it to my email: sebastian.wedzel@blacklabel.pl

**Comment by geralt1011101** [comment]
Hi @Basts

**Comment by ppotaczek** [comment]
Closed due to inactivity.
