### ISSUE TITLE
scrollablePlotArea issue on update config

### ISSUE THREAD

**Issue by dvh91** [highcharts/highcharts-react#234]
When updating the config which causes an update, highcharts' scrollablePlotArea background is getting over the yAxis labels:
https://codesandbox.io/s/highcharts-scrollableplotarea-bug-x7ho0

**Comment by ppotaczek** [comment]
Hi @dvh91,

Thank you for contacting us!

That problem is a Highcharts bug and it is related with updating y-axis when scrollablePlotArea is active. The issue is reported here: https://github.com/highcharts/highcharts/issues/8862
You can use a workaround from the thread.

Best regards!
