### ISSUE TITLE
"Unhandled Rejection (TypeError): I is undefined" when options were updated using setState

### ISSUE THREAD

**Issue by barjuandavis** [highcharts/highcharts-react#235]
I have a React component that should returns a chart after fetching data from a local API.

```js
import React, { useEffect, useState } from 'react'
import { Box, Paper } from '@material-ui/core'
import Highcharts from 'highcharts'
import HighchartsReact from 'highcharts-react-official'
import { generateChartOptions } from './helper'
 
const url = '/api/data.json'
const MyComponent = () => {
  const [state, setState] = useState([])
  
  useEffect(() => {
    const abortController = new AbortController()
    const fetchData = async () => {
      const response = await fetch(url, {signal: abortController.signal})
      const resJson = await response.json()
      const nextState = await {...{...{...resJson}.data}.someData}.hourly
      if (state.length !== nextState.length) setState(nextState)
    }
    fetchData();
    return () => {
      abortController.abort()
    }
  }, [state])

  return (
  <Box>
    <Paper> 
    <HighchartsReact 
      highcharts={Highcharts} 
      options={generateChartOptions(state)}
      allowChartUpdate={true}/> 
    </Paper>
  </Box>)
}

export default MyComponent
```
You can safely assume that ```generateChartOptions(state)``` returns a valid Highcharts options. I've tested it using the returned value of the functions (instead of passing the state via the component).

Then, the component rerenders after waiting the fetch response. After i got the data that i wanted, I got this error returned:

```
Unhandled Rejection (TypeError): I is undefined
translate
C:/dir/highcharts.src.js:32361
translate
C:/dir/highcharts.src.js:37236
redraw
C:/dir/highcharts.src.js:33487
./node_modules/highcharts/highcharts.js/</</X</B.prototype.redraw/<
C:/dir/highcharts.src.js:25547
./node_modules/highcharts/highcharts.js/</</X</B.prototype.redraw
C:/dir/highcharts.src.js:25546
update
C:/dir/highcharts.src.js:35032
./node_modules/highcharts-react-official/dist/highcharts-react.min.js/</</d</<
C:/src/HighchartsReact.js:55
```

Any idea about this issue?

**Comment by ppotaczek** [comment]
Hi @barjuandavis,

Thank you for contacting us! 

Could you reproduce the problem in some online code editor? You can start from:
https://codesandbox.io/s/highcharts-react-demo-qojil?file=/demo.jsx

Best regards!

**Comment by barjuandavis** [comment]
Sorry for the late reply. Seems like I cannot even parse local data on codesandbox?

https://codesandbox.io/s/highcharts-react-demo-1635k?file=/demo.jsx

**Comment by ppotaczek** [comment]
Hi @barjuandavis, 

Here: https://codesandbox.io/s/fetch-local-json-data-m97gv?file=/src/index.js you can find the example with correctly parsed local data, but there is a problem with the data structure passed to the chart.

**Comment by barjuandavis** [comment]
Ah, i see. It was my helper function that returns 'undefined' to the series data array when there are holes in the data. Filling the data with zeroes solved this problem. Thank you!
