### ISSUE TITLE
Organization chart

### ISSUE THREAD

**Issue by AirMust** [highcharts/highcharts-react#237]
Good day, tell me why I get an error when importing (Organization chart)

**Comment by ppotaczek** [comment]
Hi @AirMust, 

You probably missed to also load the `sankey` module:

```
  import Highcharts from "highcharts";
  import sankey from "highcharts/modules/sankey.js";
  import organization from "highcharts/modules/organization.js";

  sankey(Highcharts);
  organization(Highcharts);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-0id6z?file=/demo.jsx

**Comment by AirMust** [comment]
Thank you very much, was this addiction described somewhere? or is it just necessary to know? I mean, it wasn't my attentiveness or not

**Comment by ppotaczek** [comment]
Hi @AirMust,

You are right - there should be some information about that in API. I have reported about that on the main repository: https://github.com/highcharts/highcharts/issues/13954 

Best regards!
