### ISSUE TITLE
Render multiple charts

### ISSUE THREAD

**Issue by bajajneha27** [highcharts/highcharts-react#238]
Hi Team,

Thanks for creating this package. 
Can someone please help me with rendering multiple charts with highcharts-react? I want to access these charts using Hightcharts.charts option.

**Comment by ppotaczek** [comment]
Hi @bajajneha27,

Creating multiple charts with our wrapper is very simple. You just need to render multiple components:

```
  const Charts = () => {
    const [options1] = useState({ series: [{ data: [1, 2, 3] }] });
    const [options2] = useState({ series: [{ data: [3, 2, 1] }] });

    return (
      <div>
        <HighchartsReact highcharts={Highcharts} options={options1} />
        <HighchartsReact highcharts={Highcharts} options={options2} />
      </div>
    );
  };
```

**Live example:** https://codesandbox.io/s/highcharts-react-demo-4ltwy?file=/demo.jsx

Best regards!

**Comment by bajajneha27** [comment]
Thanks @ppotaczek

**Comment by bajajneha27** [comment]
Hey @ppotaczek ,

I need the options to be dynamic and that doesn't seem to work. Example: https://codesandbox.io/s/highcharts-react-demo-1n0y6

**Comment by ppotaczek** [comment]
Hi @bajajneha27,

You need to change the options through state:

```
  const [options, setOptions] = useState([]);

  useEffect(() => {
    setOptions([{
      series: [{ data: [1, 2, 3] }]
    }, {
      series: [{ data: [3, 2, 1] }]
    }]);
  }, []);
```

**Live example:** https://codesandbox.io/s/highcharts-react-demo-wezeo?file=/demo.jsx
**Docs:** https://en.reactjs.org/docs/hooks-state.html
