### ISSUE TITLE
Update to Highcharts 8.1.1

### ISSUE THREAD

**Issue by jamalneufeld** [highcharts/highcharts-react#239]
When using Highcharts 8.1.1 with this react library there is an error `Highcharts is not defined`. How can we get this to work with the new version? There is a security vulnerability on previous versions of the core library.

**Comment by ppotaczek** [comment]
Hi @jamalneufeld,

That problem is probably related with this issue: https://github.com/highcharts/highcharts/issues/13710 
Please check a possible workaround in the thread.

Best regards!

**Comment by jamalneufeld** [comment]
Will check it out. Is there a plan to support this without workarounds?

**Comment by pawelfus** [comment]
See my comment here: https://github.com/highcharts/highcharts/issues/13710#issuecomment-664185507 @jamalneufeld
