### ISSUE TITLE
Support defining options as child components.

### ISSUE THREAD

**Issue by jon-a-nygaard** [highcharts/highcharts-react#24]
There is several who has mentioned that they would like to be able to define the chart options as children compoents.

Example:
```jsx
<HighchartsReact
    highcharts={Highcharts}
    constructorType={'stockChart'}
>
    <Chart>
         <Title>My Chart Title</Title>
    </Chart>
</HighchartsReact>
```

I believe an easy way to support this can be that these children components is returning something that can be interpreted as an option object, and that `HighchartsReact` is merging this result from `props.children` with `props.options` before passing it into the constructor.

This can likely also be extended with `HighchartsReact` providing the said child components should this be wanted.

**Comment by davidysoards** [comment]
I believe that's what has been done here https://github.com/whawker/react-jsx-highcharts
