### ISSUE TITLE
Render Custom React Component on Tooltip Hover

### ISSUE THREAD

**Issue by Emanuel-Agapie** [highcharts/highcharts-react#241]
It would be nice if the tooltip formatter could render a React custom component instead of html only. I need to make a complex tooltip on all types of charts for my project and it would be of great help to simply render React components.

**Comment by ppotaczek** [comment]
Hi @Emanuel-Agapie,

It is a duplicate of: https://github.com/highcharts/highcharts-react/issues/23
Please check the issue above for more information and possible workaround.

Best regards!
