### ISSUE TITLE
Data grouping by buttons problem in react version

### ISSUE THREAD

**Issue by mosijava** [highcharts/highcharts-react#243]
there is a sample in highstock documentation which implement date grouping via rangeSelector buttons.
[link to this sample](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/rangeselector/datagrouping/) 

when I want to implement this behavior in my react app it didn't work.
[you can see the problem here](https://stackblitz.com/edit/highchart-datagrouping-by-rangeselector?file=src/App.js)

I don't know why this doesn't work in first place but after clicking multiple times on buttons it works.

**Comment by ppotaczek** [comment]
Hi @mosijava,

I have reproduced the behavior from the second example without React here: https://jsfiddle.net/BlackLabel/b5p1ymxg/ - if you think that is a bug, you can report it on the main repository: https://github.com/highcharts/highcharts/issues

For the chart to work properly update the chart only with new options: https://stackblitz.com/edit/highchart-datagrouping-by-rangeselector-7hyyrs?file=src/App.js or render the chart component after getting the data.

Best regards!

**Comment by mosijava** [comment]
thank you very much.
I will report that odd update behavior on them main rep.

**Comment by mosijava** [comment]
just a question:
does updating the chart only with new option affect on chart efficiency?

**Comment by ppotaczek** [comment]
Mostly rather slightly, but it is a good practice: https://github.com/highcharts/highcharts-react#optimal-way-to-update
