### ISSUE TITLE
Confuse about the update operation

### ISSUE THREAD

**Issue by poppinlp** [highcharts/highcharts-react#246]
Hi.

> A good practice is to keep all chart options in the state. When setState is called, the options are overwritten and only the new ones are passed to the chart.update method.
> Live example: https://stackblitz.com/edit/react-hketvd?file=index.js

I've tried the sample in README above. But it seems still do the updating always. To make it more obvious, I've edited it a little that updating the state by interval timer with the same series array consists of 2000 numbers.

You could find the [sample code here](https://stackblitz.com/edit/react-yb6sjz?file=index.js) and the [result page of running code here](https://react-yb6sjz.stackblitz.io/). In the result page, you could see the CPU usage is pretty high in the chrome dev tool, and the painted area is always flashing.

Am I did something wrong? Thanks.

**Comment by ppotaczek** [comment]
Hi @poppinlp,

Thank you for contacting us!

Updating 2000 points per 100 milliseconds with animation it's quite heavy operation. Please check similar example without react: http://jsfiddle.net/BlackLabel/6u159edb/

I suggest you to disable animation: http://jsfiddle.net/BlackLabel/7hxnq8fu/ and if that is not enough use the `boost` module: https://www.highcharts.com/docs/advanced-chart-features/boost-module

Best regards!

**Comment by poppinlp** [comment]
Hi @ppotaczek,

Thanks for your reply.

Actually, my purpose is not to keep updating 2000 points. I just wanna update the modified ones as your README said:
> only the new ones are passed to the chart.update method.

So I've tested it with a freezing array and expect no updating after the first render, but seems the chart always updates all data.

Am I misunderstanding the README?

**Comment by poppinlp** [comment]
Maybe I should do it via filter out the modified data in my logic and do points update for them instead of putting the whole series to highcharts?

**Comment by ppotaczek** [comment]
In that case calling `setState({ chartOptions: { options }} )` results in `chart.update({ options })`. 

> only the new ones are passed to the chart.update method.

The term 'the new ones' means all the options in a new state, the wrapper doesn't provide any filter to the options.

**Comment by poppinlp** [comment]
Oooops. Sorry. Seems it's my misunderstanding. T_T
Thank you so much.

**Comment by ppotaczek** [comment]
> Maybe I should do it via filter out the modified data in my logic and do points update for them instead of putting the whole series to highcharts?

That might be a good idea. You can get the chart reference and call the `addPoint` method directly on a series, with `redraw` parameter set to `false` and redraw the whole chart after all updates.

**Docs:** https://github.com/highcharts/highcharts-react#how-to-get-a-chart-instance

**Comment by poppinlp** [comment]
Yep. Thanks. :)

**Comment by poppinlp** [comment]
Hi @ppotaczek,

I'm back again. :)

I've made a test [here](https://stackblitz.com/edit/highcharts-try-instance?file=index.js) with just one point update after load event. But I see the repainted area in chrome dev tool is still the whole chart, even the numbers on the axis.

Could I do something to avoid it? I've disabled the animation and loaded boost module already.

**Comment by ppotaczek** [comment]
Hello @poppinlp,

> But I see the repainted area in chrome dev tool is still the whole chart, even the numbers on the axis.

That is true, the `point.update` method fires `chart.redraw` and it is necessary to calculate again axes extremes, series dimensions and positions of other elements. Changing one point can change a lot across the entire chart.

If you would like to prevent such behavior, you would have to operate directly on svg.

Best regards!

**Comment by poppinlp** [comment]
OK. Thanks.
