### ISSUE TITLE
Make chart Fullscreen

### ISSUE THREAD

**Issue by hkedia321** [highcharts/highcharts-react#247]
Is there any feature in react-highcharts that makes the chart full screen?
In highcarts there seems to be this feature: https://github.com/highcharts/highcharts/pull/12821

**Comment by ppotaczek** [comment]
Hi @hkedia321,

Thank you for contacting us!

All Highcharts features are supported by our wrapper. All you need to do is to import and initialize the `full-screen` module. Example of use:

```
  const App = () => {
    const chartComponent = useRef(null);
    ...

    const toggleFullscreen = () => {
      chartComponent.current.chart.fullscreen.toggle();
    };

    return (
      <div>
        <button onClick={toggleFullscreen}>Toggle fullscreen</button>
        <HighchartsReact
          ...
          ref={chartComponent}
        />
      </div>
    );
  };
```

**Live example:** https://codesandbox.io/s/highcharts-react-demo-forked-0snmf?file=/demo.jsx

Best regards!

**Comment by hkedia321** [comment]
Hi @ppotaczek thanks for the answer! But using it is giving some weird user experience: after coming back from full screen, the size of the original graph is changing. Is that a bug? Any idea how to fix it?
![image](https://user-images.githubusercontent.com/17807257/90660603-c603d100-e263-11ea-88a4-9bd5e7567a20.png)

**Comment by ppotaczek** [comment]
Hi @hkedia321,

That is a bug in the `full-screen` module which is reported here: https://github.com/highcharts/highcharts/issues/13222 

As a workaround you can set the height by CSS styles.

Best regards!

**Comment by brianzhou13** [comment]
Is there an updated answer for this? I tried the sandbox link, and it doesn't work. :( 

Thanks!

**Comment by ppotaczek** [comment]
Hi @brianzhou13, The issue should be fixed. Please add more information if you still have some problems.
