### ISSUE TITLE
Can't fetch the chart instance by ref

### ISSUE THREAD

**Issue by poppinlp** [highcharts/highcharts-react#249]
Hi. It's me again. Thanks for the nice tool.

I try to follow the [README](https://github.com/highcharts/highcharts-react#how-to-get-a-chart-instance) to access the chart instance by ref. But seems it doesn't work.
But in the load event, I could get it. And in the callback, I could get is also.

Here's my [sample code](https://stackblitz.com/edit/highcharts-boost?file=index.js).

Thanks.

**Comment by tiencong283** [comment]
I think you forgot to bind this to the button handler.

**Comment by ppotaczek** [comment]
Hello again!

Since v3.0.0 `highcharts-react-official` is a functional component and it is not possible to use ref attribute on it. You need to use one of the other ways to get the instance.

Thanks for pointing this out, I have to change the information about that in the docs.

Best regards!

**Comment by poppinlp** [comment]
Got it. Thanks. :)

**Comment by jenshedqvist** [comment]
The documentation is outdated and misleading then: https://www.npmjs.com/package/highcharts-react-official#how-to-get-a-chart-instance

**Comment by ppotaczek** [comment]
Hi @jenshedqvist,

Yes, it needs to be improved. If your parent component is a class component and `highcharts-react-official` v3.0.0 is used, the only way to get a chart reference is to use callback.
