### ISSUE TITLE
StockChart - Grouping trades operations by hour, days etc.

### ISSUE THREAD

**Issue by SmashPlusUltra** [highcharts/highcharts-react#254]
Hi there!
I have the following input
`[{ticker: "appl", servertime: 1576248016816, volume: 100, price: 84, datetime: "2019-12-13 14:40:16.816"},
 {ticker: "appl", servertime: 1576251054510, volume: 25, price: 86.496, datetime: "2019-12-13 15:30:54.510"}]
`
I'm converting it into a format like 
`[{x: 1576234800000, open: 84, high: 84, low: 84, close: 84, …},
{x: 1576238400000, open: 86.496, high: 86.497, low: 86, close: 86, …}]`
When I'm converting the data I'm grouping it in days, and manually calculate the open, high, low and close value.

**Is there a way**, having the trades, **to specify the time frame in which I want that trades to be grouped and display it in the stockchart automatically?**

**Comment by Basts** [comment]
Hi @SmashPlusUltra,

Thank you for contacting us!

Have you already seen the `dataGrouping.approximation` feature? Have you tried to use and customized it for your needs?

API: https://api.highcharts.com/highstock/series.line.dataGrouping.approximation

**Comment by Basts** [comment]
Closed due to inactivity.
