### ISSUE TITLE
Error when loading Boost module

### ISSUE THREAD

**Issue by bferreira** [highcharts/highcharts-react#256]
Not sure if this should be here our on the Highcharts  repo, but I am trying to use Boost module with Highcharts and highcharts-react-officia. l get the following TypeError 
![image](https://user-images.githubusercontent.com/1233578/94439323-8ef8d780-01a0-11eb-9fda-495b3ee2e476.png)

I think I am doing the imports correctly
```

import * as Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import HighchartsBoost from 'highcharts/modules/boost';

HighchartsBoost(Highcharts);
```

And I am using NextJS
Any pointers that I can try? could I be missing something on my Typescript settings.

**Comment by bferreira** [comment]
This was happening because boost module cannot be compiled on the server side. I solved  it by:
```
if (typeof window !== 'undefined') {
  HighchartsBoost(Highcharts);
}
```
And it still didn't work because I was setting the type of curve "Spline" on the series and only works with "line"

**Comment by Basts** [comment]
Hello @bferreira,

Thank you for contacting us.

I tried to reproduce your issue and seems that everything works as it should be without any additional checking which you have added. Take a look at this demo: https://stackblitz.com/edit/react-2x36qh?file=index.js

> And it still didn't work because I was setting the type of curve "Spline" on the series and only works with "line"

In the documentation you can find informations that:

>  Including modules/boost.js will, by default, activate boost for all series that support it (line series, column, bar, treemap, heatmap, scatter, bubble, area).

Which means that "Spline" series is not supported. More: https://www.highcharts.com/docs/advanced-chart-features/boost-module
