### ISSUE TITLE
gridlines and series labels do not update when changing chart options in non styled mode

### ISSUE THREAD

**Issue by chadi-kazan** [highcharts/highcharts-react#258]
`highcharts@8.2.2`
`highcharts-react-official@3.0.0` not that it's relevant
`react@16.12.0`

if i update the chart options, the `gridLineWidth` is taken into account only once. so are the series labels.
subsequent changes are not applied.
**this** works fine
`gridLineWidth = 0` then `gridLineWidth = 1`

**this** does not
`gridLineWidth = 0` then `gridLineWidth = 1` then `gridLineWidth = 0`
### to reproduce it
https://codesandbox.io/s/purple-sunset-hb1ul

It seems as if highcharts changes the inner values of the first `options` object passed to it when it receives a different object which would explain why the third time we end up with `gridLineWidth`  set to 1 instead of 0

edit: corrected eplanation

**Comment by ppotaczek** [comment]
Hi @chadi-kazan,

Thanks for reporting!

That problem looks like a Highcharts bug, so I reproduced it without React and reported it here: https://github.com/highcharts/highcharts/issues/14305.

Best regards!
