### ISSUE TITLE
Re-rendering scrollable bar chart causes layering issue

### ISSUE THREAD

**Issue by hyper-jarrod** [highcharts/highcharts-react#259]
Hello,

I am rendering a bar chart with scrolling enabled. On the initial render everything shows as expected. When the component is re-rendered the horizontal axis label are no longer fixed to the bottom of the chart.

![Screen Shot 2020-10-08 at 1 42 40 pm](https://user-images.githubusercontent.com/39473775/95409582-a8064300-096d-11eb-8943-af2d46f2f7da.png)

I have reproduced the issue in this codesandbox project:
https://codesandbox.io/s/frosty-mendel-fkwqf?file=/src/App.tsx

It renders the chart and after 5 seconds forces a state change on App component which re-renders the Chart (no chart values changed). I can see in the DOM that `class="highcharts-axis-labels highcharts-yaxis-labels"` is nested in the SVG beneath `class="highcharts-fixed"` on the first render, but on the second render it is nested in the SVG beneath `class="highcharts-scrolling"`.

If I remove all properties from ChartOptions.yAxis then the issue does not occur.

**Comment by Basts** [comment]
Hello, 

Thank you for contacting us.

It seems that it is a general bug in the Highcharts, not in the Highcharts React Wrapper.

Demo: https://jsfiddle.net/BlackLabel/a367g9uv/

I reported it here, where you can follow this thread and expect the workaround: https://github.com/highcharts/highcharts/issues/14323
