### ISSUE TITLE
Solidgauge pane track flickers on React component update starting Highcharts v8.1.0

### ISSUE THREAD

**Issue by andreyp-pragma** [highcharts/highcharts-react#260]
After updating from Highcharts v8.0.0 to Highcharts v8.2.0 we noticed that the Solidgauge chart began to flicker on React component updates that wraps the Highcharts. After testing different Highcharts versions it became clear that the bug was introduced starting v8.1.0. Here's the demo:

https://codesandbox.io/s/vigilant-pascal-hmizx?file=/src/CircleGauge.tsx:893-903

**Comment by Basts** [comment]
@andreyp-pragma,

Thank you for reporting it. I took a while to find out the reason. It seems that it is Highcharts behaviour, not related to the wrapper works. The thread will be continued here: #14351.
