### ISSUE TITLE
Chart not resizing with container

### ISSUE THREAD

**Issue by rajatmadaan786** [highcharts/highcharts-react#261]
Hello,
I am using '**highcharts-react-official**' inside the resizeable div elements. When I am resizing a div to make it big or small, The chart is not changing its height and width according to the container div. I am not able to find out any option or prop which can help me to fix this issue.

You can see the issue here:
https://stackblitz.com/edit/react-wo7kyd

When you will click the parent div, Its height and width will be changed but the chart will not. I tried to change the chart svg and chart container width and height manually, But it's not working in a correct way.

**Comment by ppotaczek** [comment]
In this case you need to use the `reflow` method:

> **reflow( [e])**
>
> Reflows the chart to its container. By default, the chart reflows automatically to its container following a window.resize event, as per the chart.reflow option. However, there are no reliable events for div resize, so if the container is resized without a window resize event, this must be called explicitly.

___

**Live demo:** https://stackblitz.com/edit/react-1ifhgc
**API Reference:** https://api.highcharts.com/class-reference/Highcharts.Chart#reflow

**Comment by rajatmadaan786** [comment]
No, It's not working when div is resizing. I called the reflow() function when the user ends up resizing the div.

**Comment by ppotaczek** [comment]
Hi @rajatmadaan786, It works fine in the live example that I provided. Could you create another where it is not working?

**Comment by rajatmadaan786** [comment]
Okay, I will try to create another example.

**Comment by rajatmadaan786** [comment]
Here's the live example URL:
https://react-bjtmoe.stackblitz.io/

When you click on the blue line, The container size will increase but the chart inside it is not increasing it's size according to container. You can see the code here: https://stackblitz.com/edit/react-bjtmoe

**Code Explanation:**

The code itself is very easy to understand as I have written it from scratch to make it easy to understand that what the problem is. I have created two components, `chart.js` & `chart_container.js`. The `chart_container.js` file is basically a wrapper around the charts. I have data logic here in this file & after processing, I am passing data and DOM element to my `chart.js` file which will render the actual chart to the DOM.  

I created ref inside `chart.js` file and passed it to the `HighchartsReact` component and after Highcharts rendered to the DOM, I returned the ref to the chart container and called `reflow()` method there. `reflow` method is available but I am not getting why it's not increasing or decreasing its size according to container size.

If you still have any confusion in explanation then you can ask.

Thank you.

**Comment by ppotaczek** [comment]
Hi @rajatmadaan786,

Thanks for the example. The `reflow` method needs to be called after every resize, you have called it only once in the `componentDidMount` method. Please check the below example, I call reflow in the 'onclick' event callback function.

**Live demo:** https://stackblitz.com/edit/react-pcfzsu?file=src%2Fchart_container.js

Best regards!

**Comment by SaeedZhiany** [comment]
@ppotaczek 

Thanks for the solution. it works but by using the reflow function we will lose the chart's animations.

What should we do for it?

**Comment by SaeedZhiany** [comment]
@ppotaczek 

Thanks for the solution. it works but by using the reflow function we will lose the chart's animations.

What should we do about it?
