### ISSUE TITLE
Spline and Line chart do not drawing at safari MacOs and iOs

### ISSUE THREAD

**Issue by TrueSpil** [highcharts/highcharts-react#263]
...

**Comment by ppotaczek** [comment]
Hi @TrueSpil,

Have you already solved your problem?

Best regards!

**Comment by TrueSpil** [comment]
yeah, sry. That was a problem with moment js date formatting from
custom string.

вт, 10 нояб. 2020 г. в 22:44, Paweł Potaczek <notifications@github.com>:
