### ISSUE TITLE
Unicode characters are not shown in exported png

### ISSUE THREAD

**Issue by grindsa** [highcharts/highcharts-react#265]
I am trying to display a headmap with unicode characters in the dataLabel. Even if the characters are shown in browser they are not visible in the exported image. 

Without the wrapper the download works fine. Thus I suspect something wrong in either my code or the wrapper as such. Can you please point me into the right direction?

[Code without wrapper (download works fine)](https://codepen.io/grindsa/pen/jOrJjOd)
[Code with wrapper (unicode chars are not shown)](https://codesandbox.io/s/highcharts-unicode-ygfee)

Thank you for your help and have a nice day

**Comment by Basts** [comment]
Hello @grindsa,

Thank you for contacting us.

There is a small difference between those two demos - the demo without the React wrapper also has included the `offline-exporting` module which is responsible for exporting the Unicode characters. After including this module into the demo with the wrapper everything works fine. Take a look: https://stackblitz.com/edit/react-aovsbf?file=index.js

**Comment by grindsa** [comment]
Hi, thank you for your replay and sorry for my delayed answer. You were totally right. After adding the offline-exporting module everything worked as expected.
