### ISSUE TITLE
Cannot read property 'apply' of undefined - on quick mount/unmount

### ISSUE THREAD

**Issue by kiknaio** [highcharts/highcharts-react#266]
React renders multiple charts at once and mount/unmount them in a short interval, because of that I'm getting 
```js
Cannot read property 'apply' of undefined
```
this error. 
Couldn't find anything relevant on the internet, so I decided to create an issue.
Also getting this error in console:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
```

**Comment by ppotaczek** [comment]
Hi @kiknaio,

Thank you for contacting us! Could you reproduce the problem in some online code editor? 
You can start from:  https://codesandbox.io/s/highcharts-react-demo-forked-yi81d?file=/demo.jsx

**Comment by ppotaczek** [comment]
Closed due to inactivity.
