### ISSUE TITLE
Support for custom legends outside of chart

### ISSUE THREAD

**Issue by ashokkumarsand** [highcharts/highcharts-react#271]
In **highcharts** we can create legends outside the chart container but with **highchart-react** this seems not possible.

**Comment by ppotaczek** [comment]
Hi @ashokkumarsand,

Thank you for contacting us!

Could you describe more precisely what do you want to achieve and what problems did you encounter? 

Best regards!

**Comment by ashokkumarsand** [comment]
`  <Row className="no-gutters">
          <span className={styles.title}>Title</span>
          {chart &&
            chart.series.map((series) => {
              return (
                <div className={styles.legend} key={series.name}>
                  <div
                    className={styles.symbol}
                    style={{ backgroundColor: series.color }}
                  />
                  <div className={styles.seriesName}>{series.name}</div>
                </div>
              );
            })}
        </Row>

        <HighchartsReact
          highcharts={Highcharts}
          options={chartOptions}
          allowChartUpdate={true}
          callback={onChartUpdated}
        />`

Requesting to provide support for outside to render legends bypassing only div ref to `HighchartsReact` component.

**Comment by ppotaczek** [comment]
Hi @ashokkumarsand,

Thanks for the information. I have created an example how to create a custom legend outside a chart, please check the below code:

```
const App = () => {
  const [chart, setChart] = useState(null);
  const [options, setOptions] = useState(...);

  return (
    <>
      <div>
        <span>Title</span>
        {chart &&
          chart.series.map((series) => {
            return (
              <div key={series.name}>
                <div style={{ backgroundColor: series.color }} />
                <div>{series.name}</div>
              </div>
            );
          })}
      </div>

      <HighchartsReact
        highcharts={Highcharts}
        options={options}
        callback={(chart) => setChart(chart)}
      />
    </>
  );
};
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forked-qk4im?file=/demo.jsx

**Comment by ashokkumarsand** [comment]
I am using a similar way to creating legends, but there is no inbuild external legends component So I can use all functions associated with legends without external effort.

Thank you
