### ISSUE TITLE
In a candlestick with volume chart, set volume bar columns based on up day/down day (with data grouping)

### ISSUE THREAD

**Issue by akhtariali** [highcharts/highcharts-react#275]
I use the following snippet to set the volume bar colors:
``` 
const splitData = (data: number[][]) => {
    // split the data set into ohlc and volume
    let ohlc: number[][] = [],
      volume: VolumeData[] = [],
      dataLength = data?.length,
      i = 0;

    for (i; i < dataLength; i += 1) {
      const [date, open, high, low, close, vol] = data[i];

      ohlc.push([date, open, high, low, close]);

      const isUpDay = close >= open;

      volume.push({ x: date, y: vol, color: isUpDay ? '#2f7ed8' : '#dd31ae' });
    }

    return { ohlc, volume };
  };
```

Everything works fine until HighCharts starts grouping the data.

I tried to use the following method on `reflow`, `render`, and `load` chart events to update the color of volume bars; needless to say, I failed :)

```
  const setVolColColors = ({ target }) => {
    const [priceActionSeries, volumeSeries] = target.series;

    const volumeColumns = volumeSeries.groupedData;
    const priceActionCandles = priceActionSeries.points;

    if (!volumeColumns || !priceActionCandles) return;

    priceActionCandles.forEach((candle, index) => {
      const candleStroke = candle?.graphic?.stroke;
      if (!candleStroke) return;

      volumeColumns[index].color = candleStroke;
    });
  };
```

What is even funnier is that when hovered, volume bars change their color to the correct color.

You can find a live demo here: https://codesandbox.io/s/highcharts-react-demo-forked-deg3h?file=/demo.jsx

**Comment by ppotaczek** [comment]
Hi @akhtariali,

Thank you for contacting us!

By changing `volumeColumns[index].color` you overwrite only an object property, not a column color (after hovering the point is updated and the color is is included). You can change the color of a column immediately by using `attr` method. Example:

    priceActionCandles.forEach((candle, index) => {
      const candleStroke = candle?.graphic?.stroke;
      if (!candleStroke) return;

      volumeColumns[index].color = candleStroke;
      volumeColumns[index].graphic.attr({
        fill: candleStroke
      });
    });

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forked-gksiv?file=/demo.jsx
**API Reference:** https://api.highcharts.com/class-reference/Highcharts.SVGElement#attr

Best regards!

**Comment by akhtariali** [comment]
Worked swiftly! Thanks a lot.
