### ISSUE TITLE
React hooks example may be incorrect

### ISSUE THREAD

**Issue by nareshbhatia** [highcharts/highcharts-react#276]
I am referring to the React Hooks example in the README under [Optimal way to update](https://github.com/highcharts/highcharts-react#optimal-way-to-update). The example provided is on [stackblitz](https://stackblitz.com/edit/react-nwseym?file=index.js).

The issue is with the `updateSeries` function:

```
const updateSeries = () => {
    setChartOptions({ 
      series: [
          { data: [Math.random() * 5, 2, 1]}
        ]
    });
}
```

This function is overwriting `chartOptions` with only the series data instead of the full chart options object. While this kind of code is ok for a class component (React will do the merge), it is not ok in a function component. Please see [React docs here](https://reactjs.org/docs/hooks-state.html#tip-using-multiple-state-variables):

> unlike this.setState in a class, updating a state variable always replaces it instead of merging it.

Am I missing something?

What confuses me even more is that the example seems to be working fine. Does that mean that the chart has internal state and it does some sort of a merge internally?

**Comment by ppotaczek** [comment]
Hi @nareshbhatia,

Thank you for contacting us!

You shouldn't think about a chart like about a component. A chart created by our wrapper is just a basic chart and it works in the same way as here: http://jsfiddle.net/BlackLabel/sun9hzw0/ 
Options are stored internally in a chart and if you change state, `chart.update` is called.

Use the `immutable` option if you want to reflect options from state - chart will be recreated on each change, similar as here: http://jsfiddle.net/BlackLabel/54apc31e/

Best regards!

**Comment by nareshbhatia** [comment]
Thanks @ppotaczek. That clears up my mental model for `<HighchartsReact>` component.

I found a similar option called `allowChartUpdate`. Is this just the opposite of `immutable` or there is more to it?

**Comment by ppotaczek** [comment]
No, `allowChartUpdate` is not the opposite of `immutable`. It just completely block updating or recreating a chart. It can be useful if you want to for example update or recreate a chart after multiple changes (not after every) in a parent component state.

**Comment by nareshbhatia** [comment]
Got it. Thank you for the clarification, @ppotaczek.
