### ISSUE TITLE
Resetting min/max values for an Axis 

### ISSUE THREAD

**Issue by vmlopezr** [highcharts/highcharts-react#277]
I am working on displaying charts where options like the min/max values of an axis can be changed via inputs.

When setting these values with numbers there are no issues. However if we want to reset to the automatic values (setting min or max to null or undefined) the chart does not update back.

This is of course not an issue if we're using the `immutable={true}` prop, but was curious if anyone's gotten this working without it?

https://stackblitz.com/edit/react-3bhxma?file=index.js

**Comment by ppotaczek** [comment]
Hi @vmlopezr,

Thank you for contacting us!

To reset the min/max options, set their values to `null`.

```
  const resetMinValue = () => {
    setMinValue(null);
  };
```
  
**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forked-b43cf?file=/demo.jsx

**Comment by vmlopezr** [comment]
Yep that solves it. Thanks for the help! I'll keep that in mind for other properties as well!
