### ISSUE TITLE
How can I reset highcharts zoom programatically?

### ISSUE THREAD

**Issue by dylanpark** [highcharts/highcharts-react#278]
I want to reset the zoom level of highcharts when an external button component is pressed.
How can I achieve this?

**Comment by ppotaczek** [comment]
Hi @dylanpark,

Thank you for contacting us! 

You can get a chart reference and call `setExtremes` method without arguments for both axes.

```
  const resetZoom = () => {
    if (chartComponent.current) {
      chartComponent.current.chart.xAxis[0].setExtremes();
      chartComponent.current.chart.yAxis[0].setExtremes();
    }
  };
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forked-wluow?file=/demo.jsx
**API Reference:** https://api.highcharts.com/class-reference/Highcharts.Axis#setExtremes

**Comment by ppotaczek** [comment]
Closed due to inactivity.
