### ISSUE TITLE
Loading highchart data dynamically on the client side.

### ISSUE THREAD

**Issue by nectario** [highcharts/highcharts-react#279]
I have 20 charts to display. How can I load the data dynamically in the client side instead of the server to speed it up? Right now it takes 15 seconds to load.

**Comment by ppotaczek** [comment]
Hi @nectario,

Thank you for contacting us!

You can get data through API request to your server and update a component state with the data. Please check the below example.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forked-rx5ef?file=/demo.jsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
