### ISSUE TITLE
Responsive Charts

### ISSUE THREAD

**Issue by t0tallyKy1e** [highcharts/highcharts-react#280]
Hello!

Hopefully this is the right place to ask this question :)
I'm currently working on a feature that uses `react-grid-layout` and `highcharts-react`, but for some reason I can't seem to get any of the responsive options working. I have an [example here](https://codesandbox.io/s/highcharts-react-demo-forked-ogv5w?file=/demo.jsx) using a forked version of the demo listed in the README with some basic parts of the chart that should be removed once the chart is below 300px.
Am I completely missing something silly or does the responsive behavior not work in this version?

**Comment by ppotaczek** [comment]
Hi @t0tallyKy1e,

Thank you for contacting us!

The structure of the responsive options is incorrect,  instead of:

        responsive: {
          condition: {
            maxWidth: 300
          },
          chartOptions: {
            credits: {
              enabled: false
            },
            legend: {
              enabled: false
            }
          }
        }

use: 

        responsive: {
          rules: [{
            condition: {
              maxWidth: 300
            },
            chartOptions: {
              credits: {
                enabled: false
              },
              legend: {
                enabled: false
              }
            }
          }]
        }

**API Reference:** https://api.highcharts.com/highcharts/responsive

Best regards!

**Comment by t0tallyKy1e** [comment]
Thanks for the quick response! I'm a little embarrassed that I missed that in the demo I provided lol - it's been a long week.
In my actual implementation I seem to have the correct configuration, but I'll see if I missed something else silly and get back to you. Thanks again!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
