### ISSUE TITLE
Single element at series data

### ISSUE THREAD

**Issue by alexandermirzoyan** [highcharts/highcharts-react#281]
Hi,
When I add only one element on a data, it is not shown on a line chart. I want to show only a single point on my chart.
I have already tried to add a config for single element like this.
```
marker: {
      visible: true
}
```

My data looks like this
```
{
   color: "#36C1A3"
   data: [354]
   name: "Line name"
   type: "spline"
}
```

I am using 
"react": "^16.13.1",
"highcharts": "^9.0.0",
"highcharts-react-official": "^3.0.0",

**Comment by ppotaczek** [comment]
Hi @alexandermirzoyan, 

Thank you for contacting us!

The case that you have described seems to work here: https://codesandbox.io/s/highcharts-react-demo-forked-0tvsw?file=/demo.jsx 
Could you reproduce the problem?

Best regards!

**Comment by alexandermirzoyan** [comment]
Thank you, dear @ppotaczek, I think my code had a bug, now it was resolved.
