### ISSUE TITLE
Ref losing issue after executing exportChart (or exportChartLocal) method

### ISSUE THREAD

**Issue by nick-mychka** [highcharts/highcharts-react#284]
Hi! I faced an issue with ref losing after invoking the exportChartLocal method (actually the same issue present with exportChart method)
Steps to reproduce: 
1. Click on the Chart Export button (the chart is exported)
2. Click on the Chart Export button again and you get an error "Cannot read property 'exporting' of undefined"

And last but not least if I want to add an image to the chart on chart load event via `chart.renderer.image(...).add()` then the chart not exported at all.
Step to reproduce: 
1. Uncomment chart option then try to make export (chart not exported)

**Base code example**: https://codesandbox.io/s/cool-heyrovsky-bxcp2?file=/src/App.js
How can I handle it? Thanks

**Comment by ppotaczek** [comment]
Hi @nick-mychka,

Thank you for contacting us! 

Highcharts creates a new chart instance for exporting and destroys it after the operation. That invokes the callback function - 'afterChartCreated' and overwrites the reference. To avoid that, save the reference only if it is not exist.

    afterChartCreated = (chart) => {
      if (!this.internalChart) {
        this.internalChart = chart;
      }
    };
    
As to your second problem - you are trying to export very big image and it freezes the process, examples: 
1. With your image: http://jsfiddle.net/BlackLabel/rb5gmyxw/
2. With some light image: http://jsfiddle.net/BlackLabel/z3qu2h4e/

**Docs:** https://www.highcharts.com/docs/export-module/client-side-export

**Comment by nick-mychka** [comment]
Thanks for the response!
