### ISSUE TITLE
3D option

### ISSUE THREAD

**Issue by samuelsowl** [highcharts/highcharts-react#288]
I was wondering is there the 3d option in react. I tried it in the piechart and it only showed 2d. Thank you.

**Comment by ppotaczek** [comment]
Hi @samuelsowl,

Thank you for contacting us!

Yes, our wrapper supports all Highcharts features. You probably missed to load `highcharts-3d` module.

```
// Import Highcharts
import Highcharts from "highcharts/highstock";
import HC3D from "highcharts/highcharts-3d";

HC3D(Highcharts);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forked-hi0v9?file=/demo.jsx

**Comment by ppotaczek** [comment]
Closed due to inactivity.
