### ISSUE TITLE
How to call reflow?

### ISSUE THREAD

**Issue by andrasferenczi** [highcharts/highcharts-react#29]
I have a similar problem just like [this OP from StackOverflow.](https://stackoverflow.com/questions/37191338/react-highcharts-how-to-call-reflow), though obviously using this wrapper around Highcharts.

I use Highchart inside divs and the chart won't resize by itself (it only gets smaller, but never bigger) and I assume I have to call the `reflow` function explicitly.

So what would be the way to call `reflow` on the component?

**Comment by sebastianbochan** [comment]
Hi @andrasferenczi,
The problem can be also related with CSS styles. Have you tried to set width:100% in chart's container div?

**Comment by KacperMadej** [comment]
You could get `chart` (on which you could later call `chart.reflow()`) from [load event](https://api.highcharts.com/highcharts/chart.events.load) - it's the context in the function. 

As Sebastian already mentioned: if size is not correct then you could check if there's a race problem (size change after function run, etc.) or a layout that could be changed into something simpler (unnecessary or forced display style in CSS, etc.).

**Comment by andrasferenczi** [comment]
Yes, `100% width` solved the issue, earlier on it was on auto and every other HTML element fit properly, except `Highchart`. 

Thanks for your help.

@sebastianbochan Just one more question: could you tell me what the problem with `auto` was in that case?

Anyway, I've typed this out, so I am going to leave it for anyone who might see something similar.

This is my css file:

    .react-grid-item > :not(.react-resizable-handle),
    .box > * {
        width: auto;
        height: auto;
        max-width: calc(100% - 40px);
        max-height: calc(100% - 40px);
    
        margin: 20px;
    }

This is what I am seeing:

![problem](https://user-images.githubusercontent.com/17592224/40996748-e6e20112-6902-11e8-924c-f7a3d5c98a61.gif)

As you can see, the image is resized accordingly. That is why I assumed that the problem should be on `Highcharts` side.

**Comment by sebastianbochan** [comment]
Hi @andrasferenczi,
It can be related with non floated objects (`float:left;`). Anyway it is difficult to predict, cause I do not have an access to live demo.

Im closing this ticket, cause its related with CSS not HC.
