### ISSUE TITLE
Highcharts does not work in Internet Explorer 11 if it is open in the portal

### ISSUE THREAD

**Issue by e965** [highcharts/highcharts-react#291]
When opening the portal, a HierarchyRequestError is thrown and the application crashes.

![image](https://user-images.githubusercontent.com/18071040/112528131-956db200-8dc5-11eb-9309-78cba59eda97.png)

Demo https://e965.github.io/react-highcharts-portal-demo/
Source https://github.com/e965/react-highcharts-portal-demo

In other browsers everything is fine:

Chrome (Edge):

![image](https://user-images.githubusercontent.com/18071040/112527408-d5806500-8dc4-11eb-87db-d236a789bc3a.png)

Firefox:

![image](https://user-images.githubusercontent.com/18071040/112527305-be417780-8dc4-11eb-9e21-e659938627dd.png)

**Comment by e965** [comment]
Continue to experiment. Added a [react-jsx-highcharts](https://www.npmjs.com/package/react-jsx-highcharts) package to the demo. Unfortunately, the application also crashes with it.

It looks like some kind of problem directly with the Highcharts. 🤔

**Comment by ppotaczek** [comment]
Hi @e965,

Thank you for contacting us!
This problem can be also only related with IE11 and React. Please try to reproduce it only with Highcharts and IE and if the problem persist, report it on the main repo.

Best regards!
