### ISSUE TITLE
Print is not working

### ISSUE THREAD

**Issue by comertcimen** [highcharts/highcharts-react#293]
I am trying to use the print button in the context menu. When I click it, my computer is starting to overheat and the windows freezes and I only see the chart in smaller size and loading preview screen. I use latest highcharts and highcharts-react. It is not about big date, I am using just months and simple numbers. Example codes on jsfiddle just works. (Vanilla js examples).
I am able to download as pdf or png by the way so I think there is no problem with exporting module.

**Comment by ppotaczek** [comment]
Hi @comertcimen,

Thank you for contacting us!

Could you provide me with a minimal live code reproduction of the problem. You can use this simple example to start: https://codesandbox.io/s/highcharts-react-demo-forked-yi81d?file=/demo.jsx

Best regards!

**Comment by comertcimen** [comment]
I rewrite the code on codesandbox but the same code crashes my app, I could understand the problem.

https://codesandbox.io/s/currying-dust-6j16j?file=/src/App.js

**Comment by ppotaczek** [comment]
Hi @comertcimen,

Your code looks fine, maybe you have used some different Highcharts or wrapper version in your app?

Best regards!

**Comment by comertcimen** [comment]
`"highcharts": "^9.0.1",
"highcharts-react-official": "^3.0.0",`

I used yarn, maybe I should use it with npm. Thanks.
