### ISSUE TITLE
Which highcharts-react version support react 15.6.2

### ISSUE THREAD

**Issue by avivaWang** [highcharts/highcharts-react#294]
In my project still use react 15.6.2 version, recently we want to use highcharts, so I want to know which highcharts-react version support react 15.6.2?

**Comment by ppotaczek** [comment]
Hi @avivaWang,

Thank you for contacting us!

Our wrapper supports React 15.6.2 in version 1.4.

Live demo: https://codesandbox.io/s/highcharts-react-demo-forked-r3mf7?file=/demo.jsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
