### ISSUE TITLE
how to get class component 'this' inside highChart event function

### ISSUE THREAD

**Issue by oaoxd0314** [highcharts/highcharts-react#295]
I am trying to use master-detail chart with line chart,and i want to change line chart's data when I select zoom in master-detail chart.

But I can't access class 'this' in highchart state.

How can i do that,any suggestion will be grateful.

here is my code
https://stackblitz.com/edit/react-xyoj8w

**Comment by ppotaczek** [comment]
Hi @oaoxd0314,

Thank you for contacting us!

You can get a reference to a component by using an arrow function and get chart from the event.

          events: {
            selection: (event) => {
              var chart = event.target,
                extremesObject = event.xAxis[0],
                min = extremesObject.min,
                max = extremesObject.max,
                detailData = [],
                xAxis = chart.xAxis[0];

              ...
              console.log(this);
              console.log(detailData);

              return false;
            }
          }

**Live demo:** https://stackblitz.com/edit/react-uhbyrc?file=withMasterDetail.js

Best regards!

**Comment by oaoxd0314** [comment]
thank you so much
