### ISSUE TITLE
is there a way to select marker on map on specific country without id

### ISSUE THREAD

**Issue by HebaAhmadSaleh** [highcharts/highcharts-react#296]
is there a way to select marker on map on specific country with isoode of country ?

**Comment by ppotaczek** [comment]
Hi @HebaAhmadSaleh,

Thank you for contacting us!

Yes, you can find the right point and call `select` method on it.

**Live demo:** https://jsfiddle.net/BlackLabel/92svy8wn/

Best regards!

**Comment by HebaAhmadSaleh** [comment]
> Hi @HebaAhmadSaleh,
> 
> Thank you for contacting us!
> 
> Yes, you can find the right point and call `select` method on it.
> 
> **Live demo:** https://jsfiddle.net/BlackLabel/92svy8wn/
> 
> Best regards!

Thank you so much, I mean for example like here 
`series: [
            {
                // Use the gb-all map with no data as a basemap
                name: 'Basemap',
                mapData: mapDataIE,
                borderColor: 'rgba(200, 200, 200, 0.3)',
                nullColor: Colors.map_color,
                showInLegend: false,
            },
            {
                // Specify points using lat/lon
                type: 'mapbubble',
                name: 'Country',
                color: Colors.main_green,
                data: [{ z: countryId, label, lat: latitude, lon: longitude }],
                cursor: 'pointer',
                showInLegend: false,
            },
        ],`

the mapbubble appears on selecting a country have id (numeric value identifies each country) but how about if I have only isoCode and lat and longtude ?

**Comment by ppotaczek** [comment]
Hello @HebaAhmadSaleh, If your points are joined with map by iso code, you can use this code to find the right point.

**Comment by ppotaczek** [comment]
Closed due to inactivity.
