### ISSUE TITLE
Display same chart in Modal

### ISSUE THREAD

**Issue by gdelacruzfdez** [highcharts/highcharts-react#297]
Good morning,
I have a question. I am implementing a Dashboard tool using Highcharts. The Dashboard has small Widgets, and each Widget has a Highcharts chart.

I want the user to be able to edit the Widgets. When the user clicks the edit button, I want to display the HighCharts chart in a modal with some extra options to modify it. However, I use a ref in order to be able to control the chart and as the chart in the modal is in another DOM node, it is treated as another different chart:

```javascript
<HighchartsReact highcharts={HighCharts} ref={chartRef} options={DEFAULT_CHART_OPTIONS} />
```

Is there any way of using the exact same Chart in both places at the same time, to avoid this problem?

Thank you!

**Comment by ppotaczek** [comment]
Hi @gdelacruzfdez,

Unfortunately this is not possible. You need to reflect changes in both charts.

Best regards!

**Comment by gdelacruzfdez** [comment]
Thank you for your answer!
