### ISSUE TITLE
[Question] Hide unwanted indexes from Y-Axis from a stacked bar chart

### ISSUE THREAD

**Issue by nabeelsuspg** [highcharts/highcharts-react#298]
#### Expected behavior
I have data set with building names on Y-axis and decimal values on the x-axis. I want to show users a stacked bar chart with one or more buildings. Each building has multiple decimal values associated with them. For example, if a user selects one building then the Y-axis should contain only one building name and the x-axis should have all values.

#### Actual behaviour
Y-axis has unknown-unwanted indexes.  

#### Screenshot
![Stacked-bar-JSFiddle-Code-Playground](https://user-images.githubusercontent.com/76268417/117042251-921cee80-acc0-11eb-8993-12f99fadbddf.png)

**Comment by ppotaczek** [comment]
Hi @nabeelsuspg,

Thank you for contacting us!

I am not sure what exactly you want to achieve. Do you want to have stacked series with only one category, like in the example below?

Live demo: https://jsfiddle.net/BlackLabel/towy95km/

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
