### ISSUE TITLE
How to create  map width highcharts-react in this example ?

### ISSUE THREAD

**Issue by ilyjs** [highcharts/highcharts-react#30]
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-pies/

**Comment by KacperMadej** [comment]
Hi @ilyjs 

For technical support please use Highcharts support channels - https://www.highcharts.com/support

The demo could be recreate in React by adding custom code in a module / plugin and loading as any other module - new series type, wrappers, etc. - and by using [chart.events.load](https://api.highcharts.com/highcharts/chart.events.load) to run code that should be executed after each chart build.
