### ISSUE TITLE
Error Highcharts 9.1.0 - Highcharts is not defined

### ISSUE THREAD

**Issue by miloszwojcik** [highcharts/highcharts-react#300]
I upgraded the Highcharts library to v9.1.0 and I'm getting an error `Highcharts is not defined` from `highcharts@9.1.0/highstock.js`

I replicated the issue here https://stackblitz.com/edit/react-y5d8dv?file=package.json

The previous versions working fine. Is there a possibility that the new version has some bugs or I missed something in the code?

Thanks. cc. @ppotaczek

**Comment by ArsenMelikyan** [comment]
I've also experienced this error. Had to downgrade to version `9.0.1`.

**Comment by ppotaczek** [comment]
Hello!

Thank you for contacting us and sorry for the late reply!

You need to also import and initialize `ema` indicator which is required by `macd`. It looks that since Highcharts 9.1 the error is handled differently.

    require('highcharts/indicators/ema')(Highcharts)
___
**Live demo:** https://stackblitz.com/edit/react-jf6vsw?file=index.js

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
I'm also experiencing the same issue.. I have a working web app, has a bug in ResetZoomButton, so I want to upgrade from 8.2.2 to 9.1 but getting this `Highcharts is not defined`.

How can I investigate what is my missing requirement?

**Comment by ppotaczek** [comment]
This problem is a Highcharts bug and it is already resolved on the master branch. 
Related issue: https://github.com/highcharts/highcharts/issues/15698

@yitzchak-ben-ezra-ecoplant - you can make Highcharts a global variable: `window.Highcharts = Highcharts;` and check errors in a console. 
Example: https://stackblitz.com/edit/react-jn72bo?file=index.js

**Comment by yitzchak-ben-ezra-ecoplant** [comment]
Thanks, it was helpful.

**Comment by ElenaNesgovorov** [comment]
We (team) upgraded the Highcharts library to v9.1.0 and we are getting same error "`Highcharts is not defined from highcharts"`
We working with TS and use standard code for TS from examples 
We temporary back to version 9.0.0 wich working fine
Thank you and best regards
