### ISSUE TITLE
Highcharts v9 - dependency alert

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts-react#301]
**Problem**:
https://github.com/highcharts/highcharts-react/security/dependabot/package.json/highcharts/open

**Possible solutions**:
A. Release a new major version of the wrapper based on HC v9+
B. Add info about the dependency alert - it seems to be looking more serious than it really is.

**Comment by ppotaczek** [comment]
The problem has been resolved by increasing Highcharts version in dev dependencies. https://github.com/highcharts/highcharts-react/commit/f7f9efcabec44f60269aecd767aefa149541d1de
