### ISSUE TITLE
Correct way of updating chart when updating props of parent?

### ISSUE THREAD

**Issue by alvarotrigo** [highcharts/highcharts-react#302]
Is there any difference between passing the chart options as props to the Chart element and actually using `useState` to change them?

Using props:
https://codesandbox.io/s/funny-easley-83y8c?file=/src/Chart.js

```js
export default function ChartParent() {
  const [color, setColor] = React.useState("blue");

  const toggleColor = () => {
    if(color === 'blue') { 
      setColor("red");
    }else{ 
      setColor("blue");
    }
  }

  return (
    <div>
      <Chart color={color}/>
      <button onClick={ () => toggleColor()}>Click</button>
    </div>
  );
}
```

```js
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";

export default function Chart(props) {
  const options = {
    chart: { type: "column" },
    colors: [props.color],
    xAxis: { categories: ["2021", "2021"] },
    series: [{ data: [49.9, 71.5] }]
  };

  return <HighchartsReact highcharts={Highcharts} options={options} />;
}
```

Using seState
https://codesandbox.io/s/dry-http-jz8gd?file=/src/Chart.js:150-530
```js
export default function Chart({color}) {
  const [options, setOptions] = React.useState({
    chart: { type: "column" },
    colors: [color],
    xAxis: { categories: ["2021", "2021"] },
    series: [{ data: [49.9, 71.5] }]
  });

  React.useEffect(() => {
    setOptions({colors: [color]});
  }, [color])

  return <HighchartsReact highcharts={Highcharts} options={options} />;
}
```

**Comment by ppotaczek** [comment]
Hello @alvarotrigo,

Thank you for contacting us! 

Yes, that make a difference. I always recommend to keep options in a state.

In the first example the `options` variable is created again and `chart.update({ ALL_OPTIONS }, true, true)` is called.
In the second, options in state are changed and: `chart.update({ colors: [color] }, true, true)` is called.

**Docs:** https://github.com/highcharts/highcharts-react#optimal-way-to-update

Best regards!

**Comment by alvarotrigo** [comment]
Awesome, thanks for the answer @ppotaczek ! 👍
