### ISSUE TITLE
A11Y Proxy Container doesn't update when chart refreshes

### ISSUE THREAD

**Issue by ashleyryan** [highcharts/highcharts-react#303]
The accessibility plugin creates hidden buttons in the DOM for interacting with the series on the chart. I noticed when running some tests with react-testing-library that even when the chart updates with new series, the accessibility elements do not. They still display labels of the previous series. 

I've created a stackblitz example here: https://stackblitz.com/edit/react-73llti

Open up the console after rendering the second set of series and you'll see that it still displays the names of the first set of series.

I can set a `key` attribute on the `HighchartsReact` component to force it to remount and completely rerender, but I wasn't sure if there was a better way to get the accessibility fields to update.

**Comment by ppotaczek** [comment]
Hi @ashleyryan,

Thank you for contacting us!

That seems to be a bug in Highcharts. I have reproduced the problem without React here: http://jsfiddle.net/BlackLabel/kz5yneb6/

Could you report it on the main repository: https://github.com/highcharts/highcharts/issues ?

Best regards!

**Comment by ashleyryan** [comment]
Thanks,  I wasn't sure if this was a react issue or Highcharts. Reported!
