### ISSUE TITLE
Error 'formatter' implicitly has return type 'any'

### ISSUE THREAD

**Issue by leftchest** [highcharts/highcharts-react#304]
thanks for this helpful project

i install **the demo to vercel** ：[https://www.highcharts.com/demo/column-stacked-and-grouped](https://www.highcharts.com/demo/column-stacked-and-grouped)

demo named chart2 code links：[https://netdisk.hncaa.cn/Chart2.tsx](https://netdisk.hncaa.cn/Chart2.tsx)

then **error note：**
<html>
<body>

01:51:24.945 | src/components/Chart2.tsx(27,5): error TS7023: 'formatter' implicitly has return type 'any' because it does not have a return type annotation and is referenced directly or indirectly in one of its return expressions.
-- | --
01:51:24.945 | src/components/Chart2.tsx(28,27): error TS2339: Property 'x' does not exist on type '{ formatter: () => any; }'.
01:51:24.946 | src/components/Chart2.tsx(29,14): error TS2339: Property 'series' does not exist on type '{ formatter: () => any; }'.
01:51:24.946 | src/components/Chart2.tsx(29,40): error TS2339: Property 'y' does not exist on type '{ formatter: () => any; }'.
01:51:24.946 | src/components/Chart2.tsx(30,26): error TS2339: Property 'point' does not exist on type '{ formatter: () => any; }'.
01:51:24.968 | error Command failed with exit code 2.
01:51:24.968 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
01:51:24.983 | Error: Command "yarn run build" exited with 2

</body>
</html>

anther demo the same usage is perfect：[https://netdisk.hncaa.cn/Chart1.tsx](https://netdisk.hncaa.cn/Chart1.tsx)
**Looking forward to your help**

**Comment by ppotaczek** [comment]
Hi @leftchest, 

Thank you for contacting us!

You need to type `this` in the the formatter function:

    tooltip: {
      formatter: function (this: Highcharts.TooltipFormatterContextObject): string {
        return ...
      }
    }

**API Reference:** https://api.highcharts.com/class-reference/Highcharts#.TooltipFormatterCallbackFunction

Best regards!
