### ISSUE TITLE
How do I set parameter to render a map with type of ‘mapbubble’?

### ISSUE THREAD

**Issue by weichenzhiyi** [highcharts/highcharts-react#305]
Hello,I wish to consult you on one question. I realized the rendering of the map，but how do I set parameter to render a map with type of ‘mapbubble’? According to the settings of Highcharts's official website，the series parameters are set as follows（url:https://www.highcharts.com/demo/maps/map-bubble ）
`series: [{
      name: 'Countries',
      color: '#E0E0E0',
      enableMouseTracking: false
  }, {
      type: 'mapbubble',
      name: 'Population 2016',
      joinBy: ['iso-a3', 'code3'],
      data: data,
      minSize: 4,
      maxSize: '12%',
      tooltip: {
          pointFormat: '{point.properties.hc-a2}: {point.z} thousands'
      }
  }]`
In my project, I set as follows 
    `series: [{              
          mapData: Highcharts.maps['cn/china'],
          enableMouseTracking: false,
          name: '中国地图',
          color: '#E0E0E0',
      },{
          type: 'mapbubble',
          mapData: Highcharts.maps['cn/china'],
          name: '中国地图',
          joinBy: ['name','name'],
          data: [{
              name: '北京',
              areacode: 110000
          },{
              name: '上海',
              areacode: 2000
          },{
              name: '广东',
              areacode: 2200
          }],
          minSize: 4,
          maxSize: '12%',
          tooltip: {
                  pointFormat: '{point.name}'
          }
      }]`
After setting, as shown in the figure.But the bubble didn't come out.
![image](https://user-images.githubusercontent.com/29937943/122851336-5d80f700-d341-11eb-8718-f844661460d3.png)

How can I achieve it? Please help me to have a look.
Thank you.

**Comment by ppotaczek** [comment]
Hi @weichenzhiyi,

Thank you for contacting us!

Your options look fine, but there is probably some problem with data. Could you show the issue in some online code editor? You can start from: https://codesandbox.io/s/highcharts-react-demo-forked-yi81d?file=/demo.jsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
