### ISSUE TITLE
'useUTC' does not exist in type 'GlobalOptions'

### ISSUE THREAD

**Issue by fedulovivan** [highcharts/highcharts-react#306]
useUTC is not declared in GlobalOptions interface in highcharts/highcharts.d.ts
which causes error for following block
```ts
Highcharts.setOptions({
    global: {
        useUTC: false,
    }
});
```

**Comment by ppotaczek** [comment]
Hi @fedulovivan, 

Thank you for contacting us!

As you can see in API, using `global.useUTC` option is deprecated. Use `time.useUTC` instead.

**API Reference:** https://api.highcharts.com/highcharts/time.useUTC

**Comment by fedulovivan** [comment]
Yep, thanks! Probably it would be better to add "global" as well and mark it with @deprecated annotation.
