### ISSUE TITLE
BoostThreshold isn't displaying data correctly

### ISSUE THREAD

**Issue by vmlopezr** [highcharts/highcharts-react#308]
Hello, this might have a better place in the highcharts repo, but i wanted to see if I was at least importing the boost module correctly

I came across an issue when using boostThreshold to force specific series to use the boost module. In the example below, i have three series:
1. Scatter plot with 20 points (PointObject array)
2. Line series with ~400 points, datetime, with a day interval for the x values.
3. Similar to number 2 above.

For some reason with the boostThreshold on the two line series (these are the only ones that should use boost) they aren't drawn correctly. I've only had success in seeing the series if i zoom in enough such that there aren't a lot of points visible.

https://stackblitz.com/edit/react-3x8nfg?file=index.js

**Comment by ppotaczek** [comment]
Hi @vmlopezr, 

Yes, the boost module is imported correctly and it works.

I have reproduced the same behavior without React: http://jsfiddle.net/BlackLabel/k6trgqf5/ so you can report the problem on the main repository: https://github.com/highcharts/highcharts/issues

Best regards!
