### ISSUE TITLE
data props changed after push into series HighMap

### ISSUE THREAD

**Issue by CaptainHoangLe** [highcharts/highcharts-react#311]
I am using highchart ver 9.1.2.
I have created a Highmap. This is my chartOptions in an async function
![image](https://user-images.githubusercontent.com/53038465/126100596-7ed2886a-92b4-4a4c-97e8-6ca3e7c247f1.png)
and return 
![image](https://user-images.githubusercontent.com/53038465/126101484-398359fe-0839-42fd-a69e-90198e8f7249.png)
mapData is result when i read a geojson file.
This is my original data
![image](https://user-images.githubusercontent.com/53038465/126101058-52a735b5-d0b0-4cae-a093-9da9080ec3fc.png)
By the magic way , after my data apply in highchart, it will be changed like that.
![image](https://user-images.githubusercontent.com/53038465/126100925-ceea29f5-7801-412a-a0ee-2b7b455bc49e.png)
Because of that reason, i think i can change map when apply a new map by select a dropdown which i have created before.
So, Please anyone can help me to slove my problem. 
Thank you very much

**Comment by ppotaczek** [comment]
Hi @CaptainHoangLe, 

Thank you for contacting us!

Highcharts for performance reasons mutates the original data array. If you want to avoid that, you can pass a copy of the array to options.

Best regards!

**Comment by CaptainHoangLe** [comment]
> Hi @CaptainHoangLe,
> 
> Thank you for contacting us!
> 
> Highcharts for performance reasons mutates the original data array. If you want to avoid that, you can pass a copy of the array to options.
> 
> Best regards!

thank you very much for your help <3
