### ISSUE TITLE
Highmap : Map is zoomed out after update geojson mapdata

### ISSUE THREAD

**Issue by CaptainHoangLe** [highcharts/highcharts-react#312]
I am using Highchart 9.1.2 and Highchart React 3.0.0
I have a Map chart and a dropdown to select map name below
![image](https://user-images.githubusercontent.com/53038465/126254122-69ce59a0-b10b-4e09-858b-ef690dc53ea6.png)
after i choose the map name geojson data will be update into chartoptions. However map will be changed like that.
![image](https://user-images.githubusercontent.com/53038465/126254237-68bcfa10-90db-4f8f-a988-70342a998491.png)
This is my config chartOptions
![image](https://user-images.githubusercontent.com/53038465/126254526-0c55b073-9722-4a7a-8efa-0619a31cb22c.png)
and my render function 
![image](https://user-images.githubusercontent.com/53038465/126254433-6b978828-f66e-443a-9a00-60053f39e045.png)
Please someone can tell me where is my mistake. thanks for your any help

**Comment by ppotaczek** [comment]
Hi @CaptainHoangLe,

Could you reproduce the issue in some online code editor? You can use: https://codesandbox.io/s/highcharts-react-demo-forked-yi81d?file=/demo.jsx to start.

Best regards!

**Comment by CaptainHoangLe** [comment]
> Hi @CaptainHoangLe,
> 
> Could you reproduce the issue in some online code editor? You can use: https://codesandbox.io/s/highcharts-react-demo-forked-yi81d?file=/demo.jsx to start.
> 
> Best regards!

I have just fixed it by setState chart_options: null. This way is not intelligent but it works for me. Thank you for your support <3
