### ISSUE TITLE
Highcharts doesn't work with react-grid-layout

### ISSUE THREAD

**Issue by FlaviusBejan** [highcharts/highcharts-react#313]
Hello,

I tried to figure this for a while, but I had no luck or the experience to figure it out.
I'm trying to have a resizable grid of charts that has certain dimensions. Each grid element will contain a chart or other components (based on the needs) that should take the size of the grid element.

Here is a demo that shows the problem: https://codesandbox.io/s/elated-turing-5nm4w

The chart in the grid cell renders outside of it. Next to "Highcharts.com" you can see the grid cell resize icon which you can drag and see the changes.
When resized on horizontal, the chart disappears, but when resized on vertical, the chart remains as it is. I've also added a Typography component to show how other components behave.

**Comment by ppotaczek** [comment]
Hi @FlaviusBejan,

Thank you for contacting us!

You need to call `reflow` method on a chart in `onLayoutChange` event.

Please check: https://api.highcharts.com/class-reference/Highcharts.Chart#reflow
Possible implementation: https://codesandbox.io/s/charming-poitras-wur-wur9j?file=/src/Chart.js

Best regards!

**Comment by FlaviusBejan** [comment]
Hey @ppotaczek,

Thank you for the fast reply.

Indeed, what you mentioned works, but only for horizontal fill. The vertical align remains the same.
I don't know why, but it seems that the height doesn't update with the resize (when using reflow). I've removed the 'Toolbar' from InteractiveGrid and the chart just went up by 50px (the Toolbar height). I did an inspect element on the chart and only the width changed, all the other CSS elements remained the same.

I've implemented your recommendation in my example, but instead of useState, I'm signaling the change of the layout through an event bus. I realized that you did the change to 'layout' from App.js because useState triggered a render of the component with the constant values. with the event pus, the App component won't trigger a render.

Using the example from the reflow documentation page I've added a change for height and in that case it works as intended: https://jsfiddle.net/87utawmz/5/

**Comment by ppotaczek** [comment]
Hello, thanks for the example! 

I have reproduced your problem without React here: https://jsfiddle.net/z0ym6jn9/

The height of 400px is a default value and it is set if a chart can not calculate height from its parent. The parent in this case is a div created by 'highcharts-react' wrapper. You need to set:

    <HighchartsReact
      ...
      containerProps={{style: {height: '100%'}}}
    />

You can use calculated height, for example: `calc(100% - 30px);` if you want to add a toolbar.

Best regards!

**Comment by FlaviusBejan** [comment]
Hey @ppotaczek,

Thank you, again, for your fast reply.
I confirm that this fixes the problem.

Thank you for your help and I wish you a good day,
Flavius
