### ISSUE TITLE
tooltip is wrong position when zoom out chart by css

### ISSUE THREAD

**Issue by CaptainHoangLe** [highcharts/highcharts-react#314]
I am using highchart 9.1.2 and react highchart ver 3.0.0
I want to zoom out map chart to responsive in my web page .However, when i using props "zoom" in html , tooltip in my chart is broken . It is showed in wrong position. 
So Please anyone can help me fix this problem. Thanks all !
This is my demo
https://stackblitz.com/edit/react-vpxzkx?fbclid=IwAR2DXnTLFcKKaGjBA5u3wHl8q_ZWIJuGVKUG3tlJ2Z3YAIGOxXC7grcWxNE&file=index.js

**Comment by ppotaczek** [comment]
Hi @CaptainHoangLe,

This issue is definitely not related with highcharts-react wrapper.
You can report it on the main repository: https://github.com/highcharts/highcharts/issues with this live example in pure JS: https://jsfiddle.net/BlackLabel/znhm49f6/

Best regards!

**Comment by CaptainHoangLe** [comment]
> Hi @CaptainHoangLe,
> 
> This issue is definitely not related with highcharts-react wrapper.
> You can report it on the main repository: https://github.com/highcharts/highcharts/issues with this live example in pure JS: https://jsfiddle.net/BlackLabel/znhm49f6/
> 
> Best regards!

Thank you so much for your reply
