### ISSUE TITLE
"stickyTracking: false" not applied to mouseOut events when changing React states

### ISSUE THREAD

**Issue by mthb-cg** [highcharts/highcharts-react#318]
The issue only occurs when updating states using react. The mouseOut event doesn't seem to have the "stickyTracking: false" property apply to it and it is triggered when it leaves the chart area rather than when it moves off the point. https://stackblitz.com/edit/react-vrshrm?file=index.js

**Comment by ppotaczek** [comment]
Hi @mthb-cg, 

Thank you for contacting us!

The chart component is updated after every `mouseOver` and `mouseOut` event and this is the reason of the problem. You can disable updates by using `allowChartUpdate` prop.

    <HighchartsReact options={options} allowChartUpdate={false} />;

Best regards!

**Comment by mthb-cg** [comment]
That worked, thank you!

**Comment by mthb-cg** [comment]
Sorry, in my actual implementation I need to update the chart for other functions and "allowChartUpdate={false}" breaks those. Is there a different work around where I don't have to disable updating?

**Comment by ppotaczek** [comment]
The other solution is to keep chart options in a state. 
Example: https://stackblitz.com/edit/react-gy3sdl?file=index.js
