### ISSUE TITLE
Changing xAxis.alternateGridColor not updating rendered chart

### ISSUE THREAD

**Issue by sunnySinghD** [highcharts/highcharts-react#319]
I have an external button that toggles a different set of options (different data, colors, etc). By default I am not using alternateGridColor, but the button press updates the options to set the alternateGridColor. The chart successfully renders, including alternateGridColor. When I click another button to modify the options again, this time not passing the alternateGridColor, alternateGridColor continues to display.

Heres an example that is similar that shows the problem: https://codesandbox.io/s/beautiful-pare-60kof?file=/src/App.js

Am I doing something wrong here? Thanks for the help.

**Comment by ppotaczek** [comment]
Hi @sunnySinghD, 

Thank you for contacting us!

As the color for alternate grid has been already set, changing it to `undefined` is treated like there is nothing to update. You can change the color to null, white or transparent.

    xAxis: {
      alternateGridColor: altOn ? "#cccccc" : null
    }
    
Best regards!

**Comment by sunnySinghD** [comment]
That works for me, I just assumed since the highcharts reference said the default value is undefined I should set it to that to disable. Thanks for the help!
