### ISSUE TITLE
Couldn't find preset "env" relative to drectory

### ISSUE THREAD

**Issue by TrueGeek** [highcharts/highcharts-react#32]
When I follow the setup instructions and then launch the simulator I get the message

> Failed to load bundle .... with error: (/Users/me/code/project/node_modules/highcharts-react-official/index.js: Couldn't find preset "env" relative to directory "/Users/me/code/project/node_modules/highcharts-react-office" (null))

Has anyone else seen this? Am I missing a step where I was supposed to setup an "env" variable?

**Comment by pawelfus** [comment]
Hi @TrueGeek 

Unfortunately, I haven't seen this error. I can not find package `highcharts-react-office` in the NPM and the only reference in this repo to `office` is ... this issue. Is this exactly the error from console?

Every similar bug report on github refers to.. babel-preset-env and that babel-preset-env should be installed. We have this in `devDependencies`, but it seems wrong to require this, even for a workaround if you don't need it. Could you provide more details? Steps to reproduce and minimal example would be great, thanks!

**Comment by TrueGeek** [comment]
Sorry, no, that's a typo at the end. highcharts-react-office should be highcarts-react-official.

Here are the complete steps to recreate:

In a terminal:

```
react-native init HighchartsTest

cd HighchartsTest

npm install highcharts-react-official highcharts react react-dom

npm install

react-native run-ios
```

The app loads fine at this point.

In App.js add these three lines at the top:

```
import { render } from 'react-dom'
import Highcharts from 'highcharts'
import HighchartsReact from 'highcharts-react-official'
```
The result is this:

![simulator screen shot - iphone 6 - 2018-06-20 at 11 22 13](https://user-images.githubusercontent.com/90821/41668169-c02b0390-747c-11e8-8e13-efd5a75f3a46.png)

**Comment by pawelfus** [comment]
Thank you for the details. You are right, it's buggy. We will check what happens there.

**Comment by sebastianbochan** [comment]
Hi @TrueGeek,
The reason of problem is missing three packages of babel.
- babel-core
- babel-preset-react
- babel-preset-env

After installation, I do not have any errors in emulator iOS and Expo.

Related topic: https://github.com/babel/babel-preset-env/issues/186

**Comment by Anujmoglix** [comment]
in react native getting issue with div ,

**Comment by Nagu07** [comment]
Can some one help how you resolved this issue

**Comment by ppotaczek** [comment]
Hi @Nagu07,

Please provide me with more information about the issue and your project configuration settings because this problem should no longer be present.
