### ISSUE TITLE
Unable to re-render SetOptions after update of language

### ISSUE THREAD

**Issue by rajeshwarKrr** [highcharts/highcharts-react#321]
Hello Team, 

I'm working with `react-i18next and highcharts, `
while using the package I will have a **t()** property from `React-i18next`, when I change language from english to french,  I'm able to translate chartOptions and .chart properties using `compoenentDidUpdate`.

below is the code snippet 

```
componentDidUpdate() {
// .... some conditions to stop rerendering and also api calls
	 chartOptions = {
        ...chartOptions,
        series: allData,
        title: {
            text: this.props.t("highcharts.xyz.title")   // t() is a prop from HOC withTranslate() of react-i18next
        },
        yAxis : {
            title: {
                text: this.props.t("highcharts.xyz.yaxisTitle")
            }
        },
        xAxis : {
            title: {
                text: this.props.t("highcharts.xyz.xaxisTitle")
            }
        }
    }
    this.setState({
        dataIsLoaded: true,
        chartOptions
    })
} 



```
But in the same way I was unable to update `setOptions` as they are global properties. (issue while trying to translate exporting options )

Note: I have found that` Highcharts.getOptions().lang` has the updated localization values after `setoptions`
Is there any other way to write a solution for this kind of scenario.

code snippet below

```
componentDidUpdate() {
	//some conditions to stop rerendering 
	
	Highcharts.setOptions({
		lang: {
			  "downloadCSV":  this.props.t("highcharts.export.downloadCSV"),
                "downloadJPEG":  this.props.t("highcharts.export.downloadJPEG"),
                "downloadPDF":  this.props.t("highcharts.export.downloadPDF"),
                "downloadPNG":  this.props.t("highcharts.export.downloadPNG"),
                "downloadSVG":  this.props.t("highcharts.export.downloadSVG"),
                "downloadXLS":  this.props.t("highcharts.export.downloadXLS"),
                "printChart":  this.props.t("highcharts.export.printChart"),
                "viewData":  this.props.t("highcharts.export.viewData"),
                "viewFullscreen":  this.props.t("highcharts.export.viewFullscreen"),
		}
	})

	console.log("getOptions", Highcharts.getOptions().lang )
}
```

Please let me know if `highcharts-react-official` have a simpler way to solve this 

I have even tried few of the properties in` <HighchartsReact /> `component from` highcharts-react-official`

but nothing worked. 

```
 <HighchartsReact
    highcharts={Highcharts}
    options={this.state.chartOptions}
   	ref={this.chartRef} // didn't work using destroy or redraw
    // allowChartUpdate = { true } // I hope this only works for the chart options
    updateArgs = { [true, true, true ] } // I gave a quick try for this, nothing worked
  />	
```

kindly help me if you have any solutions :)

**Comment by ppotaczek** [comment]
Hi @rajeshwarKrr,

Thank you for contacting us!

The only way to apply new global translations is to initialize the chart again. You can do that for example by changing key prop. Please check the below example.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-fork-2cqyz?file=/demo.jsx

Best regards!

**Comment by rajeshwarKrr** [comment]
Hey @ppotaczek  

Solution worked, :)
