### ISSUE TITLE
Cannot use Boost with Highcharts Stock module

### ISSUE THREAD

**Issue by johndatserakis** [highcharts/highcharts-react#327]
Hi there, thank you for this component.

I'm running into an issue enabling Boost on my Highcharts Stock chart.

I understand that Highcharts Stock module supports boost, as confirmed [here](https://api.highcharts.com/highstock/boost), [here](https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/boost/line-series-heavy-stock), and in other documentation.

My chart with 5 series (and 5 series in the Navigator) and about 400 points per series is getting pretty laggy - so I want to turn on Boost.

I'm made sure to enable all the options and have confirmed I can get Boost to work if I remove the `constructorType={'stockChart'}` prop on my component.

Please see my [reproduction](https://stackblitz.com/edit/react-highcharts-stock-boost-issue) demonstrating this issue. Please open the console and comment on and off the line where I add `constructorType={'stockChart'}`, currently on line `42`. 

You'll see that the console reports the series are being boosted and the Chart has its line drawn differently when the Chart type is normal. Once you uncomment that `constructorType` line, Boost is no longer activated.

Perhaps there needs to be an additional setting I'm missing when using Boost with Highcharts Stock. Thank you for taking a look.

**Comment by ppotaczek** [comment]
Hi @johndatserakis,

Thank you for contacting us!

You are right, the boost mode is not activated. Stock charts have enabled data grouping feature by default which changes data behaviour, you need to disable that feature.

**Live example:** https://stackblitz.com/edit/react-highcharts-stock-boost-issue-oef613
**API Reference:** https://api.highcharts.com/highstock/plotOptions.series.dataGrouping

Best regards!

**Comment by johndatserakis** [comment]
That's great. I see that turning off that option does in fact get Boost going. Thank you for the quick response.
