### ISSUE TITLE
chart type "solidgauge" not working in optimized production build

### ISSUE THREAD

**Issue by kjellaso** [highcharts/highcharts-react#331]
After upgrading to version 3.1.0, solidgauge is not working when doing an optimized production build, using yarn build. 

The following error is printed in the console:
The "highcharts" property was not passed.

It works when using the development version using yarn start.

**Comment by ppotaczek** [comment]
Hello @kjellaso,

> No, i've actually imported that object. I would guess it shouldn't have worked on the recat development server either if I had forgotten that.

Yes, you are right.
___
However, I just created a new React project by using create-react-ap, added `highcharts` v9.2.2 and `highcharts-react-official` v3.1.0 and the builded version created by `yarn build` works fine. Please check the below project.

[test-hc-react.zip](https://github.com/highcharts/highcharts-react/files/7374634/test-hc-react.zip)

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
