### ISSUE TITLE
anotations based on x and y positions 

### ISSUE THREAD

**Issue by bkinsey808** [highcharts/highcharts-react#334]
What is the React Highcharts version of the following

https://jsfiddle.net/bkinsey808/t5h97j24/32/

specifically i want the equivalent of the toPixels function:

```
chart.yAxis[0].toPixels(100, true)
```

**Comment by ppotaczek** [comment]
Hi @bkinsey808, 

Thank you for contacting us!

The most important thing in this case is to get the chart reference:

```
  const chartComponent = useRef(null);
  ...
  return (
    <HighchartsReact
      ref={chartComponent}
      ...
    />
  );
```

Then, you will be able to use all required chart properties in useEffect:

```
  useEffect(() => {
    const chart = chartComponent.current.chart;
    ...
    let xPx = chart.xAxis[0].toPixels(10, true); // - wPx / 2

    const annotation = {...};
    // operation directly on a chart
    chart.addAnnotation(annotation);
    // or chart update by changing options in state
    // setOptions({annotations: [annotation]});
  }, []);
```

**Live example:** https://codesandbox.io/s/highcharts-react-demo-25q15?file=/demo.jsx

Best regards!

**Comment by bkinsey808** [comment]
thank you
