### ISSUE TITLE
React 17

### ISSUE THREAD

**Issue by tedeling** [highcharts/highcharts-react#337]
Hi! 

Is React 17 support on the horizon? Highcharts is one of the last dependencies keeping us on 16. Thanks!

**Comment by ppotaczek** [comment]
Hi @tedeling,

Thank you for contacting us!

You should be able to use our wrapper with React 17. Have you encountered any problems with it?

**Live example:** https://codesandbox.io/s/highcharts-react-demo-for-1ml8j?file=/demo.jsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
