### ISSUE TITLE
redraw on change in map data

### ISSUE THREAD

**Issue by naveedmm** [highcharts/highcharts-react#338]
When drawing the map using 
`<HighchartsReact
      constructorType="mapChart"
      highcharts={Highcharts}
      options={options}
      oneToOne={true}
    />`
Options are stored in state and when the state of options is changed to show different area map the maps does't redraw,
Note: the change to series data is visible but the map isn't updating (Maybe it has something to do with setTimeOut not being set to give the time to redraw the map)
Kindly provide some guidance.

**Comment by ppotaczek** [comment]
Hi @naveedmm,

Thank you for contacting us!

First of all, there is no `oneToOne` props in the current wrapper implementation, you can use `updateArgs` instead. 

As to your main question, updating maps with the wrapper seems to work fine. I have prepared the below example with map changing for you.

**Live example:** https://codesandbox.io/s/highcharts-react-demo-kpwuz?file=/demo.jsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
