### ISSUE TITLE
Boost module not working for Heatmap chart

### ISSUE THREAD

**Issue by roger-schaer** [highcharts/highcharts-react#339]
Hello,

I've recently started using the highcharts-react wrapper and after several attempts, I'm not able to make the Boost module work with a Heatmap chart.

Here is a StackBlitz illustrating the problem: https://stackblitz.com/edit/react-osxrzm?file=index.js
If you inspect the elements in the page, you will see that there is no _image_ tag present, everything is rendered as SVG elements.

It seems to be a React + Heatmap-specific problem, as I've found an example using the React wrapper for a Line chart where the boost module works : https://stackblitz.com/edit/react-2x36qh?file=index.js

Additionally, I've also found an example without React where a Heatmap is correctly rendered by the boost module : https://jsfiddle.net/BlackLabel/zvd2otpq/

Any help would be greatly appreciated, I've been using Highcharts for many years and would love to integrate it with React!

**Comment by ppotaczek** [comment]
Hi @roger-schaer,

Thank you for contacting us!

Please check the below information about boost module from docs:

> Note: Boost should be the last module included. This is because it overrides both standard Highcharts functionality, and functionality in certain modules (namely treemap, heatmap, bubble, and scatter).

> In boost mode, turbo mode is always turned on. That means all data points should be configured as an array of numbers (e.g. [1, 2, 3]) or a two dimensional array of numbers (e.g. [ [1, 2], [2, 3], [3, 4] ]).

So, you need to change the order of initialization of modules.

```
import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts';
import HighchartsHeatmap from 'highcharts/modules/heatmap';
import HighchartsBoost from 'highcharts/modules/boost';

HighchartsHeatmap(Highcharts);
HighchartsBoost(Highcharts);
```

**Live demo:** https://stackblitz.com/edit/react-e8f4ho?file=index.js
**Docs:** https://www.highcharts.com/docs/advanced-chart-features/boost-module

Best regards!

**Comment by roger-schaer** [comment]
Thank you very much @ppotaczek, this solved the issue indeed, sorry that I missed this part in the documentation!
