### ISSUE TITLE
Dark theme colors were overwritten by elment.style

### ISSUE THREAD

**Issue by bluehenry** [highcharts/highcharts-react#340]
Hi, 

I want to apply dark-unica theme to the chart. However the some colors were overwritten, for example, 

```
.highcharts-axis-labels, .highcharts-axis-title {
    fill: #E0E0E3;
}
```

was overwritten by 

```
element.style {
    color: #666666;
    cursor: default;
    font-size: 11px;
    fill: #666666;
}

```
I assume the element.style was generated by some js files. I've tried with !import in my css, but it's not working. 

The full source code is following: 
```
import React from "react";
import Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import "highcharts/css/themes/dark-unica.scss";


const options = {
  chart: {
    type: 'spline',
  },
  title: {
    text: 'My chart'
  },
  series: [
    {
      data: [1, 2, 1, 4, 3, 6]
    }
  ]
};

const TestChart= () => {
  return (
    <>
      <HighchartsReact
        highcharts={Highcharts}
        options={options}
      />
    </>
  )
}

export default TestChart;**
```
Any suggestions?  

Thanks and regards!

**Comment by ppotaczek** [comment]
Hi @bluehenry,

Thank you for contacting us!

All you need to do is to enable styled mode:

```
  chart: {
    ...,
    styledMode: true
  },
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-forke-13b2p?file=/demo.jsx

**Docs:** https://www.highcharts.com/docs/chart-design-and-style/style-by-css
**API Reference:** https://api.highcharts.com/highcharts/chart.styledMode

Best regards!

**Comment by bluehenry** [comment]
Thanks @ppotaczek , it works perfect. Really appreciate!
