### ISSUE TITLE
Namespace '"highcharts"' has no exported member 'Options'.

### ISSUE THREAD

**Issue by wagg-matt** [highcharts/highcharts-react#341]
Hi, 

Using React with TypeScript i'm getting the error `Namespace '"highcharts"' has no exported member 'Options'.` on every instance of `highcharts.Options` is being used. This is the same way it says to use it in the docs. Is there something else I need to add in? Has the usage changed? 

The project won't build at present. I've added in a `highcharts.d.ts` file containing the following:
`
declare module 'highcharts';
declare module 'highcharts/*';
`

Any help or guidance would be greatly appreciated. 

highcharts version: 6.2.0
highcharts-react-official version: 2.2.2

Here is an example file where the issue is happening:
```
import React, { Component } from 'react';
import Highcharts from 'highcharts';
import HcExport from 'highcharts/modules/exporting';
import HighchartsReact from 'highcharts-react-official';
import './styles.css';

import { getOptions } from './HighchartOptions';
import { validateInputData } from './Validation/Validator';

HcExport(Highcharts);

class SpcChartProps {
  chartData: any;
  chartOptions: any;
  ruleSet: any
}
export default class SpcChart extends Component<SpcChartProps> {
  render () {
    const error = validateInputData(this.props.chartData);

    let options: Highcharts.Options = {};

    if (!error.flag) {
      options = getOptions(this.props.chartOptions, this.props.chartData, this.props.ruleSet);
    }

    return (
      <div className="spc-chart-container">
        <HighchartsReact
          highcharts={Highcharts}
          options={options} />
      </div>
    );
  }
};
```

**Comment by ppotaczek** [comment]
Hi @wagg-matt, 

Thank you for contacting us!

As you can see in Highcharts [changelog](https://www.highcharts.com/blog/changelog/#highcharts-v7.0.0), beta TypeScript support was added in version 7.0.0.

Best regards!

**Comment by wagg-matt** [comment]
Hi @ppotaczek 

Thanks so much for coming back to me. 

I've updated highcharts to version 8.1.2 and still getting the same issue in the same place. Have also upgrade highcharts-react-official to version 3.1.0.

Any ideas as to what it may be or what I could add into `highcharts.d.ys`?

Thanks
Matt

**Comment by ppotaczek** [comment]
Hello, I have created the below example with typescript and your config. Everything seems to work, could you adapt the example to show the problem?

**Live example:** https://codesandbox.io/s/modest-wing-h-hv24t?file=/src/App.tsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
