### ISSUE TITLE
Pie chart accessibility issue

### ISSUE THREAD

**Issue by lakshmihnm** [highcharts/highcharts-react#342]
Please find below issues regarding pie chart accessibility
1.content is not reading in proper order.
2.Focus on graph is incorrect
3.Blank spaces are getting called out
4.long press and double tap  on text field is also getting called out

**Comment by ppotaczek** [comment]
Hi @lakshmihnm,

Thank you for contacting us!

I think that the listed issues are not related with our wrapper, but directly with Highcharts. Could you compare the version in pure JS, for example: http://jsfiddle.net/BlackLabel/hgv39xn8/ and check if the problems also occur there?

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
