### ISSUE TITLE
Plotlines with Highcharts

### ISSUE THREAD

**Issue by rishabhtatia** [highcharts/highcharts-react#343]
Highcharts plotlines label hides the tooltip

**Comment by rishabhtatia** [comment]
#
![Screenshot from 2021-11-29 14-39-31](https://user-images.githubusercontent.com/73160238/143839474-0f42943b-3afd-4f5a-94fd-cb02c7a375d5.png)

**Comment by ppotaczek** [comment]
Hi @rishabhtatia,

Please reproduce the issue in some online code editor.

However, this problem is not related with our wrapper, but with Highcharts in general. In the future, for this kind of questions please use one of our support channels: https://www.highcharts.com/blog/support/

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
