### ISSUE TITLE
Highcharts Guages Styling

### ISSUE THREAD

**Issue by MuhammadAhmed1994** [highcharts/highcharts-react#344]
Is it possible to Draw this type of gauges in the left and right of the circle using Highcharts? 
Basically left side gauge is representing the shorts' %age at left, right side gauge is representing the shorts' %age at right, and the center is one simple round circle with the %age of center shots.

![image](https://user-images.githubusercontent.com/21235727/146227414-f773ed94-c2cf-4fc5-b167-0270168ddd38.png)

**Comment by ppotaczek** [comment]
Hi @MuhammadAhmed1994, 

For these types of questions please use one of our support channels: https://www.highcharts.com/blog/support/
We use this repository as a bug tracker for `highcharts-react-official` wrapper.

Best regards!
