### ISSUE TITLE
Unable to allowPointSelect on series getting 'Uncaught TypeError: Cannot add property -1, object is not extensible' error

### ISSUE THREAD

**Issue by abhimanusharma** [highcharts/highcharts-react#345]
Here are my chart options config.

```
export const deckChartConfig:Highcharts.Options = {
plotOptions: {
    series: {
      allowPointSelect: true
    }
  },
}
```

![screenshot-nimbus-capture-2021 12 29-09_42_32](https://user-images.githubusercontent.com/5707050/147626933-4e189360-354c-41e7-8f92-309f63784d46.png)

**Comment by ppotaczek** [comment]
Hi @abhimanusharma, 

Could you add more information about the problem and reproduce it in some online code editor? As you can see in this example: https://codesandbox.io/s/react-typescript-n3wvb?file=/src/App.tsx everything works as expected.

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
