### ISSUE TITLE
Uncaught TypeError: e[(t.constructorType || "chart")] is not a function

### ISSUE THREAD

**Issue by oosharma** [highcharts/highcharts-react#349]
Hi, I need your help. I am trying to use HighchartsReact in a plain HTML file with CDNs, and I am getting the error of "Uncaught TypeError: e[(t.constructorType || "chart")] is not a function" whenever I pass constructorType prop as "stockChart" to the HIghchartsReact component. The code works fine if I do not pass the constructorType prop. 

Here is my code:
```
// Inside Index.html
 <script src="https://cdnjs.cloudflare.com/ajax/libs/highcharts/7.1.1/highcharts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/react-highcharts/16.1.0/ReactHighstock.js"></script>
    <script>window.react = React</script>
    <script src="https://cdn.jsdelivr.net/npm/highcharts-react-official@2.1.3/dist/highcharts-react.min.js"></script>

```

```
// Inside index.jsx 
const options = {
    title: {
        text: 'My stock chart'
    },  
    series: [
        {
            data: [1, 2, 1, 4, 3, 6, 7, 3, 8, 6, 9]
        }
    ]
};

const App = () => <div>  
    <HighchartsReact.default 
        highcharts={ReactHighstock.Highcharts}
        constructorType={"stockChart"}
        options={options} />
</div>

let domContainer = document.querySelector('#like_button_container');
ReactDOM.render(
    <App />, domContainer
);
```

Please help me debug this error. 

Also, can you tell me if it is a bad idea to use HighchartsReact using CDN on a production website? I see there is very little information on the internet about its CDNs versions' usage.

Thanks so much for your help!

**Comment by ppotaczek** [comment]
Hi @oosharma,

Thank you for contacting us!

You need to use Highstock source code, for example:  https://cdnjs.cloudflare.com/ajax/libs/highcharts/7.1.1/highstock.js
It is not a bad idea to use HighchartsReact using CDN, little information is simply due to a lack of popularity.

Best regards!

**Comment by oosharma** [comment]
Hi @ppotaczek,

Thank you so much for your response. This solution fixed my issue! 

I'll continue playing around with the CDN version then.

Best regards!
