### ISSUE TITLE
Need Help in Finding Official CDN Link for Highcharts/Exporting

### ISSUE THREAD

**Issue by oosharma** [highcharts/highcharts-react#350]
Hi, I am trying to use the exporting features (print, save as .png, .svg, etc.) , and I figured out, I need the exporting CDN for that. Is there an official CDN link for React Highcharts Exporting?

I found a CDN online, and it works, but I am hoping to find an official CDN instead of this:  https://www.jsdelivr.com/package/npm/highcharts-exporting 

Would you recommend using this if there are no alternatives?

Here are how my CDNs look right now:
```
<script src="https://unpkg.com/react@16/umd/react.development.js" crossorigin></script>
<script src="https://unpkg.com/react-dom@16/umd/react-dom.development.js" crossorigin></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highstock/6.0.3/highstock.js"></script>
<script>window.react = React</script>
<script src="https://cdn.jsdelivr.net/npm/highcharts-react-official@2.1.3/dist/highcharts-react.min.js"></script>

// Need alternative for the following CDN
<script src="https://cdn.jsdelivr.net/combine/npm/highcharts-exporting@0.1.7,npm/highcharts-export-server@2.1.0"></script>
```

 Thanks so much for your help!

**Comment by ppotaczek** [comment]
Hi @oosharma, 

Here: https://code.highcharts.com/ you can find a nice description of Highcharts file service.

You can use for example:

```
https://code.highcharts.com/stock/6.0.3/highstock.js
https://code.highcharts.com/stock/6.0.3/modules/exporting.js
```

Best regards!

**Comment by oosharma** [comment]
Hi, 

I tried using https://code.highcharts.com/stock/6.0.3/modules/exporting.js

But I am getting the following error in my console:
Uncaught TypeError: Cannot read properties of undefined (reading 'Core/Chart/Chart.js')
    at exporting.src.js:31:68
    at exporting.src.js:22:9
    at exporting.src.js:24:2

I have created a CodeSandbox link for you to check out: https://codesandbox.io/s/react-cdn-01-forked-xgw3i?file=/index.html

Over there, if you uncomment line 18 to use the other script for exporting mentioned in my previous comment, then the exporting feature works. 

Please help in somehow making the official exporting module work for me as well. Thank you so much!

**Comment by oosharma** [comment]
Okay, I updated Highstock to use the latest version, and everything worked on the CodeSandbox example:  https://codesandbox.io/s/react-cdn-01-forked-xgw3i?file=/index.html 

But, on my localhost, if I update the version for Highstock to 7, or above, I get a black screen over the chart. Not sure why that is happening as all other settings are the same as in the CodeSandbox example. 

I'll dig deeper and raise another issue if I am not able to figure it out.

Thanks so much for your help!
