### ISSUE TITLE
Packed Bubble Chart not working with react ^17 and highcharts-react-official ^3

### ISSUE THREAD

**Issue by weilandia** [highcharts/highcharts-react#352]
Here's and example: https://codesandbox.io/s/highcharts-react-demo-forked-r6tde?file=/package.jso
<img width="1379" alt="Screen Shot 2022-01-18 at 16 32 30" src="https://user-images.githubusercontent.com/13652979/150040977-9e2ba609-9908-4132-ae5d-2e44383fcb63.png">
<img width="1381" alt="Screen Shot 2022-01-18 at 16 32 22" src="https://user-images.githubusercontent.com/13652979/150041009-500b0e66-688f-44fc-83d5-9dbd80b8b607.png">
n

**Comment by ppotaczek** [comment]
Hi @weilandia,

Thank you for contacting us!

You need to also import 'React' in your `Chart` component:

    import React from "react";
    import HighchartsReact from "highcharts-react-official";
    
**Live demo:** https://codesandbox.io/s/highcharts-react-demo-fork-bxo39?file=/components/Chart.jsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
