### ISSUE TITLE
Updating setOptions multiple times causing inconsistent options object

### ISSUE THREAD

**Issue by EitanSarikov** [highcharts/highcharts-react#354]
Hey, 
According to your docs the solution for updating the options object via react hooks is:
https://stackblitz.com/edit/react-nwseym?file=index.js

which updates specific objects inside the options object and it's working as needed.

My scenario is updating the options state with multiple useEffects which fires simultaneously and causes inconsistent options object.

exmaple:

```
const Chart = ({ isUtc, isStacked }) => {
  const [options, setOptions] = useState({
    chart: {
      type: "areaspline",
      zoomType: "x",
      spacingLeft: 12,
      spacingRight: 0,
      spacingTop: 12,
      spacingBottom: 0,
      borderWidth: 0,
      borderRadius: 6,
      style: {
        fontFamily: "Roboto",
      },
      backgroundColor: "transparent",
    },
    tooltip: {
      shared: true,
      split: false,
      enabled: true,
      valueDecimals: 2,
      xDateFormat: "%Y-%m-%d %H:%M",
      borderWidth: 0,
      borderRadius: 6,
    },

    credits: {
      enabled: false,
    },
    xAxis: {
      type: "datetime",
      gridLineWidth: 0,
      enabled: true,
      labels: {
        align: "center",
      },
      title: {
        text: "",
        style: {
          color: "#fff",
        },
      },
      tickLength: 0,
      crosshair: {
        enabled: true,
        width: 16,
      },
      startOnTick: false,
      minPadding: 0,
    },
    yAxis: {
      tickLength: 1,
      min: 0,
      type: "linear",
      gridLineWidth: 0,
      lineWidth: 1,
      title: {
        enabled: false,
      },
    },
    exporting: {
      enabled: false,
    },
    title: {
      text: "",
    },
  });

  useEffect(() => {
    console.log("utc updated");
    setOptions({time: { useUTC: isUtc } });
  }, [isUtc]);

  useEffect(() => {
    console.log("stacked updated");
    setOptions({plotOptions: { series: { stacking: isStacked ? "normal" : "" } }});
  }, [isStacked]);

  return <SdChart options={options} />;
};
```

in this case apparently what happens is that even if the utc is set to true it is getting erased by the follow up "stacked useeeffect" which apparently happens simultaneously.

Any other solutions to those kind of scenarios? or I'm doing it wrongly?

**Comment by ppotaczek** [comment]
Hi @EitanSarikov,

Thank you for contacting us! 

I assume that the problem is the same as in this example: https://codesandbox.io/s/highcharts-react-8hk1s?file=/Parent.jsx
(When you click on the 'Change both' button, only stacking is changed)

If so, use only one `useEffect` to change the options.

```
  useEffect(() => {
    console.log("title updated");
    setOptions({
      time: { useUTC: isUtc },
      plotOptions: { series: { stacking: isStacked ? "normal" : "" } }
    });
  }, [isUtc, isStacked]);
```

Example: https://codesandbox.io/s/highcharts-react-forke-lvgit?file=/Chart.jsx

Best regards!

**Comment by ppotaczek** [comment]
Hello, 
Ok, then you ca use update directly on the chart:

```
  useEffect(() => {
    chart.update({
      plotOptions: { series: { stacking: isStacked ? "normal" : "" } }
    });
  }, [isStacked]);

  useEffect(() => {
    chart.update({
      time: { useUTC: isUtc }
    });
  }, [isUtc]);
```

[How to get a chart instance?](https://github.com/highcharts/highcharts-react#how-to-get-a-chart-instance) 

___
**Live demo:** https://codesandbox.io/s/highcharts-react-forked-p8zj4?file=/Chart.jsx
**API Reference:** https://api.highcharts.com/class-reference/Highcharts.Chart#update

**Comment by ppotaczek** [comment]
Closed due to inactivity.

**Comment by waheed25** [comment]
@ppotaczek  i am trying to close the view data table on the data update, is there any method exposed for that?

**Comment by ppotaczek** [comment]
@waheed25, yes you can use `chart.hideData` method. 

Example: https://jsfiddle.net/BlackLabel/c3uy0vr6/
API: https://api.highcharts.com/class-reference/Highcharts.Chart#hideData
