### ISSUE TITLE
HighchartsReact ref attribute and its Documentation

### ISSUE THREAD

**Issue by gg2** [highcharts/highcharts-react#355]
There are 2 places in the documentation that describe how to get references to the chart component:
https://github.com/highcharts/highcharts-react#highcharts-with-typescript
https://github.com/highcharts/highcharts-react#how-to-get-a-chart-instance

Neither one is accurate to what I'm seeing.
I'm using:
highcharts: ^9.1.2
highcharts-react-official: ^3.0.0
react: ^17.0.2

And also using React's functional components, since that's the direction React wants to go now.

If I do the following, as described in the #highcharts-with-typescript section:
`const chartComponentRef = useRef<HighchartsReact.RefObject>(null);`
Then, I get "Namespace 'HighchartsReact' has no exported member 'RefObject'."

If I do the following, as described in the #how-to-get-a-chart-instance FAQ:
`const chartComponent = useRef(null);`
Then, `chartComponent.current.chart` complains "Property chart does not exist on type 'never'."

The ref attribute on HighchartsReact reports itself as:
`React.Ref<{chart: Highcharts.Chart, container: React.RefObject<HTMLDivElement>}>|undefined`
If I provide that type to `useRef`
( i.e. `useRef<React.Ref<{chart: Highcharts.Chart, container: React.RefObject<HTMLDivElement>}>>(null)` ),
then the complaint for `chartComponent.current.chart` just gets more complicated and chart still does not exist (though perhaps I could still figure out a "correct" way to reference it).

It looks like the last example in the FAQs does work, fortunately -- using the callback.

Did something change in React? in HighchartsReact? Is it possible to update the docs with what works for the latest versions?

**Comment by ppotaczek** [comment]
Hi @gg2,

Thank you for contacting us!

This problem has been resolved in version 3.1.0.
Please check this example: https://codesandbox.io/s/react-typescript-rg86j?file=/src/App.tsx

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
