### ISSUE TITLE
Chart is not responsive when using grid layout

### ISSUE THREAD

**Issue by zhyph** [highcharts/highcharts-react#357]
### Solution(?)
So it looks like by setting my global CSS to:
`
.highcharts-container,
.highcharts-container svg {
  width: 100% !important;
}
`
Kinda fix the issue I was having, but I still don't know if this is the right way, and if it'll conflict with any other highchart class in the future (and it uses `!important`, and I don't like that).
If you find a better way of making it work, don't be shy to share.
-

This was driving my crazy, and I didn't know why it wasn't working on my project, so I jumped into a CodeSandBox branch, installed everything and tested.
When I resize my window to be bigger my chart follows it and fills the space, but when I shrink it again, the chart does not shrink, it stays the same.
![GIF](https://user-images.githubusercontent.com/68618179/154158174-1c54a6d3-e61a-4c74-b783-f7212f80af7a.gif)
I'm using NextJS to reproduce this behavior.
These are the installed packages:
![image](https://user-images.githubusercontent.com/68618179/154158355-dd9785b3-0ecf-4233-950c-4857c592be14.png)
And this is the CodeSandbox: https://codesandbox.io/s/next-js-forked-e7bjut?file=/index.js
If you have a workaround for this, I would be glad to hear it.

**Comment by ppotaczek** [comment]
Hi @zhyph,

I have tested your example in: 
- Chrome v.98.0.4758.80 
- Safari v.12.1.2
- Firefox v97.0

and I was able to reproduce the problem only on Firefox. Could you add more information about your environment?

Also, there is an open issue on the main repository related with grid layout: https://github.com/highcharts/highcharts/issues/9491, so please check it for more information and a possible solution. 

Best regards!

**Comment by zhyph** [comment]
Hi @ppotaczek, it looks like this [answer](https://github.com/highcharts/highcharts/issues/9491#issuecomment-605965402) helped my problem, but I'm pretty sure it doesn't only happen with a grid layout, so I don't know if this is a permanent solution to the problem for something like a display flex, where I would need to place my wrapper component with `display: flex` too.
My main environment is **Firefox (96.0 - 64 bits) on Ubuntu 20.04 and Windows(I don't know the version)**  and now I tested in Google Chrome, and it does just work.
Since I'll be using Highcharts for a while, I'm going to be testing and sending more info about it.

**Comment by zhyph** [comment]
Hello, this is my feedback on my main problem in this post, which I was only able to reproduce on Firefox (I'm not sure why it only occurs in Firefox), and my solution was in my global CSS placement:
```
.highcharts-container,
.highcharts-container svg {
  /* I think !important is optional here, I didn't really tested it without using it */
  width: 100% !important;
  height: 100% !important;
}
```
And in the Highchart component, I would pass `containerProps= {{ style : { width: "100%", height: "100%" } }} `, if the component is stretching too much in height or width, just use a fixed px or maxWidth/Height or set it directly in the chart options.

P.S. All Highcharts parents must have a width/height of 100% (or whatever size you need it to be).
