### ISSUE TITLE
How do we Add data-testid to individual rendered elements

### ISSUE THREAD

**Issue by aarshad-devani-by** [highcharts/highcharts-react#358]
Need help with appending data-testid to individually rendered elements. Community suggest to do something like this
```js
 var pointsGraphics = chart.series[0].points.map(point => {
    	return point.graphic.element
    })
    
    pointsGraphics.forEach((elem, i) => {
    		elem.setAttribute('data-testid', 'someId-'+i)
    })
```

https://jsfiddle.net/p2yjpfp1/

Any help would be well appreciated.

This should be helpful for wider audience for identifying individually rendered elements while performing functional tests

**Comment by ppotaczek** [comment]
Hi @aarshad-devani-by,

Thank you for contacting us! 

The proposed way looks correct, but could you show a bigger context of how you use it?

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
