### ISSUE TITLE
HighchartsReact render issue using vitest and react testing library

### ISSUE THREAD

**Issue by longmatthewh** [highcharts/highcharts-react#359]
#### Expected behaviour
I should be able to render a `HighchartsReact` component in a test using vitest and react testing library.

#### Actual behaviour
When the `HighchartsReact` component attempts to be rendered, I get the following error:
`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.`

#### Live demo with steps to reproduce
https://stackblitz.com/edit/vitest-dev-vitest-t82cuf?file=test%2Fsuite.test.tsx&initialPath=__vitest__

when you load the URL above, you'll see the issue in the terminal once it's done installing deps and running tests

#### Product version
Highcharts latest

**Comment by ppotaczek** [comment]
Closed due to inactivity.
