### ISSUE TITLE
yAxis "resize" option not working

### ISSUE THREAD

**Issue by dqhuy93** [highcharts/highcharts-react#360]
Hello,

I try to enable resize at yAxis but i not working.
You can check the code at here: https://codesandbox.io/s/pie-chart-forked-mx0dyl?file=/src/index.js

Thanks,

**Comment by ppotaczek** [comment]
Hi @dqhuy93,

Thank you for contacting us!

As you can see in `yAxis.resize` API, this option requires `drag-panes` module. You need to import and initialize the module: 

```
  import Highcharts from "highcharts/highstock";
  import HighchartsReact from "highcharts-react-official";
  import dragPanes from "highcharts/modules/drag-panes";

  dragPanes(Highcharts);
```
  
**Live demo:** https://codesandbox.io/s/pie-chart-fork-zs4ocb?file=/src/index.js
**API Reference:** https://api.highcharts.com/highstock/yAxis.resize
