### ISSUE TITLE
Solid gauge legends render incorrectly after layout options change

### ISSUE THREAD

**Issue by gregbty** [highcharts/highcharts-react#361]
The solid gauge chart's legend does not re-render properly after changing the layout options dynamically unless you _explicitly_ set all of the property values that need to be overwritten. Usually the legend is rendered within the bounds of the chart.

I was able to create a repro for this: https://codesandbox.io/s/dawn-hooks-4xlitd?file=/src/App.js. Click the "Toggle Lengends" once to position the legends to the right and then another to attempt to return the legends to their original location. If you uncomment the `align`, `verticalyAlign`, and `alignColumns` properties, the chart renders properly.

**Comment by ppotaczek** [comment]
Hi @gregbty,

Thank you for contacting us!

First of all, the update works correctly - a chart is not a one to one representative of `options` property. If some of the options are updated, they are kept in a chart and another update needs to be called to back to a previous state.

Here is a simple example of similar situation without react: http://jsfiddle.net/BlackLabel/3wfeh8pm/ 

As a solution update all of the legend options or enable `immutable` property which creates a new chart after every update.

      <HighchartsReact
        immutable={true} 
       ...
      />

**Docs:** https://github.com/highcharts/highcharts-react#options-details

Best regards!

**Comment by gregbty** [comment]
Thanks for the reply! That makes sense and matches the observed behavior after I set all of the legend options.
