### ISSUE TITLE
NextJS Problem - Stock Tools or Price Indicator modules doesnt work 

### ISSUE THREAD

**Issue by musen34** [highcharts/highcharts-react#362]
Hi,

I have run highstock in my project and I have imported modules/stock-tools and called with StockTools but it doesnt shown on chart. Anybody have an idea?+

import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts/highstock';
import StockTools from "highcharts/modules/stock-tools";

AND

 if (typeof Highcharts === 'object') {
StockTools(Highcharts);
}

AND

        <HighchartsReact
          highcharts={Highcharts}
          options={chartOptions}
          constructorType={"stockChart"}
          ref={chartRef}
          containerProps={{ className: 'w-full h-full' }}
        />

highcharts and nexjt and react versions are latest!

**Comment by ppotaczek** [comment]
Hi @musen34,

Thank you for contacting us!

According to the stock-tools docs, you need to also import CSS:

```
import "highcharts/css/stocktools/gui.css";
import "highcharts/css/annotations/popup.css";
```

Live example: https://codesandbox.io/s/highcharts-react-demo-fork-06db4j?file=/demo.jsx
Docs: https://www.highcharts.com/docs/stock/stock-tools

Best regards!

**Comment by musen34** [comment]
> Hi @musen34,
> 
> Thank you for contacting us!
> 
> According to the stock-tools docs, you need to also import CSS:
> 
> ```
> import "highcharts/css/stocktools/gui.css";
> import "highcharts/css/annotations/popup.css";
> ```
> 
> Live example: https://codesandbox.io/s/highcharts-react-demo-fork-06db4j?file=/demo.jsx Docs: https://www.highcharts.com/docs/stock/stock-tools
> 
> Best regards!

Thank yo so much for your help!

I did and success:)

Btw,  I need to know why there are three js files loading? 

<img width="449" alt="Screen Shot 2022-03-24 at 10 42 19" src="https://user-images.githubusercontent.com/43618579/159866878-ac28bc80-4ace-4758-9b3f-ec45511e8302.png">

If I do not add this

 if (typeof Highcharts === 'object') {
  require('highcharts/modules/stock-tools')(Highcharts);
}

Only loading one js file (130kb) but when add above code, its increasing two files. Especially first and second js file is so similar.

I want to optimize it, because I do not use all functions.

**Comment by ppotaczek** [comment]
Hi @musen34, Could you recreate the problem in some minimal project example and add it here?

**Comment by musen34** [comment]
@ppotaczek 

I've copied some codes below;

import React, { useEffect, useState, useRef } from 'react';
import axios from 'axios';
import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts/highstock';

import "highcharts/css/stocktools/gui.css";
import "highcharts/css/annotations/popup.css";

const LineChart = ({ datach, code, period, setPeriod }) => {

  const [datafortime, setdatafortime] = useState();
  const [loading, setLoading] = useState(true);
  const [chartOptions, setChartOptions] = useState({
    chart: {
      backgroundColor: 'transparent',
      type: 'area',
      marginBottom: 20,
      spacingRight: 0,
      marginLeft: 0,
      spacingLeft: 0
    },
    legend: {
      enabled: false
    },

    title: undefined,
    yAxis: {
      currentPriceIndicator: {
        backgroundColor: '#000000',
        borderColor: '#000000',
        enabled: true,
        lineColor: '#000000',
        lineDashStyle: 'Solid',
        lineOpacity: 0.8,
        style: {
          color: '#ffffff',
          fontSize: '11px'
        },
        x: 35, //offset
        y: 0, //offset
        zIndex: 7
      },
      offset: 35,
      lineWidth: 1,
      gridLineWidth: 1,
      tickWidth: 1,
      minorGridLineWidth: 0,
      minorTickInterval: "auto",
      minorTickWidth: 1,
      minorTickLength: 5,
      minorTickPosition: "left",
      startOnTick: false,
      endOnTick: false,
      title: undefined,
      opposite: true,
      plotLines: [{
        value: 0,
        color: 'green',
        dashStyle: 'shortdash',
        width: 2,
        label: {
            text: 'Last quarter minimum'
        }
    }, {
        value: 1,
        color: 'red',
        dashStyle: 'shortdash',
        width: 2,
        label: {
            text: 'Last quarter maximum'
        }
    }],
      gridLineDashStyle: 'shortdot',
      gridLineColor: '#37495E',
                    tickPixelInterval: 10,
              crosshair: {
                color: '#7cb5ec',
                dashStyle: 'dash',
                interpolate: true,
                label: {
                  borderColor: '#cccccc',
                  enabled: true,
                  format: '{value:.4f}',
                  padding: 4
                }},
      labels: {
        x: 3,
        y: -2,
        style: {
          color: 'white',
          fontSize: '8px'
        }
      }
    },
    xAxis: {
      lineWidth: 0,
      tickLength: 0,
      tickWidth: 1,
      title: undefined,
      type: 'datetime',
      tickPixelInterval: 15,
      crosshair: {
        color: '#7cb5ec',
        dashStyle: 'dash',
        snap: false
      },
      labels: {
        style: {
          color: 'white',
          fontSize: '8px'
        }
      }
    },
    fillColor: {
      linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1 },
      stops: [
        [0, '#ff0000'],
        [1, '#f4f4f4']
      ]
    },
    credits: { enabled: false },
    exporting: {
      enabled: false
    },
    time: {
      useUTC: false
    },
    tooltip: {
      shared: true,
      useHTML: true,
      headerFormat:
        '<table style="font-size: 10px; font-weight: 300"><tr><th style="font-size: 10px; font-weight: 300">{point.key}</th></tr>',
      pointFormat: '<tr> <td style="text-align: right">{point.y} TRY</td></tr>',
      footerFormat: '</table>',
      valueDecimals: 2
    },
    rangeSelector:{
      enabled:false
  },
  scrollbar: {
    enabled: false, 
  },
  navigator: {
    outlineColor: "#283D51",
    maskFill: "rgba(154,175,198, 0.18)",
    handles: {
        backgroundColor: "#283D51",
        borderColor: "#F2F3F5"
    },
    xAxis: {
        gridLineColor: "#283D51",
        labels: {
            style: {
                color: "#71CEDC"
            }
        }
    },
    series: {
        lineColor: "#71CEDC",
        fillColor: "rgba(0, 220, 255, 0.05)",
    }
},
    plotOptions: {
      series: {
        name: code,
        color: 'rgba(63,187,204)',
        marker: {
          enabled: false
        }
      },
      area: {
        fillColor: {
          linearGradient: {
            x1: 0,
            y1: 0,
            x2: 0,
            y2: 1
          },
          stops: [
            [0, 'rgba(32,61,86, 1)'],
            [1, 'rgba(32,61,86, 0.5)']
          ]
        },
        marker: {
          radius: 2
        },
        lineWidth: 1,
        states: {
          hover: {
            lineWidth: 1
          }
        },
        threshold: null
      }
    },

    series: [{ data: datafortime }]
  });

 if (typeof Highcharts === 'object') {
  require('highcharts/modules/stock-tools')(Highcharts);
  require('highcharts/modules/annotations-advanced')(Highcharts);
  require('highcharts/modules/exporting')(Highcharts);
}

  if (process.browser) {
    Highcharts.setOptions({
      lang: {
        months: [
          'Ocak',
          'Şubat',
          'Mart',
          'Nisan',
          'Mayıs',
          'Haziran',
          'Temmuz',
          'Ağustos',
          'Eylül',
          'Ekim',
          'Kasım',
          'Aralık'
        ],
        weekdays: [
          'Pazar',
          'Pazartesi',
          'Salı',
          'Çarşamba',
          'Perşembe',
          'Cuma',
          'Cumartesi'
        ],
        shortMonths: [
          'Ock',
          'Şbt',
          'Mar',
          'Nis',
          'May',
          'Haz',
          'Tem',
          'Ağu',
          'Eyl',
          'Ekm',
          'Kas',
          'Ara'
        ]
      }
    });
  }


  return !loading ? (
    datafortime.length > 9 ? (
      <div className="w-full h-full">
        <HighchartsReact
          highcharts={Highcharts}
          options={chartOptions}
          constructorType={"stockChart"}
          ref={chartRef}
          containerProps={{ className: 'w-full h-full' }}
        />
      </div>
    ) : (
      <div className="text-xs text-white">Gösterilebilecek veri yok</div>
    )
  ) : (
    <div className="w-full h-full flex items-center justify-center">
      <div
        style={{ borderTopColor: 'transparent' }}
        className="w-6 h-6 border-2 border-white border-solid rounded-full animate-spin"></div>
    </div>
  );
};
export default React.memo(LineChart);

**Comment by ppotaczek** [comment]
Hi @musen34, Sorry for the late reply! 

I have tried to reproduce the issue by using the `create-react-app` tool, but everything seems to work as expected. Could you update the below project to show the problem?

[my-app.zip](https://github.com/highcharts/highcharts-react/files/8382996/my-app.zip)

**Comment by ppotaczek** [comment]
Closed due to inactivity.
