### ISSUE TITLE
Bubbles chart re-render changes the initial bubble radius

### ISSUE THREAD

**Issue by ileaugustin** [highcharts/highcharts-react#364]
The radius of the bubbles changes after re-rendering the chart, making them bigger, and sometimes they are out of context.

I have build this code sandbox to demonstrate the bug.

https://codesandbox.io/s/hc-bubble-chart-size-mismatch-x36ehf?file=/src/App.js:107-132

Please follow the steps to reproduce my issue.
I suspect there is a problem with how the prop `containerProps` is interpreted behind the scenes.
After reproducing the issue, try uncommenting line 70, and comment lines 66-69.

NOTE: I managed to reproduce the issue with the latest versions of highcharts and highcharts-react-official as well.

Please let me know if you need any clarifications.
Thank you!

**Comment by ppotaczek** [comment]
Hi @ileaugustin,

Thank you for contacting us!

The `containerProps` object is treated as a new one on each component update. That triggers an unnecessary chart update with the same options and finally results as a probably Highcharts bug.

Issue reproduced without react: http://jsfiddle.net/BlackLabel/oejnw60s/

The best solution for you will be to keep `containerProps` out of the component, in a state or memoize them.

Best regards!

**Comment by daniel-tabarcea** [comment]
are there any plans to fix this? re-rendering the chart with the same config should not cause this behavior. I'm seeing it when changing data after exiting the full screen chart for example. it behaves exactly like in the fiddle above if you go config 1 -> config 2 -> config 2 again -> config 1

**Comment by ppotaczek** [comment]
Hi @daniel-tabarcea, 

This problem is directly related to Highcharts, so could you report the problem on the main repository here: https://github.com/highcharts/highcharts/issues ?

**Comment by daniel-tabarcea** [comment]
I've opened [this ticket](https://github.com/highcharts/highcharts/issues/17161) on the HighCharts repo. Thanks for the help @ppotaczek!
