### ISSUE TITLE
Chart RefObject

### ISSUE THREAD

**Issue by gg2** [highcharts/highcharts-react#368]
Regarding the demonstrated examples at:
https://www.npmjs.com/package/highcharts-react-official

They don't seem to be valid anymore.
Under "Getting Started" > "Highcharts with TypeScript" mentions a RefObject. TypeScript in VS Code does not recognize a RefObject property on HighchartsReact ( where `import HighchartsReact from 'highcharts-react-official;` ).

And further down, the example "FAQ" > "How to get a chart instance?" gets a little further, but also does not work. Everywhere I try to use the ref it complains about mutable objects and the value possibly being null and, if I try to specifically check for existence and declare the type, like so:
```
useEffect(() => {
    //...
    if (chartRef.current && chartRef.current.chart) {
        const chart = chartRef.current.chart as Highcharts.Chart;
        chart.showLoading();
    }
}, []);
```
I get "Property 'chart' does not exist on type 'never'.", despite VS Code recognizing down below in the HighchartsReact component's ref property, where I pass in chartRef, that there are both a chart and container property on the React.Ref object.
'''
                <HighchartsReact
                    ref={ chartRef }
                    highcharts={ Highcharts }
                    constructorType={ 'stockChart' }
                    options={ chartConfig }
                    callback={ onChartCreated }
                />
'''

I find a RefObject interface in the source code on GitHub. I can't figure out how to import it. Although, I wonder if it's being weird because it's a namespace in the context of ES6 module imports. ???
Not sure what I might be doing wrong otherwise.

I was on highcharts-react-official 3.0.0. Updated to 3.1.0, but see no change.
(highcharts was 9.1.2; now 9.3.3)

**Comment by ppotaczek** [comment]
Hi @gg2,

Thank you for contacting us!

The problem with the reference typing has been fixed in v3.1.0. You should be able to use the notation from documentation:

    useRef<HighchartsReact.RefObject>(null);

I have also created a simple live example in TS: https://codesandbox.io/s/react-ts-9dgdnl?file=/src/App.tsx

Best regards!

**Comment by gg2** [comment]
OK. I should clarify, too, that I only see no difference in VS Code after updating. At this point, for having updated, I have to fix some other issues Material UI is having before I can properly test. But I assume Typescript won't let what I'm seeing in VS Code build, because it's still complaining about not seeing RefObject. So I'll post back when things are in a better state for proper testing that specifically ...

**Comment by gg2** [comment]
Ah. Yep, now that I got everything back to working again, 3.1.0 fixed it.
You might add the notation you referenced above to the npmjs page examples. It was the final piece to make everything work correctly, to get past the "does not exist on type never" message.
Thank you!

**Comment by ppotaczek** [comment]
Hi @gg2, I'm glad I could help. 

Thanks for your suggestion, but I am not sure what you mean. I think there is already information about typing reference: https://github.com/highcharts/highcharts-react#highcharts-with-typescript

**Comment by gg2** [comment]
There is, or at least most of the info. But it doesn't have the `<HighchartsReact.RefObject>` type.

In the example related to "For functional components and version 3.0.0 and later use useRef hook:",
`const chartComponent = useRef(null);`  could be  `const chartComponent = useRef<HighchartsReact.RefObject>(null);`.

It didn't work for me without the type specification. That might be eslint settings or whatnot, but that part was also necessary to make Typescript happy.

**Comment by ppotaczek** [comment]
But not all use TS. There is the type in the `Highcharts with TypeScript` section: 
`const chartComponentRef = useRef<HighchartsReact.RefObject>(null);`
