### ISSUE TITLE
Cannot change language dynamically

### ISSUE THREAD

**Issue by ewelina29** [highcharts/highcharts-react#370]
Hi,
I have a problem with changing language dynamically in highcharts context menu.
Once chart title is being set locally, it works great -> when the user changes app language, the title is being changed as well.
Unfortunately, the context menu buttons are set globally by 'lang' option and it isn't redrawn after language change.

I tried useEffect() on language change and using Highcharts.setOptions(...) inside this hook, but it's not working. Context menu is being translated only when I refresh the whole page.

How can I achieve my goal correctly?

**Comment by ppotaczek** [comment]
Hi @ewelina29,

Thank you for contacting us!

You need to recreate the chart after using `Highcharts.setOptions` to apply changes. The `key` attribute can be used to achieve that: 

```
const Chart = ({ language }) => {
  const [options] = useState({
    series: [
      {
        data: [1, 2, 3]
      }
    ]
  });

  return (
    <HighchartsReact key={language} highcharts={Highcharts} options={options} />
  );
};
```

**Live demo:** https://codesandbox.io/s/highcharts-react-dem-wwq4up?file=/demo.jsx

Best regards!
