### ISSUE TITLE
Unable to access chart.series.data using chartRef

### ISSUE THREAD

**Issue by whtitefall** [highcharts/highcharts-react#372]
Hi, 

I'm trying to get the color information of the scatter points on the graph using chartRef, 

however, I'm unable to access the series property from the chart instance. 

my javascript code is like this

```
    const chart = chartComponent.current.chart;
    console.log( chart.axes[0].series.length ); 
    console.log( chart.series.length ); 
    console.log( chart.series ); 
    console.log( chart.series[3] ); 

```

the response from the above code is below 

![image](https://user-images.githubusercontent.com/26782490/180590640-c65edba3-4890-4f03-b0e0-308053cc69d6.png)

I've searched for similar questions [here](https://github.com/highcharts/highcharts-react/issues/348) and [here](https://github.com/highcharts/highcharts/issues/13373)

but they are all Typescript related solutions and I'm not sure how that can be applied in my situation.

**Comment by ppotaczek** [comment]
Hi @whtitefall, 

Thank you for contacting us!

Could you reproduce the problem in some online code editor? You should be able to get the color by using the below code:

```
  useEffect(() => {
    const chart = chartComponent.current.chart;
    console.log(chart.series[0].points[1].color);
  }, []);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-1k0gbb?file=/demo.jsx

**Comment by whtitefall** [comment]
> Hi @whtitefall,
> 
> Thank you for contacting us!
> 
> Could you reproduce the problem in some online code editor? You should be able to get the color by using the below code:
> 
> ```
>   useEffect(() => {
>     const chart = chartComponent.current.chart;
>     console.log(chart.series[0].points[1].color);
>   }, []);
> ```
> 
> **Live demo:** https://codesandbox.io/s/highcharts-react-demo-1k0gbb?file=/demo.jsx

Hi, 

this is a live demo that is very close to the one I have, 

https://codesandbox.io/s/highcharts-react-demo-forked-g1co7l?file=/demo.jsx

when clicking on the "show color" button, it's unable to access the series information,

**Comment by ppotaczek** [comment]
That's because you refer to an empty chart. The chart is not immediately updated after `setOptions` call, it is an async operation. You need to use `useEffect` like below:

```
  useEffect(() => {
    if (options.series) {
      const chart = chartComponent.current.chart;

      console.log(chart.axes[0].series.length);
      console.log(chart.series.length);
      console.log(chart.series);
      console.log(chart.series[3]);
    }
  }, [options]);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-fork-17u6dm?file=/demo.jsx
