### ISSUE TITLE
Is there a way to use SVG or Canvas with this wrapper 

### ISSUE THREAD

**Issue by KevinDoherty94** [highcharts/highcharts-react#373]
Hi I'm trying to implement preferably Canvas on my chart that I've created using the wrapper in this documentation. I'm just curious if there is a way to do it and I want to implement the mousemove event to draw a path on my chart over existing data? Any help is appreciated alternatively if this is only doable with SVG just how to introduce an SVG element into my chart?

**Comment by ppotaczek** [comment]
Hi @KevinDoherty94,

Thank you for contacting us!

I don't know your exact requirements, but you should be able to position the canvas over the chart by using CSS and make it transparent. If it comes to SVG, you can just add `mousemove` event and add/edit `path` element by using Highcharts API.

**Live example:** http://jsfiddle.net/BlackLabel/7om63fv2/

Best regards!

**Comment by KevinDoherty94** [comment]
Hi @ppotaczek 

Thanks so much for getting back to me so quickly and for answering my question. 
This is indeed what I'm looking for. 

I'm also using Type Script as well but I'm getting a ts error for chart.customPath 
"Property 'customPath' does not exist on type 'Chart'." 
Any solutions to this? 

I've set the options variable to use type Highcharts.Options like in the typescript docs with the highcharts wrapper.

**Comment by ppotaczek** [comment]
Hi @KevinDoherty94,

I am glad that I could help.  

The added `customPath` property is a custom one and you need to extend `Chart` TS interface to use it correctly with TS. You can also store the path in some variable outside of the component function to avoid this problem.

**Docs:** https://www.highcharts.com/docs/advanced-chart-features/highcharts-typescript-declarations#extending-highcharts-in-typescript

**Comment by KevinDoherty94** [comment]
Thanks @ppotaczek , 

For all your help I've got it working now. And works perfectly.
