### ISSUE TITLE
Click event returns a wrong point while forcing to fire `onMouseOver` simultaneously.

### ISSUE THREAD

**Issue by wakkihaya** [highcharts/highcharts-react#374]
Hi there, I found the bug related to the events options in Highcharts. If there are work-around, please feel free to let me know 🙏 

### What I want to do
The app wants to update the tooltip automatically every 300ms by using `onMouseOver` function. And what I also want to add here is that when you click a point on the graph, the app should detect the clicked point and do something.

### Bug description
Even though clicking a point, the `click` event doesn't return the clicked point. Instead, it returns the mouse-overed point.

## Code
https://stackblitz.com/edit/react-starter-typescript-52vvg4?file=App.tsx

## Demo
![demo](https://gyazo.com/aee5bed050e786145e63b3d14d5818be)

**Comment by ppotaczek** [comment]
Hi @wakkihaya, 

Thank you for contacting us!

Please take a look at the implementation for `onContainerClick` method: https://github.com/highcharts/highcharts/blob/master/ts/Core/Pointer.ts#L1036 -> a hovered point is always treated as a clicked one.

As a solution, you can use the `findNearestKDPoint` method to find the proper point:

```
plotOptions: {
  ...,
  spline: {
    point: {
      events: {
        click(this, event) {
          const chart = this.series.chart;
          const point = chart.pointer.findNearestKDPoint(chart.series, false, event);

          console.log(point.index);
        }
      }
    }
  }
}
```

**Live demo:** https://stackblitz.com/edit/react-starter-typescript-xdacfw?file=App.tsx,index.tsx
**API Reference:** https://api.highcharts.com/class-reference/Highcharts.Pointer#findNearestKDPoint

Best regards!

**Comment by wakkihaya** [comment]
Thank you so much for a quick amazing suggestion! @ppotaczek  It totally works as I expected! You saved my time, thank you😁
