### ISSUE TITLE
Chart disappears after selected range change

### ISSUE THREAD

**Issue by mefioo** [highcharts/highcharts-react#375]
Hello,

I am currently trying to display data from the one day time range as shown here: https://codesandbox.io/s/highchart-example-pfir4m
The problem occurred when I tried to use range selector under the chart - shortening the scope causes the whole chart to disappear.

I've also tried to apply wider time range to the same yAxis data (instead of 1h time bucket, I have used 1 month) and everything seemed to work well. Is there any constraint about min time bucket?

**Comment by ppotaczek** [comment]
Hi @mefioo, 

Thank you for contacting us!

You have unsorted data - Highcharts error 15 in console: https://assets.highcharts.com/errors/15/
It seems that it is enough to reverse the data.

**Live demo:** https://codesandbox.io/s/highchart-example-fork-whkl5z?file=/src/App.js

Best regards!
