### ISSUE TITLE
After several updates the chart becomes freezy

### ISSUE THREAD

**Issue by oleksiy-lyulin** [highcharts/highcharts-react#376]
The application based on React using the "highcharts-react-official" library which is recommended in this case.

#### Expected behaviour
The chart should be permanently updated.

#### Actual behaviour
After 10-15 seconds of live updating the chart becomes freezy.
At first the left axis disappears and then the whole chart freezes (in addition, if you hover mouse pointer over the line bullet - the tooltip jumps like crazy)

#### Live demo with steps to reproduce
https://stackblitz.com/edit/react-gea6jx?file=src%2FApp.js

#### Product version
highcharts: 10.2.0
highcharts-react-official: 3.1.0
react: 18.2.0

#### Affected browser(s)
Chrome 104.0.5112.80

**Comment by raf18seb** [comment]
The problem is not visible in pure JS: https://jsfiddle.net/BlackLabel/w6dgm70n/

It's easier to see with an animation disabled: https://stackblitz.com/edit/react-bdahy7?file=src%2FApp.js

**Comment by ppotaczek** [comment]
Hi @oleksiy-lyulin, @raf18seb 

The `setInterval` call needs to be placed in `useEffect` hook, otherwise, it adds a new interval for every component update.

```
  useEffect(() => {
    setInterval(() => {
      setChartOptions({
        series: [
          {
            data: [Math.random() * 3, Math.random() * 3, Math.random() * 3],
          },
        ],
      });
    }, 500);
  }, []); 
```

**Comment by oleksiy-lyulin** [comment]
Hi Pawel and Rafal,

Thank you for your support and quick response.
Yes, you are right, that is my mistake.
Sorry for disturbing you.
Thank you again and best regards

Oleksiy

вт, 9 серп. 2022 р. о 11:10 Paweł Potaczek ***@***.***> пише:
