### ISSUE TITLE
can not use highchartsAccessibility module in highstock

### ISSUE THREAD

**Issue by Lanace** [highcharts/highcharts-react#377]
hi,
i want to use accessibility module. but i meet this error...

``` tsx
import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts/highstock';
import highchartsAccessibility from "highcharts/modules/accessibility";

highchartsAccessibility(Highcharts);
```

how can i set accessibillity module?

<img width="976" alt="image" src="https://user-images.githubusercontent.com/5744011/188070039-815e525b-322d-485e-8d7f-23b1580fe4ce.png">

**Comment by ppotaczek** [comment]
Hi @Lanace, 

Thank you for contacting us!

Which Highcharts version do you use? As you can see in the below example everything works as expected in the newest version.

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-egfrsc?file=/demo.jsx

**Comment by Lanace** [comment]
opps... i solved this problem...!

i used this version and using typescript
```
"highcharts": "^10.2.0",
"highcharts-react-official": "^3.1.0",
```

my solution is this.
error reason is Highcharts object is undefined.
so add type checking code.

``` tsx
import Highcharts from 'highcharts/highstock';
import HighchartsReact from 'highcharts-react-official';
import StockTools from "highcharts/modules/stock-tools";
import highchartsAccessibility from "highcharts/modules/accessibility";
...

if (typeof Highcharts === "object") {
  StockTools(Highcharts);
  highchartsAccessibility(Highcharts);
}
```

**Comment by Lanace** [comment]
but, i have new issue now...
i add StockTools module, then show stock tools in my screen.
however it didn't work

do i need any code...?
when i click stock tool, mouse cursor change and can use tool feature in  other example.
but in my chart, mouse cursor not changed and not working...

Thank you

**Comment by Lanace** [comment]
https://github.com/highcharts/highcharts-react/issues/362#issuecomment-1076524769

not working stock tools in this demo example...
for example draw line and text

i want to like this demo example
https://www.highcharts.com/demo/stock/stock-tools-custom-gui

**Comment by ppotaczek** [comment]
Hi, You need to load and initialize the `annotations-advanced` module.

Live example: https://codesandbox.io/s/highcharts-react-demo-goyu6n?file=/demo.jsx

**Comment by Lanace** [comment]
good! solved it!
Thank you so much..!
