### ISSUE TITLE
Missing line segment when updating the series 

### ISSUE THREAD

**Issue by whtitefall** [highcharts/highcharts-react#379]
Hi, 

I'm trying to plot a horizontal line using multiple series with a `start_position` and an `end_position`  on the x-axis. 

However, the entire line I'm getting missing some parts of the segments

For example, 

the line segement (14,30) is missing in the graph below

![image](https://user-images.githubusercontent.com/26782490/190790957-c12ca171-45da-4ca9-ae1a-f8c58acb91f2.png)

when I print out the `chartRef` I found that 

`chart.series` has a length of 5 

![image](https://user-images.githubusercontent.com/26782490/190792553-817aa2b9-95d8-4950-bfc5-09cf10bfdde9.png)

`chart.userOption.series` has length of 6 

![image](https://user-images.githubusercontent.com/26782490/190793988-ed5cf3b4-fb8b-425e-9ec4-ff75f2d39dd8.png)

This situation happens when I call `setCharOptions` to switch between different graphs like the one above, 

which means that one of the line segments is missing when I call  `setChartOptions`

I had this issue before, and I followed [this issue ](https://github.com/highcharts/highcharts-react/issues/317#issuecomment-911426733) to sort my line segments based on the value of `start_position`. 

However, this time this issue happened again, and I'm not sure where I possibly did wrong. 

I will post an online editor to reproduce the issue if needed. 

Thank you for your time!

**Comment by ppotaczek** [comment]
Hi @whtitefall,

Thank you for contacting us!

The problem can be related to data mutations, so please try to disable the `allowMutatingData` option.
If that doesn't help, please reproduce the issue in some online code editor.

**API Reference:** https://api.highcharts.com/highcharts/chart.allowMutatingData

**Comment by whtitefall** [comment]
Hi, 

I think I found the reason, the problem caused by the `linkedTo` keyworkd, 
if I'm not using the `linkedTo` keyword, the error won't happen.

**Comment by ppotaczek** [comment]
You should be able to use the `linkedTo` property without any errors, so please add more information if you want to fully solve the problem.

**Comment by ppotaczek** [comment]
Closed due to inactivity.
