### ISSUE TITLE
plotLines animate make in reactjs

### ISSUE THREAD

**Issue by phongplus** [highcharts/highcharts-react#381]
for javascript i saw this http://jsfiddle.net/kttfv1h3/
but i do not know ho to make animate for plotLines in reactjs
the data loading from websocket and updating realtime
```
chart.yAxis[0].update({
            plotLines: [
              {
                value: dataValue
              }
           ]
```

**Comment by ppotaczek** [comment]
Hi @phongplus, 

Thank you for contacting us!

You can use the same operation in a React environment, just get a chart instance and initialize the update interval in `useEffect` hook. For example:

```
const Chart = () => {
  const chartComponentRef = useRef(null);
  const [options, setOptions] = useState({...});

  useEffect(() => {
    const chart = chartComponentRef?.current?.chart;
    const series = chart.series[0],
      yAxis = chart.yAxis[0],
      plotLine,
      d,
      newY;

    ...
  }, [chartComponentRef]);

  return (
    <HighchartsReact
      ref={chartComponentRef}
      highcharts={Highcharts}
      options={options}
      constructorType="stockChart"
    />
  );
};
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-tt800o?file=/demo.jsx
**Docs:** https://github.com/highcharts/highcharts-react#how-to-get-a-chart-instance

Best regards!
