### ISSUE TITLE
How make stockTools Gui position in top of chart ?

### ISSUE THREAD

**Issue by phongplus** [highcharts/highcharts-react#382]
<img width="1461" alt="Screen Shot 2022-09-26 at 06 56 31" src="https://user-images.githubusercontent.com/91802798/192171441-3b78531c-77c4-4a4e-9f3a-3a8fd138e959.png">

```
stockTools: {
      gui: {
        enabled: true
      }
    },
```

i got document for js only, so after 2 days research I can't find a way to do it with reactjs.

**Comment by ppotaczek** [comment]
Hi @phongplus, 

Thank you for contacting us!
There is no big difference between JS and React stock tools version. You just need to define icons as HTML elements and bind events with them.

JS version: https://jsfiddle.net/BlackLabel/epb4zrq3/
React version: https://codesandbox.io/s/highcharts-react-80g4yf?file=/demo.jsx

Docs: https://www.highcharts.com/docs/stock/stock-tools

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
