### ISSUE TITLE
Cannot used with styledMode options

### ISSUE THREAD

**Issue by aydafield22** [highcharts/highcharts-react#385]
hi all, 
I've init project with nextjs, react, highcharts and highcharts-react, It works well, untill i've tried to use `styledMode: true`, the chart is not display and totally black. 
What wrong with me? I see this repo is not update in long time? is it ok to use? 
thank you.

**Comment by ppotaczek** [comment]
Hi @aydafield22,

Thank you for contacting us!

Yes, everything is fine with the wrapper and it is up-to-date with Highcharts. You just need to import default Highcharts styles to display the chart.

`@import "https://code.highcharts.com/css/highcharts.css";`

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-mybtem?file=/demo.jsx
**Docs:** https://www.highcharts.com/docs/chart-design-and-style/style-by-css

The same effect without React: https://jsfiddle.net/BlackLabel/kx7gfrq9/

Best regards!

**Comment by aydafield22** [comment]
Hello @ppotaczek, 
Many thanks your response. It works well now.
