### ISSUE TITLE
Style lastVisiblePrice label or any better solutions

### ISSUE THREAD

**Issue by aydafield22** [highcharts/highcharts-react#386]
hi all, 

Firstly my purpose is create a realtime price smooth update with last candle and a text allow multiple line and can set background color on the right both should realtime update smooth (animate) with last candle. So i found can use lastVisiblePrice label for right text and lastPrice for line price but  they are not works as expected and several minor problems.

1. How to position `lastVisiblePrice` label to right (same position with price label row),  current they are overlap on some last candles. I've tried with `style` options but it not works. 
2. How to custom style of `lastPrice` line such as: dashed instead of solid line
3. How to make `lastPrice` line and `lastVisiblePrice` label moving smooth as last candle .update (hide lastVisiblePrice label to see lastPrice line is moving faster than candle update).
4. I have two SMA indicator line but it is not draw on the first candle of chart, how to make it draw from first candle to last candle. 

This is my code demo: https://codesandbox.io/s/highcharts-react-demo-forked-y5wz08?file=/demo.jsx
Many thanks.

**Comment by aydafield22** [comment]
Hello @ppotaczek,
Many thanks your response. 
4. Is the workaround solution applied for SMA params 10,  I've tried duplicate first candle 9 times but the volume is display wrong. 

Thanks

**Comment by ppotaczek** [comment]
Hi @aydafield22,

Maybe a better idea will be to add the mocked points before the real ones and hide them. 
Please check this example: https://codesandbox.io/s/highcharts-react-demo-8f28xw?file=/demo.jsx

Best regards!

**Comment by aydafield22** [comment]
Hi @ppotaczek,
thank you so much your response and your time, let me try.

**Comment by aydafield22** [comment]
Hi @ppotaczek,
thank you so much your response and your time, let me try. I've a minor problem, It's related with candlestick, for now I added it here if can't i'll create in an other issue. I want to add an arrow shape with text at the point (candle) indicate it is highest price and lowest price as attached image.
Best regards! 
<img width="921" alt="Screenshot 2022-11-07 at 07 27 38" src="https://user-images.githubusercontent.com/104182889/200204399-265056a6-f932-4e0d-8ef2-68cfc577da69.png">

**Comment by ppotaczek** [comment]
Hi @aydafield22,

To create the custom arrow label, you can use [Highcharts SVG Renderer](https://support.highcharts.com/support/solutions/articles/44001706971-how-to-use-highcharts-svg-renderer-).

To make SMA line curved, you can reinitialize SMA indicator based on `spline` series.

```
Highcharts.seriesType(
  'sma',
  'spline',
  Highcharts.seriesTypes.sma.defaultOptions,
  Highcharts.seriesTypes.sma.prototype
);
```

Similar thread: https://www.highcharts.com/forum/viewtopic.php?t=41916
Live example: https://jsfiddle.net/BlackLabel/du59x6yk/

We use GitHub as a bug tracker, so in the future for such kind of questions please use one of our support channels: https://www.highcharts.com/blog/support/

Best regards!

**Comment by aydafield22** [comment]
Hi @ppotaczek,
Thank you your response and your time. 
Best regards!
