### ISSUE TITLE
Using series.index together with callback is hiding series

### ISSUE THREAD

**Issue by bastiW** [highcharts/highcharts-react#390]
Hi, 

## Issue 
I want to use the series.**index** for sorting. But as soon as I use the **callback** in combination with state it hides one series. 

## Options to make it work again

1) Comment line `setMyChart(chart)` to `// setMyChart(chart)` 
2) Remove the index in the series
3) Use the index in the same order as the array `[{index: 0}, {index: 1}, {index: 2}, {index: 3}]`

## Summary
But actually, I need both. The **callback** and the **index**. 

## Reproduction Link
https://stackblitz.com/edit/react-guwp9n?file=index.js 
(You see 4 data points in the series, but 3 are rendered)

## Code

```js
import React, { useState } from 'react';
import { render } from 'react-dom';
import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts';

const LineChart = () => {
  const [, setMyChart] = useState();
  const [chartOptions, setChartOptions] = useState({
    chart: {
      type: 'line',
    },
    series: [
      {
        index: 3,
        name: 'Italy',
        data: [
          [1609977600000, 856.2],
          [1610064000000, 856.8],
        ],
        color: 'green',
      },
      {
        index: 2,
        name: 'Germany',
        data: [
          [1609977600000, 757.6],
          [1610064000000, 755],
        ],
        color: 'gold',
      },
      {
        index: 1,
        name: 'Austria',
        data: [
          [1609977600000, 0],
          [1610064000000, 0],
        ],
        color: 'red',
      },
      {
        index: 0,
        name: 'France',
        data: [
          [1609977600000, 461.3],
          [1610064000000, 452.5],
        ],
        color: 'blue',
      },
    ],
  });

  return (
    <div>
      <HighchartsReact
        highcharts={Highcharts}
        options={chartOptions}
        callback={(chart) => {
          setMyChart(chart);
        }}
      />
    </div>
  );
};

render(<LineChart />, document.getElementById('root'));


```

**Comment by ppotaczek** [comment]
Hi @bastiW,

Thank you for contacting us!

The arrow function in `callback` prop is recreated on each component update and triggers unnecessary chart update. To prevent that, you can use:

      <HighchartsReact
        highcharts={Highcharts}
        options={chartOptions}
        callback={setMyChart} 
      />

Or use `useCallback` hook to memoize the function: 

```
  const storeChart = useCallback((chart) => {
    setMyChart(chart);
  }, []);

  return (
    <div>
      <HighchartsReact
        highcharts={Highcharts}
        options={chartOptions}
        callback={storeChart} 
      />
    </div>
  );
```

Best regards!

**Comment by bastiW** [comment]
Thanks a lot for your quick response. It is working like that.

Demo: https://stackblitz.com/edit/react-1zhpub?file=index.js


Still wondering why it is changing, because the props are actually the same.

**Comment by ppotaczek** [comment]
@bastiW, Everything seems to work as expected in the last example. Could you add more details what is wrong?

**Comment by bastiW** [comment]
Yes it works, so I can use it now in my app.

I just want to understand it why Highcharts is hiding one series in that case. I think there is another underlying issue in Highcharts.

**Comment by ppotaczek** [comment]
I've reproduced the issue without React here: http://jsfiddle.net/BlackLabel/Lg0b4he9/
The `index` property affects series order in an array and then Highcharts seems to incorrectly match series during update. You can report the issue on the main repository if you think it is a bug. Using `series.id` also resolves the problem.

API Reference: https://api.highcharts.com/highcharts/series.line.index

**Comment by ppotaczek** [comment]
Closed due to inactivity.
