### ISSUE TITLE
Can we do reset on navigator when we switch between custom zoom buttons.

### ISSUE THREAD

**Issue by vidyaflorency** [highcharts/highcharts-react#393]
Please see the attachment before analyzing the issue. I have a data set from 0 to 400 days. I have Custom zoom-level buttons for 25 days, 50 days, 75 days, 100 days, and All. Also, I have a navigator on X-axis.

The issue is when I select button 75, the data is displaying 50 to 75 (Navigator is setting some minRange) and gives access to show 50 to 0 data by using the navigator. But It has to display 0 to 75. 

Expected- When I select the zoom button 75 the data should display from 0 to 75 days on the x-axis. For button 100, 0 to 100 days on the x-axis. and so on. 

Current result - It is displaying 50 to 75 and giving access to drag from 50 to 0 with the help of the navigator. (navigator from right to left)
Expected result- It has to display 0 to 75. Also, it has to reset when we switch between zoom buttons.

![image](https://user-images.githubusercontent.com/68862993/211635571-47eaa8f6-3dba-45e0-ac61-da8d7f8bd1ce.png)

**Comment by KamilKubik** [comment]
Hi @vidyaflorency,

Thanks for contacting us!

Unfortunately, it's hard to help without seeing your code implementation but as you used the custom range selector buttons, you can change the click event to set the custom extremes (range between the first and last point). I've prepared an example, take a look: https://jsfiddle.net/5j2309pc/

Feel free to read more about the _setExtremes_ method here: https://api.highcharts.com/class-reference/Highcharts.Axis#setExtremes

As you can see, the above example works as you mentioned but if it's not helpful for you, would be much more helpful to debug and help you better if you reproduce your code in an online editor.

Kind Regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
