### ISSUE TITLE
When overriding `buttons.contextButton.menuItems` text for `Exit from fullscreen` doesn't show up

### ISSUE THREAD

**Issue by alexxxmf** [highcharts/highcharts-react#394]
Hey. team!

### Issue
If I opt for keeping all the default actions within the context menu when clicking on `View in fullscreen` I successfully launch fullscreen mode and when clicking on the hamburguer icon I can see i can exit fullscreen mode by clicking on `Exit from fullscreen`.
When adding an override within `exporting.buttons.contextButton.menuItems` so that I can pick just a subset of all the available buttons including the `viewFullscreen`, when going fullscreen mode I am able to exit fullscreen mode but the text from the button still reads as `View in fullscreen`.
There is no other override involving button text like the option in `lang` or `menuItemDefinitions` so this is totally unexpected behavior.

```
exporting: {
    exporting: {
      sourceWidth: 800,
      sourceHeight: 500,
      scale: 4,
      filename: generateFileName({ subMetricName: subMetric.name, type }),
      chartOptions: makeChartTitleAndCaptionOptionsForExport(chartExportProps),
      csv: { dateFormat: '%Y-%m-%d' },
      menuItemDefinitions: {
        viewFullscreen: {
          text: 'Toggle fullscreen mode',
        },
      },
      buttons: {
        contextButton: {
          menuItems: [
            'viewFullscreen',
            'separator',
            'downloadPNG',
            'downloadJPEG',
            'downloadPDF',
            'separator',
            'downloadCSV',
            'downloadXLS',
          ],
          x: -5,
          y: -13,
        },
      },
    },
}
```

### Versions
`"highcharts": "^9.3.3",`
`"highcharts-react-official": "^3.1.0",`

### Some extra info
When playing with plain highcharts seems it's still doing what it's suppose to do so could be a problem with just the react-highcharts wrapper?

**Comment by ppotaczek** [comment]
Hi @alexxxmf,

Thank you for contacting us!

I've tried to reproduce the problem in some basic example, but everything seems to work as expected here: https://codesandbox.io/s/highcharts-react-demo-r2rqpt?file=/demo.jsx

View: https://r2rqpt.csb.app/

Could you update the example to show the problem?

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
