### ISSUE TITLE
Highcharts typescript `Highcharts` is any

### ISSUE THREAD

**Issue by AlvaroAquijeDiaz** [highcharts/highcharts-react#395]
The exported interface triggers ESlint `unsafe-assignment-of-any-value`, plus the `HighchartsReact` component doesn't provide any completion for the required props.

- Nextjs - 13.x.x

```typescript
 <HighchartsReact
        ref={chartRef}
        highcharts={Highcharts} // This says any type
        options={{
          title: {
            text: "My chart",
          },
          series: [
            {
              type: "line",
              data: [1, 2, 3],
            },
          ],
        }}
      />
```

**Comment by ppotaczek** [comment]
Hi @AlvaroAquijeDiaz,

Thank you for contacting us!

Please provide me with the information about which Highcharts and HighchartsReact versions are you using?

Best regards!
