### ISSUE TITLE
xAxis.currentDateIndicator not working in react wrapper, but works in normal Highcharts

### ISSUE THREAD

**Issue by WieFel** [highcharts/highcharts-react#396]
I am trying to set the [xAxis.currentDateIndicator](https://api.highcharts.com/gantt/xAxis.currentDateIndicator) on my chart, but it is just ignored.

After comparing a vanilla highcharts jsfiddle vs a React Highcharts codesandbox, i discovered that this option somehow doesn't work in React Highcharts, also if I use the **exact** same chart-options object on both.

```typescript
{
...
  xAxis: [{
          currentDateIndicator: true,
```

Also, when looking into the types of React Highcharts, I see that it is annotated with `(Gantt)`, which would mean that it works for gantt only!? But I don't understand why, if on normal highcharts it works for all chart types...
```typescript
/**
 * (Gantt) Show an indicator on the axis for the current date and time. Can
 * be a boolean or a configuration object similar to xAxis.plotLines.
 */
currentDateIndicator?: (boolean|CurrentDateIndicatorOptions|CurrentDateIndicatorOptions);
```

**Comment by ppotaczek** [comment]
Hi @WieFel, 

Thank you for contacting us!

The current date indicator feature works for all chart types, also in React. All you need to do is to import and init `current-date-indicator` module. For example:

```
import Highcharts from "highcharts";
import currentDateIndicator from "highcharts/modules/current-date-indicator";

currentDateIndicator(Highcharts);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-hrpph9?file=/demo.jsx

Best regards!
