### ISSUE TITLE
Request: named exports instead of (or in addition to) default exports

### ISSUE THREAD

**Issue by Codex-** [highcharts/highcharts-react#397]
We've run into a tonne of issues when attempting to use `highcharts-react-official` because of how `default` has been used through different ecosystems, when bundling with esbuild (or vite) the `default` export generated by webpack ends up being `x.default.default`.

The esbuild team puts it best: https://esbuild.github.io/content-types/#default-interop

> If you are a library author: When writing new code, you should strongly consider avoiding the default export entirely. It has unfortunately been tainted with compatibility problems and using it will likely cause problems for your users at some point.

A simple solution would be to provide both the default export as you have currently (for existing users) and also the named export

**Comment by ppotaczek** [comment]
Hi @Codex-,

Thank you for your input! 

I am currently working on HighchartsReact v3.2.0, so I will add this improvement to the new wrapper version.

Best regards!

**Comment by ppotaczek** [comment]
The named export has been added in v3.2.0
