### ISSUE TITLE
Chart getting cut off on resizing 

### ISSUE THREAD

**Issue by nikunjjain-eaton** [highcharts/highcharts-react#399]
I am using HighchartsReact in react js. When i open orr close the side drawer charts get cut-off i m using below code. 

In return function 
  <HighchartsReact style={{ margin: '10px' }} ref={chartComponent} highcharts={Highcharts} options={options} allowChartUpdate={true} />

useEffect(() => {
        handleResize()
    }, [width, chartComponentBuild, chartComponent, chartComponentDemand, drawerOpen])

   const handleResize = () => {
 
            if (chartComponent.current && chartComponent.current.chart && chartComponent.current.chart.chartWidth) {
                // alert("chart2" +" "+ window.innerWidth + "  " + width)
                chartComponent.current.chart.chartWidth = 100;
                chartComponent.current.chart.reflow()

            }
        }

**Comment by ppotaczek** [comment]
Hi @nikunjjain-eaton,

Thank you for contacting us!

Could you reproduce the problem in some online code editor? You can start from: https://codesandbox.io/s/highcharts-react-demo-gbg3n3

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
