### ISSUE TITLE
WordCloud

### ISSUE THREAD

**Issue by haidercharly** [highcharts/highcharts-react#4]
Is there an official way to use the wordcloud type through the highcharts-react component? How can I import the wordcloud module the react way?

Would appreciate any help - thanks in advance!

**Comment by KacperMadej** [comment]
Hello @haidercharly 

Example for loading a module is here: https://github.com/highcharts/highcharts-react/blob/master/demo/demo.jsx#L17

With word cloud this will be similar. The code will be as:
`require('highcharts/modules/wordcloud')(Highcharts)`

Please let me know if the info is sufficient or if I should provide more.

**Comment by haidercharly** [comment]
Thank you very much @KacperMadej !
Works as expected now !
