### ISSUE TITLE
Click event packedbubble

### ISSUE THREAD

**Issue by Iulxim** [highcharts/highcharts-react#401]
Hello,

Is there any way to click an specific bubble in 'packedbubble' Highchart type and open a Modal Component portal ?
Right now, i feel like my attempt isn't quite right, and i have not seen something for packedbubble

```
const [modal, setModal] = useState(false);
plotOptions: {
        series: {
          cursor: 'pointer',
          point: {
            events: {
              click: function () {
                if (this.name === '...') {
                  setModal(true);
                }
              }
            }
          }
        }
```
and based on modal you would createPortal with the content that you need for that specific bubble.
Thank you!

**Comment by ppotaczek** [comment]
Hi @Iulxim,

Thank you for contacting us!
Your attempt looks totally fine and should work correctly. You should use point's `click` event and show a model with stored point info. Please check the below live example.

**Live demo:** https://codesandbox.io/s/highcharts-react-demooo-y5lrzq?file=/demo.jsx

Best regards!

**Comment by Iulxim** [comment]
@ppotaczek Thank you so much, this really helped!
