### ISSUE TITLE
X and Y axis grid lines not visible

### ISSUE THREAD

**Issue by TathagatNegi** [highcharts/highcharts-react#402]
Please suggest how to show grid lines in the step chart.
![image](https://user-images.githubusercontent.com/62710725/227928503-86c0b727-0fd0-451c-880b-226e46c30828.png)

**Comment by ppotaczek** [comment]
Hi @TathagatNegi,

Thank you for contacting us!

Grid lines are visible by default for y-axis, to show them also for x-axis, set:

```
  xAxis: {
    gridLineWidth: 1
  }
```

**Live example:** http://jsfiddle.net/BlackLabel/y7nogk8c/
**API Reference:** https://api.highcharts.com/highcharts/xAxis.gridLineWidth

Best regards!

**Comment by TathagatNegi** [comment]
Hi @ppotaczek 
Thanks for the response.
I have already configured this in the config but still lines are not visible. Please suggest what else to checl
![image](https://user-images.githubusercontent.com/62710725/228153684-41783e17-fe97-470b-ab2d-3e5171480bea.png)

**Comment by ppotaczek** [comment]
@TathagatNegi, please reproduce the problem in some online code editor.

**Comment by ppotaczek** [comment]
Closed due to inactivity.

**Comment by ningxi-oa** [comment]
I encountered a similar issue here. @TathagatNegi , could you please explain how you resolved it in the end?

**Comment by TathagatNegi** [comment]
@ningxi-oa  hi, i actually don’t remember. Currently im out on vacation .. will check and respond to you in a week

**Comment by xion099** [comment]
Hi @TathagatNegi 
I am also experiencing a similar issue. Could you please explain how to resolve it? I hope you are back from your vacation.
