### ISSUE TITLE
v3.2.0 - build results in lost tooltip functionality

### ISSUE THREAD

**Issue by bberz-groma** [highcharts/highcharts-react#403]
We recently upgraded  `highcharts-react-official` from 3.1.0 to 3.2.0 and as a result we had a reported bug related to our tooltips on our Visualizations. 

Our applications use `highcharts: 10.3.3` (running Node 18.12.1) and in debugging this issue, I can't really point to anything in particular other than the resulting code between running webpack server locally and running a build server via `serve -s build` results in a different experience. (there are no console errors from the build or issues resulting in a problem related to the build).

Locally, when interacting with a visualization, the tooltip renders the content as expected
![image](https://user-images.githubusercontent.com/100605721/234339779-cb09cc42-0e5c-4af3-9ba1-3eae80ccab0c.png)

However, when running a result of `build` via `serve -s build` we get this
![Pasted_Image_4_25_23__12_19_PM](https://user-images.githubusercontent.com/100605721/234339985-be8a778a-0f50-4925-92dc-3144d8b60e72.png)

It's worth noting that we're leveraging the `tooltip: formatter: () {...}` option via ChartOptions where we are rendering content inside of the tooltip but outside of that, nothing majorly custom related to this implementation. 

It is also worth noting that when we downgrade to `highcharts-react-official: 3.1.0` the issue resolved itself and the expected functionality returns.

**Comment by ppotaczek** [comment]
Hi @bberz-groma and thank you for contacting us!

I wouldn't like to blindly guess what is wrong, so I need to ask you to provide more details about the problem. Could you recreate the issue in some minimal separate project and provide it here?

Best regards!

**Comment by bberz-groma** [comment]
@ppotaczek thanks for the reply - after reverting, I tried to upgrade again and after removing package-lock and node_modules the problem seemed to resolve itself. _classic instance of remove package-lock and re-install_.

Happy to close this issue and will reopen should this issue arise again.
