### ISSUE TITLE
Error using export-data module

### ISSUE THREAD

**Issue by rafaelegh** [highcharts/highcharts-react#405]
hello, i'm using react typescript, and importing the exporting.js and export-data.js modules and i obtain an error on vscode:

![image](https://github.com/highcharts/highcharts-react/assets/58056878/317d9751-0524-4e7f-97e9-1f86308196e0)

here it's how i'm importing the modules: 

import HighchartsReact from "highcharts-react-official";
import Highcharts from 'highcharts';
import HC_exporting from 'highcharts/modules/exporting';
import HC_exportData from 'highcharts/modules/export-data';

HC_exporting(Highcharts);
HC_exportData(Highcharts);

**Comment by ppotaczek** [comment]
Hi @rafaelegh,

Thank you for contacting us!

I was able to reproduce the issue using Highcharts v11 and React. The problem seems to be a regression bug in Highcharts, so now I am planning to reproduce it in pure JS and report it on the main repository. I will keep you updated.

Best regards!

**Comment by rafaelegh** [comment]
Thank you @ppotaczek

**Comment by ppotaczek** [comment]
@rafaelegh, I reported the issue on the main repository, it is related to a wrong build for export-data module sourcemap. As a workaround, you can downgrade your Highcharts version to 10.3.3.

**Comment by ppotaczek** [comment]
Hi @laxmikanta415, This bug is related to the main Highcharts repository, so I don't know the answer to your question. You can add your comment or something like '+1' in the linked thread.

**Comment by markcorrea** [comment]
Same issue here

**Comment by surbhitt** [comment]
hi @rafaelegh,
I was trying to use the local export function (offline-export), are you using the same and if you are can you help me with how you did it. A piece of code as demonstration would suffice.

**Comment by ppotaczek** [comment]
@surbhitt, you need to load and initialize `offline-exporting`.

```
import Highcharts from 'highcharts';
import HC_exporting from 'highcharts/modules/exporting';
import HC_offlineExporting from 'highcharts/modules/offline-exporting';

HC_exporting(Highcharts);
HC_offlineExporting(Highcharts);
```

**Live example:** https://stackblitz.com/edit/react-salqui?file=index.js
**Docs:** https://www.highcharts.com/docs/export-module/client-side-export

**Comment by surbhitt** [comment]
@ppotaczek thank you I was able to download the png file. I need the png data, I wanna embed the chart image into a pdf, I am using pdfme library, instead of downloading the file immediately. How can I do that?

**Comment by ppotaczek** [comment]
Hi @surbhitt, You can get the exported image and use the pdfme library to place it in pdf.
Please check this thread: https://stackoverflow.com/questions/8995177/render-highcharts-canvas-as-a-png-on-the-page

**Comment by ravindraAtDure** [comment]
> [@surbhitt](https://github.com/surbhitt), you need to load and initialize `offline-exporting`.
> 
> ```
> import Highcharts from 'highcharts';
> import HC_exporting from 'highcharts/modules/exporting';
> import HC_offlineExporting from 'highcharts/modules/offline-exporting';
> 
> HC_exporting(Highcharts);
> HC_offlineExporting(Highcharts);
> ```
> 
> **Live example:** https://stackblitz.com/edit/react-salqui?file=index.js **Docs:** https://www.highcharts.com/docs/export-module/client-side-export

@ppotaczek It's hard to find the docs for "exportChartLocal" function. Please if you can provide.

**Comment by ppotaczek** [comment]
Hi @ravindraAtDure, I'm glad my solution helped. Below you can find the docs:

Docs: https://www.highcharts.com/docs/export-module/client-side-export
API: https://api.highcharts.com/class-reference/Highcharts.Chart#exportChartLocal
