### ISSUE TITLE
Highcharts map not rendering as expected

### ISSUE THREAD

**Issue by swsvindland** [highcharts/highcharts-react#407]
# Repo
https://codesandbox.io/s/hungry-frog-3t01io?file=/src/App.tsx

# Expected 
https://jsfiddle.net/gh/get/jquery/1.11.0/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/us/us-fl-all

I might just be missing a config option or something, but I have been unable to get the react plugin to work with the maps extension. It works great with core, but the main pull of this option is the map charts

**Comment by ppotaczek** [comment]
Hi @swsvindland,

Thank you for contacting us!

You need to set `constructorType` prop:

    <HighchartsReact
      ref={chartComponent}
      highcharts={Highcharts}
      options={options}
      constructorType="mapChart"
    />

It is also better to init the map module - `highchartsMap(Highcharts);` outside of a component definition.

**Live demo:** https://codesandbox.io/s/lingering-firefly-j87eo-j87eoi?file=/src/App.tsx
**Docs:** https://github.com/highcharts/highcharts-react#options-details

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
