### ISSUE TITLE
How to create Synchronized highcharts-react without event jquery ?

### ISSUE THREAD

**Issue by jomarquez21** [highcharts/highcharts-react#41]
the [documentation](https://www.highcharts.com/demo/synchronized-charts/dark-unica) indicates that a jquery event is added to synchronize map points, how can I do this without jquery?

I already added that when zoon is synchronized with the `setExtremes` event in the` xAxis` property, but I need the crosshairs and the tooltip, can you tell me how to do it please?

**Comment by KacperMadej** [comment]
Hi @jomarquez21 

For technical support please use https://www.highcharts.com/support

You could remove jQuery dependency and use native JavaScript event's listeners or use React features to handle events - https://reactjs.org/docs/handling-events.html
