### ISSUE TITLE
Drilldown not working

### ISSUE THREAD

**Issue by Kafierence** [highcharts/highcharts-react#410]
```
import HighchartsReact from 'highcharts-react-official';
import Highcharts from 'highcharts/highstock';
import drilldown from 'highcharts/modules/drilldown.js';
import React from 'react';
import { render } from 'react-dom';
// Import Highcharts

drilldown(Highcharts);

const options = {
  chart: {
    type: 'pie',
  },

  series: [
    {
      data: [
        {
          name: 'Edge',
          y: 4.02,
          drilldown: 'Edge',
        },
        {
          name: 'Opera',
          y: 1.92,
          drilldown: 'Opera',
        },
      ],
    },
  ],
  drilldown: {
    series: [
      {
        name: 'Edge',
        id: 'Edge',
        data: [
          ['v16', 2.6],
          ['v15', 0.92],
        ],
      },
      {
        name: 'Opera',
        id: 'Opera',
        data: [
          ['v50.0', 0.96],
          ['v49.0', 0.82],
        ],
      },
    ],
  },
};

const Detail = () => {
  return <HighchartsReact highcharts={Highcharts} options={options} />;
};

export default Detail;
```

I also use the same file in your example code
Here is the version of my librabry:
"highcharts": "^11.0.1",
   "highcharts-react-official": "^3.2.0",
    It return undefined (reading hasOwnProperty) How can I fix it in typescript ?

**Comment by ppotaczek** [comment]
Hi @Kafierence,

Thank you for contacting us!

I've tested your code and drilldown works as expected. The only problem that I found is related to importing Highcharts in TS. You should use: `import * as Highcharts from 'highcharts';`
Could you add more details?

**Live demo:** https://stackblitz.com/edit/react-starter-typescript-vf6rht

Best regards!

**Comment by Kafierence** [comment]
> Hi @Kafierence,
> 
> Thank you for contacting us!
> 
> I've tested your code and drilldown works as expected. The only problem that I found is related to importing Highcharts in TS. You should use: `import * as Highcharts from 'highcharts';` Could you add more details?
> 
> **Live demo:** https://stackblitz.com/edit/react-starter-typescript-vf6rht
> 
> Best regards!

Thank you for your reply , I also found the problem in this , because the first time when I try to render Highchart it have underfined => So I check it again   
if (typeof Highcharts === 'object') {
    HighchartsExporting(Highcharts);
    HC_drildrilldown(Highcharts);
  } and it work
