### ISSUE TITLE
Example About Drilldown highchart map in TS

### ISSUE THREAD

**Issue by KarasAtomic** [highcharts/highcharts-react#413]
I during develop a application when click from the custom map in the world , it can drilldown to a country detail  and have the marker about population in it. Can You give me a simple example can do that ? I try to do that , but when I apply drilldown and afterdrilldown function it not work ( I also import module of drilldown and something like that)

**Comment by ppotaczek** [comment]
Hi @KarasAtomic,

This is a typical support question, so in the future please use one of our support channels: https://www.highcharts.com/blog/support/

I am not sure if I understand your requirements correctly, but I moved this official map drilldown example: https://www.highcharts.com/demo/maps/map-drilldown

to React: https://codesandbox.io/s/highcharts-react-demo-btwwhw

Best regards!
