### ISSUE TITLE
Issue with using funnel chart

### ISSUE THREAD

**Issue by vikashcv** [highcharts/highcharts-react#415]
I was trying to pass chart config with funnel chart as type, but got the following error:

```
Error: Highcharts error #17: www.highcharts.com/errors/17/?missingModuleFor=funnel
 - missingModuleFor: funnel
```
Is funnel chart supported in highcharts-react?

```
import * as HighCharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
...
const chartOptions: any = {
    chart: {
      type: 'funnel',
    },
    title: {
      text: 'Sales funnel',
    },
    plotOptions: {
      series: {
        dataLabels: {
          enabled: true,
          format: '<b>{point.name}</b> ({point.y:,.0f})',
          softConnector: true,
        },
        center: ['40%', '50%'],
        neckWidth: '30%',
        neckHeight: '25%',
        width: '80%',
      },
    },
    legend: {
      enabled: false,
    },
    series: [
      {
        name: 'Unique users',
        data: [
          ['Website visits', 15654],
          ['Downloads', 4064],
          ['Requested price list', 1987],
          ['Invoice sent', 976],
          ['Finalized', 846],
        ],
      },
    ],

    responsive: {
      rules: [
        {
          condition: {
            maxWidth: 500,
          },
          chartOptions: {
            plotOptions: {
              series: {
                dataLabels: {
                  inside: true,
                },
                center: ['50%', '50%'],
                width: '100%',
              },
            },
          },
        },
      ],
    },
  };
  return (
    <HighchartsReact
      highcharts={HighCharts}
      ref={chartComponentRef}
      options={chartOptions}
      {...props}
    />```

**Comment by ppotaczek** [comment]
Hi @vikashcv,

Thank you for contacting us!

Yes, every Highcharts feature is supported in `highcharts-react-official`. To use `funnel` series type, you need to load and initialize `funnel` module:

```
import Highcharts from "highcharts";
import HighchartsReact from "highcharts-react-official";
import funnelModule from "highcharts/modules/funnel";

funnelModule(Highcharts);
```

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-wrcms6
**API Reference:** https://api.highcharts.com/highcharts/series.funnel

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.

**Comment by vikashcv** [comment]
Hi @ppotaczek , Thank you so much!

**Comment by truonglv1** [comment]
Hi @ppotaczek, I followed your instructions and got the error on picture. Can you help me?
![Screenshot 2023-12-15 005429](https://github.com/highcharts/highcharts-react/assets/45839760/866b87f7-d4cc-4768-8524-9407c6601097)
"

**Comment by ppotaczek** [comment]
Hi @truonglv1,
I see that you are using Remix, so there is probably similar issue as with Next.js. Please try to use the below solution:

```
if (typeof Highcharts === 'object') {
    funnelModule(Highcharts);
}
```

**Comment by kishoremurali21** [comment]
Hi @ppotaczek,

Thank you for sharing the demo. Unfortunately, the link (https://codesandbox.io/s/highcharts-react-demo-wrcms6) doesn’t seem to be working for me. Could you please check if it’s still active or if there’s another link I should use?

Thanks in advance!
