### ISSUE TITLE
Redraw issues with highstock xrange scrollbars

### ISSUE THREAD

**Issue by phi-lam** [highcharts/highcharts-react#416]
Hello,

I have an edge case issue that occurs when the bars in an xrange graph are removed such that the highstock scrollbar disappears.

When data is re-added and the scrollbar should be re-enabled, the bars of the chart don't resize, and sometimes the scrollbar doesn't re-enable properly at all.

In the first image, I have all the data present

In the second image, I filter out all but one user

In the third image, I restore the filter to the state shown in the first image, however, only one user is visible, and is drawn at that size. Reflow and redraw have no effect, but refreshing the page brings back the data.

Is this an issue on my end, or are there known issues/workarounds when using the Highstock scrollbar? 

Thanks,
Phi

<img width="815" alt="image" src="https://github.com/highcharts/highcharts-react/assets/28878402/c6a389a1-6342-4eaa-81d2-c05362caca05">

<img width="735" alt="image" src="https://github.com/highcharts/highcharts-react/assets/28878402/96de74a3-12c1-4138-b868-689002c7495e">

<img width="736" alt="image" src="https://github.com/highcharts/highcharts-react/assets/28878402/3ccb093a-1105-444d-a28d-a3c8ad1cd9f1">

**Comment by phi-lam** [comment]
I've also included my scrollbar options for the yAxis here: 
<img width="310" alt="image" src="https://github.com/highcharts/highcharts-react/assets/28878402/7036653d-e347-429e-8913-99b95fe3e7f1">

**Comment by ppotaczek** [comment]
Hi @phi-lam,

Thank you for contacting us!

The issue can be related to the way of updating the chart. Could you reproduce the problem in some online code editor, so I could investigate it?

You can start from: https://codesandbox.io/s/highcharts-react-demo-forked-gbg3n3

Best regards!

**Comment by phi-lam** [comment]
Thank you for the reply! I will get to work on it

**Comment by phi-lam** [comment]
I have had issues getting the code to work in the online editor, however I've found that the problem is rooted in a buggy attempt to manually setExtremes(). Allowing highcharts to manage that itself has resolved most of the issues. Thank you for your time!
