### ISSUE TITLE
Treemap Drilldown button disappears

### ISSUE THREAD

**Issue by btomy** [highcharts/highcharts-react#42]
Hi,
I discovered a bug when i was using the Drilldown Treemap series for my project.
So if you drilldown into the series and then you change the data ( Graph will reload) the drilldown button disappears after the graph is loaded 

#### How to reproduce
Once you click on any of the Continents and drilldown into the series. 
Then click on the 6 months radio button. The new data will be loaded
*The drilldown button disappers* 

#### Live demo demonstrating bug
https://stackblitz.com/edit/react-wbxgyv

Github Repo
https://github.com/btomy/Highcharts-treemap

#### Versions
* React JSX Highcharts version: 3.1.0
* Highcharts version: 6.1.1
* React version: 16.4.1

**Comment by KacperMadej** [comment]
Hi @btomy 

Are you using highcharts-react-official Node package in your project? This repository is for that package. For general Highcharts support please see https://www.highcharts.com/support

For bugs in the third party React JSX Highcharts contact it's authors or maintainers.

**Comment by btomy** [comment]
Hi @KacperMadej 

No i am using the react-jsx-highcharts. Sure i will raise the issue there.
Thanks you 👍
