### ISSUE TITLE
Chart Resize based on father´s container ( avoiding reflow )

### ISSUE THREAD

**Issue by jrivax** [highcharts/highcharts-react#420]
Hi there !!! First of all thanks in advance.

I have a problem resizing highchart react based on it's fathers container, when collapsing a menu for example. I just created a codeSand to reproduce the issue and what was my surprise, it worked well.

https://codesandbox.io/s/highcharts-react-demo-forked-j9kmgg?file=/chartStyles.css

To my surprise, when I coded my application and did the same thing, it didn't work. I have tried everything, in fact I have loaded the small code directly in the application load and it doesn't work, it doesn't work  as in the sandbox, black magic.

Do you have any idea why this could be happening ? Using reflow is not an option, due to the large amount of casuistry that can be, collapsed menus, stacked views, etc.

![Screenshot 2023-06-19 at 16 03 40](https://github.com/highcharts/highcharts-react/assets/15192079/acdb670c-6f87-49a8-813d-a054e45eff8c)

![Screenshot 2023-06-19 at 16 04 15](https://github.com/highcharts/highcharts-react/assets/15192079/4ce6848b-958e-4e70-a0fa-ea8672e9487b)

Thanks a lot in advance. Cheers.

**Comment by jrivax** [comment]
Hi @ppotaczek ,

Thanks a lot for the quick response, let me check quickly your sollution, if not, I will try to create a small react project to try to reporduce and share.

Versions were the same, I just set on the code sandbox to the ones been used.

Keep you informe. Cheers !!

**Comment by ppotaczek** [comment]
Thanks for the example!

In this case the best solution would to use `chart.reflow`, but due to your limitations, you can use the below config:

```
<HighchartsReact
  ...
  immutable={true}
  containerProps={{ style: { width: "100%", height: '100%' } }}
/>
```

The chart will be recreated on each layout change and its dimensions adapted.

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
