### ISSUE TITLE
how to set global options

### ISSUE THREAD

**Issue by pdeva** [highcharts/highcharts-react#423]
when using the highcharts react, what is the recommended way to set global options that all other `HighchartsReact` instances will use?

i tried doing this:
``` js
import Highcharts from "highcharts";
Highcharts.setOptions({
    time: {
        useUTC: false,
    }
});
``` 
and got this error:

```
TypeError: import_highcharts2.default.setOptions is not a function
```

**Comment by ppotaczek** [comment]
Hi @pdeva, 

Thank you for contacting us!

There is no any special way of using global options required by our wrapper.

Please check this simple example: https://codesandbox.io/s/highcharts-react-demo-5r7tdy - your notation should work correctly.

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
