### ISSUE TITLE
Typescript 5.2.2 type errors

### ISSUE THREAD

**Issue by swsvindland** [highcharts/highcharts-react#426]
Repo
```
https://codesandbox.io/p/sandbox/festive-tesla-75txz8?file=%2Fsrc%2FApp.tsx%3A8%2C2
```
1. Go to code sandbox
2. run pnpm install
3. run pnpm build
```
src/App.tsx:6:33 - error TS2833: Cannot find namespace 'HighchartsReact'. Did you mean 'Highcharts'?

6 interface BarChartProps extends HighchartsReact.Props {
                                  ~~~~~~~~~~~~~~~

src/App.tsx:13:36 - error TS2833: Cannot find namespace 'HighchartsReact'. Did you mean 'Highcharts'?

13   const chartComponentRef = useRef<HighchartsReact.RefObject>(null);
                                      ~~~~~~~~~~~~~~~
 ```

It looks like the update to 5.2 had some breaking changes to how declaring modules works

```
https://devblogs.microsoft.com/typescript/announcing-typescript-5-2-rc/#consistent-export-checking-for-merged-symbols
```

**Comment by benoitgrasset-cliq** [comment]
same issue, need to downgrade typescript: `"typescript": "~5.1.6"`

**Comment by ppotaczek** [comment]
Hi @swsvindland, @benoitgrasset-cliq

Thanks for reporting!

I've created a branch: `426-typescript-5.2.2-fix` with a potential fix. Would it be possible for you to test it in your use cases?

PR: https://github.com/highcharts/highcharts-react/pull/427

Best regards!

**Comment by benoitgrasset** [comment]
Hi @ppotaczek , 
I tested with `"highcharts-react-official": "highcharts/highcharts-react#426-typescript-5.2.2-fix"`, and it works great, nice job :+1:

**Comment by swsvindland** [comment]
@ppotaczek Looks good on my end as well. Thanks!!!

**Comment by heath-freenome** [comment]
@ppotaczek I'm also have this issue. Any eta on the fix being release?

**Comment by ppotaczek** [comment]
Thanks for your comments! 
I am planning to release highcharts-react-official v3.2.1 on Monday.

**Comment by ppotaczek** [comment]
Version 3.2.1 has been released: https://www.npmjs.com/package/highcharts-react-official

**Comment by val1984** [comment]
@ppotaczek Thank you for the quick resolution. I confirm your fix works 👍
