### ISSUE TITLE
Highcharts accessibility module causes incorrect markers to be displayed

### ISSUE THREAD

**Issue by cmccormick-im** [highcharts/highcharts-react#429]
I have noticed that the highcharts accessibility module causes markers for individual data points to be incorrectly displayed after the window is resized. See the following example: https://stackblitz.com/edit/react-starter-typescript-6kkkzr?file=App.tsx 

Even though the second point should have the marker disabled, after resizing the window a couple of times, the marker comes back.

**Comment by ppotaczek** [comment]
Hi @cmccormick-im,

Thank you for contacting us!

This problem has been already reported on the highcharts main repository and it is marked as a bug: https://github.com/highcharts/highcharts/issues/17946

You can add you comments there.

Best regards!
