### ISSUE TITLE
yAxis is displayed incorrectly when formatter Highcharts.numberFormat

### ISSUE THREAD

**Issue by buithienai** [highcharts/highcharts-react#430]
<img width="476" alt="image" src="https://github.com/highcharts/highcharts-react/assets/38641926/bc93ee8c-71b1-4945-b50c-59334f599980">

![Screen Shot 2023-09-19 at 15 21 10](https://github.com/highcharts/highcharts-react/assets/38641926/dfe593fe-5d65-48bb-b6af-83ed954b2a6d)

**Comment by ppotaczek** [comment]
Hi @buithienai,

Thank you for contacting us!

The `numberFormat` method is not officially supported, however it should work as expected. 

You can check implementation of the method here: https://github.com/highcharts/highcharts/blob/e137bddbc5a74063da5074812f00f19b0eff56bf/ts/Core/Templating.ts#L379

Below, you can find a simple example with the method.

**Live demo:** https://jsfiddle.net/BlackLabel/0epnt5ud/
**API Reference:** https://api.highcharts.com/class-reference/Highcharts

Best regards!

**Comment by buithienai** [comment]
> Hi @buithienai,
> 
> Thank you for contacting us!
> 
> The `numberFormat` method is not officially supported, however it should work as expected.
> 
> You can check implementation of the method here: https://github.com/highcharts/highcharts/blob/e137bddbc5a74063da5074812f00f19b0eff56bf/ts/Core/Templating.ts#L379
> 
> Below, you can find a simple example with the method.
> 
> **Live demo:** https://jsfiddle.net/BlackLabel/0epnt5ud/ **API Reference:** https://api.highcharts.com/class-reference/Highcharts
> 
> Best regards!


@ppotaczek please edit data: [1,2]

Not resolve!!!

![image](https://github.com/highcharts/highcharts-react/assets/38641926/ffc9691b-baa0-467d-831e-6c21b8b27b8c)

**Comment by ppotaczek** [comment]
@buithienai, that's because the `numberFormat` method, depending on the second argument, rounds number to the closest integer. 

**Live example:** https://jsfiddle.net/BlackLabel/esrgL2f1/

**Comment by buithienai** [comment]
> https://jsfiddle.net/BlackLabel/esrgL2f1/

@ppotaczek 
No, I want format integer. Please help me.

**Comment by ppotaczek** [comment]
So instead of using formatter, disable the `allowDecimals` option:

```
yAxis: {
  allowDecimals: false
}
```

**Live demo:** https://jsfiddle.net/BlackLabel/xuht6bd7/
**API Reference:** https://api.highcharts.com/highcharts/yAxis.allowDecimals

**Comment by buithienai** [comment]
> So instead of using formatter, disable the `allowDecimals` option:
> 
> ```
> yAxis: {
>   allowDecimals: false
> }
> ```
> 
> **Live demo:** https://jsfiddle.net/BlackLabel/3rcyt05n/ **API Reference:** https://api.highcharts.com/highcharts/yAxis.allowDecimals

Great, thanks!
