### ISSUE TITLE
Type error with Typescrypt

### ISSUE THREAD

**Issue by v360-bruno-sato** [highcharts/highcharts-react#432]
I'm tryied to add highcharts on my React+TS project, but I'm got this error to add a type to de chart refs:
<img width="1592" alt="Screenshot 2023-09-27 at 14 52 41" src="https://github.com/highcharts/highcharts-react/assets/58693054/bd585c9d-ad27-4ee8-991b-177ff49694c2">

I'm using version 3.1.0 of highcharts-react-official

**Comment by ppotaczek** [comment]
Hi @v360-bruno-sato,

Thank you for contacting us!
This problem can be related to https://github.com/highcharts/highcharts-react/issues/426. It was resolved in v3.2.1. Could you check if the problem occurs with the newest wrapper version?

Best regards!

**Comment by v360-bruno-sato** [comment]
Hello @ppotaczek.
Updated to v3.2.1 have worked here. Thanks.
