### ISSUE TITLE
The URL of symbol is not working for local path.

### ISSUE THREAD

**Issue by Abhi2019** [highcharts/highcharts-react#433]
I have seen in many post, it works for http or https with the URL. Why not for the local path.
 marker: {
        symbol:' url(./images/critical_alert.svg)'
  },
  
  It is not working,

**Comment by Abhi2019** [comment]
https://codesandbox.io/s/highcharts-react-demo-6gh3fl?file=/demo.jsx:145-160

**Comment by KamilKubik** [comment]
Hello @Abhi2019,

Thank you for contacting us!

I appreciate you've shared your code. You should keep the images inside the `public` folder: [updated demo](https://codesandbox.io/s/highcharts-react-demo-forked-j7nv55).

Duplicated/extended topic: [HC Forum topic](https://www.highcharts.com/forum/viewtopic.php?f=9&t=51463&p=188890#p188890).

Kind Regards!

**Comment by Abhi2019** [comment]
Thanks, Kamil for the reply, so there is no need to give the "public" folder path, only to give image path which inside of the public folder.

suppose the file in two away from the public directory. "../../../../../public/images/circle.svg" or Just "images/circle.svg".

**Comment by Abhi2019** [comment]
Thanks, Kamil for the reply, do you know why the image being scattered on the graph, shown  in the same code sandbox?

**Comment by Abhi2019** [comment]
Yes, I got it , it is because I am giving px for height and width.  I am closing it.
