### ISSUE TITLE
Not Aligning Label Component in Bar Chart Rendering via Portal 

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts-react#435]
## Description

In the provided [example](https://codesandbox.io/s/highcharts-react-demo-forked-56crg6?file=/demo.jsx:1026-1044), we implemented a column chart where the `label component` was rendered with proper alignment. However, when we switched the chart type from column to bar, the label component no longer aligned correctly.

## Steps to reproduce

1. Set up a column chart as described in the [linked example](https://codesandbox.io/s/highcharts-react-demo-forked-56crg6?file=/demo.jsx).
2. Observe how the `label component` is correctly aligned.
3. Change the chart type from column to bar.
4. Note that the `label component` fails to align properly [exapmle](https://codesandbox.io/s/highcharts-react-demo-forked-8slsh8?file=/demo.jsx). 

## Expected Behavior

When changing the chart type from column to bar, the `label component` should remain properly aligned, similar to the column chart rendering.

## Actual Behavior

In the bar chart rendering, the `label component` is not properly aligned.

## Relevant Screenshots 
Aligned in Column
<img width="707" alt="image" src="https://github.com/highcharts/highcharts-react/assets/75986382/759f8bbe-ff4a-456d-8af8-e9e2c0df019b">
NotAligned in Bar
<img width="433" alt="image" src="https://github.com/highcharts/highcharts-react/assets/75986382/5a625bac-0737-4586-ad8e-fb39572804c1">

**Comment by ppotaczek** [comment]
Hi @Satyam7Jha,

Thank you for contacting us!

Please note that rendering custom HTML by using React portals is an experimental feature and it is not officially supported.

To make the labels properly aligned, you can add the below style:

    <Fragment>
      {createPortal(
        <div style={{ transform: "translateY(-50%)" }}>
          <div>React</div>
          {tick.pos}
        </div>,
        tick.label.element
      )}
    </Fragment>

**Live demo:** https://codesandbox.io/s/highcharts-react-demo-1-9s7pyq?file=/demo.jsx

Best regards!

**Comment by Satyam7Jha** [comment]
Hey, @ppotaczek, I truly appreciate your assistance. Your solution worked perfectly.

I was wondering, will Highcharts implement the capability to render custom components in the foreseeable future? This feature could be significantly beneficial.

**Comment by ppotaczek** [comment]
Hi @Satyam7Jha, It's hard to say, as far as I know, it is not planned in the near future. Such implementation could be complex and complicated. Related thread here: https://github.com/highcharts/highcharts-react/issues/23
