### ISSUE TITLE
highcharts react series: arearange defaulting the linewidth to 1 even given the lineWidth as 0 in options

### ISSUE THREAD

**Issue by SriSaiNikhilKantipudi** [highcharts/highcharts-react#437]
sample code: "highcharts-react-official": "^3.1.0"
{
            name: 'Range',
            type: 'arearange',
            data: getSharedArea(),
            lineWidth: 0,
            fillOpacity: 0.3,
            zIndex: 0,
            marker: {
                enabled: false
            },
            color: '#0069aa',
}

**Comment by ppotaczek** [comment]
Hi @SriSaiNikhilKantipudi,

Thank you for contacting us!

I've tried to reproduce the problem, but `lineWidth` property in the `arearange` series works fine. Please check the below example and adapt it to show the problem.

**Live example:** https://codesandbox.io/s/highcharts-react-demo-xcgk7m?file=/demo.jsx

Best regards!

**Comment by SriSaiNikhilKantipudi** [comment]
It is the same code i am using. Even i tried changing the fillOpacity to10  and changes are being reflected but not for lineWidth even i change it to 5 or 10 it is showing the default lineWidth

**Comment by ppotaczek** [comment]
@SriSaiNikhilKantipudi, Could you reproduce the problem in some online code editor? Which Highcharts version do you use?

**Comment by ppotaczek** [comment]
Closed due to inactivity.
