### ISSUE TITLE
Setting numericSymbols to null or any other value than default has no effect

### ISSUE THREAD

**Issue by JWahlander** [highcharts/highcharts-react#443]
I'm trying to disable metric prefixes on axis labels in order to write the full number for high numbers but setting the `numericSymbols`  to null, as described  here (https://api.highcharts.com/highcharts/lang.numericSymbols),  is not possible since `numericSymbols` is typed to string[]. 
I've aslo tried to enter other values in a string array but that does not have any effect.

**Comment by ppotaczek** [comment]
Hi @JWahlander, 

Thank you for contacting us!

You are right, the type should be: `numericSymbols: Array<string | null>`. 
Please report it on the main repository: https://github.com/highcharts/highcharts/issues

However, you can set empty array to achieve the wanted result:

```
Highcharts.setOptions({
  lang: {
    numericSymbols: []
  }
});
```

Or you can also use `format` option, for example:

```
  yAxis: {
    labels: {
      format: '{value}'
    }
  }
```

**Live demo:** https://jsfiddle.net/BlackLabel/2mq53tvf/
**API Reference:** https://api.highcharts.com/highcharts/yAxis.labels.format

Best regards!

**Comment by ppotaczek** [comment]
@JWahlander, Using an empty array seems to work fine: https://jsfiddle.net/BlackLabel/wpbLnqx3/
Which Highcharts version do you use?

**Comment by JWahlander** [comment]
@ppotaczek I got it to work now but only if I use the Highchart.setOptions() function. 
If I submit the value in the options property in <HighchartReact> component it doesn't work.

**Comment by ppotaczek** [comment]
@JWahlander, using the `setOptions` method is the proper way. In Highcharts API we can read: 

> **lang**
> Language object. The language object is global and it can't be set on each chart initialization. Instead, use Highcharts.setOptions to set it before any chart is initialized.

**API:** https://api.highcharts.com/highcharts/lang
