### ISSUE TITLE
Vector Plot Availability

### ISSUE THREAD

**Issue by Jungmin81** [highcharts/highcharts-react#445]
When will the Vector Plot in React become possible?
I looked it up and found that the vector plot available in React 18 does not exist...

**Comment by ppotaczek** [comment]
Hi @Jungmin81, 

The `highcharts-react-official` module supports all Highcharts features. You need to only import and initialize vector module:

```
import Highcharts from "highcharts";
import vectorModule from "highcharts/modules/vector";

vectorModule(Highcharts);
```

**Live demo:** https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-ck66hs?file=%2Fdemo.jsx%3A19%2C7
**Docs:** https://www.highcharts.com/docs/chart-and-series-types/vector-plot

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
