### ISSUE TITLE
unable to use highchart with react 18 

### ISSUE THREAD

**Issue by Parth1508** [highcharts/highcharts-react#448]
while implementing Highchart for my project where im using react 18 with Typescript. I'm getting the error :
./node_modules/highcharts/highcharts.js 292:100
Module parse failed: Unexpected token (292:100)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|         let r = !e;
|         return t.forEach(t => {
>           if (t.length > 1) for (o = t.length - 1; o > 0; o--) (s = t[o] - t[o - 1]) < 0 && !r ? (e?.(), e = void 0) : s && (void 0 === i || s < i) && (i = s);
|         }), i;
|       },

while npm run start

Code Snippet : 
import React, { useRef } from 'react';
import * as Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';

const options: Highcharts.Options = {
    title: {
        text: 'My chart'
    },
    series: [{
        type: 'line',
        data: [1, 2, 3]
    }]
};

const HighchartDemo = (props: HighchartsReact.Props) => {
  const chartComponentRef = useRef<HighchartsReact.RefObject>(null);

  return (
    <HighchartsReact
      highcharts={Highcharts}
      options={options}
      ref={chartComponentRef}
      {...props}
    />
  );
};
export default HighchartDemo

**Comment by ppotaczek** [comment]
Hi @Parth1508,

Thank you for contacting us!

I've tried to reproduce the issue, but everything seems to work fine with the newest Highcharts and React 18. Could you create a minimal project with problem reproduction and add it here as rar archive?

Best regards!

**Comment by menasheh** [comment]
@Parth1508 I'm not a contributor so look to ppotaczek first, but could you share your package.json? I'm also curious if you're using vite.

**Comment by ppotaczek** [comment]
Closed due to inactivity.

**Comment by KiranMohan** [comment]
I am facing the same issue after upgrading from highcharts 10.3.3 to 11.3.0.

node - 14.21.3
npm - 8.0.0
highcharts-react - 3.2.1
react - 16.8.3

The issue is happening both in jsx and tsx.

**Comment by ppotaczek** [comment]
Hi @KiranMohan, Could you reproduce the problem in some online code editor? You can use this example, as a base to start: https://codesandbox.io/p/sandbox/highcharts-react-demo-gbg3n3

**Comment by codes-anas** [comment]
Hi,
downgrade the highcharts to 10.3.3 . Now it's working fine
