### ISSUE TITLE
Stock chart indicator customization

### ISSUE THREAD

**Issue by volkandincer** [highcharts/highcharts-react#449]
**Hello, I am using Highcharts Stock for technical charts, and I want to customize the indicators. I want to remove certain items from the list of indicators. Can you help me with how to do this?**

**Comment by ppotaczek** [comment]
Hi @volkandincer,

This question is not related with `highcharts-react-official`, so in the future please use one of our support channels: https://www.highcharts.com/support/

You can find answer to your question in one of the below threads:
- https://www.highcharts.com/forum/viewtopic.php?t=47293
- https://stackoverflow.com/questions/61261368/costumize-indicators-from-stock-tools

Best regards!
