### ISSUE TITLE
parliament(item) chart

### ISSUE THREAD

**Issue by rlaebqebq** [highcharts/highcharts-react#451]
Hi.
I want to draw a parliaments chart of a high chart through highcharts-react
But it's hard because there's no reference. Can you help me?
Is there any way to implement?

https://www.highcharts.com/docs/chart-and-series-types/item-chart

**Comment by ppotaczek** [comment]
Hi @rlaebqebq,

Thank you for contacting us!

The most important thing is to import and initialize the `item-series` module:

```
import Highcharts from "highcharts";
import itemSeries from "highcharts/modules/item-series";

itemSeries(Highcharts);
```

**Live demo:** https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-rlflfn

Best regards!

**Comment by oysteinmoseng** [comment]
@rlaebqebq Could you specify a bit what you were struggling to find in the docs/reference?

**Comment by ppotaczek** [comment]
Closed due to inactivity.
