### ISSUE TITLE
Donut Chart invisible until after HMR 

### ISSUE THREAD

**Issue by menasheh** [highcharts/highcharts-react#453]
Highcharts seems to show an empty chart until you edit main.jsx. Saving with an extra space is enough to trigger the chart to load, but by default it won't load.

Minimal repro:
[highcharts-issue.zip](https://github.com/highcharts/highcharts-react/files/13894095/highcharts-issue.zip)

**Comment by menasheh** [comment]
Discovered it can be fixed by adding [] around series in donut chart options. However, why does HMR make it work? That's quite odd.

**Comment by KamilKubik** [comment]
Hello [menasheh](https://github.com/menasheh),

Thanks for contacting us!

In general, defininig series as an array of objects is the only supported way to create a chart, and you should stick to that. The reason for this is that you can create many series. Feel free to explore the series as a [definition](https://www.highcharts.com/docs/chart-concepts/series) and in our [API](https://api.highcharts.com/highcharts/series).

I debugged your code, and it seems the rerender causes the correct chart's load. I think the reason for this behavior is that on the first render, the chart instance is created, and Highcharts handles the incorrect series format, but the chart isn't rendered at some point. Then, having the correctly formatted data, the chart is rendered after the rerender occurs.

I agree that if there's any error, the information should be returned to avoid misleading. Therefore, it would be reasonable to add such a statement, and feel free to report it [here](https://github.com/highcharts/highcharts/issues/new/choose). Note that the error handling functionality currently exists, and you can test it, e.g., by defining a wrong series type.

Kind Regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
