### ISSUE TITLE
Rendering simple chart with React Testing Library fails (computes NaN values)

### ISSUE THREAD

**Issue by baixue23** [highcharts/highcharts-react#454]
## Issue
I am using `jest` and `React Testing Library` to render a Highchart. The rendered SVG contains many NaN values and does not display correctly. This is an issue because I want to use Snapshot Testing for the charts.

## Visual proof
The chart used is the default example. The screenshot shows it is not rendering correctly in the browser:

<img width="614" alt="Screenshot 2024-01-18 at 13 55 00" src="https://github.com/highcharts/highcharts-react/assets/139135577/b24fa054-db82-4328-84fc-85cbcf0e37c8">

## Steps to reproduce
1. Open this minimal StackBlitz project: https://stackblitz.com/edit/node-dq9php?file=test%2Ftest.jsx
2. Run the test with `npm install && npx jest` (test will pass, it is just used to generated the file `output.html`)
3. Inspect the generated file `output.html`.
4. Observe # 1: The file contains weird NaN values
5. Observe # 2: When opening the file in the browser, the chart does not render correctly. (StackBlitz makes this unnecessarily hard; you need to copy the contents of output.html to you local file)

**Comment by KamilKubik** [comment]
Hello [baixue23](https://github.com/baixue23),

Thanks for contacting us!

The major problem is with the testing environment, and to render the SVG elements correctly, you need to use the Headless browser. As I can see, you used the **jsdom** which as we can read in the [docs](https://jestjs.io/docs/tutorial-jquery), only _simulate a DOM environment as if you were in the browser_ but actually doesn't run it. Unfortunately, Jest doesn't support it officially, but you can try to extend it using [puppeteer](https://jestjs.io/docs/puppeteer).

What Highcharts uses internally, and what I can recommend for testing, is [Qunit](https://qunitjs.com/intro/), which in the _Integrations_ section refers to the different solutions on how to run the tests in the Headless browser so the chart can render as expected.

Kind Regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
