### ISSUE TITLE
Runtime error when chart tries to update while hovering over a series

### ISSUE THREAD

**Issue by aarizti** [highcharts/highcharts-react#455]
## Description

If a user is hovering over a given series, Highcharts sometimes crashes if it needs to re-initialize the chart with new options data (using the immutable prop). The stack trace we get is:

Uncaught TypeError: Cannot destructure property 'chart' of 'o' as it is undefined.
    at C.D (highcharts-more.js:7:1)
    at t.<computed> (highcharts.js:8:1)
    at C.haloPath (highcharts.js:8:1)
    at C.setState (highcharts.js:8:1)
    at C.destroy (highcharts.js:8:1)
    at n.destroy (highcharts.js:8:1)
    at tt.destroy (highcharts.js:8:1)
    at tt.getContainer (highcharts.js:8:1)
    at tt.firstRender (highcharts.js:8:1)
    at tt.<anonymous> (highcharts.js:8:1)

D @ highcharts-more.js:7
t.<computed> @ highcharts.js:8
haloPath @ highcharts.js:8
setState @ highcharts.js:8
destroy @ highcharts.js:8
destroy @ highcharts.js:8
destroy @ highcharts.js:8
getContainer @ highcharts.js:8
firstRender @ highcharts.js:8
(anonymous) @ highcharts.js:8
C @ highcharts.js:8
init @ highcharts.js:8
tt @ highcharts.js:8
chart @ highcharts.js:8
e @ highcharts-react.min.js:1
(anonymous) @ highcharts-react.min.js:1
commitHookEffectListMount @ react-dom.development.js:23150
commitLayoutEffectOnFiber @ react-dom.development.js:23268
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25981
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
queue.<computed> @ task.js:61
run @ task.js:35
eventListener @ task.js:46

highcharts.js:8 Uncaught TypeError: Cannot read properties of undefined (reading 'destroy')
    at tt.destroy (highcharts.js:8:1)
    at highcharts-react.min.js:1:1
    at safelyCallDestroy (react-dom.development.js:22932:1)
    at commitDeletionEffectsOnFiber (react-dom.development.js:24100:1)
    at recursivelyTraverseDeletionEffects (react-dom.development.js:23989:1)
    at commitDeletionEffectsOnFiber (react-dom.development.js:24118:1)
    at recursivelyTraverseDeletionEffects (react-dom.development.js:23989:1)
    at commitDeletionEffectsOnFiber (react-dom.development.js:24018:1)
    at recursivelyTraverseDeletionEffects (react-dom.development.js:23989:1)
    at commitDeletionEffectsOnFiber (react-dom.development.js:24118:1)

This happens pretty often in the examples we have in our app and is currently preventing us from upgrading `highcharts-react-official` and `highcharts` (not sure in which of the two libraries the problem lies). By switching off and on different chart options, I determined that this setting causes the problem: `plotOptions.series.states.hover.enabled`. When that is true, and the hover is enabled, the chart crashes; if it is disabled, the problem goes away (we can hover over the series safely, but ofc the hover behavior is lost).

## Version

This works fine on highcharts-react-official@v2.2.2 and highcharts@v9.2.1. It crashes with versions **highcharts-react-official@v3.2.1 and highcharts@v11.3.0**

## Steps to reproduce

Unfortunately, I couldn't replicate the issue in a sandbox environment, even though I'm using the same code as in our app. The code can be seen [here](https://codesandbox.io/p/sandbox/highcharts-bug-wxtnr2?file=%2Fsrc%2F_app.js). I'm sort of mimicking some remote calls we do in our actual instances of charts throughout the app with some timeouts. Due to those timeouts, the chart renders three times in the space of around 2 to 2.5 seconds. This exact code snippet with the `setTimeout`s is also failing in our app. To replicate it, we need to follow a particular pattern when hovering over the series: we first hover on the first time series that appears (the black one), then on the second when it shows (the blue one), and back to hovering on the first, and then when the third series appears the chart crashes 😅 

Thanks!

**Comment by ppotaczek** [comment]
Hi @aarizti,

Thank you for contacting us!

Unfortunately, it's very hard to predict what's causing the problem without being able to reproduce it. With enabled `immutable` option, the chart is recreated on each update, so it is even more resistant to these types of errors.

Maybe you would be able to reproduce the problem in some minimal project and provide a .zip archive here? Also, it would be great if you could check if highcharts or highcharts-react-official version update is causing the issue.

Best regards!

**Comment by aarizti** [comment]
Hi @ppotaczek , thanks for the prompt answer :)

I was finally able to replicate the issue in the provided sandbox ([here](https://codesandbox.io/p/sandbox/highcharts-bug-wxtnr2)). The problem seems to happen when the `HighchartsMore` module is added (you can try to comment it out in the code, and then everything works fine).

I'm not sure if this is a wrapper issue or a highcharts issue. In principle, I would say highcharts, because if I revert `highcharts-react` to 2.2.2 the issue still happens. It only works if I revert highcharts to 9.2.1.

Regards.

**Comment by ppotaczek** [comment]
Hi @aarizti, 

Thank you for providing more information!
I've successfully reproduced the problem without React: https://jsfiddle.net/BlackLabel/ocz0te35/

The issue turned out to be a Highcharts regression bug since version 11.3.0, so I reported it on the main repository: https://github.com/highcharts/highcharts/issues/20572

As a workaround you can use Highcharts v11.2.0: https://codesandbox.io/p/sandbox/highcharts-bug-forked-9htzrh

Best regards!

**Comment by aarizti** [comment]
Many thanks, @ppotaczek :)

Highcharts v11.2.0 works like a charm.

Regards!
