### ISSUE TITLE
Usage in React, Grid lines not visible 

### ISSUE THREAD

**Issue by ningxi-oa** [highcharts/highcharts-react#456]
Hello there, i currently working on a project which used the library "highchart". But i notice the chart that i created, it's X and Y axis grid lines are not visible: 

here is the part of codes where i set up X and Y axis :
<img width="567" alt="Screenshot 2024-02-02 at 16 30 45" src="https://github.com/highcharts/highcharts-react/assets/157483503/500121d8-a923-41b3-b865-f3b9a9db517f">

and here is the result that i've got :
![Screenshot 2024-02-02 at 16 31 33](https://github.com/highcharts/highcharts-react/assets/157483503/77be42c7-43b5-4060-bf25-25447deae7f4)

I don't kown if this is due to i did'n import the correct module, In the component that i used "highchart" :
<img width="539" alt="Screenshot 2024-02-02 at 16 31 45" src="https://github.com/highcharts/highcharts-react/assets/157483503/8809dd83-8f23-479e-84f1-b0acace36ca4">

Could anyone help me with that? Thanks in advance! :)

**Comment by ppotaczek** [comment]
Hi @ningxi-oa,

Thank you for contacting us!

I've tried to reproduce the issue, but grid lines are correctly displayed when I use your code. Please check the below example and try to adapt it to show the problem.

**Live demo:** https://stackblitz.com/edit/react-a5tqyo

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
