### ISSUE TITLE
Tooltip is going under axis-component

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts-react#457]
I am implementing the axis using React Portal. Sometimes, randomly, my tooltip goes inside the AxisLabel component.

Implementation: https://codesandbox.io/p/sandbox/highcharts-react-demo-1-9s7pyq?file=%2Fdemo.jsx%3A57%2C19

<img width="985" alt="image" src="https://github.com/highcharts/highcharts-react/assets/75986382/2621f065-cb17-4b7b-8d20-29cd58f65d5d">

**Comment by ppotaczek** [comment]
Hi @Satyam7Jha,

Thank you for contacting us!

This issue is related to pure Highcharts and well explained here: https://github.com/highcharts/highcharts/issues/12236

As a solution enable `outside` option for toolip:

    tooltip: {
      outside: true
    }

**Live demo:** https://stackblitz.com/edit/react-ekgasi
**API Reference:** https://api.highcharts.com/highcharts/tooltip.outside

Best regards!

**Comment by Satyam7Jha** [comment]
Thanks, @ppotaczek, but I'd prefer not to enable the outside true option because my tooltip extends beyond the chart, making it look a bit awkward. Can you please suggest an alternative solution?

**Comment by ppotaczek** [comment]
Hi @Satyam7Jha, 

As an alternative solution, you can disable the default tooltip background and add your own by enabling `useHTML` option and styling returned HTML. For example: 

    tooltip: {
      useHTML: true,
      backgroundColor: 'transparent',
      formatter: function (tooltip) {
        const defaultVal = tooltip.defaultFormatter.call(this, tooltip);
        const defaultValAsString = defaultVal.reduce(
          (acc, val) => acc + val,
          ''
        );

        return `<div style="background-color: #fff; padding: 8px; border: 1px solid black;">${defaultValAsString}</div>`;
      },
    }

**Live demo:** https://stackblitz.com/edit/react-ekgasi
**API Refernece:** https://api.highcharts.com/highcharts/tooltip.formatter

Best regards!

**Comment by Satyam7Jha** [comment]
https://codesandbox.io/p/sandbox/highcharts-react-demo-1-forked-6pw8ld?file=%2Fdemo.jsx%3A67%2C14

here iam using react portal to render custom tooltip then also it is happning.

https://github.com/highcharts/highcharts-react/assets/75986382/6a4e1abc-373e-41ab-9082-e5a962d73bcd

**Comment by ppotaczek** [comment]
You can use the same technique for a custom tooltip rendered through React portals.
 
**Example:** https://stackblitz.com/edit/react-ctskp1

**Comment by Satyam7Jha** [comment]
could you please add you fix in : https://codesandbox.io/p/sandbox/highcharts-react-demo-1-forked-6pw8ld?file=%2Fdemo.jsx%3A67%2C14.

**Comment by ppotaczek** [comment]
Sure, the fix added in codesandbox: https://codesandbox.io/p/sandbox/highcharts-react-6f5kgd

**Comment by ppotaczek** [comment]
Closed due to inactivity.
