### ISSUE TITLE
Zones rendering issue after updating to highcharts@11.3.0

### ISSUE THREAD

**Issue by xsevcika2** [highcharts/highcharts-react#459]
Hello, 
after updating Highcharts to version 11.3.0 my histogram started behaving strangely and I will be glad if you have any idea what to do about it and will be able to advise me.

**Issue:**
In my project, I was using histogram zones to color specific bins according to values however after updating to the latest version, the zone colors were no longer applied.

### Old version `highcharts@11.2.0`
![image](https://github.com/highcharts/highcharts-react/assets/25958497/585bbda7-6322-400e-b0c3-4e14e1b9009d)

### Latest version `highcharts@11.3.0`
![image](https://github.com/highcharts/highcharts-react/assets/25958497/2ac71ec8-756d-43c6-9470-3049a4ccf3ab)

**My assumptions:**
I think it might be due to the histogram rendering, so I tried commenting out React.StrictMode first. 
```js
root.render(
  // <React.StrictMode>
  <App />
  // </React.StrictMode>
);
```
Then I found that the chart zones are indeed displayed but after changing the data (Button - "Update Data" in the example) they are missing again.

I haven't moved any further yet. I have forked one of your stackblitz examples and created replicable code [https://stackblitz.com/edit/react-wul4iv?file=index.js](https://stackblitz.com/edit/react-wul4iv?file=index.js) and would be grateful for any advice!

**Comment by ppotaczek** [comment]
Hi @xsevcika2,

Thank you for contacting us! 

There is a bug in Highcharts v11.3.0 related to using zones with multiple series.
As a workaround use Highcharts v11.2.0 or add the plugin from one of the below threads.

Similar thread: https://stackoverflow.com/questions/78007238/how-can-i-display-a-line-that-has-gone-missing-in-a-highcharts-graph/78020005#78020005

Related issue: https://github.com/highcharts/highcharts/issues/20613

**Comment by ManuelElvir** [comment]
Hello, I am facing the same issue after updating Highcharts to v11.3.0.

**Comment by xsevcika2** [comment]
@ManuelElvir,

The simplest workaround for me was to downgrade even further to Highcharts v11.1.0 🙂

Hope it can help you too. Have a nice day!

**Comment by ppotaczek** [comment]
@xsevcika2, thanks for providing more information!

You are right - the problem is already resolved on the master branch and will be available in the next Highcharts version.
If you want to use Highcharts 11.3.0, you can add the plugin from this example: https://stackblitz.com/edit/vitejs-vite-7ffpfv?file=src%2FLineHighchart.tsx

Best regards!
