### ISSUE TITLE
Plotbands added via API are not added to plotOptions 

### ISSUE THREAD

**Issue by wlefaou** [highcharts/highcharts-react#462]
Hello,

I have encountered some surprising behavior while trying to add & remove plotbands to a graph :

When adding a plotband via the api, plotbands are not added to the xAxis's plotOptions, if the chart was initialised without plotOptions (but are displayed on the chart).

Here is a demo : https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-9msqws

In this demo, the add button adds a plotband with id '1'. The remove button tries to retrieve plotbands's ids in the options, to remove them with removePlotBand(plotBand.id)
So to reproduce : click "add plotband" and then click "remove plotband"
This doesn't work because no plotbands are found, despite the plotband being displayed.

2 possible workarounds (I added them as comments in the demo) :
 - Adding empty plotbands to chart's initial configuration. With this, the addPlotband method does add plotband to the plotOptions, so the delete method does find and remove the plotband
 - Calling removePlotband with the id. Despite the plotband not being in the options, calling removePlotband with id works.(

1st workaround is simple and works fine, but wanted to know if this a bug, or maybe a result of a wrong usage on my side ?

**Comment by ppotaczek** [comment]
Hi @wlefaou, 

Thank you for contacting us!

It's not a bug. In the API we can read:

> **options** :[Highcharts.AxisOptions](https://api.highcharts.com/class-reference/Highcharts.html#.AxisOptions)
> Current options for the axis after merge of defaults and user's options.

If you need, you can refer to plot bands by using:

    chart.current?.chart.xAxis[0].plotLinesAndBands

or as you suggested, remove a plot band by id.

**API Reference:** https://api.highcharts.com/class-reference/Highcharts.Axis#options

Best regards!

**Comment by wlefaou** [comment]
Ok, thank you for your answer !

**Comment by pavel-spacil** [comment]
@ppotaczek the `plotLinesAndBands` is not public property thus not available in typescript
