### ISSUE TITLE
Add a react ref to each point

### ISSUE THREAD

**Issue by caionakai** [highcharts/highcharts-react#464]
Hi, I have a line chart that has some vertices, to each vertex/point I'd like to add a react ref in order to pass this ref as a prop in a floating menu component that uses the ref to calculate the position of this menu. Is there any way to achieve that?

**Comment by ppotaczek** [comment]
Hi @caionakai,

Thank you for contacting us!

You can get a reference to points in some chart events, `render` is the most suited for your case I think.
Maybe keeping all points in a state is enough to achieve what you plan? For example:

```
  const [points, setPoints] = useState([]);
  const [chartOptions, setChartOptions] = useState({
    chart: {
      events: {
        render: function(){
          setPoints(this.series[0].points);
        }
      }
    },
    xAxis: {
      categories: ['A', 'B', 'C'],
    },
    series: [
      { data: [1, 2, 3] }
    ]
  });

  useEffect(() => {
    console.log(points);
  }, [points]);
```

**Live demo:** https://stackblitz.com/edit/react-xorsqm?file=index.js

Best regards!

**Comment by caionakai** [comment]
Hi @ppotaczek , thank you for your quick response.

Actually, this other component that I'm trying to integrate looks like this

`<Menu triggerEl={myReactRefToAPoint} >`

So 'myReactRefToAPoint' should come from useRef hook and I'd like to have something like the following example if points were rendered this way (which is not the case ik)

`<Point ref={myReactRefToAPoint}`

The menu component uses `react-popper` which uses a react ref to calculate the position for each menu. I was wondering if it's possible to get a ref from useRef to each point so that I could use it to pass to this other react-popper based component.

**Comment by caionakai** [comment]
Oh I see, I actually managed to solve this by using the html element that comes from graphic.element instead of using a react ref, I appreciate your help, thank you.
