### ISSUE TITLE
Cannot read properties of undefined (reading 'forEach')

### ISSUE THREAD

**Issue by coligomed-rverma** [highcharts/highcharts-react#467]
#### Issue

I am using Highchart with Highchart React, and using the column chart, I am passing all the data and the data is also an array every time, but still, I am getting this undefined error in sentry.

Here is the screenshot of stack trace, please some look into this issue.

![image](https://github.com/highcharts/highcharts/assets/135992336/0653d1bf-9921-4c96-a25d-209ee6a19b91)

Below is the chart option that I am passing
```
{
  chart: {
    height: 132,
    type: "column",
  },
  title: {
    text: undefined,
  },
  legend: { enabled: false },
  xAxis: {
    categories: ["Jan', "Feb", ....],
    title: undefined,
    labels: {
      style: {
        textOverflow: "none",
      },
    },
  },
  yAxis: {
    gridLineWidth: 1,
    gridLineDashStyle: "Dash",
    title: undefined,
    opposite: true,
    tickInterval: 50,
  },
  tooltip: {
    enabled: true,
    backgroundColor: "#fff",
    borderRadius: 6,
    xDateFormat: "%b", // for full format use "%e %b %Y %l:%M %p",
  },
  credits: {
    enabled: false,
  },
  exporting: {
    enabled: false,
  },
series: [
      {
        name: "7 Days",
        color: colors.primary,
        data: data7Days,
      },
      {
        name: "14 Days",
        color: colors.success.main,
        data: data14Days,
      },
    ],
}
```
**Note** data7Days and data14Days are always an array

#### Product version
```
"highcharts": "^9.3.3",
"highcharts-react-official": "^3.1.0",
 ```

**Comment by coligomed-rverma** [comment]
> Hi @coligomed-rverma,
> 
> Thank you for contacting us!
> 
> I've tried to reproduce the problem in `highcharts` v9.3.3 and `highcharts-react-official` v3.1.0, but everything seems to work fine with using your code. Could you adapt this live demo: https://stackblitz.com/edit/react-tiggcb to show the issue?
> 
> Best regards!

Here is the template https://stackblitz.com/edit/react-s3c1qx?file=index.js, though this does not give an error here. This is just happening randomly and happening in prod.

Actually, I have a data range changer dropdown, and when it is changed we call API to fetch new data. Then only the undefined error occurred. And this is happening in production only not in dev. So not sure why this error it there.

Please help me out, thanks.

**Comment by ppotaczek** [comment]
@coligomed-rverma, Your chart config looks correct and it's really hard to say what is causing the problem without reproducing it. I can only guess that sometimes your data format is incorrect. I think that you should check what data comes in when the error occurs.

Best regards!

**Comment by KamilKubik** [comment]
Closed due to inactivity.
