### ISSUE TITLE
Is this the correct way to use the Boost module to improve performance?

### ISSUE THREAD

**Issue by TowhidKashem** [highcharts/highcharts-react#472]
Hi,

I would like a gut-check on my implementation of the boost module for performance. I just want to make sure I'm doing it right:

```
import * as Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import Boost from 'highcharts/modules/boost';
import Accessibility from 'highcharts/modules/accessibility';
import Exporting from 'highcharts/modules/exporting';
import ExportData from 'highcharts/modules/export-data';
import OfflineExporting from 'highcharts/modules/offline-exporting';

Boost(Highcharts); // <------------ here
Accessibility(Highcharts);
Exporting(Highcharts);
ExportData(Highcharts);
OfflineExporting(Highcharts);

export const LineChart: React.FC = () => {
  //...
  
  return (
    <HighchartsReact
      ref={chartRef}
      highcharts={Highcharts}
      containerProps={{ className: 'line-graph' }}
      options={{
        chart: {
          //...
        },   
        xAxis: {
          //...
        },
        yAxis: {
          //...
        },
        series: [
          //...
        ],
        boost: {
          enabled: true,
          allowForce: true,
          pixelRatio: 1,
          seriesThreshold: 1,
          useGPUTranslations: true,
          usePreallocated: true
        }
      }}
    />
  )
}
```

Does this look right to you or am I missing anything in the above options which could improve performance further?

And according to the [docs](https://www.highcharts.com/docs/advanced-chart-features/boost-module) it mentions that the boost module renders the charts using WebGL and not SVG, yet when I inspect the rendered charts using chrome's devtools inspector, all I see are SVG elements and not a canvas as one would expect for WebGL rendered components. So does this mean something is wrong with the implementation above and I'm still not using boost correctly?

**Comment by ppotaczek** [comment]
Hi @TowhidKashem,

Thank you for contacting us!

Your configurations looks fine. I've also tested the provided code here: https://stackblitz.com/edit/react-fvmezd and the series is correctly created as an image.

![image](https://github.com/highcharts/highcharts-react/assets/22988131/bfd10abe-ee9d-43fc-b045-832c739551f1)

**Docs:** https://www.highcharts.com/docs/advanced-chart-features/boost-module

Best regards!

**Comment by TowhidKashem** [comment]
@ppotaczek thanks for confirming the config looks good! I didn't know the boost module was supposed to create the series as an image but it sounds like that's what you mean? I was able to find the src of the image you're showing in the screenshot:

`data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAA94AAAGQCAYAAABYoLgeAAAAAXNSR0IArs4c6QAAIABJREFUeF7t3dFxXMcRBVCIVcxGOZgOgZEqBIM5IBtXga63IEVLArCzi9f9Zt49/KFcxk5Pnx593CK39duDXwQIECBAgAABAgQIECBAgECZwG9lJzuYAAECBAgQIECAAAECBAgQeBC8PQICBAgQIECAAAECBAgQIFAoIHgX4jqaAAECBAgQIECAAAECBAgI3t4AAQIECBAgQIAAAQIECBAoFBC8C3EdTYAAAQIECBAgQIAAAQIEBG9vgAABAgQIECBAgAABAgQIFAoI3oW4jiZAgAABAgQIECBAgAABAoK3N0CAAAECBAgQIECAAAECBAoFBO9CXEcTIECAAAECBAgQIECAAAHB2xsgQIAAAQIECBAgQIAAAQKFAoJ3Ia6jCRAgQIAAAQIECBAgQICA4O0NECBAgAABAgQIECBAgACBQgHBuxDX0QQIECBAgAABAgQIECBAQPD2BggQIECAAAECBAgQIECAQKGA4F2I62gCBAgQIECAAAECBAgQICB4ewMECBAgQIAAAQIECBAgQKBQQPAuxHU0AQIECBAgQIAAAQIECBAQvL0BAgQIECBAgAABAgQIECBQKCB4F+I6mgABAgQIECBAgAABAgQICN7eAAECBAgQIECAAAECBAgQKBQQvAtxHU2AAAECBAgQIECAAAECBARvb4AAAQIECBAgQIAAAQIECBQKCN6FuI4mQIAAAQIECBAgQIAAAQKCtzdAgAABAgQIECBAgAABAgQKBQTvQlxHEyBAgAABAgQIECBAgAABwdsbIECAAAECBAgQIECAAAEChQKCdyGuowkQIECAAAECBAgQIECAgODtDRAgQIAAAQIECBAgQIAAgUIBwbsQ19EECBAgQIAAAQIECBAgQEDw9gYIECBAgAABAgQIECBAgEChgOBdiOtoAgQIECBAgAABAgQIECAgeHsDBAgQIECAAAECBAgQIECgUEDwLsR1NAECBAgQIECAAAECBAgQELy9AQIECBAgQIAAAQIECBAgUCggeBfiOpoAAQIECBAgQIAAAQIECAje3gABAgQIECBAgAABAgQIECgUELwLcR1NgAABAgQIECBAgAABAgQEb2+AAAECBAgQIECAAAECBAgUCgjehbiOJkCAAAECBAgQIECAAAECgrc3QIAAAQIECBAgQIAAAQIECgUE70JcRxMgQIAAAQIECBAgQIAAAcHbGyBAgAABAgQIECBAgAABAoUCgnchrqMJECBAgAABAgQIECBAgIDg7Q0QIECAAAECBAgQIECAAIFCAcG7ENfRBAgQIECAAAECBAgQIEBA8PYGCBAgQIAAAQIECBAgQIBAoYDgXYjraAIECBAgQIAAAQIECBAgIHh7AwQIECBAgAABAgQIECBAoFBA8C7EdTQBAgQIECBAgAABAgQIEBC8vQECBAgQIECAAAECBAgQIFAoIHgX4jqaAAECBAgQIECAAAECBAgI3t4AAQIECBAgQIAAAQIECBAoFBC8C3EdTYAAAQIECBAgQIAAAQIEBG9vgAABAgQIECBAgAABAgQIFAoI3oW4jiZAgAABAgQIECBAgAABAoK3N0CAAAECBAgQIECAAAECBAoFBO9CXEcTIECAAAECBAgQIECAAAHB2xsgQIAAAQIECBAgQIAAAQKFAoJ3Ia6jCRAgQIAAAQIECBAgQICA4O0NECBAgAABAgQIECBAgACBQgHBuxDX0QQIECBAgAABAgQIECBAQPD2BggQIECAAAECBAgQIECAQKGA4F2I62gCBAgQIECAAAECBAgQICB4ewMECBAgQIAAAQIECBAgQKBQQPAuxHU0AQIECBAgQIAAAQIECBAQvL0BAgQIECBAgAABAgQIECBQKCB4F+I6mgABAgQIECBAgAABAgQICN7eAAECBAgQIECAAAECBAgQKBQQvAtxHU2AAAECBAgQIECAAAECBARvb4AAAQIECBAgQIAAAQIECBQKCN6FuI4mQIAAAQIECBAgQIAAAQKCtzdAgAABAgQIECBAgAABAgQKBQTvQlxHEyBAgAABAgQIECBAgAABwdsbIECAAAECBAgQIECAAAEChQKCdyGuowkQIECAAAECBAgQIECAgODtDRAgQIAAAQIECBAgQIAAgUIBwbsQ19EECBAgQIAAAQIECBAgQEDw9gYIECBAgAABAgQIECBAgEChgOBdiOtoAgQIECBAgAABAgQIECAgeHsDBAgQIECAAAECBAgQIECgUEDwLsR1NAECBAgQIECAAAECBAgQELy9AQIECBAgQIAAAQIECBAgUCggeBfiOpoAAQIECBAgQIAAAQIECAje3gABAgQIECBAgAABAgQIECgUELwLcR1NgAABAgQIECBAgAABAgQEb2+AAAECBAgQIECAAAECBAgUCgjehbiOJkCAAAECBAgQIECAAAECgrc3QIAAAQIECBAgQIAAAQIECgUE70JcRxMgQIAAAQIECBAgQIAAAcHbGyBAgAABAgQIECBAgAABAoUCgnchrqMJECBAgAABAgQIECBAgIDg7Q0QIECAAAECBAgQIECAAIFCAcG7ENfRBAgQIECAAAECBAgQIEBA8PYGCBAgQIAAAQIECBAgQIBAoYDgXYjraAIECBAgQIAAAQIECBAgIHh7AwQIECBAgAABAgQIECBAoFBA8C7EdTQBAgQIECBAgAABAgQIEBC8vQECBAgQIECAAAECBAgQIFAoIHgX4jqaAAECBAgQIECAAAECBAgI3t4AAQIECBAgQIAAAQIECBAoFBC8C3EdTYAAAQIECBAgQIAAAQIEBG9vgAABAgQIECBAgAABAgQIFAoI3oW4jiZAgAABAgQIECBAgAABAoK3N0CAAAECBAgQIECAAAECBAoFBO9CXEcTIECAAAECBAgQIECAAAHB2xsgQIAAAQIECBAgQIAAAQKFAoJ3Ia6jCRAgQIAAAQIECBAgQICA4O0NECBAgAABAgQIECBAgACBQgHBuxDX0QQIECBAgAABAgQIECBAQPD2BggQIECAAAECBAgQIECAQKGA4F2I62gCBAgQIECAAAECBAgQICB4ewMECBAgQIAAAQIECBAgQKBQQPAuxHU0AQIECBAgQIAAAQIECBAQvL0BAgQIECBAgAABAgQIEIgT+P2P/365NP386eX3T7/96+Hh4eWfHx4en75++vdeKIL3XpLOIUCAAAECBAgQIECAAIHpBC4B+41w/RK8v397Cd7Pj09fPz9WNCB4V6g6kwABAgQIECBAgAABAgTaBF4J11vtP//0uiNcv9es4N32FBQiQIAAAQIECBAgQIAAgXsF/hKut0P+9lfD/z9cb/931Z9e33N/wfseNZ8hQIAAAQIECBAgQIAAgd0FhsP1JXjX/dXwvRsTvPcWdR4BAgQIECBAgAABAgQIvClw1nD93sgFb/9CECBAgAABAgQIECBAgMCuAtc2hv/518IX+5Pre5EE73vlfI4AAQIECBAgQIAAAQLhAjNsDF9hBIL3ClNyRwIECBAgQIAAAQIECBwkMPvG8INYbioreN/E5YcJECBAgAABAgQIECBwPoHh711/er78d65n2hi+wjQE7xWm5I4ECBAgQIAAAQIECBD4oMBwuN7qLLQx/IMsLR8XvFuYFSFAgAABAgQIECBAgEC9gHBdb3xPBcH7HjWfIUCAAAECBAgQIECAwEECNoYfBP+BsoL3B/B8lAABAgQIECBAgAABAlUCNoZXyfafK3j3m6tIgAABAgQIECBAgACBi4CN4RkPQfDOmLMuCRAgQIAAAQIECBA4SGD4e9c2hh80ofqygne9sQoECBAgQIAAAQIECJxcYDhcbw42hp/8NfyzPcE7buQaJkCAAAECBAgQIEDgHgHh+h41n9kEBG/vgAABAgQIECBAgAABAj8EbAz3FCoEBO8KVWcSIECAAAECBAgQIDC1wDtLzR4vF3/+/u3yu78WPvUcV7mc4L3KpNyTAAECBAgQIECAAIGbBG7ZGL4d/PT180vo9ovAzgKC986gjiNAgAABAgQIECBAoE9g+HvXNob3DUWlfwgI3h4FAQIECBAgQIAAAQJTCwyH660LfzV86lmmXk7wTp28vgkQIECAAAECBAhMJGCp2UTDcJXdBQTv3UkdSIAAAQIECBAgQIDAawJXw/X2IUvNPJ4TCgjeJxyqlggQIECAAAECBAgcKWBj+JH6as8oIHjPOBV3IkCAAAECBAgQIDC5gI3hkw/I9aYSELynGofLECBAgAABAgQIEJhHYHipmY3h8wzNTaYUELynHItLESBAgAABAgQIEOgRGA7X23VsDO8ZiiqnExC8TzdSDREgQIAAAQIECBD4q8DVpWY/F5oJ154OgRIBwbuE1aEECBAgQIAAAQIE+gVe+d71lx+3eLz8bmN4/1BUJPDw8CB4ewYECBAgQIAAAQIEFhK4ZanZ09fPL4HbLwIEDhUQvA/lV5wAAQIECBAgQIDAPwWGv3dtqZnnQ2AJAcF7iTG5JAECBAgQIECAwNkEhsP11rilZmcbv37CBATvsIFrlwABAgQIECBAoE9AuO6zVonAzAKC98zTcTcCBAgQIECAAIHpBWwMn35ELkjgcAHB+/ARuAABAgQIECBAgMAKAjaGrzAldyQwp4DgPedc3IoAAQIECBAgQOAAARvDD0BXkkCAgOAdMGQtEiBAgAABAgQI/BIY/t61jeGeDQECOwkI3jtBOoYAAQIECBAgQGAegeFwvV3ZxvB5BucmBE4qIHifdLDaIkCAAAECBAicXUC4PvuE9UfgPAKC93lmqRMCBAgQIECAwOkEbAw/3Ug1RCBSQPCOHLumCRAgQIAAAQJzCdgYPtc83IYAgX0FBO99PZ1GgAABAgQIECDwhoCN4Z4GAQKpAoJ36uT1TYAAAQIECBAoEBj+3rWN4QX6jiRAYFYBwXvWybgXAQIECBAgQGBSgeFwvd3fxvBJp+haBAh0CgjendpqESBAgAABAgQWERCuFxmUaxIgsISA4L3EmFySAAECBAgQILC/gI3h+5s6kQABAq8JCN7eBQECBAgQIEDg5AI2hp98wNojQGB6AcF7+hG5IAECBAgQIEDguoCN4deN/AQBAgSOEhC8j5JXlwABAgQIECBwo8Dw965tDL9R1o8TIECgVkDwrvV1OgECBAgQIEDgJoHhcL2damP4TbZ+mAABAkcJCN5HyatLgAABAgQIxAoI17Gj1zgBAqECgnfo4LVNgAABAgQI1ArYGF7r63QCBAisJCB4rzQtdyVAgAABAgSmE7AxfLqRuBABAgSmExC8pxuJCxEgQIAAAQKzCdgYPttE3IcAAQJrCQjea83LbQkQIECAAIEigeHvXdsYXjQBxxIgQOC8AoL3eWerMwIECBAgQOBvAsPhevucjeHeDwECBAjsJCB47wTpGAIECBAgQGAOAeF6jjm4BQECBAj8EhC8vQYCBAgQIEBgOQEbw5cbmQsTIEAgWkDwjh6/5gkQIECAwNwCNobPPR+3I0CAAIExAcF7zMlPESBAgAABAkUCNoYXwTqWAAECBKYRELynGYWLECBAgACB8woMf+/axvDzPgKdESBAIFhA8A4evtYJECBAgMCeAsPheitqY/ie9M4iQIAAgckFBO/JB+R6BAgQIEBgJgFLzWaahrsQIECAwCoCgvcqk3JPAgQIECDQJHA1XG/3eP7+7XIdf3LdNBVlCBAgQGBlAcF75em5OwECBAgQ+IDAO0vNHi/HCtcf0PVRAgQIECDwS0Dw9hoIECBAgMCJBW7ZGL4xPH39/BK6/SJAgAABAgR2ExC8d6N0EAECBAgQOEZgeKmZjeHHDEhVAgQIEIgXELzjnwAAAgQIEFhBYDhcb8343vUKI3VHAgQIEAgSELyDhq1VAgQIEJhb4OpSs5/fuRau5x6k2xEgQIAAgb8JCN6eBAECBAgQaBS4Gq63u1hq1jgRpQgQIECAQL2A4F1vrAIBAgQIBArYGB44dC0TIECAAIE3BARvT4MAAQIECNwpMPy9a0vN7hT2MQIECBAgcA4Bwfscc9QFAQIECBQJDIfrrb6lZkVTcCwBAgQIEFhbQPBee35uT4AAAQI7CAjXOyA6ggABAgQIEHhTQPD2OAgQIEAgQuDqUjMbwyPegSYJECBAgMARAoL3EepqEiBAgECZwCtLzb78KPZ4+d3G8DJ7BxMgQIAAAQKvCwjeXgYBAgQILCfwzsbwrZdH4Xq5kbowAQIECBA4tYDgferxao4AAQLrCgx/79rG8HWH7OYECBAgQCBEQPAOGbQ2CRAgMKPAcLjeLm9j+IwjdCcCBAgQIEBgQEDwHkDyIwQIECBwv4Bwfb+dTxIgQIAAAQLnEBC8zzFHXRAgQOBQARvDD+VXnAABAgQIEJhcQPCefECuR4AAgZkEbAyfaRruQoAAAQIECKwiIHivMin3JECAQJOAjeFN0MoQIECAAAECMQKCd8yoNUqAAIFfAsPfu7Yx3LMhQIAAAQIECHxYQPD+MKEDCBAgMKfAcLjerm9j+JxDdCsCBAgQIEDgFAKC9ynGqAkCBFIFhOvUyeubAAECBAgQWElA8F5pWu5KgECkgI3hkWPXNAECBAgQIHAiAcH7RMPUCgECawvYGL72/NyeAAECBAgQIPCWgODtbRAgQKBRwMbwRmylCBAgQIAAAQKTCAjekwzCNQgQOI/A8PeubQw/z9B1QoAAAQIECBB4R0Dw9jwIECBwh8BwuN7OtjH8DmEfIUCAAAECBAicR0DwPs8sdUKAwM4CwvXOoI4jQIAAAQIECIQKCN6hg9c2AQIvAjaGewkECBAgQIAAAQLVAoJ3tbDzCRCYQsDG8CnG4BIECBAgQIAAgUgBwTty7JomcE4BG8PPOVddESBAgAABAgRWFxC8V5+g+xMIExj+3rWN4WEvQ7sECBAgQIAAgXkFBO95Z+NmBGIFhsP1JmRjeOw70TgBAgQIECBAYBUBwXuVSbkngZMJCNcnG6h2CBAgQIAAAQIE3hQQvD0OAgTKBGwML6N1MAECBAgQIECAwEICgvdCw3JVArMK2Bg+62TciwABAgQIECBAYAYBwXuGKbgDgQUEbAxfYEiuSIAAAQIECBAgMKWA4D3lWFyKwDECw9+7tjH8mAGpSoAAAQIECBAgsKSA4L3k2FyawP0Cw+F6K2Fj+P3QPkmAAAECBAgQIEDgh4Dg7SkQOKGApWYnHKqWCBAgQIAAAQIElhUQvJcdnYunC1wN1xvQ8/dvFyd/cp3+XPRPgAABAgQIECBwoIDgfSC+0gRGBN5ZavZ4+bxwPcLoZwgQIECAAAECBAgcJiB4H0avMIFfArdsDN8+9fT180vo9osAAQIECBAgQIAAgekFBO/pR+SCZxEYXmpmY/hZRq4PAgQIECBAgAABAhcBwdtDILCjwHC43mr63vWO8o4iQIAAAQIECBAgMK+A4D3vbNxsUoGrS81+fudauJ50gq5FgAABAgQIECBAoFdA8O71Vm0RgavheuvDUrNFpumaBAgQIECAAAECBI4VELyP9Vf9YAEbww8egPIECBAgQIAAAQIEAgQE74Ahp7doY3j6C9A/AQIECBAgQIAAgWMFBO9j/VXfSWB4qZmN4TuJO4YAAQIECBAgQIAAgVEBwXtUys8dLjAcrreb2hh++LxcgAABAgQIECBAgACBFwHB20uYSuDqUjMbw6eal8sQIECAAAECBAgQIHBdQPC+buQnCgRe+d71lx9lHi+/2xheoO5IAgQIECBAgAABAgSOEBC8j1APqXnLUrOnr59fArdfBAgQIECAAAECBAgQOJmA4H2ygXa3M/y9a0vNukejHgECBAgQIECAAAECkwgI3pMMYuZrDIfrrQlLzWYepbsRIECAAAECBAgQIHCAgOB9APqMJYXrGafiTgQIECBAgAABAgQInEFA8D7DFAd7sDF8EMqPESBAgAABAgQIECBAYEcBwXtHzFmOsjF8lkm4BwECBAgQIECAAAECBPx3vJd9AzaGLzs6FydAgAABAgQIECBAIEzAn3hPPPDh713bGD7xFF2NAAECBAgQIECAAIF0AcH74BcwHK63e9oYfvC0lCdAgAABAgQIECBAgMDtAoL37WY3f0K4vpnMBwgQIECAAAECBAgQIHAaAcF7p1HaGL4TpGMIECBAgAABAgQIECBwMgHB+8aB2hh+I5gfJ0CAAAECBAgQIECAQLiA4P3KA7AxPPzfCu0TIECAAAECBAgQIEBgRwHB+wfm7388/+fh4eHLj//5+PD8/dvln20M3/G5OYoAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYD0tYeCAAAEs0lEQVQAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQKCdyO2UgQIECBAgAABAgQIECCQJyB4581cxwQIECBAgAABAgQIECDQKCB4N2IrRYAAAQIECBAgQIAAAQJ5AoJ33sx1TIAAAQIECBAgQIAAAQKNAoJ3I7ZSBAgQIECAAAECBAgQIJAnIHjnzVzHBAgQIECAAAECBAgQINAoIHg3YitFgAABAgQIECBAgAABAnkCgnfezHVMgAABAgQIECBAgAABAo0CgncjtlIECBAgQIAAAQIECBAgkCcgeOfNXMcECBAgQIAAAQIECBAg0CggeDdiK0WAAAECBAgQIECAAAECeQKCd97MdUyAAAECBAgQIECAAAECjQL/A6Djstyy9VqlAAAAAElFTkSuQmCC`

I thought the boost module would cause the entire chart to render in a canvas element but it sounds like instead it just causes the series part of the chart to render in an image tag? And the rest still render as SVG, is that right? If so, I can close the ticket, thanks again!

**Comment by ppotaczek** [comment]
@TowhidKashem, Yes, that's right. The Boost module renders only series using WebGL on a canvas and adds it as an image inside the chart's SVG structure.

One more thing about your config - for the modules you use it doesn't matter, but in general, the Boost module should be initialized as the last one.

> Note: Boost should be the last module included. This is because it overrides both standard Highcharts functionality, and functionality in certain modules (namely treemap, heatmap, bubble, and scatter).

```
import * as Highcharts from 'highcharts';
import HighchartsReact from 'highcharts-react-official';
import Accessibility from 'highcharts/modules/accessibility';
import Exporting from 'highcharts/modules/exporting';
import ExportData from 'highcharts/modules/export-data';
import OfflineExporting from 'highcharts/modules/offline-exporting';
import Boost from 'highcharts/modules/boost';

Accessibility(Highcharts);
Exporting(Highcharts);
ExportData(Highcharts);
OfflineExporting(Highcharts);
Boost(Highcharts); // <------------ here
```
