### ISSUE TITLE
Issue: Component Getting Unmounted from DOM When Using Scroll

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts-react#476]
Description

We have implemented our axis component using a portal to render a custom component in our Highcharts chart. However, we are encountering an issue where the custom component becomes invisible when we scroll in chart. The component seems to unmount from the DOM upon scrolling, as demonstrated in the video below.
Steps to Reproduce

Implementation of custom component for axis: https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-56crg6?file=%2FLabelComponent.jsx%3A4%2C25

Expected Behavior

The custom component should remain visible and stay mounted in the DOM even when the scrollbar is scrolled.
Actual Behavior

The custom component becomes invisible and appears to unmount from the DOM when the scroll is scrolled.
Additional Information
Reproducible in codeSandbox : https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-mh9krd?file=%2Fdemo.jsx

    Video Demonstration: 

https://github.com/highcharts/highcharts-react/assets/75986382/43959799-ab60-4b80-a145-b86c43293528

https://github.com/highcharts/highcharts-react/assets/75986382/5d8f4fa8-723f-4d0a-942e-0f66bdc140a9

**Comment by KamilKubik** [comment]
Hello [Satyam7Jha](https://github.com/Satyam7Jha),

Thanks for contacting us and sharing the reproducible issue, 

It seems the main issue is with the built-in HC `render` event you use to set the ticks which fires every time you fire the scroll event. Then it causes unnecessary component rerenders, built-in HC `reflow` method, etc., and you end up with some performance issues, and at some point, HC seems not to read the ticks properly.

Reading the ticks only once the chart is rendered should be enough, and you can use the built-in HC [load](https://api.highcharts.com/highcharts/chart.events.load) event instead. Kindly take a look at your updated [demo](https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-ztnwkz?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwrjfbqk00073b6llwfho13m%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwrjfbqk00033b6lee54nvmj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwrjfbqk00043b6lm10xcnqe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwrjfbqk00063b6lyj5ngxm8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwrjfbqk00033b6lee54nvmj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrjfbqk00023b6l63gdyfm9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A66%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A66%252C%2522endColumn%2522%253A24%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwrjfbqk00033b6lee54nvmj%2522%252C%2522activeTabId%2522%253A%2522clwrjfbqk00023b6l63gdyfm9%2522%257D%252C%2522clwrjfbqk00063b6lyj5ngxm8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrjfbqk00053b6lvztch9s9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwrjfbqk00063b6lyj5ngxm8%2522%252C%2522activeTabId%2522%253A%2522clwrjfbqk00053b6lvztch9s9%2522%257D%252C%2522clwrjfbqk00043b6lm10xcnqe%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwrjfbqk00043b6lm10xcnqe%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Kind Regards!

**Comment by Satyam7Jha** [comment]
Thanks for the help, @KamilKubik. However, since we've moved setTick to load, it's updating only once, resulting in the same tick for all points. Here are some live examples illustrating the issue:

https://github.com/highcharts/highcharts-react/assets/75986382/a362a191-95ce-4a82-a838-477e7f078c95


https://github.com/highcharts/highcharts-react/assets/75986382/1fc9de4c-52de-4d63-9a90-8ee9094c41bc

[demo](https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-ztnwkz?file=%2Fdemo.jsx)

Could you please help with this issue?

**Comment by KamilKubik** [comment]
Thanks for your clarification!

I can see there's a functionality responsible for manually removing (unmounting) the labels that refer to some React errors (I can't see any). Have you tried removing it, [demo](https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-m45zr8?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwrjfbqk00073b6llwfho13m%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwrjfbqk00033b6lee54nvmj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwrjfbqk00043b6lm10xcnqe%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwrjfbqk00063b6lyj5ngxm8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwrjfbqk00033b6lee54nvmj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrjfbqk00023b6l63gdyfm9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A66%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A66%252C%2522endColumn%2522%253A24%257D%255D%257D%255D%252C%2522id%2522%253A%2522clwrjfbqk00033b6lee54nvmj%2522%252C%2522activeTabId%2522%253A%2522clwrjfbqk00023b6l63gdyfm9%2522%257D%252C%2522clwrjfbqk00063b6lyj5ngxm8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrjfbqk00053b6lvztch9s9%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwrjfbqk00063b6lyj5ngxm8%2522%252C%2522activeTabId%2522%253A%2522clwrjfbqk00053b6lvztch9s9%2522%257D%252C%2522clwrjfbqk00043b6lm10xcnqe%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwrjfbqk00043b6lm10xcnqe%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)?

Also, I'd like to point you to a slightly different implementation I've prepared here: [demo](https://codesandbox.io/p/sandbox/highcharts-react-demo-forked-z9hp6z?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clwrs0qii00073b6l18vzcgxi%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clwrs0qii00033b6le4w32sx6%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clwrs0qii00043b6lsrfdivgd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clwrs0qii00063b6lu6u9o8rv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clwrs0qii00033b6le4w32sx6%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrs0qii00023b6lateadouw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fdemo.jsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clwrs0qii00033b6le4w32sx6%2522%252C%2522activeTabId%2522%253A%2522clwrs0qii00023b6lateadouw%2522%257D%252C%2522clwrs0qii00063b6lu6u9o8rv%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clwrs0qii00053b6l1bnhez8h%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clwrs0qii00063b6lu6u9o8rv%2522%252C%2522activeTabId%2522%253A%2522clwrs0qii00053b6l1bnhez8h%2522%257D%252C%2522clwrs0qii00043b6lsrfdivgd%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clwrs0qii00043b6lsrfdivgd%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Let me know how the above works for you,
Regards!

**Comment by Satyam7Jha** [comment]
Thank you for your help
