### ISSUE TITLE
Incorrect Typescript usage documentation

### ISSUE THREAD

**Issue by romaleev** [highcharts/highcharts-react#480]
In Typescript highcharts-react-official should be imported with named import:
`import { HighchartsReact } from 'highcharts-react-official'`
instead of 
`import HighchartsReact from 'highcharts-react-official'`

Otherwise I get errors:
```
TS2604: JSX element type HighchartsReact does not have any construct or call signatures.
TS2786: HighchartsReact cannot be used as a JSX component.
Its type
typeof import("/project/node_modules/highcharts-react-official/dist/highcharts-react.min")
is not a valid JSX element type.
```

```
"typescript": "^5.4.5
"highcharts": "11.4.3",
"highcharts-react-official": "3.2.1",
```

Please update the docs

**Comment by KamilKubik** [comment]
Hello [romaleev](https://github.com/romaleev) and thanks for bringing it up!

Yes, I agree the docs should be updated - I've opened the [PR](https://github.com/highcharts/highcharts-react/pull/482) with the suggested change. 

Kind Regards!
