### ISSUE TITLE
mapline is hidden when draw from LA to Taiwan

### ISSUE THREAD

**Issue by tuanlam0201** [highcharts/highcharts-react#484]
![Screenshot from 2024-07-09 16-15-52](https://github.com/highcharts/highcharts-react/assets/163503189/53f221b6-7abf-41f2-80f0-4d5c5bcacf8a)
![Screenshot from 2024-07-09 16-16-01](https://github.com/highcharts/highcharts-react/assets/163503189/7193b9fe-c170-4832-a325-9b0225d2ceea)

img1 is expectation in figma
img2 is my code :(((

Thank u 

{
    chart: {
      map: props.mapData,
      height: props.height,
    },
    title: {
      text: '',
    },
    plotOptions: {
      mapline: {
        nullColor: props.theme.palette.error.main,
      },
      mappoint: {
        marker: {
          fillColor: props.theme.palette.error.main,
          lineWidth: 1,
          symbol: 'mapmarker',
          radius: 8,
        },
      },
    },
    mapView: {
      projection: {
        name: 'WebMercator',
      },
      center: [0, 40],
      zoom: 1,
    },
    mapNavigation: {
      enabled: true,
      buttonOptions: {
        verticalAlign: 'bottom',
      },
    },
    xAxis: {
      lineWidth: 0,
      tickWidth: 0,
      labels: {
        enabled: false,
      },
    },
    yAxis: {
      lineWidth: 0,
      tickWidth: 0,
      labels: {
        enabled: false,
      },
    },
    legend: {
      enabled: false,
    },
    series: [
      {
        type: 'map',
        data: [
          ['us', 10],
          ['tw', 20],
        ],
        joinBy: 'hc-key',
        name: 'Map Data',
        states: {
          hover: {
            color: props.theme.palette.primary.main,
          },
        },
        color: props.theme.palette.primary.main,
        dataLabels: {
          enabled: false,
          format: '{point.name}',
        },
      },
      {
        type: 'mappoint',
        name: 'State',
        dataLabels: {
          enabled: true,
          y: -30,
          format: `
        <div style="color: #fff">
        <span style="color: inherit; display: block; margin-bottom: 5px">{point.name}</span>
        <span style="color: inherit; display: block; margin-bottom: 5px">VERITIV</span>
        <span style="color: inherit; display: block; margin-bottom: 5px">9330 Nw 110th Avenue, Miami, Fl 33178, USA</span>
        </div>
        `,
          backgroundColor: props.theme.palette.commonBlackStatesMain.main,
          borderRadius: 4,
          padding: 8,
          useHTML: true,
        },
        data: [
          {
            lon: 121.59,
            lat: 25.10,
            name: 'Amsterdam',
          },
          {
            lon: -118.24,
            lat: 34.05,
            name: 'LA',
          },
        ],
      },
      {
        type: 'mapline',
        dashStyle: 'Dash',
        lineWidth: 2,
        data: [
          {
            geometry: {
              type: "LineString",
              coordinates: [
                [121.59, 25.10],
                [-118.24, 34.05],
              ],
            },
          },
        ],
      },
    ],
  };

**Comment by KamilKubik** [comment]
Hello [tuanlam0201](https://github.com/tuanlam0201)!

Thanks for contacting us.

As I can see you received an answer in this [thread](https://github.com/highcharts/highcharts/issues/21503). Since the problem isn't directly related to the React integration and we try not to duplicate the issues, I kindly refer you there.

Kind Regards!
