### ISSUE TITLE
I'm trying to find a way to center my flag but can't seem to do it #21540

### ISSUE THREAD

**Issue by tuanlam0201** [highcharts/highcharts-react#486]
![Screenshot from 2024-07-16 10-43-03](https://github.com/user-attachments/assets/984cb1c2-8800-41ec-8989-c3f5d71c2dcc)

![Screenshot from 2024-07-16 13-32-46](https://github.com/user-attachments/assets/be8e9f77-fcc3-44fa-a260-5be776c0b393)

const options: Highcharts.Options = {
    chart: {
      height: 600,
      margin: 0,
    },
    plotOptions: {
      series: {
        borderWidth: 0,
        states: {
          hover: {
            enabled: false, // Disable hover effect
          },
        },
        dataLabels: {
          enabled: true,
          formatter: function () {
            const { point } = this;
            const flag = getEmojiFlag('VN');
            return `<div style="font-size: 24px">${flag} </div><br/>
                    <span style="color: ${secondary.main}">${point.name}</span>
            `;
          },
          style: {
            textOutline: 'none',
            lineHeight: 20,
          },
        },
      },
    },
    tooltip: {
      valueDecimals: 1,
      backgroundColor: commonBlackStatesMain.main,
      padding: 14,
      borderRadius: shape.borderRadius * 2,
      useHTML: true,
      formatter: function () {
        const { point } = this;
        const flag = getEmojiFlag('VN');
        return `
          <div style="min-width: 270px">
            <span style="font-size: 24px; color: inherit; display: block; margin-bottom: 5px; color: white; fontWeight: 600">
              ${point.value}%
            </span>
            <span style="color: inherit; display: block; margin-bottom: 5px; color: white; fontWeight: 600">
            ${flag}  ${point.name}</span>
            <span style="color: inherit; display: block; color: ${text.secondary}">Shipments <span style="color: white">${point.value}</span></span>
          </div>`;
      },
    },
    colors: TREEMAP_PALLET_COLOR,
    series: [
      {
        type: 'treemap',
        layoutAlgorithm: 'squarified',
        clip: false,
        colorByPoint: true,
        data: data,
      },
    ],
    title: {
      text: '',
    },
  };

**Comment by KamilKubik** [comment]
Moved to: https://github.com/highcharts/highcharts/issues/21540.
