### ISSUE TITLE
Cannot center data label

### ISSUE THREAD

**Issue by tuanlam0201** [highcharts/highcharts-react#487]
![Screenshot from 2024-07-16 14-49-42](https://github.com/user-attachments/assets/0e506c14-0ef6-4bab-8de5-f7bbe7fe36e4)
![Screenshot from 2024-07-16 10-43-03](https://github.com/user-attachments/assets/13cb2bf3-7c6c-4d50-8d10-6073bb4421ff)

 const options: Highcharts.Options = {
    chart: {
      height: 600,
      margin: 0,
    },
    plotOptions: {
      series: {
        borderWidth: 0,
        states: {
          hover: {
            enabled: false, // Disable hover effect
          },
        },
        dataLabels: {
          enabled: true,
          align: 'center',
          formatter: function () {
            const { point } = this;
            const flag = getEmojiFlag('VN');
            return `<div style="font-size: 24px">${flag} </div><br/>
                    <span style="color: ${secondary.main}">${point.name}</span>
            `;
          },
          style: {
            textOutline: 'none',
            lineHeight: 20,
            textAlign: 'center',
          },
        },
      },
    },
    tooltip: {
      valueDecimals: 1,
      backgroundColor: commonBlackStatesMain.main,
      padding: 14,
      borderRadius: shape.borderRadius * 2,
      useHTML: true,
      formatter: function () {
        const { point } = this;
        const flag = getEmojiFlag('VN');
        return `
          <div style="min-width: 270px">
            <span style="font-size: 24px; color: inherit; display: block; margin-bottom: 5px; color: white; fontWeight: 600">
              ${point.value}%
            </span>
            <span style="color: inherit; display: block; margin-bottom: 5px; color: white; fontWeight: 600">
            ${flag}  ${point.name}</span>
            <span style="color: inherit; display: block; color: ${text.secondary}">Shipments <span style="color: white">${point.value}</span></span>
          </div>`;
      },
    },
    colors: TREEMAP_PALLET_COLOR,
    series: [
      {
        type: 'treemap',
        layoutAlgorithm: 'squarified',
        clip: false,
        colorByPoint: true,
        data: data,
      },
    ],
    title: {
      text: '',
    },
  };

**Comment by KamilKubik** [comment]
Hello [tuanlam0201](https://github.com/tuanlam0201)!

Thanks for contacting us again.

As I can see, you created a similar [issue](https://github.com/highcharts/highcharts/issues/21540) on the core repository. Since the issue isn't related to the React integration, I'd like to kindly refer you there, where the answer will be provided. Also, we try to avoid duplicating the issues among the repositories.

Kind Regards!
