### ISSUE TITLE
Can i add a marker at the end of the path Gauge?

### ISSUE THREAD

**Issue by dotuanlam-0201** [highcharts/highcharts-react#488]
Hi sir,

Im using GaugeChart and i have a problem to custom gauge,
the expectation is the point at the end of path 
![Frame 2157](https://github.com/user-attachments/assets/ebbf0768-9306-4cea-ac98-3b26aa1b2b39)
and this is my result: 
![Screenshot from 2024-07-23 17-00-13](https://github.com/user-attachments/assets/42eb6e02-1ff4-4078-bb62-36dae381ab74)

const GaugeChart = ({ height = 300 }: IProps) => {
  const {
    palette: { primary },
  } = useTheme();

  const options: Highcharts.Options = {
    chart: {
      margin: 0,
      height: height,
    },
    tooltip: {
      enabled: false,
    },
    title: { text: '' },
    credits: {
      enabled: false,
    },
    pane: {
      size: '100%',
      startAngle: -90,
      endAngle: 90,
      background: [
        {
          innerRadius: '90%',
          outerRadius: '100%',
          backgroundColor: alpha(primary.main, 0.07),
          borderWidth: 0,
          shape: 'arc',
        },
      ],
    },
    plotOptions: {
      solidgauge: {
        stickyTracking: true,
        crisp: true,
        innerRadius: '90%',
        radius: '100%',
        dataLabels: {
          enabled: false,
        },
        custom: {
          width: 12,
          height: 12,
          backgroundColor: 'red',
        },
      },
    },
    yAxis: {
      labels: {
        enabled: false,
      },
      min: 0,
      max: 100,
      gridLineColor: 'transparent',
      lineColor: 'transparent',
      minorTickLength: 0,
      tickPosition: 'inside',
      tickLength: 0,
      stops: [[0, primary.main]],
    },
    series: [
      {
        type: 'solidgauge',
        data: [90],
      },
    ],
  };
  return <HighchartsReact highcharts={Highcharts} options={options} />;
};

export default GaugeChart;

Thanks for your help!!

**Comment by KamilKubik** [comment]
Hello [dotuanlam-0201](https://github.com/dotuanlam-0201)!

Thanks for contacting us.

To achieve it using the `solidgauge` series, you have to render a custom and properly positioned element using the [circle](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer#circle) method on the [SVGRenderer](https://api.highcharts.com/class-reference/Highcharts.SVGRenderer) class. I've prepared a potential solution using your configuration: [demo](https://stackblitz.com/edit/react-5gxjrk?file=index.js). Please note that the calculations should be adjusted to the current chart's configuration. 

Alternatively, you can use the `gauge` chart type and change the default dial to the circle by overwriting the core code to achieve a similar effect. Here's an [example](https://jsfiddle.net/dfliess/zahmyrxo/) taken from [this](https://www.highcharts.com/forum/viewtopic.php?t=44651) topic. 

Let me know how this works for you,
Kind Regards!

**Comment by dotuanlam-0201** [comment]
Many thank sir!
