### ISSUE TITLE
Question: Remove 1/2 solidchart

### ISSUE THREAD

**Issue by dotuanlam-0201** [highcharts/highcharts-react#489]
Hi,
Sometime i use the solid gauge chart but i just use 50%  upper and can i remove 1/2 chart below

link jsfiddle: ` https://jsfiddle.net/e95mcn2v/20/`

![Screenshot from 2024-07-25 10-38-46](https://github.com/user-attachments/assets/132148b4-0f82-4326-9ab4-c0f7476dc309)

**Comment by KamilKubik** [comment]
Hello [dotuanlam-0201](https://github.com/dotuanlam-0201)!

Thanks for contacting us again.

I'm unsure if I understand your requirement, but I assume you'd like to have the chart cut off "horizontally" by 50%. If so, you can easily adjust the [endAngle](https://api.highcharts.com/highcharts/pane.endAngle) property. Kindly take a look at the [demo](https://jsfiddle.net/BlackLabel/s9f148pL/).

If that's not helpful, could you elaborate more about your requirements?

Kind Regards!

**Comment by dotuanlam-0201** [comment]
Dear Mr KamilKubik,

![Screenshot from 2024-07-25 14-41-06](https://github.com/user-attachments/assets/f5cef8ad-ebe2-4d8b-90f2-1c253b15996a)

Im sorry for the missunderstanding, 
my idea is i will use ` startAngle: -90,
      endAngle: 90,` to use 50% chart above.
     But my problem is remove the blank space below like a image

**Comment by KamilKubik** [comment]
I can see the point now, thanks for your clarification!

You can operate over the [pane.center](https://api.highcharts.com/highcharts/pane.center) and [pane.size](https://api.highcharts.com/highcharts/pane.size) properties like this: [demo](https://jsfiddle.net/BlackLabel/65d39ryL/). The blank space is removed, but the chart is a bit scaled-up, so you should adjust the [chart.height](https://api.highcharts.com/highcharts/chart.height) property depending on your needs: [demo](https://jsfiddle.net/BlackLabel/y2vm6cdL/).

Here's the related [thread](https://stackoverflow.com/questions/51460874/highcharts-solid-gauge-remove-wasted-space-in-pane).

Kind Regards!

**Comment by dotuanlam-0201** [comment]
Many thank sir
