### ISSUE TITLE
Proper Changelog

### ISSUE THREAD

**Issue by orangecoding** [highcharts/highcharts-react#49]
Hi,

as this is the official react binding of highchart, it would be nice to have a proper changelog as ppl rely on this. 

a CHANGELOG.md with proper versioning would be awesome.

**Comment by KacperMadej** [comment]
Hi @orangecoding 

Logging changes is a good feature for sure.

1. We could add info in releases list - https://github.com/highcharts/highcharts-react/releases

2. Where's definition for CHANGELOG.md? Could this be used other than by opening a GitHub page to view the list? @orangecoding 

We could do 1, 2 or both, but we need more info to decide.

**Comment by orangecoding** [comment]
A common thing for open source repos is to either use the github release page as you mention or (and I recommend doing this) maintain a CHANGELOG.md which is a simple markup file. See react as an example of what I mean.

https://github.com/facebook/react/blob/master/CHANGELOG.md

**Comment by KacperMadej** [comment]
@gvaartjes Is there any more preferred format or should/could we add both (CHANGELOG.md and GitHub release list) for React, Angular and Vue wrappers?

**Comment by TorsteinHonsi** [comment]
Just a thought - we recently created a structure for changelogs in the main highcharts repo, see https://github.com/highcharts/highcharts/tree/master/changelog/highcharts. It might be an idea to follow the same pattern, but I'll leave it to you guys to decide.

**Comment by orangecoding** [comment]
@TorsteinHonsi it's a bit unusual, but I actually like it. It might however be easier for a small repo like this to maintain the changelog in a single md file.

**Comment by TorsteinHonsi** [comment]
Yes, for Highcharts we have other considerations. We primarily use it as the source for generating https://www.highcharts.com/documentation/changelog.

**Comment by gvaartjes** [comment]
@KacperMadej I would prefer the single file, like @orangecoding suggested. If we need (not likely) a similar structure as Highcharts, we can always cut it up later. 
Can you make sure a _CHANGELOG.md_ is also added for the Angular and the Vue wrapper?

**Comment by KacperMadej** [comment]
@gvaartjes 
Done for `highcharts-react` (https://github.com/highcharts/highcharts-react/blob/master/CHANGELOG.md)
I'll handle `highcharts-angular` and @Denyllon will handle `highcharts-vue` on Monday.

**Comment by gvaartjes** [comment]
@KacperMadej thx!
