### ISSUE TITLE
Height difficulties

### ISSUE THREAD

**Issue by gjevardat** [highcharts/highcharts-react#494]
Hello 

I read many posts here and there including the official documentation to figure out how to have 100% height for a chart, but unless setting absolute values , I cannot succeed !

The parent div container is properly set to 100% height or/and h-full and then I force the HighCharts like this 

      <HighchartsReact 
        highcharts={Highcharts}
        options={options}
        ref={chartComponentRef}
        containerProps={ { style: { height: "100%" } }}
        />

But it remains 400px height.

Only setting an absolute value like

      <HighchartsReact 
        highcharts={Highcharts}
        options={options}
        ref={chartComponentRef}
        containerProps={ { style: { height: 1000 } }}
        />

has an effect!

Thanks for any help

I'am using  "highcharts": "^11.4.8", and     "highcharts-react-official": "^3.2.1",

**Comment by ppotaczek** [comment]
Hi @gjevardat,

Thank you for contacting us!

Could you reproduce the problem in some online code editor? The below example works as expected:

      <div style={{height: "100vh"}}>
        <HighchartsReact
          highcharts={Highcharts}
          options={chartOptions}
          containerProps={ { style: { height: "100%" } }}
        />
      </div>

**Live demo:** https://stackblitz.com/edit/react-edsjbb?file=index.js

Are you sure the direct parent of the chart container has the appropriate height set?

**Comment by gjevardat** [comment]
Confirmed that the simple example work in my app.
I'll dig in to identify cause...

**Comment by gjevardat** [comment]
Ok I found an explanation not sure how to fix it properly.
My chart is in a nested grid layout.

When the chart is direct ancestor of root container it works as expected, but if there is a first row of components in the grid then the HighChart expands 100% + size of the first row !

More clearly: when sized 100% vertically it is actually taking 100% but slightly shifted downward by the size of the components at the top of the Chart
Not sure how to fix that, any idea welcome:

**Comment by ppotaczek** [comment]
Hi @gjevardat, Thanks for the additional information. 
You probably need to set `height: 100%` style for all container elements. I mean something like here: https://stackblitz.com/edit/react-4mr7ep

I can also investigate the issue more deeply if you present it in a simple live example.

Best regards!

**Comment by gjevardat** [comment]
Thanks that was it 100% instead of 100hv  :)
Many thanks

**Comment by denchen** [comment]
Sorry to bring up a closed topic, but I'm having similar issues.

My container setup is rather complicated, so I'm having difficulties replicating the issue, but my charts are contained in a container wtihin a container within a CSS Grid. The innermost container has `h-64` (or `height: 256px`), and through various settings detailed here and elsewhere, the chart either renders at 400px, or it renders at the correct height, but the width is shrunk, I believe due to aspect ratio.

Here's the weird thing:

If I set containerProps as such:

```tsx
<HighchartsReact
  containerProps={{
    height: 100%;
  }}
/>
```

Then the chart renders at 400px, but if I set it to 99.9%, then it renders at the correct height. So does Highcharts itself have some special logic for `height: 100%` vs any other height value? Or is this perhaps a CSS thing? I will continue to try to make a barebones reproduction, and if I can, I'll open a new issue, but it's been difficult. But I would like to know how Highcharts deals with percentage heights.

**Comment by gjevardat** [comment]
@denchen 
My 2 cents on this  is that I really needed to have an immediate div parent wrapping the HighChart component at 100% height
<div style={{ height: "100%" }}>
      <HighchartsReact
        highcharts={Highcharts}
        options={chartOptions }
        ref={chartComponentRef}
        containerProps={{ style: { height: "100%" } }}
      />
    </div>

**Comment by ppotaczek** [comment]
Hi @denchen, 

I think the best answer here will be to provide the exact code showing how the height is calculated.

From Highcharts source code: https://github.com/highcharts/highcharts/blob/0863a0f305da17d62dff7a17001f2736f9386d3b/ts/Core/Chart/Chart.ts#L1394

```
enableDefaultHeight =
  containerBox.height > 1 &&
  !(
    // #21510, prevent infinite reflow
    (
      !chart.renderTo.parentElement?.style.height &&
      chart.renderTo.style.height === "100%"
    )
  )

...
                
chart.chartHeight = Math.max(
  0,
  relativeLength(
    heightOption as any,
    chart.chartWidth
  ) ||
  (enableDefaultHeight ? containerBox.height : 400)
);
```

Best regards!

**Comment by alexong-wk** [comment]
> @denchen My 2 cents on this is that I really needed to have an immediate div parent wrapping the HighChart component at 100% height
> 
> ```
> <div style={{ height: "100%" }}>
>       <HighchartsReact
>         highcharts={Highcharts}
>         options={chartOptions }
>         ref={chartComponentRef}
>         containerProps={{ style: { height: "100%" } }}
>       />
> </div>
> ```

This helped solve my issue! Was working at this for so long and had similar difficulties with my charts being inside a MUI Data Grid slot (essentially living under a grid component)

**Comment by mark-buhagiar** [comment]
Just wanted to point out, that in our project we are using tailwind, and the wrapping element had the `h-full` class. This **did not work**. We had to explicitly set the `style={{height: '100%'}}`.
I'm sure there'll be others who run into the same scenario!
