### ISSUE TITLE
Render custom component on data-labels

### ISSUE THREAD

**Issue by Satyam7Jha** [highcharts/highcharts-react#499]
How can I render a custom component in Highcharts' dataLabels, similar to how it's achieved for tooltips using React Portals?

For reference, here's an example where a custom tooltip is implemented using React Portals: [Codesandbox Example](https://codesandbox.io/p/sandbox/highcharts-custom-tooltip-forked-8mq7x5?file=%2Findex.tsx).

I would like to achieve the same behavior for dataLabels. Can you help with this implementation?

**Comment by KamilKubik** [comment]
Hi [Satyam7Jha](https://github.com/Satyam7Jha)!

First, I'd like to refer you to [this](https://stackoverflow.com/questions/66619738/how-to-use-a-react-component-as-the-label-in-highcharts) thread, which shows a very straightforward implementation that should be suitable for most cases.

I can see some limitations in the mentioned thread. Therefore, as an alternative, you should follow the same approach as for a custom tooltip, except that you should render a custom data label for every point and render them under the proper references. Kindly refer to the simple implementation: [demo](https://stackblitz.com/edit/react-starter-typescript-rh4qa8?file=App.tsx,CustomDataLabel.tsx).

Kind Regards!

**Comment by jacquesg** [comment]
@KamilKubik On the highcharts [roadmap](https://www.highcharts.com/roadmap/) there is mention of improved React integration.

Will this solve all the nuances associated with using React components for formatting tooltips/labels?

**Comment by KamilKubik** [comment]
@jacquesg absolutely!

As the roadmap partially states, we plan to achieve a more React-friendly, meaning a more generative version. I'd highly encourage you to contact us directly via [contant form under the roadmap section](https://shop.highcharts.com/contact) for more detailed information and some potential early-staged concepts. 

Regards!

**Comment by Satyam7Jha** [comment]
Thanks @KamilKubik
