### ISSUE TITLE
Bug when updating multiple series and their y_axis

### ISSUE THREAD

**Issue by sebabouche** [highcharts/highcharts-react#53]
### Expected Behavior
When showing multiple series and their own y_axis, it should be possible to remove one series (and its y_axis).
### Current Behavior
+ Adding a series and custom y_axis works fine 
+ but removing one raises a `Uncaught TypeError: Cannot read property 'hoverSeries' of undefined `
### Steps to Reproduce
This bug is reproduced in this [stackblitz](https://stackblitz.com/edit/react-wbzhpv?file=Chart.js).
Here you have [a working fork](https://stackblitz.com/edit/react-6zewjs?file=Chart.js) with the  **y_axis options** commented out.
### Detailed Description
This problem occurs when you need to dynamically add or remove series from a chart with their own y_axis [as detailed here](https://www.highcharts.com/demo/combo-dual-axes).

**Comment by ppotaczek** [comment]
Hello @sebabouche,

This problem is not related with react wrapper: http://jsfiddle.net/BlackLabel/L15k2nge/
I reported this problem on highcharts repository: https://github.com/highcharts/highcharts/issues/9097

**Comment by rohankk2** [comment]
How to fix this bug ?

**Comment by ppotaczek** [comment]
Hi @rohankk2,

This problem has been fixed since version: 6.2.0 

Live demo: https://stackblitz.com/edit/react-ckjh7r?file=Chart.js

Best regards!
