### ISSUE TITLE
Importable map data

### ISSUE THREAD

**Issue by cheshrkat** [highcharts/highcharts-react#55]
I'm trying to get maps working, specifically trying to reproduce https://jsfiddle.net/gh/get/library/pure/highslide-software/highcharts.com/tree/master/samples/mapdata/countries/au/au-all in a React project.

It seems that the map data isn't available in any official Highcharts package (eg. discussion at https://forum.highcharts.com/highmaps-usage-f14/map-not-rendering-t39804/ suggests manually importing the map you need).

Is a manual import still the only way to get the maps working? If so is there any chance the map data will get included in this or the main package in future?

**Comment by ppotaczek** [comment]
Hi cheshrkat,

Yes, for now manual import is the only way to get the maps working. You can submit your suggestion here: https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api

We are trying to keep github only for bugs, so for future please ask this type of questions on support: https://www.highcharts.com/support

Best regards!

**Comment by cheshrkat** [comment]
Thanks for the advice, I've made the suggestion at https://highcharts.uservoice.com/forums/55896-highcharts-javascript-api/suggestions/35712394-publish-the-map-collection-data-as-an-react-npm-pa
