### ISSUE TITLE
how to load completely new data and new charttype on a react highchart

### ISSUE THREAD

**Issue by rohankk2** [highcharts/highcharts-react#57]
I use this.setState to load new options into the highchart. 
Essentially i have two scenarios:
1. based on a few filters I want to see column chart 
2. if the filters are changed I want to see a grouped line chart

These components individually work well. However if i have loaded a highcharts react chart in grouped line chart format and I switch to the column chart for some reason the x axis still has values from the previous chart type

What is the best way to update the highchart with completely new options and data ? my problem is somehow data from a previously displayed chart type keeps showing up on the x axis even though when I console.log my chart options they are different. 

My thinking is that when I change the chart options of this.state and pass it to the highcharts react compoenent it just merges the options and hence I see data from different charts

**Comment by ppotaczek** [comment]
Hi @rohankk2,

After `setState`, the `highcharts-react` wrapper uses `chart.update()` to update chart options, which are merged, not overwritten.

API: https://api.highcharts.com/class-reference/Highcharts.Chart#update

In your case the best way to achieve the wanted result is to create two `HighchartsReact` components and display them alternately depending on some condition.

```
  render() {
    return (
      <div>
        {this.state.displayedChart === 1 && (
          <HighchartsReact
            highcharts={Highcharts}
            constructorType={"chart"}
            options={this.state.options}
          />
        )}
        {this.state.displayedChart === 2 && (
          <HighchartsReact
            highcharts={Highcharts}
            constructorType={"chart"}
            options={this.state.options}
          />
        )}
      </div>
    );
  }
```

Live demo: https://codesandbox.io/s/xp63rx42y4

We are trying to keep github only for bugs, so for future please ask this type of questions on support: https://www.highcharts.com/support
