### ISSUE TITLE
TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by siddharthdb** [highcharts/highcharts-react#59]
Hi team,

Getting error on line 63.

Module.<anonymous>
node_modules/highcharts-react-official/src/HighchartsReact.js:63
  60 |   return HighchartsReact;
  61 | }(React.PureComponent);
  62 | 
> **63 | module.exports = HighchartsReact;**
View compiled
Module../node_modules/highcharts-react-official/src/HighchartsReact.js

Please change the above highlighted line to 

**export default HighchartsReact;**

**Comment by siddharthdb** [comment]
Please merge the Pull Request.
https://github.com/highcharts/highcharts-react/pull/58/commits/4b12a642d1481cb044426f7501c47c50a23f8f1b

**Comment by hazratgs** [comment]
update package npm! 1.5.1 error!

**Comment by hazratgs** [comment]
> Node package on NPM repo looks like updated to 1.5.2
> https://www.npmjs.com/package/highcharts-react-official
> 
> Maybe it was some upload / refresh delay. All is fine now @hazratgs ?

Error left, please fix it.

**Comment by KacperMadej** [comment]
@hazratgs 
Please provide live demo and details about the problem. From what you have provided so far I'm not able to recreate the problem or resolve it.

**Comment by hazratgs** [comment]
why not translate the code in ES5 right away and not for a demo? we still connect it to the project where the modules are not compiled

**Comment by ppotaczek** [comment]
Hello hazratgs, In the new version of the wrapper - 2.0.0, the code is compiled to ES5.
