### ISSUE TITLE
v1.4.1 Crashes apps on React 15.

### ISSUE THREAD

**Issue by elvisspirjan** [highcharts/highcharts-react#60]
v1.4.1 Should be the major release.
Default configuration like ^1.4.0 will treat this update as minor.

ERROR in main.6050d7c9af6340703376.js from UglifyJs 
SyntaxError: Unexpected token: name (React) [./~/highcharts-react-official/src/HighchartsReact.js:1,0]

**Comment by hazratgs** [comment]
and 16.4
![image](https://user-images.githubusercontent.com/4028580/47651890-7c7d5a00-db95-11e8-889b-0bf914c0ce10.png)

**Comment by hazratgs** [comment]
last version package

**Comment by ppotaczek** [comment]
Hi @elvisspirjan, @hazratgs,

Thank you for reporting this issue. Indeed, 'highcharts-react-official' v1.4.1 Should be the major release. I think that a good solution will be to keep v1.4.1 in its current form and add v1.4.2 in the same form as 1.4.0.

**Comment by alexhans1** [comment]
according to npm versioning you should really go with 2.0.0
https://docs.npmjs.com/getting-started/semantic-versioning

**Comment by ppotaczek** [comment]
Version 1.4.1 was created by accident but it was only available on github. Why did not you use the npm package?

Now there is a new version 2.0.0 and 1.4.1 release is removed from github.
