### ISSUE TITLE
time.useUTC is not getting configured

### ISSUE THREAD

**Issue by raquelguimaraes** [highcharts/highcharts-react#7]
I have a chart options object that is configuring the `time.useUTC` option to `false` but the resulting chart is still on utc. I took the full options object and pasted on a jsfiddle and it worked there.

**Comment by KacperMadej** [comment]
Hi @raquelguimaraes 

Please check the version of Highcharts you are loading for the React app.
The `time` was added in version 6.0.5.

**Comment by raquelguimaraes** [comment]
you are correct, I was on 6.0.4.
sorry about that and thanks for the very fast reply :)
