### ISSUE TITLE
What is the reason for removing containerProps in v2?

### ISSUE THREAD

**Issue by far1s** [highcharts/highcharts-react#71]
Thank you for providing this great Highchart React API guys. Just wondering why `containerProps` was removed in v2, since we're using it in our App to set a `className` to the inner highcharts container. Do you provide an alternative in v2?

**Comment by ppotaczek** [comment]
Hi @far1s, thank you for your question.

`containerProps` has been replaced by a direct reference to the container, which I think adds more flexibility. I prepared the following example, which shows how you can get to the `container` reference and add class.

    class App extends React.Component {
      constructor(props) {
        super(props);

        this.chartComponent = React.createRef();

        this.state = {
          options: {
            series: [{
              data: [1,2,3]
            }]
          }
        };
      }

      componentDidMount(){
        const container = this.chartComponent.current.container.current
        container.classList.add('container')
      }

      render() {
        return (
          <HighchartsReact
            constructorType={"chart"}
            ref={this.chartComponent}
            highcharts={Highcharts}
            options={this.state.options}
          />
        );
      }
    }

Live example: https://codesandbox.io/s/v0vjwq3ww7

**Comment by far1s** [comment]
@ppotaczek Thank you for your answer and the example

**Comment by milesegan** [comment]
It's nice to have this flexibility but it's also a lot more manual work to do this for every chart then to just pass a prop. Is there any way to bring this back or provide some kind of similarly convenient API?

**Comment by ppotaczek** [comment]
Hi @milesegan,

As I said in the related issue: https://github.com/highcharts/highcharts-react/issues/72, we will come back to the old `containerProps` in the next version.

Best regards!
