### ISSUE TITLE
How can I make a chart fill its parent div

### ISSUE THREAD

**Issue by mjdavidson** [highcharts/highcharts-react#72]
When I set no height/width, it seems to default too an arbitrary w/h. I want to only control the parent div's w/h so I can make the chart responsive

**Comment by ppotaczek** [comment]
Hello @mjdavidson, thank you for contacting us. 

You can set chart container element 'width' and 'height' styles to `100%`. This will allow you to manipulate the chart dimensions by parent element:

    class App extends React.Component {
      constructor(props) {
        super(props);
        this.chartComponent = React.createRef();

        this.state = {
          options: {
            series: [{
              data: [1, 2, 3]
            }]
          }
        };
      }

      componentDidMount() {
        const container = this.chartComponent.current.container.current;

        container.style.height = "100%";
        container.style.width = "100%";
        this.chartComponent.current.chart.reflow();
      }

      render() {
        return (
          <div style={{height: 300 + 'px', width: 300 + 'px'}}>
            <HighchartsReact
              constructorType={"chart"}
              ref={this.chartComponent}
              highcharts={Highcharts}
              options={this.state.options}
            />
          </div>
        );
      }
    }

Live demo: https://codesandbox.io/s/0mm8yl107v

We are trying to keep GitHub for bugs, so for future questions of this type please use: https://www.highcharts.com/support

**Comment by milesegan** [comment]
I'm having similar issues since upgrading to version 2 of this library. Previously I was able to just set something like:

`            containerProps={{ style: { height: "100%" } }}`

And the charts would automatically size to fit their container. This no longer works for me in 2.0. Manually assigning refs and reflowing charts is going to be a lot of work if we have to do that for every chart.

**Comment by milesegan** [comment]
That's great. Thanks for being flexible on this @ppotaczek.

**Comment by ppotaczek** [comment]
I added the `containerProps` option in the version 2.1.0:

    render() {
      return (
        <div>
          <HighchartsReact
            highcharts={Highcharts}
            containerProps={{ style: { height: "300px" } }}
            options={options}
          />
        </div>
      );
    }

Live demo: https://codesandbox.io/s/o511wvqlq6

Best regards!

**Comment by milesegan** [comment]
Thanks @ppotaczek !

**Comment by dibyn** [comment]
`<div id={'container'}>
        <HighchartsReact
          highcharts={Highcharts}
          constructorType={'chart'}
          options={data || []}
          containerProps={{ style: { height: 'calc(100vh - 170px)' } }}
        />
      </div>`
This worked so much better.
Thanks @ppotaczek
