### ISSUE TITLE
Boost + shared tooltip + updating data crashes

### ISSUE THREAD

**Issue by jonfreedman** [highcharts/highcharts-react#74]
Your support team told me to raise a bug directly.  If you look at [this](https://codesandbox.io/s/zlozmoy1l4) example you can see the chart data is updating every 500ms, as soon as you hover over a point the next update will crash with a TypeError `Cannot read property 'series' of undefined`

The support team created a comparable example without using react which works [here](http://jsfiddle.net/BlackLabel/4neh85L2/).

**Comment by ppotaczek** [comment]
Hi @jonfreedman, Thank you for reporting.

I successfully separated the problem from the react wrapper. Reported issue: https://github.com/highcharts/highcharts/issues/9572

To workaround, you can create reference to the chart and call `update` with new data directly on the chart:

    updateState = () => {
      this.chart.current.chart.update({
        data: {
          columns: [
            ["Time", "2018-11-28", "2018-11-29", "2018-11-30"],
            ["s1", Math.random(), Math.random(), Math.random()],
            ["s2", Math.random(), Math.random(), Math.random()]
          ]
        }
      });
    }

Live demo: https://codesandbox.io/s/yqpyz4m73z
