### ISSUE TITLE
Setting hover based on state

### ISSUE THREAD

**Issue by francvasquez** [highcharts/highcharts-react#79]
I'd like the points in my chart to hover (i.e. show tooltip) not only when user mouses over, but also based on a variable (state set by user when clicking on a button). How would I do that in React, based on the simple example below?

import React from 'react'
import HighchartsReact from 'highcharts-react-official'

const options = {
  title: {
    text: 'My chart'
  },
  series: [{
    data: [120, 122.4, 145, 153, 355, 244, 245, 211, 311, 200, 198, 122]
  }]
 xAxis: {
    categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
 }
}

const Mychart = () => <HighchartsReact
  highcharts={Highcharts}
  options={options}
/>

export default MyChart

**Comment by ppotaczek** [comment]
Hi @francvasquez,

This is support question, for the future please create this kind of threads on support: https://www.highcharts.com/blog/support/

To show tooltip, you need to call `refresh` method on it with the right point as an argument. Also, you can set `'hover'` point state to add 'hover' effect.

    import React from "react";
    import { render } from "react-dom";
    // Import Highcharts
    import Highcharts from "highcharts/highstock";
    import HighchartsReact from "highcharts-react-official";

    class App extends React.Component {
      constructor(props) {
        super(props);
        this.chartComponent = React.createRef();
        this.state = {
          hoveredPoint: 4
        };
      }

      componentDidMount() {
        this.updateTooltip();
      }

      componentDidUpdate() {
        this.updateTooltip();
      }

      updateTooltip() {
        const chart = this.chartComponent.current.chart;

        chart.series[0].points[this.state.hoveredPoint].setState("hover");
        chart.tooltip.refresh(chart.series[0].points[this.state.hoveredPoint]);
      }

      changeHoverPoint(e) {
        this.setState({
          hoveredPoint: e.target.value
        });
      }

      render() {
        return (
          <div>
            <input
              value={this.state.hoveredPoint}
              onChange={evt => this.changeHoverPoint(evt)}
            />
            <HighchartsReact
              constructorType={"chart"}
              ref={this.chartComponent}
              highcharts={Highcharts}
              options={...}
            />
          </div>
        );
      }
    }

    render(<App />, document.getElementById("root"));

Live demo: https://codesandbox.io/s/62k6lz39vr

API: https://api.highcharts.com/class-reference/Highcharts.Point#setState
