### ISSUE TITLE
Synchroised chart tooltip issue with multiple line series

### ISSUE THREAD

**Issue by Rahul-Sagore** [highcharts/highcharts-react#80]
I am rendering two charts:
1) Line chart with multiple series (two line series)
2) Column Chart.

I need synchronised tooltip on both chart. I followed this code snippet: https://www.highcharts.com/demo/synchronized-charts

It worked fine to synchronise the tooltip, but first chart, which has two line, is not working properly. When I hover over first line, point on second line should be active, but it is not highlighting the point:

![screen shot 2018-12-20 at 4 49 05 pm](https://user-images.githubusercontent.com/3587851/50281938-2632e600-0477-11e9-8875-25db57895600.png)

Only the first line has circle highlighting on hover.

This is the code for hover event in `componentDidMount`

```
['mousemove', 'touchmove', 'touchstart'].forEach(function (eventType) {
    document.getElementById('container').addEventListener(
        eventType,
        function (e) {
            var chart,
                point,
                i,
                event;

            for (i = 0; i < Highcharts.charts.length; i = i + 1) {
                chart = Highcharts.charts[i];
                // Find coordinates within the chart
                event = chart.pointer.normalize(e);
                // Get the hovered point
                point = chart.series[0].searchPoint(event, true);

                if (point) {
                    point.highlight(e);
                }
            }
        }
    );
});
```

So on hover `point.highlight(e);` this calls throws js error (I think this error stoping the highlighting the second point):

![image](https://user-images.githubusercontent.com/3587851/50282045-79a53400-0477-11e9-944f-740b75bbe5f9.png)

**Note:** Let me know if needed more context/code

**Comment by ppotaczek** [comment]
Hi @Rahul-Sagore,

Please do not duplicate threads - this is a support question, so we will continue the discussion on stackoverflow: 

https://stackoverflow.com/questions/53864608/react-highchart-synchronized-chart-and-tooltip-is-not-highlighting-the-points

Best regards!
