### ISSUE TITLE
Charts in Tabs do not re render properly

### ISSUE THREAD

**Issue by jose-nunez** [highcharts/highcharts-react#81]
Hi, 
I'm adding some charts inside a simple react tab implementation. The chart does not refresh properly every time I change the front tab. I have recreated the situation in here:  https://codepen.io/jose-nunez/pen/bOgBOY
Am I missing something? 
Any help is most appreciated.

Thanks

**Comment by ppotaczek** [comment]
Hi @jose-nunez,

I answered your question on stackoverflow: https://stackoverflow.com/questions/53879308/highchartsreact-does-not-render-properly-in-custom-tabs/53897258#53897258

Please do not duplicate threads - we track all topics on stackoverflow with 'highcharts' tag.

I remain at your disposal if you have any additional questions.

Best regards!

**Comment by jose-nunez** [comment]
I didn't know about that. I won't duplicate them in the future.
I got your answer and replied back. Thanks a lot. 
Merry Christmas and happy new year!
