### ISSUE TITLE
the hight can not set?why always 400px?

### ISSUE THREAD

**Issue by Carrie999** [highcharts/highcharts-react#82]

**Comment by sebastianbochan** [comment]
Hi @Carrie999,
Thank you for contacting us. Could you elaborate how you set the height? By the chart options or css styles?

**Comment by Carrie999** [comment]
> Hi @Carrie999,
> Thank you for contacting us. Could you elaborate how you set the height? By the chart options or css styles?
solved,thanks

**Comment by lemonbuzz** [comment]
Hi, I'm trying to set height to parent, but the chart doesn't follow. How can I replicate this behavior:

https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/chart/height/

Btw, i'm not using the height params of HighCharts core

**Comment by ppotaczek** [comment]
Hi @lemonbuzz,

The wrapper creates its own `div` element for the chart, so you need to refer directly to the chart container, for example:

    class App extends React.Component {
        componentDidMount() {
          const component = this.refs.chartComponent;

          component.container.current.style.height = "100%";
          component.chart.reflow();
        }

        render() {
          return (
            <div style={{ height: 600 + 'px'}}>
              <h2>Highcharts</h2>
              <HighchartsReact highcharts={Highcharts} options={options} ref="chartComponent"/>
            </div>
          );
        }
    }

Best regards!

**Comment by lemonbuzz** [comment]
Thanks for your help. I ended up setting the size with the APIs parameter :)
