### ISSUE TITLE
Disappearing borderRadius on mouseover 

### ISSUE THREAD

**Issue by matsomo** [highcharts/highcharts-react#86]
Hey, I'm having a similar issue to this: https://github.com/highcharts/highcharts/issues/1466
My problem is that I'm unsure how I would implement the Rounded-Corners plugin with React

BorderRadius issue recreated: https://stackblitz.com/edit/react-jwx4rb

highcharts: 7.0.1
highcharts-react-official: 2.0.0
react: 16.5.0

**Comment by ppotaczek** [comment]
Hi @matsomo,

This problem looks like a bug related to `xrange` series, so I reported it on Highcharts repository: https://github.com/highcharts/highcharts/issues/9880

You can add the `rounded-corners` plugin in this way: https://stackblitz.com/edit/react-hmgxcc?file=index.js, but it does not solve your problem.

Best regards!
