### ISSUE TITLE
How to dynamically update HighchartsReact?

### ISSUE THREAD

**Issue by Gunner17** [highcharts/highcharts-react#87]
Is it possible to get a reference (ex: this.chart) of the Highcharts when using the official HighchartsReact component? I would like to dynamically update the chart using the reference : this.chart.update(options)

**Comment by KacperMadej** [comment]
Hi @Gunner17 

The chart.update runs when changes are detected, so using chart instance to call chart.update manually might be causing problems when default wrapper chart.update will be called and might alter you changes making chart changes unpredictable.

Chart instance is accessible as described in this issue: https://github.com/highcharts/highcharts-react/issues/44#issuecomment-438703318

_Internal note:_
@ppotaczek Is that comment up to date? Chart instance access is not in docs - maybe it should be added?

**Comment by ppotaczek** [comment]
Hi @Gunner17, 

A good practice to dynamically update a chart is to keep options in a component state and call `setState` to change the options and update the chart:

    class App extends React.Component {
      constructor(props) {
        super(props);
        this.state = {
          options: {
            series: [{
                data: [1, 2, 3]
            }]
          }
        }
      }

      componentDidMount(){
        const component = this;
        setInterval(function(){
          component.setState({
            options: {
              series: [{
                data: [Math.random() * 5, Math.random() * 5, Math.random() * 5]
              }]
            }
          });
        }, 2000);
      }

      render() {
        return (
          <div>
            <h2>Highcharts</h2>
            <HighchartsReact
              highcharts={Highcharts}
              options={this.state.options}
            />
          </div>
        );
      }
    }

Live demo: https://codesandbox.io/s/ovx6kqokqq

On the other hand, if you do not keep options in the state, there are no restrictions to get the chart reference and manually update it:

    componentDidMount() {
      const chart = this.refs.chartComponent.chart;

      chart.update({
        series: [{
          data: [3, 2, 1]
        }]
      });
    }

    render() {
      return (
          <HighchartsReact ... ref="chartComponent"/>
      );
    }

@KacperMadej - Yes, good point. I will add the information to the docs.

**Comment by AlexCarrithers** [comment]
It should be noted that the above setInterval method in componentDidMount will need to be cleared in componentWillUnmount. Otherwise it will continue to run.

```
  componentDidMount(){
    const component = this;
    this.interval = setInterval(function(){
     // do interval stuff
    }, 2000);
  }

componentWillUnmount() {
  clearInterval(this.interval)
}
```

**Comment by pedroo21** [comment]
Just a note. Considering React refs is currently deprecated, I suggest the following:
```
componentDidMount() {
  this.chartRef = React.createRef();
}

render() {
  return (
    <HighchartsReact
      highcharts={ Highcharts }
      constructorType={ 'stockChart' }
      options={ options }
      ref={ this.chartRef }
    />
  );
}
```
