### ISSUE TITLE
Re-adding chart into view results in empty chart

### ISSUE THREAD

**Issue by Shiroe** [highcharts/highcharts-react#88]
Hello, I have a component rendering several charts (3) in one page based on filters rows. One filter row corresponds to one triad of charts (3 charts in vertical view with full-width of the container each) and the capability to add a second filter-row which corresponds to a second triad of charts (these appear also in vertical view which in each row this time instead of full-width i have  them at 50% for comparison purposes). 

So far so good, i am able to add the second triad column into view and appears correctly, also i can remove the second filter-row thus removing the second triad and making the first one again 100% width with no problems so far but the problem lies if i want `re-add` the second triad which i end up getting almost the same result as before only that the second triad has `empty` charts.

I tried different approaches like `reflow()`, `redraw()` and `window.dispatchEvent(new Event('resize'))` but the second triad remains empty.

```javascript
componentDidUpdate() {
    window.dispatchEvent(new Event('resize'));
}
```

```javascript
<div className={`${columns.length === 1 ? '--single' : '--multiple'}`}>
    {columns.map((col, idx) => (
        <div key={idx} className='charts-group'>
            {col.map(ds => (
                <HighchartsReact
                    key={`${ds.title.text}`}
                    highcharts={Highcharts}
                    constructorType={'stockChart'}
                    options={ds}
                />
            ))}
        </div>
    ))}
</div>
```

[Screenshots](https://imgur.com/a/eXHPrXZ)

**Comment by ppotaczek** [comment]
Hi Shiroe, 

I would like to precisely explore the problem, so could you reproduce this issue in some online code editor (for example: https://codesandbox.io/s/ovx6kqokqq)?

Best regards!

**Comment by ppotaczek** [comment]
Hi Shiroe, 

I am glad that you have solved this problem. It's hard for me to add anything because I do not know your code, but your assumption seems to make sense.

We try to keep the github repository only for bugs, so for this type of questions please use Highcharts support: https://www.highcharts.com/blog/support/

Best regards!
