### ISSUE TITLE
Uncaught Error: Highcharts error #16: www.highcharts.com/errors/16

### ISSUE THREAD

**Issue by jakehsiao0909** [highcharts/highcharts-react#89]
`import React from "react";`
`import Highcharts from "highcharts/modules/wordcloud";`
`import HighchartsChart from "highcharts-react-official";`

`var text =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean bibendum erat ac justo sollicitudin, quis lacinia ligula fringilla. Pellentesque hendrerit, nisi vitae posuere condimentum, lectus urna accumsan libero, rutrum commodo mi lacus pretium erat. Phasellus pretium ultrices mi sed semper. Praesent ut tristique magna. Donec nisl tellus, sagittis ut tempus sit amet, consectetur eget erat. Sed ornare gravida lacinia. Curabitur iaculis metus purus, eget pretium est laoreet ut. Quisque tristique augue ac eros malesuada, vitae facilisis mauris sollicitudin. Mauris ac molestie nulla, vitae facilisis quam. Curabitur placerat ornare sem, in mattis purus posuere eget. Praesent non condimentum odio. Nunc aliquet, odio nec auctor congue, sapien justo dictum massa, nec fermentum massa sapien non tellus. Praesent luctus eros et nunc pretium hendrerit. In consequat et eros nec interdum. Ut neque dui, maximus id elit ac, consequat pretium tellus. Nullam vel accumsan lorem.";
`
`var lines = text.split(/[, ]+/g);`

`var data = Highcharts.reduce(
  lines,
  (arr, word) => {
    var obj = Highcharts.find(arr, obj => {
      return obj.name === word;
    });
    if (obj) {
      obj.weight += 1;
    } else {
      obj = {
        name: word,
        weight: 1
      };
      arr.push(obj);
    }
    return arr;
  },
  []
);`

`const options = {
  series: [
    {
      type: "wordcloud",
      data: data,
      name: "Occurences"
    }
  ],
  title: {
    text: "Terms in EVA Conversation"
  }
};`

`const wordCloud = props => {

  return (
    <div className="worcloud">
      <HighchartsChart highcharts={Highcharts} options={options} />
    </div>
  );
};`

`export default wordCloud;`

I also have these 2 in the index.html

` <script src="https://code.highcharts.com/highcharts.js"></script>`
`<script src="https://code.highcharts.com/modules/wordcloud.js"></script>`

Cant find a solution to this.

**Comment by KacperMadej** [comment]
Hi @jakehsiao0909 

It looks like you are loading Highcharts at least twice.
Please report with full config to the tech support - https://www.highcharts.com/blog/support/

**Comment by jakehsiao0909** [comment]
Thanks! I found the problem to the error! Solved

**Comment by srinivasrk** [comment]
If I am using components (pre-compiled and stand alone) which all uses highcharts how do I make sure that this error does not happen?

For my usecase I have 2 pre-compiled svelte time series panel and bubble chart panel, and they both import highcharts!

**Comment by ppotaczek** [comment]
Hi @srinivasrk,

The same Highcharts should be shared through all components, but if you want to use pre-compiled and stand alone components, you can create different namespace for Highcharts in each component or in some way conditionally initiate Highcharts.

Best regards!
