### ISSUE TITLE
When re-rendering series is null

### ISSUE THREAD

**Issue by lija9** [highcharts/highcharts-react#9]
Hi, I have tried this wrapper in my application.

I have a modal that is showing when double clicking on an item. Modal is suppose to show chart. First time it shows, but when I close modal and chart is destroyed and open modal again the series part from options is null. I store options in my state. 
Part of the code:
this.state = {
    options: {
                title: {
                  text: 'My stock chart'
                },
                chart: {
                    type: 'spline',
                    animation: Highcharts.svg, // don't animate in old IE
                    marginRight: 10,
                    events: {
                        load: function () {
                            // set up the updating of the chart each second
                            var series = this.series[0];
                            
                            temperatureIntervalId = setInterval(function () {
                                fetch('http://localhost/API/api/asset/randomNumber')
                                .then(results => {
                                    return results.json();
                                }).then(data => {
                                    var x = (new Date()).getTime(), // current time
                                    y = data;
                                    series.addPoint([x, y], true, true);
                                });
                            }, 1000);
                        }
                    }
                },
                series: [{
                    data: generateStartingNumbers()
                }]
            }
}

the generateStartingNumbers is a function that returns random points like in the highcharts tutorial.
The first time I open modal, everything is OK and the chart is rendering and updating after fetch adding new points to the graph.

This is how I render my modal:

render() {
        return (
            <ReactModal
            isOpen={this.state.modalIsOpen}
            onAfterOpen={this.afterOpenModal}
            onRequestClose={this.closeModal}
            style={customStyles}
            contentLabel="Example Modal"
            overlayClassName="overlay"
            shouldFocusAfterRender={true}
            >
            <HighchartsReact
                ref="highchart"
                highcharts={Highcharts}
                constructorType={'stockChart'}
                options={this.state.options}
                update={true}
            />
        </ReactModal>
        );
    }

After the second opening of the Modal from the options everything is ok except the series part which is null and I don't know why.

Thanks,
Ivan

**Comment by KacperMadej** [comment]
Hi @lija9 
Maybe the variable is cleared or is wrongly referenced somewhere. Please try debugging to check when and why the value of the variable is changing.

**Comment by KacperMadej** [comment]
For technical support please contact [Highcharts support](https://www.highcharts.com/support).
