### ISSUE TITLE
Is Highcharts Gantt supported?

### ISSUE THREAD

**Issue by savnik** [highcharts/highcharts-react#90]
Is Highcharts Gantt supported using this wrapper or is it planned to be?

**Comment by ppotaczek** [comment]
Hi @savnik, 

Yes, Highcharts Gantt is supported by this wrapper. Below you can find a simple example of use:

    import React from "react";
    import { render } from "react-dom";
    import HighchartsReact from "highcharts-react-official";
    // Import Highcharts
    import Highcharts from "highcharts";
    import highchartsGantt from "highcharts/modules/gantt";

    highchartsGantt(Highcharts);

    class App extends React.Component {
      constructor(props) {
        super(props);
      }

      render() {
        return (
          <div>
            <HighchartsReact
              highcharts={Highcharts}
              constructorType={"ganttChart"}
              options={{
                yAxis: {
                  type: "category",
                  grid: {
                    enabled: true,
                    columns: [{ title: "Xyz", categories: ["x", "y"] }]
                  }
                },
                series: [
                  {
                    data: [
                      { x: 0, x2: 100000, y: 0 },
                      { x: 100000, x2: 200000, y: 1 }
                    ]
                  }
                ]
              }}
            />
          </div>
        );
      }
    }

    render(<App />, document.getElementById("root"));

Live demo: https://codesandbox.io/s/oqz2m2m6ny

Best regards!

**Comment by savnik** [comment]
@ppotaczek Great thanks!

Updating the data series then does not seam to work. When updating a series or categories the gantt chart is not loading properly. Here is an example where I have a button which append a row to the series. In the demo: https://www.highcharts.com/gantt/demo/interactive-gantt is seams like the update function works. 



```
import React from "react";
import { render } from "react-dom";
import HighchartsReact from "highcharts-react-official";
// Import Highcharts
import Highcharts from "highcharts";
import highchartsGantt from "highcharts/modules/gantt";
import Button from "@material-ui/core/Button";

highchartsGantt(Highcharts);

class App extends React.Component {
  constructor(props) {
    super(props);

    this.state = {
      series: [
        {
          data: [{ x: 0, x2: 100000, y: 0 }, { x: 100000, x2: 200000, y: 1 }]
        }
      ]
    };
  }

  updateData = () => {
    this.setState({
      ...this.state,
      series: [
        {
          data: [...this.state.series[0].data, { x: 0, x2: 10000, y: 1 }]
        }
      ]
    });
  };

  render() {
    console.log(this.state);
    return (
      <div>
        <HighchartsReact
          highcharts={Highcharts}
          constructorType={"ganttChart"}
          options={{
            yAxis: {
              type: "category",
              grid: {
                enabled: true,
                columns: [{ title: "Xyz", categories: ["x", "y"] }]
              }
            },
            series: this.state.series
          }}
        />
        <Button onClick={this.updateData}>Add Data</Button>
      </div>
    );
  }
}

render(<App />, document.getElementById("root"));

```

Live demo: 
https://codesandbox.io/s/9ym0v4xnpw

**Comment by ppotaczek** [comment]
Hi @savnik,

Unfortunately this problem is a Highcharts Gantt bug. The issue is related with updating axis grid and it is reported here: https://github.com/highcharts/highcharts/issues/9269

The chart works fine without the grid columns: https://codesandbox.io/s/vv4kzmmqy

Best regards!

**Comment by savnik** [comment]
Ah Thanks @ppotaczek!

**Comment by ppotaczek** [comment]
@savnik,

To avoid unnecessary updating of the axis grid, you can keep all the chart options in the state.

Live demo: https://codesandbox.io/s/oqqnz55vpq

**Comment by savnik** [comment]
@ppotaczek good point I will try that
