### ISSUE TITLE
Solid gauge representing series "y" value wrong

### ISSUE THREAD

**Issue by mpaberzs** [highcharts/highcharts-react#92]
Using this same config produces different result on solid gauge when ran outside react wrapper (correct) and with react wrapper (wrong). It seems like it's highlighting not the actual value but defined max - actual value on the gauge.

So setting `0.36375` when `1` is the max value results in this when using react wrapper:

![wrongsolidgauge](https://user-images.githubusercontent.com/3092553/52856092-20cae280-312c-11e9-8a9d-7afcedf9c07a.png)

the config:
```
Highcharts.chart('container', {
  "chart": {
    "type": "solidgauge",
    "width": 190,
    "height": 230
  },
  "title": {
    "text": null
  },
  "tooltip": {
    "enabled": false
  },
  "pane": {
    "startAngle": 0,
    "endAngle": 360,
    "background": [{
      "outerRadius": "112%",
      "innerRadius": "88%",
      "backgroundColor": "rgb(237, 238, 240)",
      "borderWidth": 0
    }]
  },
  "yAxis": {
    "min": 0,
    "max": 1,
    "lineWidth": 0,
    "tickPositions": []
  },
  "plotOptions": {
    "solidgauge": {
      "dataLabels": {
        "enabled": true,
        "borderWidth": 0,
        "color": "#1A2C40",
        "verticalAlign": "middle",
        "y": 0,
        "style": {
          "fontFamily": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", \"Roboto\", \"Oxygen\", \"Ubuntu\", \"Cantarell\", \"Fira Sans\", \"Droid Sans\", \"Helvetica Neue\", sans-serif",
          "fontSize": "18px"
        }
      },
      "linecap": "round",
      "stickyTracking": false,
      "rounded": true
    }
  },
  "series": [{
    "name": "",
    "data": [{
      "color": "#537DD7",
      "radius": "112%",
      "innerRadius": "88%",
      "y": 0.36375
    }]
  }],
  "credits": {
    "enabled": false
  },
  "loaded": true
});
```

**Comment by ppotaczek** [comment]
Hi @mpaberzs,

Thank you for contacting us!

I tested your chart config:
- without the wrapper: https://jsfiddle.net/BlackLabel/otpudgye/
- with the wrapper: https://codesandbox.io/s/ko3z3n7r4r

and it seems that both look the same. Could you reproduce your problem in some online code editor?

Best regards!

**Comment by mpaberzs** [comment]
@ppotaczek thank you for your quick and well formed reply!

I'm noticing this actually might be because I'm using constructorType="mapChart", changing it just to chart seems to have 'fixed' it! So my bad, sorry. Closing the issue.
