### ISSUE TITLE
Is NPM really required?

### ISSUE THREAD

**Issue by yhoiseth** [highcharts/highcharts-react#93]
In [the documentation](https://github.com/highcharts/highcharts-react#general-prerequisites), it says that NPM version 6.4.1 or higher is required.

Is this really the case? I would think that Yarn could also be used?

**Comment by yhoiseth** [comment]
I haven't had any issues using Yarn (not that I expected any).

Maybe it should be clarified in the documentation in case it trips up anyone who's not familiar with JS packaging?

**Comment by ppotaczek** [comment]
Hi @yhoiseth,

Thank you for reporting!

Yes - you are right, you can use Yarn instead of NPM and you should not encounter any problems. I will add a correction in the documentation.

Best regards!

**Comment by ppotaczek** [comment]
I have added a note in the documentation about the possibility of using another package manager.

Best regards!
