### ISSUE TITLE
Refreshing stock chart options causes TypeError: undefined is not an object (evaluating 'b.xData[0]')

### ISSUE THREAD

**Issue by rchancey** [highcharts/highcharts-react#96]
I am having an issue where the chart works super and renders fine.. and I can manipulate it. but then I  try  to refresh the data and rerender the chart. I get this error:
TypeError: undefined is not an object (evaluating 'b.xData[0]')

happens in the below code.. and my  series data is fine since in fact I did not change the actual data I  just changed something else on teh page and it rerendered the page.. 
`  /**
             * Get minimum from all base series connected to the navigator
             *
             * @param  {number} currentSeriesMin
             *         Minium from the current series
             *
             * @return {number} Minimum from all series
             */
            getBaseSeriesMin: function (currentSeriesMin) {
                return this.baseSeries.reduce(
                    function (min, series) {
                        return Math.min(min, series.xData[0]);
                    },
                    currentSeriesMin
                );
            },
`

**Comment by ppotaczek** [comment]
Hi @rchancey,

It is very hard to help you without looking at your code.
Could you provide us with some minimal live example which presents the described situation?

Best regards!

**Comment by ppotaczek** [comment]
Closed due to inactivity.
