### ISSUE TITLE
How do I implement solid gauge using the plugin?

### ISSUE THREAD

**Issue by vaibhav6496** [highcharts/highcharts-react#98]
Hi tried using Solid Gauge by giving following import statement:
import HighchartsReact from 'highcharts-react-official'
import Highcharts from 'highcharts'

And I used it as:
<HighchartsReact
                      highcharts={Highcharts}
                      options={option}
                      className="highcharts"
                    />

Options are correct as I used same option on codepen and it worked perfectly.

**Comment by ppotaczek** [comment]
Hi @vaibhav6496,

You need to import and initialize `highcharts-more` and `solid-gauge` module:

    import Highcharts from "highcharts/highcharts.js";
    import highchartsMore from "highcharts/highcharts-more.js"
    import solidGauge from "highcharts/modules/solid-gauge.js";
    import HighchartsReact from "highcharts-react-official";

    highchartsMore(Highcharts);
    solidGauge(Highcharts);

Live demo: https://codesandbox.io/s/rkzro8yy4

In the future please ask this type of questions on one of the support channels: https://www.highcharts.com/blog/support/

Best regards!

**Comment by talented-full-dev** [comment]
Great!
You are right.
